### ISSUE TITLE
More diagnostic fixes

### ISSUE THREAD

**Issue by sam-mccall** [clangd/clangd#42] opened 2019-05-03 10:29 UTC
Clang mostly only emits those that are nice to read, which usually means short.

But some diagnostics have really obvious/useful fixes, e.g.:
 - unhandled enum cases
 - member initializers in the wrong order

Unclear if the logic should go in sema, clangd, or even clang-tidy.

**Comment by kadircet** [comment] 2021-12-16 08:45
I believe this is something we value in general and try to improve as we stumble upon such cases. but the issue is too vague on its own to be acted directly. Hence closing this one.

But I am creating a more general "roadmap" document, in which I put an item around this one. Hopefully I'll make it available soon.

**Closed by kadircet** 2021-12-16 08:45 UTC
Labels: enhancement
