### ISSUE TITLE
include-cleaner doesn't understand std::hash extensions for custom types

### ISSUE THREAD

**Issue by slymas** [clangd/clangd#1555] opened 2023-03-24 10:44 UTC
I have a header (HashUtils.h) with multiple extensions to std::hash, which lets me put Qt-specific types as keys in to std::unordered_* containers. I simply include HashUtils.h where I want to have implicit hashing of those custom types, but clangd gives the "Included header HashUtils.h is not used directly (fix available)" warning on all occasions.

Example hash extension from the header:

```
namespace std {
template <>
struct hash<QPointF> {
  size_t operator()(const QPointF& p) const noexcept { /* content removed for brevity */ }
};
```

**System information**

Output of clangd --version:
clangd version 15.0.0 (git://code.qt.io/clang/llvm-project.git 218224bce00c69b6f8a396e681c51256fc6f1b99)
Features: linux
Platform: x86_64-unknown-linux-gnu

Editor/LSP plugin:
Qt Creator 9.0.2

Operating system:
Ubuntu 22.04.2 LTS

**Comment by hokein** [comment] 2023-03-28 08:18
Yeah, this is a known issue of using the extension point code pattern, this pattern is hard for the IWYS/IWYU tool to handle.

We're working on a better solution for this (we plan to propose a new IWYU `always_keep` pragma). For now, to suppress the false unused-include diagnostics, you can
1) add a trailing `// IWYU pragma: keep` on `#include "HashUtils.h"` 
2) or add this header to the clangd's `IgnoreHeaders` config, something like below
```
Diagnostics:
    Includes:
     IgnoreHeader: [
        HashUtils\.h
     ]
```

**Comment by slymas** [comment] 2023-03-28 08:42
Hi,

Thanks for confirming the issue. I already set up "pragma keep" for all false reports to silence them in code.

**Comment by kadircet** [comment] 2024-07-30 14:26
duplicate of https://github.com/clangd/clangd/issues/2050

**Closed by kadircet** 2024-07-30 14:26 UTC
Labels: include-cleaner
