### ISSUE TITLE
WarningsAsErrors in .clang-tidy can override -Wno-error in compile_flags.txt

### ISSUE THREAD

**Issue by bstaletic** [clangd/clangd#1905] opened 2024-01-15 13:00 UTC
If `.clang-tidy` has `WarningsAsErrors: '*'` and clangd is configured to use clang-tidy, then all warnings will be treated as errors, regardless of what is in `compile_flags.txt`.

#### `compile_flags.txt`

```
-Wno-error
-Wfor-loop-analysis
```

#### `diagnostic_test.cc`

```
int main() { for (int j; j;){} }
```
#### `.clang-tidy`

```
---
WarningsAsErrors: '*'
```

I have pased the entire clangd log below, but the key part is:

    V[13:32:05.016] >>> {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[{"code":"-Wfor-loop-analysis","message":"Variable 'j' used in loop condition not modified in loop body","range":{"end":{"character":26,"line":0},"start":{"character":25,"line":0}},"severity":1,"source":"clang"}],"uri":"file:///home/bstaletic/work/test/clang_bug/diagnostic_test.cc","version":1}}

Here, you can see `severity` set to `1`, even without `-Werror=for-loop-analysis`.

**Logs**

```
I[13:32:04.999] clangd version 17.0.1 (https://github.com/ycm-core/llvm f0e018b8aadf1be25e3af0daa7a87d505de67957)
I[13:32:04.999] Features: linux
I[13:32:04.999] PID: 24895
I[13:32:04.999] Working directory: /home/bstaletic/work/test/clang_bug
I[13:32:04.999] argv[0]: /home/bstaletic/.vim/pack/bundle/start/YouCompleteMe/third_party/ycmd/third_party/clangd/output/bin/clangd
I[13:32:04.999] argv[1]: -header-insertion-decorators=0
I[13:32:04.999] argv[2]: -resource-dir=/home/bstaletic/.vim/pack/bundle/start/YouCompleteMe/third_party/ycmd/third_party/clang/lib/clang/17.0.1
I[13:32:04.999] argv[3]: -limit-results=500
I[13:32:04.999] argv[4]: -log=verbose
V[13:32:04.999] User config file is /home/bstaletic/.config/clangd/config.yaml
I[13:32:04.999] Starting LSP over stdin/stdout
V[13:32:04.999] <<< {"id":1,"jsonrpc":"2.0","method":"initialize","params":{"capabilities":{"textDocument":{"codeAction":{"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}}},"completion":{"completionItem":{"documentationFormat":["plaintext","markdown"],"resolveSupport":{"properties":["documentation","detail"]}},"completionItemKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]}},"documentSymbol":{"hierarchicalDocumentSymbolSupport":false,"labelSupport":false,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]}},"hover":{"contentFormat":["plaintext","markdown"]},"inlay_hint":{},"semanticTokens":{"augmentSyntaxTokens":true,"formats":["relative"],"requests":{"full":{"delta":false},"range":true},"tokenModifiers":[],"tokenTypes":["namespace","type","class","enum","interface","struct","typeParameter","parameter","variable","property","enumMember","event","function","method","member","macro","keyword","modifier","comment","string","number","regexp","operator"]},"signatureHelp":{"signatureInformation":{"documentationFormat":["plaintext","markdown"],"parameterInformation":{"labelOffsetSupport":true}}},"synchronization":{"didSave":true}},"workspace":{"applyEdit":true,"didChangeWatchedFiles":{"dynamicRegistration":true},"symbol":{"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]}},"workspaceEdit":{"documentChanges":true},"workspaceFolders":true}},"initializationOptions":{},"processId":24880,"rootPath":"/home/bstaletic/work/test/clang_bug","rootUri":"file:///home/bstaletic/work/test/clang_bug","workspaceFolders":[{"name":"clang_bug","uri":"file:///home/bstaletic/work/test/clang_bug"}]}}

I[13:32:04.999] <-- initialize(1)
I[13:32:05.000] --> reply:initialize(1) 0 ms
V[13:32:05.000] >>> {"id":1,"jsonrpc":"2.0","result":{"capabilities":{"astProvider":true,"callHierarchyProvider":true,"clangdInlayHintsProvider":true,"codeActionProvider":{"codeActionKinds":["quickfix","refactor","info"]},"compilationDatabase":{"automaticReload":true},"completionProvider":{"resolveProvider":false,"triggerCharacters":[".","<",">",":","\"","/","*"]},"declarationProvider":true,"definitionProvider":true,"documentFormattingProvider":true,"documentHighlightProvider":true,"documentLinkProvider":{"resolveProvider":false},"documentOnTypeFormattingProvider":{"firstTriggerCharacter":"\n","moreTriggerCharacter":[]},"documentRangeFormattingProvider":true,"documentSymbolProvider":true,"executeCommandProvider":{"commands":["clangd.applyFix","clangd.applyTweak"]},"foldingRangeProvider":true,"hoverProvider":true,"implementationProvider":true,"inactiveRegionsProvider":true,"inlayHintProvider":true,"memoryUsageProvider":true,"referencesProvider":true,"renameProvider":true,"selectionRangeProvider":true,"semanticTokensProvider":{"full":{"delta":true},"legend":{"tokenModifiers":["declaration","definition","deprecated","deduced","readonly","static","abstract","virtual","dependentName","defaultLibrary","usedAsMutableReference","usedAsMutablePointer","constructorOrDestructor","userDefined","functionScope","classScope","fileScope","globalScope"],"tokenTypes":["variable","variable","parameter","function","method","function","property","variable","class","interface","enum","enumMember","type","type","unknown","namespace","typeParameter","concept","type","macro","modifier","operator","bracket","label","comment"]},"range":false},"signatureHelpProvider":{"triggerCharacters":["(",")","{","}","<",">",","]},"standardTypeHierarchyProvider":true,"textDocumentSync":{"change":2,"openClose":true,"save":true},"typeDefinitionProvider":true,"typeHierarchyProvider":true,"workspaceSymbolProvider":true},"serverInfo":{"name":"clangd","version":"clangd version 17.0.1 (https://github.com/ycm-core/llvm f0e018b8aadf1be25e3af0daa7a87d505de67957) linux x86_64-unknown-linux-gnu"}}}

V[13:32:05.001] <<< {"jsonrpc":"2.0","method":"initialized","params":{}}

I[13:32:05.001] <-- initialized
V[13:32:05.001] <<< {"jsonrpc":"2.0","method":"workspace/didChangeConfiguration","params":{"settings":{}}}

I[13:32:05.001] <-- workspace/didChangeConfiguration
V[13:32:05.002] <<< {"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"languageId":"cpp","text":"int main() { for (int j; j;){} }\n","uri":"file:///home/bstaletic/work/test/clang_bug/diagnostic_test.cc","version":1}}}

I[13:32:05.002] <-- textDocument/didOpen
I[13:32:05.002] Loaded compilation database from /home/bstaletic/work/test/clang_bug/compile_flags.txt
V[13:32:05.002] Broadcasting compilation database from /home/bstaletic/work/test/clang_bug
I[13:32:05.002] ASTWorker building file /home/bstaletic/work/test/clang_bug/diagnostic_test.cc version 1 with command 
[/home/bstaletic/work/test/clang_bug]
/home/bstaletic/.vim/pack/bundle/start/YouCompleteMe/third_party/ycmd/third_party/clangd/output/bin/clang-tool -Wno-error -Wfor-loop-analysis -resource-dir=/home/bstaletic/.vim/pack/bundle/start/YouCompleteMe/third_party/ycmd/third_party/clang/lib/clang/17.0.1 -- /home/bstaletic/work/test/clang_bug/diagnostic_test.cc
V[13:32:05.003] Driver produced command: cc1 -cc1 -triple x86_64-unknown-linux-gnu -fsyntax-only -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name diagnostic_test.cc -mrelocation-model pic -pic-level 2 -pic-is-pie -mframe-pointer=all -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu x86-64 -tune-cpu generic -debugger-tuning=gdb -fcoverage-compilation-dir=/home/bstaletic/work/test/clang_bug -resource-dir /home/bstaletic/.vim/pack/bundle/start/YouCompleteMe/third_party/ycmd/third_party/clang/lib/clang/17.0.1 -internal-isystem /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13 -internal-isystem /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/x86_64-pc-linux-gnu -internal-isystem /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/backward -internal-isystem /home/bstaletic/.vim/pack/bundle/start/YouCompleteMe/third_party/ycmd/third_party/clang/lib/clang/17.0.1/include -internal-isystem /usr/local/include -internal-isystem /usr/lib/gcc/x86_64-pc-linux-gnu/13/../../../../x86_64-pc-linux-gnu/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -Wno-error -Wfor-loop-analysis -fdeprecated-macro -fdebug-compilation-dir=/home/bstaletic/work/test/clang_bug -ferror-limit 19 -fgnuc-version=4.2.1 -fcxx-exceptions -fexceptions -no-round-trip-args -D__GCC_HAVE_DWARF2_CFI_ASM=1 -x c++ /home/bstaletic/work/test/clang_bug/diagnostic_test.cc
V[13:32:05.003] Building first preamble for /home/bstaletic/work/test/clang_bug/diagnostic_test.cc version 1
I[13:32:05.009] Built preamble of size 232136 for file /home/bstaletic/work/test/clang_bug/diagnostic_test.cc version 1 in 0.01 seconds
V[13:32:05.009] indexed preamble AST for /home/bstaletic/work/test/clang_bug/diagnostic_test.cc version 1:
  symbol slab: 0 symbols, 120 bytes
  ref slab: 0 symbols, 0 refs, 128 bytes
  relations slab: 0 relations, 24 bytes
I[13:32:05.011] Indexing c++17 standard library in the context of /home/bstaletic/work/test/clang_bug/diagnostic_test.cc
V[13:32:05.016] indexed file AST for /home/bstaletic/work/test/clang_bug/diagnostic_test.cc version 1:
  symbol slab: 1 symbols, 4448 bytes
  ref slab: 1 symbols, 1 refs, 4248 bytes
  relations slab: 0 relations, 24 bytes
V[13:32:05.016] Build dynamic index for main-file symbols with estimated memory usage of 11520 bytes
I[13:32:05.016] --> textDocument/publishDiagnostics
V[13:32:05.016] >>> {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[{"code":"-Wfor-loop-analysis","message":"Variable 'j' used in loop condition not modified in loop body","range":{"end":{"character":26,"line":0},"start":{"character":25,"line":0}},"severity":1,"source":"clang"}],"uri":"file:///home/bstaletic/work/test/clang_bug/diagnostic_test.cc","version":1}}

V[13:32:06.737] Ignored diagnostic. /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/shared_ptr_atomic.h:102:49:too many arguments provided to function-like macro invocation
V[13:32:06.737] Ignored diagnostic. /home/bstaletic/.vim/pack/bundle/start/YouCompleteMe/third_party/ycmd/third_party/clang/lib/clang/17.0.1/include/stdatomic.h:89:9:macro 'atomic_is_lock_free' defined here
V[13:32:06.737] Ignored diagnostic. /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/shared_ptr_atomic.h:102:5:redefinition of 'atomic_is_lock_free' as different kind of symbol
V[13:32:06.737] Ignored diagnostic. /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/atomic:1294:5:previous definition is here
V[13:32:06.737] Ignored diagnostic. /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/shared_ptr_atomic.h:105:7:expected expression
V[13:32:06.737] Ignored diagnostic. /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/shared_ptr_atomic.h:109:6:expected ';' at end of declaration
V[13:32:06.737] Ignored diagnostic. /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/shared_ptr_atomic.h:113:48:expected ')'
V[13:32:06.737] Ignored diagnostic. /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/shared_ptr_atomic.h:113:5:to match this '('
V[13:32:06.737] Ignored diagnostic. /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/shared_ptr_atomic.h:113:5:expected expression
V[13:32:06.737] Ignored diagnostic. /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/shared_ptr_atomic.h:113:52:expected ';' at end of declaration
V[13:32:06.737] Ignored diagnostic. /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/shared_ptr_atomic.h:114:5:expected unqualified-id
V[13:32:06.737] Ignored diagnostic. /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/shared_ptr_atomic.h:137:5:expected parameter declarator
V[13:32:06.737] Ignored diagnostic. /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/shared_ptr_atomic.h:137:5:expected ')'
V[13:32:06.737] Ignored diagnostic. /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/shared_ptr_atomic.h:137:5:to match this '('
V[13:32:06.738] Ignored diagnostic. /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/shared_ptr_atomic.h:150:41:too many arguments provided to function-like macro invocation
V[13:32:06.738] Ignored diagnostic. /home/bstaletic/.vim/pack/bundle/start/YouCompleteMe/third_party/ycmd/third_party/clang/lib/clang/17.0.1/include/stdatomic.h:140:9:macro 'atomic_load' defined here
V[13:32:06.738] Ignored diagnostic. /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/shared_ptr_atomic.h:150:5:redefinition of 'atomic_load' as different kind of symbol
V[13:32:06.738] Ignored diagnostic. /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/atomic:1397:5:previous definition is here
V[13:32:06.738] Ignored diagnostic. /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/shared_ptr_atomic.h:151:7:expected expression
V[13:32:06.738] Ignored diagnostic. /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/shared_ptr_atomic.h:151:69:expected ';' at end of declaration
V[13:32:06.738] Ignored diagnostic. /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/shared_ptr_atomic.h:174:5:expected parameter declarator
V[13:32:06.738] Ignored diagnostic. /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/shared_ptr_atomic.h:174:5:expected ')'
V[13:32:06.738] Ignored diagnostic. /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/shared_ptr_atomic.h:174:5:to match this '('
V[13:32:06.738] Ignored diagnostic. /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/shared_ptr_atomic.h:189:47:too many arguments provided to function-like macro invocation
V[13:32:06.738] Ignored diagnostic. /home/bstaletic/.vim/pack/bundle/start/YouCompleteMe/third_party/ycmd/third_party/clang/lib/clang/17.0.1/include/stdatomic.h:137:9:macro 'atomic_store' defined here
V[13:32:06.738] Ignored diagnostic. /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/shared_ptr_atomic.h:189:5:variable has incomplete type 'void'
V[13:32:06.749] Ignored diagnostic. /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/shared_ptr_atomic.h:190:34:use of undeclared identifier '__p'
V[13:32:06.749] Ignored diagnostic. too many errors emitted, stopping now
I[13:32:07.429] Indexed c++17 standard library (incomplete due to errors): 13647 symbols, 1916 filtered
V[13:32:07.474] Build dynamic index for header symbols with estimated memory usage of 8227308 bytes
```

**System information**

Output of `clangd --version`:
```
clangd version 17.0.1 (https://github.com/ycm-core/llvm f0e018b8aadf1be25e3af0daa7a87d505de67957)
Features: linux
Platform: x86_64-unknown-linux-gnu
```
Editor/LSP plugin: YCM/ycmd

Operating system: Gentoo linux

**Comment by HighCommander4** [comment] 2024-01-15 18:24
This diagnostic is issued both by the compiler frontend, and by clang-tidy.

If I run the compiler on the command line, I get the diagnostic from the frontend, with severity warning as per the `-Wno-error`:

```console
$ clang++ -c -Wno-error -Wfor-loop-analysis diagnostic_test.cc
diagnostic_test.cc:1:26: warning: variable 'j' used in loop condition not modified in loop body [-Wfor-loop-analysis]
    1 | int main() { for (int j; j;){} }
      |                          ^
1 warning generated.
```

If I run clang-tidy on the command line, I get the diagnostic from clang-tidy, with severity error as per the `WarningsAsErrors: '*'`:

```console
$ clang-tidy diagnostic_test.cc
3 warnings generated.
diagnostic_test.cpp:1:26: error: Branch condition evaluates to a garbage value [clang-analyzer-core.uninitialized.Branch,-warnings-as-errors]
    1 | int main() { for (int j; j;){} }
      |                          ^
diagnostic_test.cpp:1:19: note: 'j' declared without an initial value
    1 | int main() { for (int j; j;){} }
      |                   ^~~~~
diagnostic_test.cpp:1:26: note: Branch condition evaluates to a garbage value
    1 | int main() { for (int j; j;){} }
      |                          ^
diagnostic_test.cpp:1:26: error: variable 'j' used in loop condition not modified in loop body [clang-diagnostic-for-loop-analysis,-warnings-as-errors]
    1 | int main() { for (int j; j;){} }
      |                          ^
diagnostic_test.cpp:1:26: error: variable 'j' is uninitialized when used here [clang-diagnostic-uninitialized,-warnings-as-errors]
    1 | int main() { for (int j; j;){} }
      |                          ^
diagnostic_test.cpp:1:24: note: initialize the variable 'j' to silence this warning
    1 | int main() { for (int j; j;){} }
      |                        ^
      |                         = 0
3 warnings treated as errors
```

clangd generates diagnostics both from the frontend and from clang-tidy. I guess in this case they get merged, and the higher severity prevails?

I think this is basically working as intended:
 * If you'd like clangd to provide only the compiler frontend diagnostics and not clang-tidy diagnostics, you can run clangd with `--clang-tidy=false`.
 * If you want clangd to provide clang-tidy diagnostics but don't want this one to be an error, you can use a more narrowly tailored `WarningsAsErrors` setting.

**Comment by bstaletic** [comment] 2024-01-15 18:40
My specific use case was writing a test for YCM, where I needed `-Wfor-loop-analysis` to be a warning.
The current behaviour threw me for a loop, because the diagnostics code was `-Wfor-loop-analysis`, which to me indicates the frontent as the source (starting with `-W`).
Had the `code` been `clang-diagnostic-for-loop-analysis` I would have suspected clang-tidy config immediately.

> If you'd like clangd to provide only the compiler frontend diagnostics and not clang-tidy diagnostics, you can run clangd with `--clang-tidy=false`.

That's what I ended up doing in said test, so my use case is addressed. If this is working as intended, that's fine by me.

One more thing to note is that, with the same C++ and clang-tidy file as above and the following `compile_flags.txt`:

```
-Wno-error
-Wno-for-loop-analysis
```

clangd will not report any diagnostics. If `WarningsAsErrors` is applied from the clang-tidy invocation, why isn't the for-loop-analysis reported in both cases?

**Comment by HighCommander4** [comment] 2024-01-17 07:31
> One more thing to note is that, with the same C++ and clang-tidy file as above and the following `compile_flags.txt`:
> 
> ```
> -Wno-error
> -Wno-for-loop-analysis
> ```
> 
> clangd will not report any diagnostics. If `WarningsAsErrors` is applied from the clang-tidy invocation, why isn't the for-loop-analysis reported in both cases?

Good question. I looked into this a bit, and it turns out my mental model of how things work under the hood was a bit inaccurate.

 * Rather than thinking of them as two diagnostics, it's more accurate to think of them as one diagnostic, which clang-tidy presents under a modified name (`clang-diagnostic-for-loop-analysis` rather than `-Wfor-loop-analysis`).
 * When clangd processes the file, only one instance of the diagnostic is generated (so there is nothing to "merge").
   * If clangd's clang-tidy support is enabled, clangd checks whether this is a diagnostic that clang-tidy recognizes.
   * That checks returns true for this diagnostic.
   * If the check returns true, clangd does some clang-tidy related processing, including applying any clang-tidy `WarningAsErrors` setting
   *But when presenting the diagnostic, clangd uses the original name (e.g. `-Wfor-loop-analysis`)

So that explains the various things we are seeing:
 * Why `WarningsAsErrors` takes precedence over `-Wno-error`
 * Why the diagnostic is always presented under its original name (`-Wfor-loop-analysis`)
 * Why `-Wno-for-loop-analysis` results in no diagnostic (the flag results in the diagnostic not being generated in the first place)

To make things less confusing, perhaps when clang-tidy support is enabled, these diagnostics should be presented under their clang-tidy name (e.g. `clang-diagnostic-for-loop-analysis`)?

**Comment by bstaletic** [comment] 2024-01-17 17:37
Ok, that makes sense. Thanks for the explanation. I was curious and had to try the opposite case:

- Only `-Werror` in `compile_flags.txt`
- Only `Checks:          'clang-diagnostic-for-loop-analysis'` in `.clang-tidy` in an attempt to enable `clang-diagnostic-for-loop-analysis`
- Same source file as before.

The diagnostic was not produced.
If my understand is correct, this is also expected. We are still talking about the front-end generated warning, so users need to enable those through `-Wthing`, but then severity modification, thought `WarningsAsErrors` is possible through `.clang-tidy`.

> To make things less confusing, perhaps when clang-tidy support is enabled, these diagnostics should be presented under their clang-tidy name (e.g. `clang-diagnostic-for-loop-analysis`)?

That would have definitely avoided my confusion, but if users still need to specify `-Wfor-loop-analisys`, the proposed change might be misleading in a different way.

**Comment by HighCommander4** [comment] 2024-01-17 17:42
> I was curious and had to try the opposite case:
> 
>     * Only `-Werror` in `compile_flags.txt`
> 
>     * Only `Checks:          'clang-diagnostic-for-loop-analysis'` in `.clang-tidy` in an attempt to enable `clang-diagnostic-for-loop-analysis`
> 
>     * Same source file as before.
> 
> 
> The diagnostic was not produced. If my understand is correct, this is also expected. We are still talking about the front-end generated warning, so users need to enable those through `-Wthing`, but then severity modification, thought `WarningsAsErrors` is possible through `.clang-tidy`.

Yep, that matches my understanding.

> > To make things less confusing, perhaps when clang-tidy support is enabled, these diagnostics should be presented under their clang-tidy name (e.g. `clang-diagnostic-for-loop-analysis`)?
> 
> That would have definitely avoided my confusion, but if users still need to specify `-Wfor-loop-analisys`, the proposed change might be misleading in a different way.

Good point. Maybe this is just working as intended then.

**Closed by HighCommander4** 2024-01-17 17:42 UTC
