### ISSUE TITLE
Hovering on `using enum ...` gives out hex value instead of enumeration name.

### ISSUE THREAD

**Issue by i-ky** [clangd/clangd#1284] opened 2022-09-09 07:09 UTC
In the following code:
```cpp
enum class Foo {Bar, Baz};

void test() {
  using enum Foo;
  Bar;
}
```
hovering over `Bar;` (line 5) gives the following tip:
![image](https://user-images.githubusercontent.com/25753618/189141888-510c4ac0-aa5a-4b06-8000-e362fad170af.png)
Note the hex value (pointer address?) instead of `enum` name.

_Originally posted by @i-ky in https://github.com/clangd/clangd/issues/1281#issuecomment-1240760281_

**Comment by tom-anders** [comment] 2022-09-10 14:06
I debugged a bit and it looks like the reason for this is that `explicitReferenceTargets` (Hover.cpp:1058) in this case returns two `NamedDecl`s, where the first is a `UsingEnumDecl` and the second is a `EnumConstantDecl`.

Hover then assumes the first element of the returned vector is always the one we need, even though we'd want the `EnumConstantDecl` in this case.

This btw also happens for other using declarations:

```
namespace ns { void foo(); }
void bar() {
    using ns::foo;
    foo(); // <- Hover refers to the using declaration instead of the function declaration
}
```

One solution would be to check if the first element is a `BaseUsingDecl` and if so use the second item of `explicitReferenceTargets` instead of the first one. With this, the regression test I added passes and all other Hover tests as well.

Or maybe `explicitReferenceTargets` itself should be fixed?

@sam-mccall @HighCommander4 what do you guys think?

**Comment by tom-anders** [comment] 2022-09-11 10:58
Proposed fix: https://reviews.llvm.org/D133664

**Closed** 2022-09-15 09:22 UTC
