### ISSUE TITLE
Massive memory consumption when indexing code with "new()" on heap

### ISSUE THREAD

**Issue by XinqiBao** [clangd/clangd#928] opened 2021-11-16 11:06 UTC
I use Vim/YouCompleteMe with clangd-completer installed as my Language Server.
When the plugin handle c++ code like below, its clangd process will "eats" up memory very quickly. Like, 30M for HOG_SIZE comes 9G on memory consumption in my case.
```
#define HOG_SIZE (300 * 1000 * 1000)
struct Hog {
    static Hog* hogSet;   // no matter it's static or not
    static void Init() { hogSet = new Hog[HOG_SIZE]; }
};
int main() { return 0; }
```
I have tried on clangd version 10.0.0, 12.0.0, and 13.0.0, also tried to clean up all the configs, the result stays the same.
Not sure whether it is cased by the same issue with #251 or not.

clangd version:
10.0.0, 12.0.0, 13.0.0

Editor/LSP plugin:
Vim/YouCompleteMe

Operating system:
Ubuntu 20.04.2 LTS
CentOS Linux release 7.8.2003 (Core)

**Comment by XinqiBao** [comment] 2021-11-16 11:07
BTW, the log
```
I[18:52:16.028] clangd version 12.0.0
I[18:52:16.029] PID: 2972865
I[18:52:16.029] Working directory: /home/baoxq/test
I[18:52:16.029] argv[0]: /home/baoxq/.vim/plugged/YouCompleteMe/third_party/ycmd/third_party/clangd/output/bin/clangd
I[18:52:16.029] argv[1]: -log=verbose
I[18:52:16.029] argv[2]: -header-insertion-decorators=0
I[18:52:16.029] argv[3]: -resource-dir=/home/baoxq/.vim/plugged/YouCompleteMe/third_party/ycmd/third_party/clang/lib/clang/12.0.0
I[18:52:16.029] argv[4]: -limit-results=500
V[18:52:16.029] User config file is /home/baoxq/.config/clangd/config.yaml
I[18:52:16.029] Starting LSP over stdin/stdout
V[18:52:16.029] <<< {"id":1,"jsonrpc":"2.0","method":"initialize","params":{"capabilities":{"textDocument":{"codeAction":{"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}}},"completion":{"completionItem":{"documentationFormat":["plaintext","markdown"]},"completionItemKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]}},"documentSymbol":{"hierarchicalDocumentSymbolSupport":false,"labelSupport":false,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]}},"hover":{"contentFormat":["plaintext","markdown"]},"signatureHelp":{"signatureInformation":{"documentationFormat":["plaintext","markdown"],"parameterInformation":{"labelOffsetSupport":true}}},"synchronization":{"didSave":true}},"workspace":{"applyEdit":true,"didChangeWatchedFiles":{"dynamicRegistration":true},"symbol":{"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]}},"workspaceEdit":{"documentChanges":true}}},"initializationOptions":{},"processId":2972615,"rootPath":"/home/baoxq/test","rootUri":"file:///home/baoxq/test"}}

I[18:52:16.029] <-- initialize(1)
I[18:52:16.031] --> reply:initialize(1) 2 ms
V[18:52:16.031] >>> {"id":1,"jsonrpc":"2.0","result":{"capabilities":{"astProvider":true,"callHierarchyProvider":true,"codeActionProvider":{"codeActionKinds":["quickfix","refactor","info"]},"compilationDatabase":{"automaticReload":true},"completionProvider":{"allCommitCharacters":[" ","\t","(",")","[","]","{","}","<",">",":",";",",","+","-","/","*","%","^","&","#","?",".","=","\"","'","|"],"resolveProvider":false,"triggerCharacters":[".","<",">",":","\"","/"]},"declarationProvider":true,"definitionProvider":true,"documentFormattingProvider":true,"documentHighlightProvider":true,"documentLinkProvider":{"resolveProvider":false},"documentOnTypeFormattingProvider":{"firstTriggerCharacter":"\n","moreTriggerCharacter":[]},"documentRangeFormattingProvider":true,"documentSymbolProvider":true,"executeCommandProvider":{"commands":["clangd.applyFix","clangd.applyTweak"]},"hoverProvider":true,"implementationProvider":true,"memoryUsageProvider":true,"referencesProvider":true,"renameProvider":true,"selectionRangeProvider":true,"semanticTokensProvider":{"full":{"delta":true},"legend":{"tokenModifiers":[],"tokenTypes":["variable","variable","parameter","function","method","function","property","variable","class","enum","enumMember","type","dependent","dependent","namespace","typeParameter","concept","type","macro","comment"]},"range":false},"signatureHelpProvider":{"triggerCharacters":["(",","]},"textDocumentSync":{"change":2,"openClose":true,"save":true},"typeHierarchyProvider":true,"workspaceSymbolProvider":true},"serverInfo":{"name":"clangd","version":"clangd version 12.0.0"}}}

V[18:52:16.033] <<< {"jsonrpc":"2.0","method":"initialized","params":{}}

I[18:52:16.033] <-- initialized
V[18:52:16.033] <<< {"jsonrpc":"2.0","method":"workspace/didChangeConfiguration","params":{"settings":{}}}

I[18:52:16.033] <-- workspace/didChangeConfiguration
V[18:52:16.033] <<< {"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"languageId":"cpp","text":"#include <iostream>\n\nusing namespace std;\n\n#define HOG_SIZE (30 * 1000 * 1000)\n\nstruct Hog {\n    Hog* hogSet;\n\n    void Init() { hogSet = new Hog[HOG_SIZE]; }\n};\n\nint main() {\n    cout << sizeof(Hog) << endl;\n\n    return 0;\n}\n","uri":"file:///home/baoxq/test/memhog_clang.cc","version":1}}}

I[18:52:16.033] <-- textDocument/didOpen
I[18:52:16.034] Failed to find compilation database for /home/baoxq/test/memhog_clang.cc
I[18:52:16.034] ASTWorker building file /home/baoxq/test/memhog_clang.cc version 1 with command clangd fallback
[/home/baoxq/test]
/usr/bin/clang /home/baoxq/test/memhog_clang.cc -fsyntax-only -resource-dir=/home/baoxq/.vim/plugged/YouCompleteMe/third_party/ycmd/third_party/clang/lib/clang/12.0.0
V[18:52:16.037] Driver produced command: cc1 -cc1 -triple x86_64-unknown-linux-gnu -fsyntax-only -disable-free -disable-llvm-verifier -discard-value-names -main-file-name memhog_clang.cc -mrelocation-model static -mframe-pointer=all -fmath-errno -fno-rounding-math -mconstructor-aliases -munwind-tables -target-cpu x86-64 -tune-cpu generic -fno-split-dwarf-inlining -debugger-tuning=gdb -resource-dir /home/baoxq/.vim/plugged/YouCompleteMe/third_party/ycmd/third_party/clang/lib/clang/12.0.0 -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9 -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/x86_64-linux-gnu/c++/9 -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/x86_64-linux-gnu/c++/9 -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/backward -internal-isystem /usr/local/include -internal-isystem /home/baoxq/.vim/plugged/YouCompleteMe/third_party/ycmd/third_party/clang/lib/clang/12.0.0/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -fdeprecated-macro -fdebug-compilation-dir /home/baoxq/test -ferror-limit 19 -fgnuc-version=4.2.1 -fcxx-exceptions -fexceptions -faddrsig -x c++ /home/baoxq/test/memhog_clang.cc
V[18:52:16.037] Building first preamble for /home/baoxq/test/memhog_clang.cc version 1
V[18:52:16.274] indexed preamble AST for /home/baoxq/test/memhog_clang.cc version 1:
  symbol slab: 6364 symbols, 1951704 bytes
  ref slab: 0 symbols, 0 refs, 128 bytes
  relations slab: 419 relations, 8728 bytes
V[18:52:16.302] Build dynamic index for header symbols with estimated memory usage of 5423896 bytes
V[18:52:16.306] Built preamble of size 2653976 for file /home/baoxq/test/memhog_clang.cc version 1
V[18:52:25.600] indexed file AST for /home/baoxq/test/memhog_clang.cc version 1:
  symbol slab: 5 symbols, 5376 bytes
  ref slab: 9 symbols, 14 refs, 4608 bytes
  relations slab: 0 relations, 24 bytes
V[18:52:25.600] Build dynamic index for main-file symbols with estimated memory usage of 14152 bytes
I[18:52:25.600] --> textDocument/publishDiagnostics
V[18:52:25.600] >>> {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[],"uri":"file:///home/baoxq/test/memhog_clang.cc","version":1}}
```

**Comment by HighCommander4** [comment] 2021-11-17 09:24
Definitely unrelated to #251, which had to do with clangd's own memory usage.

This is an upstream issue in the parser, reproducible by invoking the compiler directly. Output with a trunk build of clang:

```
$ clang++ -c main.cpp
LLVM ERROR: out of memory
Allocation failed
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.      Program arguments: clang++ -c main.cpp
1.      main.cpp:4:54: current parser token '}'
2.      main.cpp:2:1: parsing struct/union/class body 'Hog'
3.      main.cpp:4:24: parsing function body 'Hog::Init'
4.      main.cpp:4:24: in compound statement ('{}')
 #0 0x00007ff5302348e3 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/home/nr/programs/clang/dev/bin/../lib/libLLVMSupport.so.14git+0x1a88e3)
 #1 0x00007ff53023261e llvm::sys::RunSignalHandlers() (/home/nr/programs/clang/dev/bin/../lib/libLLVMSupport.so.14git+0x1a661e)
 #2 0x00007ff530233c5d llvm::sys::CleanupOnSignal(unsigned long) (/home/nr/programs/clang/dev/bin/../lib/libLLVMSupport.so.14git+0x1a7c5d)
 #3 0x00007ff530150313 (anonymous namespace)::CrashRecoveryContextImpl::HandleCrash(int, unsigned long) CrashRecoveryContext.cpp:0:0
 #4 0x00007ff5301504be CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #5 0x00007ff5341a1730 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x12730)
 #6 0x00007ff52f78d7bb raise /build/glibc-vjB4T1/glibc-2.28/signal/../sysdeps/unix/sysv/linux/raise.c:51:1
 #7 0x00007ff52f778535 abort /build/glibc-vjB4T1/glibc-2.28/stdlib/abort.c:81:7
 #8 0x00007ff530162b0d llvm::report_bad_alloc_error(char const*, bool) (/home/nr/programs/clang/dev/bin/../lib/libLLVMSupport.so.14git+0xd6b0d)
 #9 0x00007ff530162d62 (/home/nr/programs/clang/dev/bin/../lib/libLLVMSupport.so.14git+0xd6d62)
#10 0x00007ff52fd582cc operator new(unsigned long) /home/nr/builds/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/libsupc++/../../../../gcc-9.1.0/libstdc++-v3/libsupc++/new_op.cc:50:3
#11 0x00007ff52e0f659b clang::APValue::MakeArray(unsigned int, unsigned int) (/home/nr/programs/clang/dev/bin/../lib/../lib/libclangAST.so.14git+0x17459b)
#12 0x00007ff52e3d0f96 (anonymous namespace)::ArrayExprEvaluator::VisitCXXConstructExpr(clang::CXXConstructExpr const*, (anonymous namespace)::LValue const&, clang::APValue*, clang::QualType) ExprConstant.cpp:0:0
#13 0x00007ff52e38d1c4 (anonymous namespace)::PointerExprEvaluator::VisitCXXNewExpr(clang::CXXNewExpr const*) ExprConstant.cpp:0:0
#14 0x00007ff52e389191 EvaluatePointer(clang::Expr const*, (anonymous namespace)::LValue&, (anonymous namespace)::EvalInfo&, bool) ExprConstant.cpp:0:0
#15 0x00007ff52e3754e4 Evaluate(clang::APValue&, (anonymous namespace)::EvalInfo&, clang::Expr const*) ExprConstant.cpp:0:0
#16 0x00007ff52e379168 clang::StmtVisitorBase<llvm::make_const_ptr, (anonymous namespace)::LValueExprEvaluator, bool>::Visit(clang::Stmt const*) ExprConstant.cpp:0:0
#17 0x00007ff52e36fe81 EvaluateLValue(clang::Expr const*, (anonymous namespace)::LValue&, (anonymous namespace)::EvalInfo&, bool) ExprConstant.cpp:0:0
#18 0x00007ff52e375357 Evaluate(clang::APValue&, (anonymous namespace)::EvalInfo&, clang::Expr const*) ExprConstant.cpp:0:0
#19 0x00007ff52e372b4c EvaluateAsRValue((anonymous namespace)::EvalInfo&, clang::Expr const*, clang::APValue&) ExprConstant.cpp:0:0
#20 0x00007ff52e372d28 clang::Expr::EvaluateForOverflow(clang::ASTContext const&) const (/home/nr/programs/clang/dev/bin/../lib/../lib/libclangAST.so.14git+0x3f0d28)
#21 0x00007ff52cf72b2c clang::Sema::CheckForIntOverflow(clang::Expr*) (/home/nr/programs/clang/dev/bin/../lib/../lib/libclangSema.so.14git+0x21ab2c)
#22 0x00007ff52cf7314e clang::Sema::CheckCompletedExpr(clang::Expr*, clang::SourceLocation, bool) (/home/nr/programs/clang/dev/bin/../lib/../lib/libclangSema.so.14git+0x21b14e)
#23 0x00007ff52d27bf9a clang::Sema::ActOnFinishFullExpr(clang::Expr*, clang::SourceLocation, bool, bool) (/home/nr/programs/clang/dev/bin/../lib/../lib/libclangSema.so.14git+0x523f9a)
#24 0x00007ff52d49cf91 clang::Sema::ActOnExprStmt(clang::ActionResult<clang::Expr*, true>, bool) (/home/nr/programs/clang/dev/bin/../lib/../lib/libclangSema.so.14git+0x744f91)
#25 0x00007ff52da19d62 clang::Parser::ParseExprStatement(clang::Parser::ParsedStmtContext) (/home/nr/programs/clang/dev/bin/../lib/../lib/libclangParse.so.14git+0xf3d62)
#26 0x00007ff52da1947f clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::ParsedAttributesWithRange&) (/home/nr/programs/clang/dev/bin/../lib/../lib/libclangParse.so.14git+0xf347f)
#27 0x00007ff52da17821 clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*) (/home/nr/programs/clang/dev/bin/../lib/../lib/libclangParse.so.14git+0xf1821)
#28 0x00007ff52da216b1 clang::Parser::ParseCompoundStatementBody(bool) (/home/nr/programs/clang/dev/bin/../lib/../lib/libclangParse.so.14git+0xfb6b1)
#29 0x00007ff52da226e8 clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) (/home/nr/programs/clang/dev/bin/../lib/../lib/libclangParse.so.14git+0xfc6e8)
#30 0x00007ff52d9629cd clang::Parser::ParseLexedMethodDef(clang::Parser::LexedMethod&) (/home/nr/programs/clang/dev/bin/../lib/../lib/libclangParse.so.14git+0x3c9cd)
#31 0x00007ff52d96112a clang::Parser::ParseLexedMethodDefs(clang::Parser::ParsingClass&) (/home/nr/programs/clang/dev/bin/../lib/../lib/libclangParse.so.14git+0x3b12a)
#32 0x00007ff52d99c7da clang::Parser::ParseCXXMemberSpecification(clang::SourceLocation, clang::SourceLocation, clang::ParsedAttributesWithRange&, unsigned int, clang::Decl*) (/home/nr/programs/clang/dev/bin/../lib/../lib/libclangParse.so.14git+0x767da)
#33 0x00007ff52d99a1ae clang::Parser::ParseClassSpecifier(clang::tok::TokenKind, clang::SourceLocation, clang::DeclSpec&, clang::Parser::ParsedTemplateInfo const&, clang::AccessSpecifier, bool, clang::Parser::DeclSpecContext, clang::ParsedAttributesWithRange&) (/home/nr/programs/clang/dev/bin/../lib/../lib/libclangParse.so.14git+0x741ae)
#34 0x00007ff52d972e0e clang::Parser::ParseDeclarationSpecifiers(clang::DeclSpec&, clang::Parser::ParsedTemplateInfo const&, clang::AccessSpecifier, clang::Parser::DeclSpecContext, clang::Parser::LateParsedAttrList*) (/home/nr/programs/clang/dev/bin/../lib/../lib/libclangParse.so.14git+0x4ce0e)
#35 0x00007ff52da3eeda clang::Parser::ParseDeclOrFunctionDefInternal(clang::ParsedAttributesWithRange&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/home/nr/programs/clang/dev/bin/../lib/../lib/libclangParse.so.14git+0x118eda)
#36 0x00007ff52da3ebe5 clang::Parser::ParseDeclarationOrFunctionDefinition(clang::ParsedAttributesWithRange&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (/home/nr/programs/clang/dev/bin/../lib/../lib/libclangParse.so.14git+0x118be5)
#37 0x00007ff52da3d8f2 clang::Parser::ParseExternalDeclaration(clang::ParsedAttributesWithRange&, clang::ParsingDeclSpec*) (/home/nr/programs/clang/dev/bin/../lib/../lib/libclangParse.so.14git+0x1178f2)
#38 0x00007ff52da3b8af clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, bool) (/home/nr/programs/clang/dev/bin/../lib/../lib/libclangParse.so.14git+0x1158af)
#39 0x00007ff52da3b097 clang::Parser::ParseFirstTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&) (/home/nr/programs/clang/dev/bin/../lib/../lib/libclangParse.so.14git+0x115097)
#40 0x00007ff52d95d3a7 clang::ParseAST(clang::Sema&, bool, bool) (/home/nr/programs/clang/dev/bin/../lib/../lib/libclangParse.so.14git+0x373a7)
#41 0x00007ff532a4cfe0 clang::FrontendAction::Execute() (/home/nr/programs/clang/dev/bin/../lib/libclangFrontend.so.14git+0x124fe0)
#42 0x00007ff5329c4baf clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/home/nr/programs/clang/dev/bin/../lib/libclangFrontend.so.14git+0x9cbaf)
#43 0x00007ff53418ad43 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/home/nr/programs/clang/dev/bin/../lib/libclangFrontendTool.so.14git+0x3d43)
#44 0x0000000000411e46 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/home/nr/programs/clang/dev/bin/clang-14+0x411e46)
#45 0x000000000040fcfd ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) driver.cpp:0:0
#46 0x00007ff532730d42 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, bool*) const::$_1>(long) Job.cpp:0:0
#47 0x00007ff530150227 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/home/nr/programs/clang/dev/bin/../lib/libLLVMSupport.so.14git+0xc4227)
#48 0x00007ff532730787 clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, bool*) const (/home/nr/programs/clang/dev/bin/../lib/libclangDriver.so.14git+0xaf787)
#49 0x00007ff5326f7a48 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&) const (/home/nr/programs/clang/dev/bin/../lib/libclangDriver.so.14git+0x76a48)
#50 0x00007ff5326f7d47 clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) const (/home/nr/programs/clang/dev/bin/../lib/libclangDriver.so.14git+0x76d47)
#51 0x00007ff532713a58 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) (/home/nr/programs/clang/dev/bin/../lib/libclangDriver.so.14git+0x92a58)
```

**Comment by HighCommander4** [comment] 2021-11-17 09:29
Reported upstream as https://bugs.llvm.org/show_bug.cgi?id=52530

**Comment by kadircet** [comment] 2021-11-19 11:10
this is a duplicate of https://bugs.llvm.org/show_bug.cgi?id=51712.

**Closed by kadircet** 2021-11-19 11:10 UTC
Labels: upstream
