### ISSUE TITLE
Support CompileFlags order and include replacement.

### ISSUE THREAD

**Issue by Falven** [clangd/clangd#777] opened 2021-05-18 14:14 UTC
Hello again,
This is a follow-up to [the issue I opened yesterday](https://github.com/clangd/clangd/issues/776).
Thank you @HighCommander4 for your comment.

After some more research, and comparison of the compilation command between the Arduino CLI and clangd, I found some inconsistencies between the compilation commands.

Again, for a running sample [see here](https://github.com/Falven/clangd-arduino).

One inconsistency is that the file is being compiled with the `-x c++-header` flag. Makes sense that `clangd` doesn't know `.ino` files are supposed to be `.cpp` files. To fix, I created this `.clangd` configuration:

```
If:
  PathMatch: .*\.ino
CompileFlags:
  Remove: -x
  Add: [-xc++]
```

However, the `-xc++` flag is being appended to the very end of the command.

```
C:\Users\falve\AppData\Local\Arduino15\packages\arduino\tools\arm-none-eabi-gcc\7-2017q4\bin\arm-none-eabi-g++.exe --target=arm-none-eabi --driver-mode=g++ -mcpu=cortex-m0plus -mthumb -c -g -Os -w -ffunction-sections -fdata-sections -fno-threadsafe-statics -nostdlib --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -DF_CPU=48000000L -DARDUINO=10607 -DARDUINO_SAMD_MKRWIFI1010 -DARDUINO_ARCH_SAMD -DUSE_ARDUINO_MKR_PIN_LAYOUT -D__SAMD21G18A__ -DUSB_VID=0x2341 -DUSB_PID=0x8054 -DUSBCON -DUSB_MANUFACTURER="Arduino LLC" -DUSB_PRODUCT="Arduino MKR WiFi 1010" -DUSE_BQ24195L_PMIC -IC:\Users\falve\AppData\Local\Arduino15\packages\arduino\tools\CMSIS\4.5.0/CMSIS/Include/ -IC:\Users\falve\AppData\Local\Arduino15\packages\arduino\tools\CMSIS-Atmel\1.2.0/CMSIS/Device/ATMEL/ -IC:\Users\falve\AppData\Local\Arduino15\packages\arduino\hardware\samd\1.8.11\cores\arduino/api/deprecated -IC:\Users\falve\AppData\Local\Arduino15\packages\arduino\hardware\samd\1.8.11\cores\arduino/api/deprecated-avr-comp -IC:\Users\falve\AppData\Local\Arduino15\packages\arduino\hardware\samd\1.8.11\cores\arduino -IC:\Users\falve\AppData\Local\Arduino15\packages\arduino\hardware\samd\1.8.11\variants\mkrwifi1010 -std=gnu++11 c:\source\repos\clangd-arduino\clangd-arduino.ino -isystem c:\users\falve\appdata\local\arduino15\packages\arduino\tools\arm-none-eabi-gcc\7-2017q4\bin\../lib/gcc/arm-none-eabi/7.2.1/../../../../arm-none-eabi/include/c++/7.2.1 -isystem c:\users\falve\appdata\local\arduino15\packages\arduino\tools\arm-none-eabi-gcc\7-2017q4\bin\../lib/gcc/arm-none-eabi/7.2.1/../../../../arm-none-eabi/include/c++/7.2.1/arm-none-eabi -isystem c:\users\falve\appdata\local\arduino15\packages\arduino\tools\arm-none-eabi-gcc\7-2017q4\bin\../lib/gcc/arm-none-eabi/7.2.1/../../../../arm-none-eabi/include/c++/7.2.1/backward -isystem c:\users\falve\appdata\local\arduino15\packages\arduino\tools\arm-none-eabi-gcc\7-2017q4\bin\../lib/gcc/arm-none-eabi/7.2.1/include -isystem c:\users\falve\appdata\local\arduino15\packages\arduino\tools\arm-none-eabi-gcc\7-2017q4\bin\../lib/gcc/arm-none-eabi/7.2.1/include-fixed -isystem c:\users\falve\appdata\local\arduino15\packages\arduino\tools\arm-none-eabi-gcc\7-2017q4\bin\../lib/gcc/arm-none-eabi/7.2.1/../../../../arm-none-eabi/include -xc++ -fsyntax-only -resource-dir=c:\Users\falve\AppData\Roaming\Code\User\globalStorage\llvm-vs-code-extensions.vscode-clangd\install\12.0.0\clangd_12.0.0\lib\clang\12.0.0
```

in reality, it should come before the source input file in the command:

```
C:\Users\falve\AppData\Local\Arduino15\packages\arduino\tools\arm-none-eabi-gcc\7-2017q4\bin\arm-none-eabi-g++.exe --target=arm-none-eabi --driver-mode=g++ -mcpu=cortex-m0plus -mthumb -c -g -Os -w -ffunction-sections -fdata-sections -fno-threadsafe-statics -nostdlib --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -DF_CPU=48000000L -DARDUINO=10607 -DARDUINO_SAMD_MKRWIFI1010 -DARDUINO_ARCH_SAMD -DUSE_ARDUINO_MKR_PIN_LAYOUT -D__SAMD21G18A__ -DUSB_VID=0x2341 -DUSB_PID=0x8054 -DUSBCON -DUSB_MANUFACTURER="Arduino LLC" -DUSB_PRODUCT="Arduino MKR WiFi 1010" -DUSE_BQ24195L_PMIC -IC:\Users\falve\AppData\Local\Arduino15\packages\arduino\tools\CMSIS\4.5.0/CMSIS/Include/ -IC:\Users\falve\AppData\Local\Arduino15\packages\arduino\tools\CMSIS-Atmel\1.2.0/CMSIS/Device/ATMEL/ -IC:\Users\falve\AppData\Local\Arduino15\packages\arduino\hardware\samd\1.8.11\cores\arduino/api/deprecated -IC:\Users\falve\AppData\Local\Arduino15\packages\arduino\hardware\samd\1.8.11\cores\arduino/api/deprecated-avr-comp -IC:\Users\falve\AppData\Local\Arduino15\packages\arduino\hardware\samd\1.8.11\cores\arduino -IC:\Users\falve\AppData\Local\Arduino15\packages\arduino\hardware\samd\1.8.11\variants\mkrwifi1010 -xc++ -std=gnu++11 c:\source\repos\clangd-arduino\clangd-arduino.ino -isystem c:\users\falve\appdata\local\arduino15\packages\arduino\tools\arm-none-eabi-gcc\7-2017q4\bin\../lib/gcc/arm-none-eabi/7.2.1/../../../../arm-none-eabi/include/c++/7.2.1 -isystem c:\users\falve\appdata\local\arduino15\packages\arduino\tools\arm-none-eabi-gcc\7-2017q4\bin\../lib/gcc/arm-none-eabi/7.2.1/../../../../arm-none-eabi/include/c++/7.2.1/arm-none-eabi -isystem c:\users\falve\appdata\local\arduino15\packages\arduino\tools\arm-none-eabi-gcc\7-2017q4\bin\../lib/gcc/arm-none-eabi/7.2.1/../../../../arm-none-eabi/include/c++/7.2.1/backward -isystem c:\users\falve\appdata\local\arduino15\packages\arduino\tools\arm-none-eabi-gcc\7-2017q4\bin\../lib/gcc/arm-none-eabi/7.2.1/include -isystem c:\users\falve\appdata\local\arduino15\packages\arduino\tools\arm-none-eabi-gcc\7-2017q4\bin\../lib/gcc/arm-none-eabi/7.2.1/include-fixed -isystem c:\users\falve\appdata\local\arduino15\packages\arduino\tools\arm-none-eabi-gcc\7-2017q4\bin\../lib/gcc/arm-none-eabi/7.2.1/../../../../arm-none-eabi/include -fsyntax-only -resource-dir=c:\Users\falve\AppData\Roaming\Code\User\globalStorage\llvm-vs-code-extensions.vscode-clangd\install\12.0.0\clangd_12.0.0\lib\clang\12.0.0
```

The compiler complains:
`arm-none-eabi-g++.exe: warning: '-x c++' after last input file has no effect`

Edit:
I am also trying to figure out if there is a way to perform include style replacement. E.g.:
Replace All `-isystemc:/some/path/to/include/` with `-Ic:/some/path/to/include/` as the compiler I am using implicitly performs C linkage for `-isystem` includes. In the meantime going to see if there is another way to address this.

Edit 2:
[It is a bug with this compiler **from 2017**](https://bugs.launchpad.net/gcc-arm-embedded/+bug/1698539). So I doubt I will ever see an update that addresses the bug directly. A replacement will be the ideal solution.

**System information**
clangd version 11.0.0
Editor/LSP plugin: VSCode clangd
Operating system: Windows 10 x64 Version 10.0.19043 Build 19043

**Comment by kadircet** [comment] 2021-05-19 14:42
unfortunately this is a dupe of #555.

as for the replacement of parts of flags, it is not something we support today, but might consider.

**Comment by Falven** [comment] 2021-05-19 15:31
> unfortunately this is a dupe of #555.
> 
> as for the replacement of parts of flags, it is not something we support today, but might consider.

@kadircet I resolved the second issue by manually upgrading the compiler, for now, but this may break the rest of the Arduino framework.

**Comment by JPTIZ** [comment] 2021-12-24 23:57
Looks like this one is fixed now: https://github.com/clangd/clangd/issues/555#event-5061633899

**Comment by sam-mccall** [comment] 2021-12-25 00:58
Yep, -x is fixed. 
(Meanwhile, I don't think we've seen other cases that need search/replace in args)

**Closed by sam-mccall** 2021-12-25 00:58 UTC
