### ISSUE TITLE
Implement textDocument/callHierarchy

### ISSUE THREAD

**Issue by HighCommander4** [clangd/clangd#162] opened 2019-09-30 00:51 UTC
I would like to implement a call hierarchy feature, where the callers of a function, and their callers in turn, are visualized in a tree view (possibly lazily populated, similar to type hierarchy).

There is a [proposed LSP extension](https://github.com/Microsoft/vscode-languageserver-node/pull/420) for this, `"textDocument/callHierarchy"`, which is in a fairly mature state (its reference implementation in nodejs has merged, but it has not appeared in an LSP release yet).

I would like to discuss and agree on the design -- particularly about changes to the index data structures -- before doing implementation work. I assume this issue is a good place for such discussion.

There was some previous discussion of this during the review of type hierarchy (when we contemplated using the same data structure for both), which is useful background: please see [this review comment](https://reviews.llvm.org/D59407#1447070) and the comments that follow, until [this one](https://reviews.llvm.org/D59407#1478794).

Reviewing that discussion, it sounds like the most straightforward way to implement this wouid be to extend the `Ref` class to store the `SymbolID` of the referencing entity. Then a call hierarchy request would proceed as follows:

  * Find the refs of the function on which call hierarchy was invoked.
  * Filter to those references which are calls. (We can extend `RefKind` for this purpose.) This provides the first level of the call hierarchy.
  * Take the `SymbolID`s from those `Ref`s and search for their references in turn, providing the next level of the call hierarchy, and so on until the number of levels requested by the client have been computed.

Does this still seem like the desirable approach?

@sam-mccall @hokein @ilya-biryukov @kadircet @gribozavr

**Comment by HighCommander4** [comment] 2019-10-28 00:05
Just wanted to ping about this. I'm eager to get started on this work and would appreciate your feedback on the proposed design!

**Comment by kadircet** [comment] 2019-10-29 15:01
Hi Nathan!

First of all thanks for taking a look at this, and sorry for the late reply.

There are a couple of things to consider while implementing LSP extensions, especially if they are expensive, we need to make sure irrelevant users don't pay for these costs.

We believe that call hierarchy falls into that expensive bucket due to its implications on disk and runtime memory usage. So it would be nice to implement it behind a flag, until it is widely adopted by most of the editors being used with clangd.

That being said, there are a couple of different approaches we could try that would result in different tradeoffs:
- do we just want a callee/caller information between functions ?
- do we care about locations of the calls ?
- do we rather want a general "contained by/contains" information ?

As for approaches:
1- using relation slabs, with a new relation kind called "callee/caller" that only creates these relations between functions. lacking relation information
2- using relation slabs again, same as above but creating these relations between every type of symbols, not just functions, with a kind called "containedin". again lacking relation info.
3- your proposed solution, adding another `SymbolID` to `Ref` for reflecting a "Container".

To illustrate the three:
```cpp
class X;
void bar() {
  X x;
  aux();
}
void foo() {
  bar();
  bar();
  X y;
}
```

- The first approach would result in two relations:
  - `foo is caller of bar`
  - `bar is caller of aux`
- The second would result in 4:
  - `bar is contained in foo`
  - `aux is contained in bar`
  - `X is contained in bar`
  - `X is contained in foo`
- The last one would result in 5, with loc informations:
  - `bar is contained in foo at loc1`
  - `bar is contained in foo at loc2`
  -  `aux is contained in bar at loc3`
  - `X is contained in bar at loc4`
  - `X is contained in foo at loc5`

It would be nice to see some numbers around disk/memory usage of clangd index on LLVM project. I believe for the last one it should be enough to just add the field into `Ref` structure, populate it with dummy IDs and implement serialization/deserialization logic to see numbers, but for the first two, you might need to change logic in `SymbolCollector`.

As for putting behind a flag, it should rather be easy for the `RelationSlab` based model since we can hide it in `SymbolCollector`, but I believe it will rather be harder for the `Ref` one. We can discuss it more, after we decide with which implementation we'll move forward.

**Comment by widgetii** [comment] 2019-10-29 16:37
Hi, guys

It would be nice to implement CodeLens feature using same data structures too. https://github.com/microsoft/language-server-protocol/blob/master/versions/protocol-2-x.md#textDocument_codeLens

It seems that only cquery supports it now.

**Comment by HighCommander4** [comment] 2019-10-29 21:59
> To illustrate the three:
> 
> ```c++
> class X;
> void bar() {
>   X x;
>   aux();
> }
> void foo() {
>   bar();
>   bar();
>   X y;
> }
> ```
> 
>     * The first approach would result in two relations:
>       
>       * `foo is caller of bar`
>       * `bar is caller of aux`
> 
>     * The second would result in 4:
>       
>       * `bar is contained in foo`
>       * `aux is contained in bar`
>       * `X is contained in bar`
>       * `X is contained in foo`
> 
>     * The last one would result in 5, with loc informations:
>       
>       * `bar is contained in foo at loc1`
>       * `bar is contained in foo at loc2`
>       * `aux is contained in bar at loc3`
>       * `X is contained in bar at loc4`
>       * `X is contained in foo at loc5`

I think we want the third one, for a couple of reasons.

  * Location information is useful for being able to navigate to the site of a call from the call hierarchy view (e.g. by double-clicking on an entry in the hierarchy). This is very useful if you're e.g. tracing the origin of a parameter which is passed through several level of calls to a target function. Having to separately call "Find references" find the location, or manually scan the function body for the reference, is a lot more cumbersome by comparison.
  * This is the most general representation of the three, and can serve as the basis for other features as well. For example, I recently filed https://github.com/clangd/clangd/issues/177 for annotating references with the name of the function in which they occur; that would also require locations. By contrast, if we go with the first or second approach, we might just find ourselves later wanting to switch to the third, or add location data separately, to accomoddte additional use cases.

I agree that disk and memory usage is a potential concern. Two observations here:

  * The description above makes it appear like the third option requires a lot more space, but note that information like "bar is contained at loc1" is already stored in the existing `Ref` table, so the added cost would just be the incremental cost of storing the "in foo" part.
  * There is prior art for C++ IDEs supporting this feature (including location information) going back at least 10 years (with Eclipse CDT being a concrete example), which suggests the overhead isn't prohibitive.

I'm certainly happy to take some measurements of disk and memory usage for this third approach, using your suggestion of adding a dummy field to the `Ref` structure.

**Comment by HighCommander4** [comment] 2019-10-29 22:02
> It would be nice to implement CodeLens feature using same data structures too. https://github.com/microsoft/language-server-protocol/blob/master/versions/protocol-2-x.md#textDocument_codeLens

Are you referring to the "number of references" code lens? That seems like something we could implement using the existing index data which powers "find references". I would suggest filing a new issue so we don't forget about it.

**Comment by HighCommander4** [comment] 2019-11-13 02:25
> I'm certainly happy to take some measurements of disk and memory usage for this third approach, using your suggestion of adding a dummy field to the `Ref` structure.

I've done this for the LLVM codebase, and have found that the size of the index on disk increased from 60 MB to 81 MB.

I'm not sure what is the best way to measure memory usage. The virtual memory size of the process in `top` seems to have actually _decreased_ (3.1 GB to 2.4 GB), which probably means there are other factors contributing to that.

**Comment by MarkZ3** [comment] 2019-11-13 03:40
Just throwing a user's opinions out there: 81MB seems perfectly reasonable to me considering CDT's index for LLVM I have is 454MB. I've seen people using Visual Assist with similar sized projects and it takes GBs on disk and users still think it's OK.

**Comment by HighCommander4** [comment] 2019-11-13 03:51
> Just throwing a user's opinions out there: 81MB seems perfectly reasonable to me considering CDT's index for LLVM I have is 454MB.

I should mention that my measurements used the build configuration of LLVM which I use to develop clangd, which includes `-DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra"` and `-DLLVM_TARGETS_TO_BUILD=X86`. This does exclude parts of the LLVM tree from the build, so the comparison to CDT's index size may not be apples-to-apples.

**Comment by MarkZ3** [comment] 2019-11-13 03:59
> This does exclude parts of the LLVM tree from the build, so the comparison to CDT's index size may not be apples-to-apples.

Fair point, I had -DLLVM_ENABLE_PROJECTS=clang;clang-tools-extra;lldb;libcxx;libcxxabi -DLLVM_TARGETS_TO_BUILD=X86

**Comment by kadircet** [comment] 2019-11-13 10:46
> > I'm certainly happy to take some measurements of disk and memory usage for this third approach, using your suggestion of adding a dummy field to the `Ref` structure.
> 
> I've done this for the LLVM codebase, and have found that the size of the index on disk increased from 60 MB to 81 MB.
> 
> I'm not sure what is the best way to measure memory usage. The virtual memory size of the process in `top` seems to have actually _decreased_ (3.1 GB to 2.4 GB), which probably means there are other factors contributing to that.

So this sounds like ~35% increase in disk size. For memory you can check the clangd logs, after building serving structures, it will print something like:

`BackgroundIndex: serving version 2 (648548346 bytes)`

**Comment by HighCommander4** [comment] 2019-11-15 06:48
Serving structure size has gone from 445 MB to 502 MB, a 12.8% increase. I guess that's less than for disk usage because the memory representation is less space-efficient (e.g. includes more padding bytes) than the disk representation.

Any thoughts on whether these increases would be acceptable?

**Comment by ChristianKuehnel** [comment] 2019-11-21 08:49
We have a few fairly large projects. Let me clarify if the increase in memory is actually a show stopper for these. They have already been complaining about the memory requirements of clangd. I'll get back to this thread when I have some feedback...

**Comment by HighCommander4** [comment] 2019-11-22 03:53
> > * The first approach would result in two relations:
> >   
> >   * `foo is caller of bar`
> >   * `bar is caller of aux`
> > 
> > * The second would result in 4:
> >   
> >   * `bar is contained in foo`
> >   * `aux is contained in bar`
> >   * `X is contained in bar`
> >   * `X is contained in foo`
> > 
> > * The last one would result in 5, with loc informations:
> >   
> >   * `bar is contained in foo at loc1`
> >   * `bar is contained in foo at loc2`
> >   * `aux is contained in bar at loc3`
> >   * `X is contained in bar at loc4`
> >   * `X is contained in foo at loc5`
> > ```
> 
> I think we want the third one, for a couple of reasons. [...]

In my eagerness to describe what I would like as a user, I forgot a very important consideration: what the [proposed `textDocument/callHierarchy` protocol](https://github.com/Microsoft/vscode-languageserver-node/pull/420) specifies :)

The protocol says the response to a call hierarchy request is a list of objects of this form:

```
interface CallHierarchyCall {
    range: Range,
    form: CallHierarchySymbol,
    to: CallHierarchySymbol
};
```

where an object of this type represents a single caller-callee relationship. `CallHierarchySymbol` contains information similar to e.g. `DocumentSymbol` (i.e., things we would need a `Symbol` object to derive).

Note that these relationship objects contain the location (`range`) of the reference.

So, if we are to conform to the protocol as proposed, we would need to go with the third option.

**Comment by HighCommander4** [comment] 2019-11-26 18:03
> So, if we are to conform to the protocol as proposed, we would need to go with the third option.

I guess I should qualify that claim a bit. We could conceivably conform to the protocol without storing things exactly as described in the third option.

For example, we could, instead:

  * Store caller-callee relationships (without location info) in the `Relation` slab (as per options 1 or 2)
  * Extend `Symbol` to store an additional `SymbolLocation` covering the entire range of the symbol's definition (e.g. the entire function body)
  * When handling the request:
      1. Look up the callers in the `Relation` slab
      2. For each caller, look it up in the `Symbol` slab and get its definition range
      3. Look up the callee in the `Ref` slab, and filter the refs to those which fall within the caller's definition range, to reconstitue the locations of the individual calls

This could yield some space savings, at the cost of added implementation complexity, and possibly runtime performance and accuracy (the latter because physical containment of the range doesn't necessarily imply semantic containment).

**Comment by HighCommander4** [comment] 2019-12-18 03:06
To summarize our options here:

  1. **Store the enclosing symbol for all Refs.** (The third out of Kadir's [original options](https://github.com/clangd/clangd/issues/162#issuecomment-547465078).) This should be fairly straightforward to implement, and the most general one in terms of what features it will enable. It does come with a disk and memory usage cost, measured on an example project (LLVM) to be 35% (disk) and 13% (memory), as described [above](https://github.com/clangd/clangd/issues/162#issuecomment-554236435).

 2. **Store caller-callee Relations + the ranges of symbol definitions.** This should allow inferring location information in most cases, as described in the [previous comment](https://github.com/clangd/clangd/issues/162#issuecomment-558750135). This will likely save some space and memory (has not been implemented and measured), at the cost of added implementation complexity, runtime performance, and accuracy.

 3. **Store caller-callee Relations without any additional info.** (The first or second out of Kadir's [original options](https://github.com/clangd/clangd/issues/162#issuecomment-547465078).) This is the most space-efficient approach, but importantly, **would not allow us to implement `textDocument/callHierarchy` as specified** (since it is specified to include location information).

I would really appreciate some guidance of which of the options to pursue, so that I can begin implementation work!

**Comment by sam-mccall** [comment] 2020-01-08 15:43
Some feedback on usefulness from tobiashieta on discord whose team is mixed clang/ccls:

> one of the devs asked for a "view all callers of this function" dialog that's something he use a lot in ccls.

@HighCommander4 Sorry for the indecision and delay here, this is a hard call.

I think #1 is the best in terms of functionality, and the tradeoff in resources has been a hard call to make because we don't have a good alternative to background indexing for large projects. However I think we now have a plan - we'll build a separate (sharable) index server of some form in this year.

So we're on board with #1 now if you're happy with it (I talked to @kadircet offline). Thanks for bearing with us!

**Comment by HighCommander4** [comment] 2020-01-09 22:17
Thanks @sam-mccall! I'll give implement option 1 a try.

**Comment by tabir** [comment] 2020-02-29 07:32
@HighCommander4, can I try out your solution for option 3?

**Comment by HighCommander4** [comment] 2020-02-29 17:35
@tabir As in, you would like to try implementing it? Sure, I don't mind. I haven't had a chance to start on it yet.

**Comment by tabir** [comment] 2020-02-29 18:01
@HighCommander4, sorry, I got the impression you did or at least started a poc.

**Comment by HighCommander4** [comment] 2020-02-29 19:22
@tabir Ah, ok, you meant try using it. Yeah, there's nothing available to try yet. I will post here when there is.

**Comment by HighCommander4** [comment] 2020-06-09 06:34
While working on implementing this, I realized that our chosen option:

>    1. **Store the enclosing symbol for all Refs.** (The third out of Kadir's [original options](https://github.com/clangd/clangd/issues/162#issuecomment-547465078).) This should be fairly straightforward to implement, and the most general one in terms of what features it will enable. It does come with a disk and memory usage cost, measured on an example project (LLVM) to be 35% (disk) and 13% (memory), as described [above](https://github.com/clangd/clangd/issues/162#issuecomment-554236435).

is suitable for implementing the **callers** side of the call hierarchy, but not the **callees** side, which is also part of the protocol. Indeed, the algorithm I described at the beginning for implementing "call hierarchy":

> I would like to implement a call hierarchy feature, where the callers of a function, and their callers in turn, are visualized in a tree view (possibly lazily populated, similar to type hierarchy).
> 
> [...] Then a call hierarchy request would proceed as follows:
> 
>    * Find the refs of the function on which call hierarchy was invoked.
> 
>    * Filter to those references which are calls. (We can extend `RefKind` for this purpose.) This provides the first level of the call hierarchy.
> 
>    * Take the `SymbolID`s from those `Ref`s and search for their references in turn, providing the next level of the call hierarchy, and so on until the number of levels requested by the client have been computed.

only considers finding callers and not callees.

By contrast, the alternative approaches of storing caller-callee Relations are suitable for finding both callers and callees (at the cost of having to maintain each relation in duplicate, a caller --> callee relation, and a callee --> caller relation, for lookup purposes).

Am I perhaps overlooking an efficient way to find callees given our existing index data structures (with `Ref` amended with the proposed "referrer" / "enclosing symbol" field)? Or do we need to reconsider our choice here?

**Comment by HighCommander4** [comment] 2020-06-09 06:47
> Am I perhaps overlooking an efficient way to find callees given our existing index data structures (with `Ref` amended with the proposed "referrer" / "enclosing symbol" field)?

I guess we could just build a reverse lookup table for referrers when building our serving structures from the `RefSlab`?

**Comment by kadircet** [comment] 2020-06-09 09:44
> Am I perhaps overlooking an efficient way to find callees given our existing index data structures (with Ref amended with the proposed "referrer" / "enclosing symbol" field)? Or do we need to reconsider our choice here?

it depends on what `get functions called by this function` workflow looks like. From my reading of the proposal attached in the first comment, it is going to be invoked from current file. Hence we'll have the AST available for the function body. Therefore we can just look into AST to figure out functions called by it.

but if LSP extends the proposal to recursively ask for callees inside callees then it might be necessary to use index (and possibly some extra data propagation to stash symbol IDs of callees in case of a lazy resolve)

**Comment by HighCommander4** [comment] 2020-06-09 16:59
> but if LSP extends the proposal to recursively ask for callees inside callees then it might be necessary to use index (and possibly some extra data propagation to stash symbol IDs of callees in case of a lazy resolve)

Yes, I believe that's the intention, to populate a tree view with multiple levels. An AST-based search could work for the initial invocation in the current file, but I don't think we'd want to then build an AST for a callee in another file to find its callees in turn.

**Comment by sam-mccall** [comment] 2020-06-09 22:03
We could consider not implementing that part.
My sense is that callers is a bit more useful than callees, and recursive is only a bit more useful than a single level. So even if we don't find a way to implement recursive callees, we're still getting most of the value.

That said, adding a lookup ref by container structure seems ok to me.

**Comment by HighCommander4** [comment] 2020-06-22 06:19
I ran into another issue that affects callers as well:

>    * Find the refs of the function on which call hierarchy was invoked.
> 
>    * Filter to those references which are calls. (We can extend `RefKind` for this purpose.) This provides the first level of the call hierarchy.
> 
>    * Take the `SymbolID`s from those `Ref`s and search for their references in turn, providing the next level of the call hierarchy, and so on until the number of levels requested by the client have been computed.

Clangd does not currently store references to "main-file only" functions (that is, functions that are local to a .cpp file, such as static functions and functions declared in the anonymous namespace) in the index.

This is fine when it comes to invoking call hierarchy directly on a main-file function; since the callers of a main-file function are in the same file, we can find these using the AST.

However, if you invoke call hierarchy on some initial function A, and one of its callers is a main-file function in a different file, then we can't find the callers of _that_ using either the AST (since it's in a different file) or the index (since such references are not indexed).

**Comment by kadircet** [comment] 2020-06-24 16:23
Right :/ I suppose we can leave that as a limitation for now, as user can still navigate to that file and get desired caller information (and for such a symbol callers have to be in the implementation file)

As for the solution, the most obvious way would be to start collecting references to implementation details. I suppose this was an optimization for saving space (as you've noted we don't need them for any other lsp features, when they are applicable they're always available through AST). It seems to be introduced with https://github.com/llvm/llvm-project/commit/e83caccb58cd360368fcda4381b63f6b43c84032 and only concern in the patch seems to be around number of calls to `shouldCollectSymbol` rather than number of refs in the end.
Any chance this was a random consequence and we can safely change the order of `shouldCollectSymbol` check and reference recording @sam-mccall @hokein ?

In any case, it would be great if you could run an experiment over LLVM to see how this affects disk and memory usage.

**Comment by HighCommander4** [comment] 2020-06-24 17:23
> I suppose we can leave that as a limitation for now, as user can still navigate to that file and get desired caller information (and for such a symbol callers have to be in the implementation file)

Note that it has the potential to be a fairly significant limitation.

To take an example from the clangd codebase itself: suppose I want to know which LSP messages involve using `SelectionTree`. I invoke call hierarchy on `SelectionTree::createEach()`, hoping to see the `ClangdLSPServer` methods that use it as the leaves of the callers tree. However, many of these call paths go through main-file functions like `getDeclAtPosition()` in XRefs.cpp. So, my callers tree is currently interrupted at those points (of which there are several), and I have to invoke call hierarchy anew for each of those functions to get my answers.

> In any case, it would be great if you could run an experiment over LLVM to see how this affects disk and memory usage.

Sure, I can give this a try.

**Comment by HighCommander4** [comment] 2020-07-06 02:20
> > In any case, it would be great if you could run an experiment over LLVM to see how this affects disk and memory usage.
> 
> Sure, I can give this a try.

Here is the effect that I'm finding indexing refs to main-file symbols has on index size for the LLVM codebase:

 * disk size: 104 MB --> 112 MB (7.6% increase)
 * memory (serving structures): 630MB --> 676 MB (7.3% increase)

**Comment by kadircet** [comment] 2020-07-06 10:25
what is the baseline? is it current master or including the container for all refs change ?

Because numbers are very different for my experience on master, 86mb disk and 786mb on memory (serving structure)

maybe it is the case that you didn't wait until background index went idle?

**Comment by HighCommander4** [comment] 2020-07-06 15:08
Both measurements were taken with the "referrer" field included, yes. I can take measurements without that, if you'd prefer.

(I did wait until the background indexer was idle, and looked at the output displayed when it was finished.)

**Comment by kadircet** [comment] 2020-07-06 15:54
yeah it would be great if you could measure against the current HEAD, without the referrer field.

**Comment by HighCommander4** [comment] 2020-07-06 18:10
Measurements without the referrer field:

* disk size: 74 MB --> 79 MB (7% increase)
* memory (serving structures): 558 MB --> 597 MB (6.9% increase)

**Comment by HighCommander4** [comment] 2020-10-13 06:34
Apologies for the long turnaround time here. I've now posted a draft implementation of incoming calls [here](https://reviews.llvm.org/D89296).

**Comment by kadircet** [comment] 2020-10-13 21:09
Thanks! I took a quick look, it is kind of big for a single review, it would be great if you could split it into multiple pieces (at least 2, one for updating `Ref` struct and indexer/serialization infra, another for implementing callHierarchy support).

In addition to that I would suggest using `Container` instead of `Referrer`, but I did not check the detailed semantics of the field, I am just talking according to our previous discussions, things might've changed for you in the meantime.

Also the piece around performing an Index lookup to get back to a particular symbol sounds a little unfortunate. Is the proposal final? Did people already request addition of a `data` field?
If we are already late for the party then I would suggest one of the following:
- The request still has a progressToken attached to it, I presume(it is unclear from the spec) it is preserved between prepare and subsequent requests. So we can keep a mapping in ClangdServer and stash symbolIDs.
- Make use of the `selectionRange` and `uri` to recreate original selectiontree.

**Comment by HighCommander4** [comment] 2020-10-13 23:26
Thanks for having a look!

> the piece around performing an Index lookup to get back to a particular symbol sounds a little unfortunate.

Agreed.

> Is the proposal final?

The API appears in the ["3.16 (upcoming)"](https://microsoft.github.io/language-server-protocol/specifications/specification-3-16/) version of the spec, but the [LSP issue for it](https://github.com/microsoft/language-server-protocol/issues/468) is still open, so I assume it's not super-final.

> Did people already request addition of a `data` field?

Not that I'm aware. I can make such a request.

>    * The request still has a progressToken attached to it, I presume(it is unclear from the spec) it is preserved between prepare and subsequent requests. So we can keep a mapping in ClangdServer and stash symbolIDs.

Ok, I can give this a try.

>    * Make use of the `selectionRange` and `uri` to recreate original selectiontree.

This would only be helpful for the first level of the call hierarchy. For subsequent levels, the `uri` can be in a different file for which there is no AST.

**Comment by HighCommander4** [comment] 2020-10-13 23:56
> > Did people already request addition of a `data` field?
> 
> Not that I'm aware. I can make such a request.

Requested [here](https://github.com/microsoft/language-server-protocol/issues/468).

**Comment by HighCommander4** [comment] 2020-10-21 00:10
> > > Did people already request addition of a `data` field?
> > 
> > Not that I'm aware. I can make such a request.
> 
> Requested [here](https://github.com/microsoft/language-server-protocol/issues/468#issuecomment-708070694).

I'm happy to report that this request was [approved](https://github.com/microsoft/language-server-protocol/issues/468#issuecomment-712746233) and the `data` field now appears in the [call hierarchy spec](https://microsoft.github.io/language-server-protocol/specifications/specification-3-16/#textDocument_prepareCallHierarchy). I'll update my patch to make use of it, which means the workarounds suggested in [this comment](https://github.com/clangd/clangd/issues/162#issuecomment-708010771) should not be necessary.

**Comment by kadircet** [comment] 2020-10-21 07:15
oh wow, that's great to hear! thanks for acting so swiftly!

**Comment by HighCommander4** [comment] 2020-11-25 01:38
Update: support for incoming calls is now in LLVM trunk.

For best results, I recommend running clangd with `--collect-main-file-refs=true`, to address the limitation discussed in [this comment](https://github.com/clangd/clangd/issues/162#issuecomment-648955687). (I hope to make this the default in the near future.)

**Comment by petr-tik** [comment] 2021-02-25 00:12
Looks like this issue could be closed and tagged what release (I assume 11) ships with this feature

**Comment by HighCommander4** [comment] 2021-02-25 00:32
What's implemented so far is the **incoming calls** part of the feature.

The LSP protocol does include **outgoing calls** functionality as well, and @qchateau has [a patch implementing it](https://reviews.llvm.org/D93829), but it's still under review.

One of the questions that came up during the review of outgoing calls is whether the feature would even be widely-used enough to be worth the additional memory footprint it requires. If anyone following this issue has thoughts on whether or not they'd use outgoing calls, that would be useful info.

**Comment by HighCommander4** [comment] 2021-02-25 00:33
As for the release in which incoming calls will appear, it will be the upcoming clangd 12. (11 has been out for a while.)

**Comment by njames93** [comment] 2021-02-25 04:23
> What's implemented so far is the **incoming calls** part of the feature.
> 
> The LSP protocol does include **outgoing calls** functionality as well, and @qchateau has [a patch implementing it](https://reviews.llvm.org/D93829), but it's still under review.
> 
> One of the questions that came up during the review of outgoing calls is whether the feature would even be widely-used enough to be worth the additional memory footprint it requires. If anyone following this issue has thoughts on whether or not they'd use outgoing calls, that would be useful info.
IMO the main reason for outgoing calls would be to better understand what templates get instantiated. But I don't believe we would even get full support on that front.

**Comment by pidgeon777** [comment] 2021-06-15 14:26
I vote for outgoing calls to be implemented, also.

It is a great feature which help to understand the code better.

Also, [ccls](https://github.com/MaskRay/ccls) already implements it, even if not through the official LSP standard. This is a point against ccls, but so far it has proven to work.

Moreover, the outgoing calls capability is already supported in other common programming languages (Python, TypeScript...).

Maybe a flag could be enabled to the command line so that call hierarchy capabilities are disabled? To optimize resource usage and so on for those eventually not interested in this feature.

**Comment by ebarcsa** [comment] 2021-06-17 13:11
I had the chance to try out this feature with clang/12 on our bigger project. Unfortunate that it seems to be buggy for me, Find All References find the incoming calls, but Show Call Hierarchy doesn't. Well, for some function it works for others not. 
Tried this too: `"--collect-main-file-refs=true"`
I noticed for example one function declared in header used 2 places in a cc and only 1 usage shows up in call hierarchy.

**Comment by HighCommander4** [comment] 2021-06-18 18:42
> I had the chance to try out this feature with clang/12 on our bigger project. Unfortunate that it seems to be buggy for me, Find All References find the incoming calls, but Show Call Hierarchy doesn't. Well, for some function it works for others not.

Thanks for trying it. If you're able to share code examples where call hierarchy does not work, I'm happy to investigate them.

**Comment by yoav-za** [comment] 2021-06-19 06:54
I also found it to give incomplete results.

You can try reproducing it by indexing llvm code (llvmorg-12.0.0):
1. Go to clang-tools-extra/clangd/Protocol.cpp and look for `indexSymbolKindToSymbolKind`
2. Look for its references. You should see that it is called by `FindSymbols.cpp:getWorkspaceSymbols`, `FindSymbols.cpp:declToSym`, `XRefs.cpp:declToHierarchyItem` and `XRefs.cpp:symbolToHierarchyItem`.
3. Look at the hierarchy representation and you'll find that only `FindSymbols.cpp:getWorkspaceSymbols` and `XRefs.cpp:symbolToHierarchyItem` are shown.

**Comment by HighCommander4** [comment] 2021-06-29 04:24
@yoav-za thanks very much for the example! I can reproduce it, and after some investigation I believe I know the cause. I filed #806 to track and will post a fix there.

**Comment by kadircet** [comment] 2021-12-20 12:54
AFAICT there are two possible enhancements to current feature:
- Providing a better range for the CallHierarchyItems (currently we only have the symbol's name). This is a dupe of https://github.com/clangd/clangd/issues/59.
- Implementing outgoingcalls support, this requires changes to current infra without unclear impact. Hence requires some justification, which I believe deserves it's own discussion.

Hence closing this issue, while mentioning the missing outgoing calls support as a known limitation for interested parties to tackle.

**Closed by kadircet** 2021-12-20 12:54 UTC

**Comment by HighCommander4** [comment] 2021-12-21 00:38
>    * Implementing outgoingcalls support, this requires changes to current infra without unclear impact. Hence requires some justification, which I believe deserves it's own discussion.

For what it's worth, I _have_ come across a use case for outgoing calls. Suppose you have a function which, based on its behaviour you know it must call _some_ system call (or other API in some interesting API layer), but you don't know which one, and the call may be deep inside several layers of wrappers. In such situations, outgoing calls allows you to locate that API call at a glance, much more efficiently than having to scan the definition of the function at each layer and perform go-to-definition repeatedly (which also suffers from the problem that you have to wait for the AST build delay before you can invoke go-to-definition).

I've also heard concerns that, since call hierarchy is a single capability at the protocol level, clients don't really surface the fact that a server doesn't support one direction very nicely (e.g. the button to show outgoing calls will be there, but the result will always be empty, leading users to possibly think their setup or the language server is broken). Not sure how sympathetic you are to this consideration, but thought I'd mention it.

**Comment by kadircet** [comment] 2021-12-21 16:13
> For what it's worth, I have come across a use case for outgoing calls. Suppose you have a function which, based on its behaviour you know it must call some system call (or other API in some interesting API layer), but you don't know which one, and the call may be deep inside several layers of wrappers. In such situations, outgoing calls allows you to locate that API call at a glance, much more efficiently than having to scan the definition of the function at each layer and perform go-to-definition repeatedly (which also suffers from the problem that you have to wait for the AST build delay before you can invoke go-to-definition).

This sounds useful indeed, with the downside of branching. In theory if there are multiple layers of calls with each layer having a bunch and user doesn't know what they're looking at exactly it might be hard to figure out which branch to take (benefits of seeing the code is questionable too). Maybe we can implement a cheaper version of this with pseudoparsing, we wouldn't have perfect type matching but we can at least list all the overloads with matching number of arguments (and cross fingers that this is more helpful than annoying).

> I've also heard concerns that, since call hierarchy is a single capability at the protocol level, clients don't really surface the fact that a server doesn't support one direction very nicely (e.g. the button to show outgoing calls will be there, but the result will always be empty, leading users to possibly think their setup or the language server is broken). Not sure how sympathetic you are to this consideration, but thought I'd mention it.

Thanks! This is actually something we care about, and it was unfortunate that clangd returned a successful looking response. I've sent out llvm/llvm-project@1a929525e86a20d0b3455a400d0dbed40b325a13 to fail with `method not found` (vscode doesn't do a good job of surfacing that error, but hopefully other editors are more sensible).

**Comment by pidgeon777** [comment] 2021-12-21 23:29
Personally I hope `callHierarchy/outgoingCalls` will one day be implemented. `ccls` already has it and I find it to be useful for code navigation/inspection/learning.

**Comment by pidgeon777** [comment] 2021-12-22 08:28
A sample of implementation from [ccls](https://github.com/MaskRay/ccls):

https://github.com/MaskRay/ccls/blob/master/src/messages/ccls_call.cc

**Comment by HighCommander4** [comment] 2021-12-22 08:59
Note, we do have a proposed clangd implementation, at https://reviews.llvm.org/D93829. Based on the discussion in that patch, the sticking point is that the patch adds 5-10% to the size of the in-memory representation of a typical project's index, and it was not clear if the feature is worth this cost.

**Comment by qchateau** [comment] 2021-12-22 10:20
Just adding my input there, from the experience I had while implementing it.
I found it rather useful for 2 things:
- understand the various code paths at a glance in new code
- find out that implicit constructors or cast operators were called

That being said I did not particularly miss it since I stopped using it

**Comment by superboy0712** [comment] 2022-03-09 12:57
Hi, I am thinking of making some butterfly call graphs (show both incoming/outgoing calls) visualization plugins based on clangd LSP. However, found it was not implemented yet.  The call depth Outgoing calls are indeed very useful for understanding code call paths and reasoning dependencies.

**Comment by pidgeon777** [comment] 2022-03-09 15:05
@superboy0712 I agree, it would be useful to implement it in clangd.

Anyway, could you provide us with more info about your project?

**Comment by superboy0712** [comment] 2022-03-11 11:38
@pidgeon777 I haven't implemented it. But it was inspired by the Sourcetrail.  It supports a limited depth of outgoing call paths, so that won't make users buried into too deep non-interesting paths.  I would recommend clangd can also support APIs with the customized depth of outgoing calls, which might significantly reduce the footprint of memory usage.

**Comment by pidgeon777** [comment] 2022-03-11 12:34
I also used Sourcetrail. A real pity that the project is now abandoned.

**Comment by pidgeon777** [comment] 2022-07-01 07:47
> Note, we do have a proposed clangd implementation of outgoing calls, at https://reviews.llvm.org/D93829. Based on the discussion in that patch, the sticking point is that the patch adds 5-10% to the size of the in-memory representation of a typical project's index, and it was not clear if the feature is worth this cost.

Any chance this will be implemented?

**Comment by HighCommander4** [comment] 2022-07-01 08:30
> > Note, we do have a proposed clangd implementation of outgoing calls, at https://reviews.llvm.org/D93829. Based on the discussion in that patch, the sticking point is that the patch adds 5-10% to the size of the in-memory representation of a typical project's index, and it was not clear if the feature is worth this cost.
> 
> Any chance this will be implemented?

There hasn't been any new discussion about outgoing calls recently.

Since this issue is closed, perhaps it would be best to file a new one (or, even better, a [Discussion](https://github.com/clangd/clangd/discussions)) about it.

**Comment by jrwrigh** [comment] 2022-07-09 15:56
I've created a discussion here: #1206

Side note: I find it odd that GH will back-link references between issues and PRs, but apparently not with discussions.

**Comment by pidgeon777** [comment] 2023-04-04 12:10
Hopefully, this will be implemented, maybe a flag could be used to let a user decide whether to enable this feature or not, if memory usage is a concern.

**Comment by pidgeon777** [comment] 2023-11-08 12:39
Bump hoping for good news

**Comment by HighCommander4** [comment] 2023-11-08 18:01
To avoid any confusion:
 * "Incoming calls" has been supported for years.
 * "Outgoing calls" support is in progress. Please follow https://github.com/clangd/clangd/discussions/1206 and https://reviews.llvm.org/D93829 for updates on that.

**Comment by catskul** [comment] 2024-12-17 17:18
Landed here:

https://github.com/llvm/llvm-project/pull/117673
