### ISSUE TITLE
ClangD extemely high memory usage

### ISSUE THREAD

**Issue by dud2683** [clangd/clangd#2072] opened 2024-06-21 14:39 UTC
When exploring the blis.h of the blis library in usr/local/include/blis/ 
the memory usage grows until system crash very rapidly.
Steps to reproduce, download blis library https://github.com/flame/blis
Build the library and install,
Open  usr/local/include/blis/blis.h and connect to clangd

Output of `clangd --version`:17.0.6

Editor/LSP plugin: Neovim

Operating system: Arch

**Comment by HighCommander4** [comment] 2024-06-21 18:38
This has been fixed in https://github.com/llvm/llvm-project/commit/3093d731dff93df02899dcc62f5e7ba02461ff2a for clangd 19.

**Comment by HighCommander4** [comment] 2024-06-21 18:38
Duplicate of #1384

**Closed by HighCommander4** 2024-06-21 18:38 UTC

**Comment by dud2683** [comment] 2024-06-23 23:45
Thank you very much!
