### ISSUE TITLE
Message: ignored auto-triggered completion, preceding char did not match

### ISSUE THREAD

**Issue by mihaelartz** [clangd/clangd#52] opened 2019-06-05 17:11 UTC
## Clangd Version
```clangd version 8.0.1-svn360950-1~exp1~20190517004233.70 (branches/release_80)```

## Clangd Output
https://gist.github.com/mihaelartz/b5074b05dcb497aedcb9e97ffe9cc8e5

**Comment by sam-mccall** [comment] 2019-06-06 21:42
@ilya-biryukov I guess this is https://reviews.llvm.org/D55994. Do we need to return an error instead of `[]` in this case?

**Comment by ilya-biryukov** [comment] 2019-06-07 08:40
We do return an error in that case, with an `UnknownErrorCode (-32001)`.
The intention was always to return `RequestCancelled` code, I'll send a patch to do so.

Looking at [coc.nvim source code](https://github.com/neoclide/coc.nvim/blob/33fdf740aa7f74f48f721eaa969d6aab346af31f/src/language-client/client.ts#L4059), this should fix the issue.

**Comment by ilya-biryukov** [comment] 2019-06-07 08:48
Sent out [D6299](https://reviews.llvm.org/D62999) for review, it should fix this.

**Comment by mihaelartz** [comment] 2019-06-07 09:36
@ilya-biryukov Same problem appear in vscode, with vscode-clangd extension.

**Comment by ilya-biryukov** [comment] 2019-06-07 10:36
We don't expect users to see those logs.

But actually, it turned out returning empty completion list does not show a completion window in VSCode, that looks like the best fix so far

**Comment by ilya-biryukov** [comment] 2019-06-07 16:22
Landed a fix in r362811, could you please check the problem is gone after it?

**Comment by mihaelartz** [comment] 2019-06-07 18:57
@ilya-biryukov First release build on Ubuntu repository. Compile takes a long time.

**Comment by ilya-biryukov** [comment] 2019-06-11 16:25
We don't manage the ubuntu packages on our own, so I'm afraid you'll have to wait for the new LLVM release to get the fix.

Alternatively, you could grab a fresh build from https://apt.llvm.org/

**Closed by ilya-biryukov** 2019-06-11 16:25 UTC
