### ISSUE TITLE
Rename does not work properly in the header file

### ISSUE THREAD

**Issue by lh123** [clangd/clangd#428] opened 2020-06-12 06:54 UTC
**System information**
Output of `clangd --version`: clangd version 11.0.0 (https://github.com/llvm/llvm-project.git 3badd17b6989621b5aa2732800f697dabbda034d)
Editor/LSP plugin: VSCode
Operating system: Win10

```c++
// test.h
class Test {};
```
rename `Test` to `Test_new`.
```c++
// test.h
class Test_new_new {};
```

**Comment by hokein** [comment] 2020-06-12 09:23
I didn't reproduce this issue (on linux), it works as expected.

could you share a clangd log (http://clangd.llvm.org/troubleshooting.html#gathering-logs)? there should be some entries for rename, like 

```
V[11:17:48.665] <<< {"id":24,"jsonrpc":"2.0","method":"textDocument/rename","params":{"newName":"Test_new","position":{"character":7,"line":0},"textDocument":{"uri":"file:///tmp/t.h"}}}

I[11:17:48.665] <-- textDocument/rename(24)
V[11:17:48.665] ASTWorker running Rename on version 6 of /tmp/t.h
I[11:17:48.666] --> reply:textDocument/rename(24) 0 ms
V[11:17:48.666] >>> {"id":24,"jsonrpc":"2.0","result":{"changes":{"file:///tmp/t.h":[{"newText":"Test_new","range":{"end":{"character":10,"line":0},"start":{"character":6,"line":0}}}]}}}
```

**Comment by lh123** [comment] 2020-06-12 10:18
```
V[18:17:19.813] <<< {"id":16,"jsonrpc":"2.0","method":"textDocument/codeAction","params":{"context":{"diagnostics":[]},"range":{"end":{"character":8,"line":0},"start":{"character":8,"line":0}},"textDocument":{"uri":"file:///d%3A/tt/test.h"}}}

I[18:17:19.813] <-- textDocument/codeAction(16)
V[18:17:19.814] ASTWorker running EnumerateTweaks on version 2 of d:\tt\test.h
I[18:17:19.815] --> reply:textDocument/codeAction(16) 1 ms
V[18:17:19.815] >>> {"id":16,"jsonrpc":"2.0","result":[{"command":{"arguments":[{"file":"file:///d:/tt/test.h","selection":{"end":{"character":8,"line":0},"start":{"character":8,"line":0}},"tweakID":"AnnotateHighlightings"}],"command":"clangd.applyTweak","title":"Annotate highlighting tokens"},"kind":"refactor","title":"Annotate highlighting tokens"},{"command":{"arguments":[{"file":"file:///d:/tt/test.h","selection":{"end":{"character":8,"line":0},"start":{"character":8,"line":0}},"tweakID":"DumpAST"}],"command":"clangd.applyTweak","title":"Dump CXXRecordDecl AST"},"kind":"info","title":"Dump CXXRecordDecl AST"},{"command":{"arguments":[{"file":"file:///d:/tt/test.h","selection":{"end":{"character":8,"line":0},"start":{"character":8,"line":0}},"tweakID":"ShowSelectionTree"}],"command":"clangd.applyTweak","title":"Show selection tree"},"kind":"info","title":"Show selection tree"},{"command":{"arguments":[{"file":"file:///d:/tt/test.h","selection":{"end":{"character":8,"line":0},"start":{"character":8,"line":0}},"tweakID":"DumpSymbol"}],"command":"clangd.applyTweak","title":"Dump symbol under the cursor"},"kind":"info","title":"Dump symbol under the cursor"},{"command":{"arguments":[{"file":"file:///d:/tt/test.h","selection":{"end":{"character":8,"line":0},"start":{"character":8,"line":0}},"tweakID":"DumpRecordLayout"}],"command":"clangd.applyTweak","title":"Show class layout"},"kind":"info","title":"Show class layout"}]}

I[18:17:19.815] --> textDocument/clangd.fileStatus
V[18:17:19.815] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"idle","uri":"file:///d:/tt/test.h"}}

V[18:17:21.043] <<< {"id":17,"jsonrpc":"2.0","method":"textDocument/prepareRename","params":{"position":{"character":8,"line":0},"textDocument":{"uri":"file:///d%3A/tt/test.h"}}}

I[18:17:21.043] <-- textDocument/prepareRename(17)
V[18:17:21.043] ASTWorker running PrepareRename on version 2 of d:\tt\test.h
I[18:17:21.043] --> reply:textDocument/prepareRename(17) 0 ms
V[18:17:21.043] >>> {"id":17,"jsonrpc":"2.0","result":{"end":{"character":10,"line":0},"start":{"character":6,"line":0}}}

I[18:17:21.043] --> textDocument/clangd.fileStatus
V[18:17:21.043] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"idle","uri":"file:///d:/tt/test.h"}}

V[18:17:26.679] <<< {"id":18,"jsonrpc":"2.0","method":"textDocument/rename","params":{"newName":"Test_new","position":{"character":8,"line":0},"textDocument":{"uri":"file:///d%3A/tt/test.h"}}}

I[18:17:26.679] <-- textDocument/rename(18)
V[18:17:26.680] ASTWorker running Rename on version 2 of d:\tt\test.h
I[18:17:26.683] --> reply:textDocument/rename(18) 3 ms
V[18:17:26.683] >>> {"id":18,"jsonrpc":"2.0","result":{"changes":{"file:///D:/tt/test.h":[{"newText":"Test_new","range":{"end":{"character":10,"line":0},"start":{"character":6,"line":0}}}],"file:///d:/tt/test.h":[{"newText":"Test_new","range":{"end":{"character":10,"line":0},"start":{"character":6,"line":0}}}]}}}

I[18:17:26.683] --> textDocument/clangd.fileStatus
V[18:17:26.683] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"idle","uri":"file:///d:/tt/test.h"}}

V[18:17:26.711] <<< {"jsonrpc":"2.0","method":"textDocument/didChange","params":{"contentChanges":[{"range":{"end":{"character":10,"line":0},"start":{"character":10,"line":0}},"rangeLength":0,"text":"_new"},{"range":{"end":{"character":10,"line":0},"start":{"character":10,"line":0}},"rangeLength":0,"text":"_new"}],"textDocument":{"uri":"file:///d%3A/tt/test.h","version":3}}}

I[18:17:26.711] <-- textDocument/didChange
I[18:17:26.713] --> textDocument/clangd.fileStatus
V[18:17:26.713] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"file is queued","uri":"file:///d:/tt/test.h"}}

I[18:17:26.762] --> textDocument/clangd.fileStatus
V[18:17:26.763] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"file is queued","uri":"file:///d:/tt/test.h"}}

I[18:17:26.763] Failed to find compilation database for d:\tt\test.h
I[18:17:26.764] ASTWorker building file d:\tt\test.h version 3 with command clangd fallback
[d:\tt]
D:\mingw64\bin\clang -xobjective-c++-header d:\tt\test.h -fsyntax-only -resource-dir=D:\clangd\lib\clang\11.0.0
V[18:17:26.768] Driver produced command: cc1 -cc1 -triple x86_64-w64-windows-gnu -fsyntax-only -disable-free -disable-llvm-verifier -discard-value-names -main-file-name test.h -mrelocation-model pic -pic-level 2 -mframe-pointer=none -fmath-errno -fno-rounding-math -mconstructor-aliases -munwind-tables -target-cpu x86-64 -dwarf-column-info -debugger-tuning=gdb -resource-dir D:\clangd\lib\clang\11.0.0 -internal-isystem D:\mingw64\x86_64-w64-mingw32\include\c++ -internal-isystem D:\mingw64\x86_64-w64-mingw32\include\c++\x86_64-w64-mingw32 -internal-isystem D:\mingw64\x86_64-w64-mingw32\include\c++\backward -internal-isystem D:\mingw64\x86_64-w64-mingw32\include\c++\8.1.0 -internal-isystem D:\mingw64\x86_64-w64-mingw32\include\c++\8.1.0\x86_64-w64-mingw32 -internal-isystem D:\mingw64\x86_64-w64-mingw32\include\c++\8.1.0\backward -internal-isystem D:\mingw64\include\c++\8.1.0 -internal-isystem D:\mingw64\include\c++\8.1.0\x86_64-w64-mingw32 -internal-isystem D:\mingw64\include\c++\8.1.0\backward -internal-isystem D:\mingw64\lib\gcc\x86_64-w64-mingw32\8.1.0\include\c++ -internal-isystem D:\mingw64\lib\gcc\x86_64-w64-mingw32\8.1.0\include\c++\x86_64-w64-mingw32 -internal-isystem D:\mingw64\lib\gcc\x86_64-w64-mingw32\8.1.0\include\c++\backward -internal-isystem D:\clangd\lib\clang\11.0.0\include -internal-isystem D:\mingw64\x86_64-w64-mingw32/sys-root/mingw/include -internal-isystem D:\mingw64\x86_64-w64-mingw32\include -internal-isystem D:\mingw64\include -fdeprecated-macro -fdebug-compilation-dir d:\tt -ferror-limit 19 -fno-use-cxa-atexit -fgnuc-version=4.2.1 -fobjc-runtime=gcc -fobjc-exceptions -fcxx-exceptions -fexceptions -fseh-exceptions -faddrsig -x objective-c++-header d:\tt\test.h
I[18:17:26.768] --> textDocument/clangd.fileStatus
V[18:17:26.768] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"parsing includes,running Update (3)","uri":"file:///d:/tt/test.h"}}

V[18:17:26.768] Reusing preamble version 1 for version 3 of d:\tt\test.h
V[18:17:26.800] indexed file AST for d:\tt\test.h version 3:
  symbol slab: 1 symbols, 4456 bytes
  ref slab: 1 symbols, 1 refs, 4256 bytes
  relations slab: 0 relations, 24 bytes
V[18:17:26.800] Build dynamic index for main-file symbols with estimated memory usage of 11552 bytes
I[18:17:26.800] --> textDocument/publishDiagnostics
V[18:17:26.800] >>> {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[],"uri":"file:///d:/tt/test.h","version":3}}

I[18:17:26.800] --> textDocument/semanticHighlighting
V[18:17:26.800] >>> {"jsonrpc":"2.0","method":"textDocument/semanticHighlighting","params":{"lines":[{"isInactive":false,"line":0,"tokens":"AAAABgAMAAg="}],"textDocument":{"uri":"file:///d:/tt/test.h","version":3}}}

I[18:17:26.800] --> textDocument/clangd.fileStatus
V[18:17:26.800] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"idle","uri":"file:///d:/tt/test.h"}}

V[18:17:27.050] <<< {"id":19,"jsonrpc":"2.0","method":"textDocument/documentSymbol","params":{"textDocument":{"uri":"file:///d%3A/tt/test.h"}}}

I[18:17:27.050] <-- textDocument/documentSymbol(19)
V[18:17:27.050] ASTWorker running documentSymbols on version 3 of d:\tt\test.h
I[18:17:27.050] --> reply:textDocument/documentSymbol(19) 0 ms
V[18:17:27.051] >>> {"id":19,"jsonrpc":"2.0","result":[{"kind":5,"name":"Test_new_new","range":{"end":{"character":20,"line":0},"start":{"character":0,"line":0}},"selectionRange":{"end":{"character":18,"line":0},"start":{"character":6,"line":0}}}]}

I[18:17:27.051] --> textDocument/clangd.fileStatus
V[18:17:27.051] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"idle","uri":"file:///d:/tt/test.h"}}

V[18:17:27.702] <<< {"id":20,"jsonrpc":"2.0","method":"textDocument/documentLink","params":{"textDocument":{"uri":"file:///d%3A/tt/test.h"}}}

I[18:17:27.702] <-- textDocument/documentLink(20)
V[18:17:27.702] ASTWorker running DocumentLinks on version 3 of d:\tt\test.h
I[18:17:27.702] --> reply:textDocument/documentLink(20) 0 ms
V[18:17:27.702] >>> {"id":20,"jsonrpc":"2.0","result":[]}

I[18:17:27.702] --> textDocument/clangd.fileStatus
V[18:17:27.702] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"idle","uri":"file:///d:/tt/test.h"}}

```

**Comment by lh123** [comment] 2020-06-12 10:42
![ay73z-aafp6](https://user-images.githubusercontent.com/10697249/84494622-6d044380-acdc-11ea-8e17-7cbdcb431086.gif)

**Comment by hokein** [comment] 2020-06-12 12:00
Thanks for the information, now I see the problem.

The result contains edits for two files! Looks like we hit #108 :( the case-insensitive drive letter confuses clangd, which makes file deduplication in rename fails.

- `file:///D:/tt/test.h` -- likely from the dynamic index;
- `file:///d:/tt/test.h` -- from the client request;

**Comment by andyborrell** [comment] 2021-04-13 20:27
If anyone needs a hacky fix to just get this working, this is what I'm using:

```
diff --git a/clang-tools-extra/clangd/refactor/Rename.cpp b/clang-tools-extra/clangd/refactor/Rename.cpp
index ea75de6e86e..0d361d0de46 100644
--- a/clang-tools-extra/clangd/refactor/Rename.cpp
+++ b/clang-tools-extra/clangd/refactor/Rename.cpp
@@ -313,8 +313,9 @@ findOccurrencesOutsideFile(const NamedDecl &RenameDecl,
     if ((R.Kind & RefKind::Spelled) == RefKind::Unknown)
       return;
     if (auto RefFilePath = filePath(R.Location, /*HintFilePath=*/MainFile)) {
-      if (*RefFilePath != MainFile)
+      if (MainFile.compare_lower(*RefFilePath) != 0) {
         AffectedFiles[*RefFilePath].push_back(toRange(R.Location));
+      }
     }
   });
```
You should only use this on Windows though as it makes it ignore case completely.

**Comment by njames93** [comment] 2021-04-13 22:25
I believe this was fixed in https://github.com/llvm/llvm-project/commit/b63cd4db915c08e0cb4cf668a18de24b67f2c44c which is in the branch for the clangd-12 release.

**Closed** 2021-11-05 13:34 UTC
Labels: bug, windows
