### ISSUE TITLE
Vs Code extension - Problems tab "remains behind" 

### ISSUE THREAD

**Issue by ghita** [clangd/clangd#300] opened 2020-03-04 08:43 UTC
This is a great extension for VS Code (version 0.0.20) but it keeps old issues in Problems panel for long, long time. I made fixes, rebuild the respective target but the Problems and in actual files actually I still have error reports (squiggles).

Use clangd like this:

clangd version 9.0.0-2~ubuntu18.04.2 (tags/RELEASE_900/final)
[11:17:17.906] Working directory: 
[11:17:17.906] argv[0]: /usr/bin/clangd-9
[11:17:17.906] argv[1]: --background-index=true
[11:17:17.906] argv[2]: -j=2

**Comment by ghita** [comment] 2020-03-04 08:46
Reloading window (Developer- Reload Window) fixes the issue.

**Comment by sam-mccall** [comment] 2020-03-04 08:47
Are the "stuck" problems in files that you're actively editing, or in files that include headers you're editing? (We don't rebuild dependent files when headers are edited yet).

Do the old issues eventually go away by themselves (just performance is bad) or do they stick around until you take some action?

(Rebuilding the target in your build system has no effect on clangd)

**Comment by ghita** [comment] 2020-03-04 08:52
I was changing some include path in CMake then run configure. There were many affected cpp files that needed to change the include path (from form inc1/file.h to inc2/file.h) and I fixed all of them -> I could not get rid of the errors even after I continued working on those files -> only Reload worked

**Comment by sam-mccall** [comment] 2020-03-04 08:55
Ah yes, restarting clangd is the only way to pick up changes to `compile_comands.json` at the moment.

It'd be nice to observe changes to it and rebuild open files.

**Comment by sam-mccall** [comment] 2020-03-04 08:56
So I think this is effectively a dupe of https://github.com/clangd/clangd/issues/83

**Closed by sam-mccall** 2020-03-04 08:56 UTC

**Comment by ghita** [comment] 2020-03-04 13:04
Is there a FAQ section describing modifying header and how to manually retrigger dependent cpp-s (that I actively work on) to update their state ?
