### ISSUE TITLE
Support  recursively detecting presence of header files for auto-include when completing

### ISSUE THREAD

**Issue by beyond-fu** [clangd/clangd#1670] opened 2023-06-10 02:34 UTC
Hi,
I am always bothered by auto-include when using code completion just like this:
```
// this is my common.h
#include <stdio.h>
// something
```
```// this is my test.c
#include <common.h>
#include <stdio.h>
printf("hello world\n");
```
I have included `<common.h>` header, but when I type printf function and complete it, clangd auto-include `<stdio.h>` for me. Sometimes this may cause errors. For now I use `--header-insertion=never` in my config file. 

So as describes in the title, is it possible to implement a feature to let `clangd` know I have included `<stdio.h>` in `<common.h>`, i.e. recursively detecting the presence of header files. Personally, I think it is hard to implement, and it may cause performance loss when project is a little big.(I'm not familiar with the principle of `clangd` this kind of tools.)

Thanks!

**Comment by HighCommander4** [comment] 2023-06-10 05:42
cc @VitaNuo, @hokein, as you have worked on include-cleaner, maybe you have an idea of the level of difficulty of implementing this and the likely performance impact?

**Comment by HighCommander4** [comment] 2023-06-10 05:46
Oops, I overlooked that we already have #70 open for this. Let's close this as a duplicate of that one.

**Closed by HighCommander4** 2023-06-10 05:46 UTC
Labels: enhancement
