### ISSUE TITLE
Highlights misbehaving under edit

### ISSUE THREAD

**Issue by dwilliamson** [clangd/clangd#210] opened 2019-11-25 11:37 UTC
Issue Type: <b>Bug</b>

Syntax highlighting seems to be frozen under edits. While the text moves around, the highlights stay fixed.

![CommentHighlights](https://user-images.githubusercontent.com/1532903/69537326-cfcc0280-0f77-11ea-8881-df9e47e863af.gif)

This does not happen with vscode-clangd disabled.

Extension version: 0.0.19
Clangd version: 9.0.0
VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6800K CPU @ 3.40GHz (12 x 3398)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.91GB (25.76GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by dwilliamson** [comment] 2019-11-25 12:25
Each change made in image above prints this to output ~250 times:

```
E[12:24:15.700] Tried to add semantic token with an invalid range
```

**Comment by hokein** [comment] 2019-11-25 13:10
It looks like an issue of semantic highlighting. The log indicates clangd failed on an invalid range. Is the source code you are editing valid? would be nice if you could provide a small code snippet that can reproduce the issue.

As a workaround now, you can disable this feature by setting `"clangd.semanticHighlighting": false,` in the vscode settings.

**Comment by dwilliamson** [comment] 2019-11-26 22:36
The code does all combine fine. After my upgrade to 9.0.0 there appear to be regular semantic highlighting crashes, as well:

```
I[22:33:08.155] --> textDocument/publishDiagnostics
I[22:33:08.156] --> textDocument/semanticHighlighting
I[22:33:08.156] --> textDocument/clangd.fileStatus
I[22:33:08.170] --> textDocument/semanticHighlighting
I[22:33:08.175] --> textDocument/clangd.fileStatus
 #0 0x00007ff69fa9e2d0 c:\program files\llvm\bin\clangd.exe 0x162e2d0 c:\program files\llvm\bin\clangd.exe 0x162ff9a
 #1 0x00007ff69fa9e2d0 c:\program files\llvm\bin\clangd.exe 0x1630112 c:\program files\llvm\bin\clangd.exe 0x1635ee2
 #2 0x00007ff69fa9e2d0 c:\program files\llvm\bin\clangd.exe 0x13b1988 c:\program files\llvm\bin\clangd.exe 0x13b3799
 #3 0x00007ff69fa9e2d0 c:\program files\llvm\bin\clangd.exe 0x137c396 c:\program files\llvm\bin\clangd.exe 0x137b01c
 #4 0x00007ff69fa9e2d0 c:\program files\llvm\bin\clangd.exe 0x1383e69 c:\program files\llvm\bin\clangd.exe 0x1384b06
 #5 0x00007ff69fa9e2d0 c:\program files\llvm\bin\clangd.exe 0x1308cee c:\program files\llvm\bin\clangd.exe 0x134b9b2
 #6 0x00007ff69fa9e2d0 c:\program files\llvm\bin\clangd.exe 0x130806b c:\program files\llvm\bin\clangd.exe 0x13079fc
 #7 0x00007ff69fa9e2d0 c:\program files\llvm\bin\clangd.exe 0x1306893 c:\program files\llvm\bin\clangd.exe 0x1327d00
 #8 0x00007ff69fa9e2d0 c:\program files\llvm\bin\clangd.exe 0x1326e30 c:\program files\llvm\bin\clangd.exe 0x1346590
 #9 0x00007ff69fa9e2d0 c:\program files\llvm\bin\clangd.exe 0x13060fa c:\program files\llvm\bin\clangd.exe 0x1304dd2
#10 0x00007ff69fa9e2d0 c:\program files\llvm\bin\clangd.exe 0x1300bfe c:\program files\llvm\bin\clangd.exe 0x4ec742
#11 0x00007ff69fa9e2d0 c:\program files\llvm\bin\clangd.exe 0x3359bd c:\program files\llvm\bin\clangd.exe 0x339cdd
#12 0x00007ff69fa9e2d0 c:\program files\llvm\bin\clangd.exe 0x397f3f c:\program files\llvm\bin\clangd.exe 0x3953a1
#13 0x00007ff69fa9e2d0 c:\program files\llvm\bin\clangd.exe 0x422a91 c:\program files\llvm\bin\clangd.exe 0x422c89
#14 0x00007ff69fa9e2d0 (c:\program files\llvm\bin\clangd.exe+0x162e2d0)
#15 0x00007ff69fa9ff9a (c:\program files\llvm\bin\clangd.exe+0x162ff9a)
#16 0x00007ff69faa0112 (c:\program files\llvm\bin\clangd.exe+0x1630112)
0x00007FF69FA9E2D0 (0x000001F2691B4BC0 0x0000000000000000 0x00007FF69FBEA834 0x0000000000000002)
0x00007FF69FA9FF9A (0x0000000000000004 0x00007FF69FBEA7FA 0x0000000000000003 0x00007FF69FBEA7F5)
0x00007FF69FAA0112 (0x000001F2691B4BC0 0x0000000000000004 0x000001F2691B4BC0 0x0000000000000004)
0x00007FF69FAA5EE2 (0x0000000000000000 0x0000000000000000 0x000000E7D729B548 0x0000945A9E0FBC7D)
0x00007FF69F821988 (0x0000000000000000 0x0000000000000000 0x0000000000000008 0x000001F2680EA060)
0x00007FF69F823799 (0x000001F268D16260 0x00007FF69FA3B38F 0x0000000000000000 0x0000000000000004)
0x00007FF69F7EC396 (0x00000011000000B8 0x00000017000000B8 0x0000945A9E0FD28D 0x000001F2680EA070)
0x00007FF69F7EB01C (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000001)
0x00007FF69F7F3E69 (0x000001F268DDD938 0x00007FF69EFD06CC 0x0000000000000000 0x000001F266B0EE10)
0x00007FF69F7F4B06 (0x000000E7D729CAA0 0x00007FF69EA41557 0x0000000000000000 0x000001F268955498)
0x00007FF69F778CEE (0x0000000000000000 0x00007FF69E535E78 0x0000945A9E0FDA8D 0x0000000000000000)
0x00007FF69F7BB9B2 (0x000000E7D729D910 0x0000000000000000 0x000001F266E963D0 0x0000000000000000)
0x00007FF69F77806B (0x0000945A9E0FC64D 0x000001F2680EA070 0x0000000000000F92 0x000000E7D729D740)
0x00007FF69F7779FC (0x000001F268DDD430 0x00007FF69EC874D2 0x0000945A9E0FC4AD 0x000001F266E963D0)
0x00007FF69F776893 (0x0000000100000000 0x000001F268D16221 0x000001F200000001 0x00007FF69FA45CC3)
0x00007FF69F797D00 (0x000000F010288202 0x0000945A9E0FC35D 0x0000000000000000 0x000000000000000F)
0x00007FF69F796E30 (0x0000000000000001 0x000001F2645081C0 0x000001F264500E10 0x0000000000000000)
0x00007FF69F7B6590 (0x0000945A9E0FCE7D 0x000001F268DAD618 0x0000000000000000 0x000001F266C2F180)
0x00007FF69F7760FA (0x000000E7D729E008 0x0000000000000000 0x000001F2680EA060 0x000000E7D729DFF8)
0x00007FF69F774DD2 (0x0000000000000000 0x000001F2646C5530 0x000000E7D729E390 0x00007FF69E974882)
0x00007FF69F770BFE (0x000001F268120F30 0x00007FF69F04C5E2 0x000001F26987B850 0x000001F26987B850)
0x00007FF69E95C742 (0x000000E7D729E850 0x000000E7D729E600 0x0000000000000000 0x0000000000000000)
0x00007FF69E7A59BD (0x000001F2662F8E00 0x00007FF69E758CC0 0x1FFFFFFFFFFFFFFF 0x000000E7D729F650)
0x00007FF69E7A9CDD (0x000000E7D729F801 0x00007FFBC425C062 0x000000E7D729F808 0x000001F2661519A0)
0x00007FF69E807F3F (0x000001F265EE8EB0 0xFFFFFFFFFFFFFFFF 0x000001F265EE8EB0 0x000000E7D729FB90)
0x00007FF69E8053A1 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
0x00007FF69E892A91 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
0x00007FF69E892C89 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
0x00007FFBDB57E3FE (0x0000000000000000 0x0000[Error - 22:33:08] Connection to server got closed. Server will not be restarted.
[Error - 22:33:08] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\Don Williamson\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.0.19\node_modules\vscode-jsonrpc\lib\main.js:902:25)
	at Object.dispose (c:\Users\Don Williamson\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.0.19\node_modules\vscode-languageclient\lib\client.js:74:35)
	at ClangdLanguageClient.handleConnectionClosed (c:\Users\Don Williamson\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.0.19\node_modules\vscode-languageclient\lib\client.js:2236:42)
	at ClangdLanguageClient.handleConnectionClosed (c:\Users\Don Williamson\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.0.19\node_modules\vscode-languageclient\lib\main.js:154:15)
	at closeHandler (c:\Users\Don Williamson\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.0.19\node_modules\vscode-languageclient\lib\client.js:2223:18)
	at CallbackList.invoke (c:\Users\Don Williamson\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.0.19\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (c:\Users\Don Williamson\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.0.19\node_modules\vscode-jsonrpc\lib\events.js:121:36)
	at closeHandler (c:\Users\Don Williamson\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.0.19\node_modules\vscode-jsonrpc\lib\main.js:238:26)
	at CallbackList.invoke (c:\Users\Don Williamson\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.0.19\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (c:\Users\Don Williamson\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.0.19\node_modules\vscode-jsonrpc\lib\events.js:121:36)
	at StreamMessageReader.fireClose (c:\Users\Don Williamson\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.0.19\node_modules\vscode-jsonrpc\lib\messageReader.js:111:27)
	at Socket.<anonymous> (c:\Users\Don Williamson\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.0.19\node_modules\vscode-jsonrpc\lib\messageReader.js:151:46)
	at Socket.emit (events.js:205:15)
	at Pipe.<anonymous> (net.js:586:12)

```

**Comment by dwilliamson** [comment] 2019-11-27 10:51
Semantic highlighting disabled is performing perfectly, as of old.

**Comment by quackerd** [comment] 2019-12-10 20:16
I have the same issue. I was working on FreeBSD kernel code base and after a while the entire syntax highlighting would become jammed. I just tried deleting some empty lines and observed the similar behavior as OP.

**Comment by hokein** [comment] 2020-01-27 12:34
I believe this is a duplicate of #232, see the [explanation](https://github.com/clangd/clangd/issues/232#issuecomment-578726402)

**Closed by hokein** 2020-01-27 12:34 UTC

**Comment by dwilliamson** [comment] 2020-01-27 12:53
Actually, #232 is the duplicate.
