### ISSUE TITLE
GoToDefinition doesn't always work in template classes

### ISSUE THREAD

**Issue by me-ransh** [clangd/clangd#441] opened 2020-06-24 06:24 UTC
I created a minimal working example for go-to-definition not working inside a template class:

```cpp
struct A {
  void foo() {}
};

template <int N> struct B {
  const int n = 3;
  static constexpr int m = 3;
  A a;

  void bar() {
    this->a.foo();

    B<N> *p;
    p->a.foo();

    B<n> *q;
    q->a.foo();

    B<m> *r;
    r->a.foo();

    const int k = 3;
    B<k> *s;
    s->a.foo();

    B<3> *t;
    t->a.foo();
  }
};
```
In the above example, go-to-definition works only on the last two calls to `a.foo()`.
This is surprising, given that hovering on any `a` correctly recognizes the type as `struct A`.

The output of the clangd extension doesn't show any error (a `textDocument/definition` is sent to the server, and a reply is received, I'm guessing it's an empty one).

**System information**
Output of `clangd --version`: 
```
clangd version 10.0.0 (https://github.com/llvm/llvm-project d32170dbd5b0d54436537b6b75beaf44324e0c28)
```
Editor/LSP plugin: 
```
vscode-clangd v0.1.6
```
Operating system: 
```
Debian GNU/Linux 8 (jessie) 64-bit
```

**Comment by kirillbobyrev** [comment] 2020-06-24 07:30
Unfortunately, this is a regression in Clangd 10.0 that you are using. This bug is no longer present at HEAD. You can download latest Clangd snapshot here https://github.com/clangd/clangd/releases or have VSCode download it for you.

**Comment by me-ransh** [comment] 2020-06-24 09:56
Thanks for the quick response.

What do you mean by "have VSCode download it"? Doesn't it download the latest _stable_ release?
Anyway, I downloaded it manually and the go-to-definition problem is indeed fixed in that version. 

There are still other, seemingly related issues:
1. Find references on `A::foo` returns just the last two calls (`s->a.foo()` and `t->a.foo()`)
2. Hover information on any of the first 4 `a.foo()` calls is empty

**Comment by me-ransh** [comment] 2020-06-25 10:32
Should I open another issue for the problems I mentioned?

**Comment by HighCommander4** [comment] 2020-06-25 15:08
No, this one is fine as it's still open.

**Comment by HighCommander4** [comment] 2020-06-26 00:46
>     1. Find references on `A::foo` returns just the last two calls (`s->a.foo()` and `t->a.foo()`)

This is a known issue, on file as #258. Note that the solution I suggest in that issue wouldn't handle this snippet exactly as written, only in the case where `B::bar()` is actually instantiated somewhere in the project. We could conceivably go with a heuristic approach instead (or in addition) that would handle the snippet as written.

**Comment by HighCommander4** [comment] 2020-06-26 01:01
> We could conceivably go with a heuristic approach instead (or in addition) that would handle the snippet as written.

It looks like the heuristic approach has come up already as well, as in tracked in #399. I think we can consider the find references part of this a duplicate of that.

Will keep this open to investigate the hover part further.

**Comment by HighCommander4** [comment] 2020-06-26 02:02
Ha! It turns out that the reason go-to-definition works for the first four cases is via the textual heuristic; AST-based attempts fail.

So, we have a couple of options for fixing this:

  * Get hovers to use a textual heuristic as well (tracked in #303)
  * Improve our AST-based heuristics so they handle these cases

**Comment by HighCommander4** [comment] 2020-06-26 02:07
The reason our current AST-based heuristics fail is that an expression like `this.a->foo` is two nested `CXXDependentScopeMemberExpr`s: `this->a` (with base expression `this` and member name `a`), and `this->a.foo` (with base expression `this->a` and member name `foo`).

Our current heuristic handles cases where the base expression's type resolves to a template specialization type or similar; so it works for `this->a` because the type of `this` resolves to `B<N>`. However, it does not work for `this->a.foo` because the type of `this->a` is a dependent type.

**Comment by HighCommander4** [comment] 2020-06-26 02:09
> So, we have a couple of options for fixing this:
> 
>     * Get hovers to use a textual heuristic as well (tracked in #303)
> 
>     * Improve our AST-based heuristics so they handle these cases

The choice here also affects whether or not #399 will actually fix the find-refs part of this. If we go with the textual approach, #399 will not fix the find-refs part (unless we get find-refs to use a textual heuristic as well, which is less likely to fly).

**Comment by HighCommander4** [comment] 2020-06-29 06:57
> For this reason, I'd like to at least explore improving our AST-based heuristics.

I was able to get this to work: [proposed patch](https://reviews.llvm.org/D82739).

**Closed** 2020-07-21 06:03 UTC
