### ISSUE TITLE
Incorrect Highlighting in Vscode

### ISSUE THREAD

**Issue by jagannatharjun** [clangd/clangd#232] opened 2019-12-19 07:29 UTC
I was working on QBittorrent using Cmake Project on VSCODE. 
I am seeing incorrect syntax heightening on the whole project
![image](https://user-images.githubusercontent.com/34717789/71153356-ee63a780-225e-11ea-981c-9b01f03df9c3.png)
![image](https://user-images.githubusercontent.com/34717789/71154136-d55bf600-2260-11ea-817e-cd2f47fb1954.png)

It mainly happens with comments but when clangd is parsing, this also happens with other things close to the comments.

**Comment by Web-eWorks** [comment] 2019-12-20 23:47
Can confirm this as an issue, it occurs in multiple C++ projects both large and small. For reference, I tested this on the [pioneerspacesim/pioneer](https://github.com/pioneerspacesim/pioneer) and [Godot](https://github.com/godotengine/godot) repos, as well as several small projects of my own.

It appeared approximately a month ago, although the lack of changelog for the vscode extension makes pinpointing a problem.

**Comment by returnL** [comment] 2019-12-30 07:16
I also encountered this problem

**Comment by erikfroseth** [comment] 2020-01-27 12:16
Same thing happens for me.
Debian, clangd version 9.0.1-6

**Comment by erikfroseth** [comment] 2020-01-27 12:21
Going for a wild guess here...
I notice that the VSCode log prints out the following lines when bad highlighting happens:

```
E[13:18:01.084] Tried to add semantic token with an invalid range
E[13:18:01.084] Tried to add semantic token with an invalid range
```

Looking at git blame, and based on comment from @Web-eWorks saying that this appeared in november, maybe commit 87e0cb4f1ad299c87c3e26676a9b31b3caf58921 is the cause for this.

**Comment by hokein** [comment] 2020-01-27 12:32
I think the issue is that clangd v9 doesn't have a fully support semantic highlighting (miss sending out of diff when the document is changed),  and we [enabled this feature](https://github.com/llvm/llvm-project/commit/0f61f9fca851d6b32553f1c36cc0ce2a341bfbce#diff-b1c40181d874ec66beb3f4d220b060d6) in vscode by default.

Two options here:
1) use the truck version of clangd (clangd v10 will be released soon)
2) or disable the feature by setting `"clangd.semanticHighlighting": false` in the vscode settings if you are using clangd v9.

**Comment by erikfroseth** [comment] 2020-01-27 13:05
`"clangd.semanticHighlighting": false` did the trick. Thank you!

**Closed** 2020-03-18 11:03 UTC
