### ISSUE TITLE
Documents displayed in hover do not retain line breaks

### ISSUE THREAD

**Issue by lh123** [clangd/clangd#95] opened 2019-07-13 12:03 UTC
![image](https://user-images.githubusercontent.com/10697249/61171340-c9308600-a5a8-11e9-80f8-2bdf06f524ae.png)

**Comment by smhc** [comment] 2019-07-14 07:04
Using coc.nvim with neovim I have a slightly different issue - there is no space between "Declared in" and "`global namespace`".

![space](https://user-images.githubusercontent.com/6404304/61180413-4a475600-a659-11e9-9037-dc7bfe0a8fc1.png)

Possibly from this line of code?: https://github.com/llvm-mirror/clang-tools-extra/blob/480d1d002ab582d82d996ea0909ab07e068d2fbb/clangd/XRefs.cpp#L1276

**Comment by ilya-biryukov** [comment] 2019-08-12 12:38
Thanks for reporting this!  Fixing the multi-line issue should be easy enough in our code that renders the markdown strings. I'll take a look.

@smhc, for the coc.nvim issue - it's true that we probably don't add a space between the text and the inline block, but most markdown renderers seem to add it anyway. 
Does markdown specify whether the space should be added when rendering? If yes, should this be fixed in `coc.nvim`?

**Comment by ilya-biryukov** [comment] 2019-08-12 12:42
Looking at how GitHub renders the corresponding markdown block, we should probably add a space too:
Declared in`global namespace`
vs
Declared in `global namespace`

The space does make a difference and the version with a space looks nicer.

**Comment by ilya-biryukov** [comment] 2019-08-12 13:10
A fix for the missing space in coc.nvim is under review: https://reviews.llvm.org/D66086

**Comment by ilya-biryukov** [comment] 2019-08-12 13:28
Preserving line breaks: https://reviews.llvm.org/D66087

**Comment by sam-mccall** [comment] 2019-08-12 14:29
Regarding newlines: It's not clear that preserving them is an improvement overall.

If the code looks like this:
```
// This is a comment that describes how a class works and
// rambles a little bit, spanning two lines by the end.
```
then preserving line breaks in the markdown will often result in *rendering* like this:

>This is a comment that describes how
> a class works and
> rambles a little bit, spanning two
> lines by the end

(which probably looks familiar to anyone who deals with mailing lists a lot...)

Comments tend to be a mish-mash of paragraphs, code examples, bulleted lists, and other structure (like doxygen-ish comments). My guess is that paragraphs are generally more common than structure, and merging structure does more damage than failing to merge paragraphs. i.e. simply preserving all breaks will make a few cases much better and most cases slightly worse. I'm not sure that's actually an improvement.

We can improve on this by using heuristics to understand what's likely, such as:
 - a break after a "short" line is probably a hard one
 - a break after a `.`, or before an uppercase letter, is likely hard
 - a change in indentation indicates some structure
 - double-line-breaks are always hard

Patches welcome-ish - I think we actually need some design here first.

Ilya points out we're in no-man's-land at the moment: we don't strip the newlines when rendering as plaintext, but we don't preserve them in markdown. Though there's some virtue here too: plaintext clients are going to tend towards using a code font, and preserving newlines is relatively more useful when the font is monospace (as it does a better job of preserving structure).

(The missing space is uncontroversial I think)

**Comment by kadircet** [comment] 2020-01-15 15:11
note that new rendering behavior strips newlines in plaintext mode too.

**Comment by lolleko** [comment] 2020-03-03 20:26
<img width="1332" alt="Screenshot 2020-03-03 at 21 24 07" src="https://user-images.githubusercontent.com/4759511/75816467-8fa9c680-5d95-11ea-828b-1f2a0cff3db6.png">

I agree current rendering behaviour looks weird. No line breaks, missing bullet lists....

**Comment by sam-mccall** [comment] 2020-03-03 20:41
We talked about heuristics to detect line breaks in the past, telling the difference between a soft-wrap and a hard-wrap isn't trivial but usually possible (punctuation, is the line shorter than the longest line, etc).

A maybe-simpler alternative/fallback: detect when the documentation has "interesting formatting" and render the whole thing as a verbatim code block.

Regarding the example, detecting the comment is markdown and preserving it is interesting but also challenging. I don't know that markdown comments are *all* that common but I kind of wish they were, maybe we should be the change we want to see...

**Comment by kadircet** [comment] 2021-12-16 14:15
This has been improved with https://github.com/llvm/llvm-project/commit/b194e7d6313be3b6e6db6e2d617a76c6dde2651b and a bunch of follow-up work. As mentioned above, we don't think breaking at every newline is going to provide an optimal UX behavior in majority of the cases.

Closing for now as there are no more actionable suggestions, feel free to re-open or start new issues/discussions if you've ideas around more heuristics.

**Closed by kadircet** 2021-12-16 14:15 UTC

**Comment by mphe** [comment] 2026-02-25 09:05
Has https://github.com/llvm/llvm-project/commit/b194e7d6313be3b6e6db6e2d617a76c6dde2651b been reverted with the latest release (LLVM+clangd 22.1.0)?
Considering the following example, it should render as a single line `this is a comment with line breaks` if I understand it correctly, but it doesn't. It appears with all line breaks retained. Am I missing something?
```cpp
/// this is a comment
/// with
/// line breaks.
void foo();
```

**Comment by HighCommander4** [comment] 2026-02-25 19:07
cc @tcottin, maybe you know the answer to the above?

**Comment by tcottin** [comment] 2026-02-25 21:00
Can't reproduce with [latest prerelease](https://github.com/clangd/clangd/releases/tag/snapshot_20260222) and VSCode.

<img width="280" height="146" alt="Image" src="https://github.com/user-attachments/assets/f7f677d8-7004-4086-8994-169583101099" />

@mphe What client are you using?
Maybe it does not support markdown rendering or you have disabled it on client side?

I am not sure out of my head, but I think this should be sent to the client like this:
```
this is a comment\nwith\nline breaks.
```
On clients supporting markdown, this should be rendered as a single line.

**Comment by mphe** [comment] 2026-02-25 22:34
@tcottin I can still reproduce it with the latest snapshot. I've tested with 3 versions now:
- clangd 21.1.6: one line
- clangd 22.1.0: 3 lines
- clangd 23.0.0git (the latest prerelease): 3 lines

I'm using Neovim with builtin LSP.
I thought clangd was responsible for dropping newlines, as explained in the commit message of https://github.com/llvm/llvm-project/commit/b194e7d6313be3b6e6db6e2d617a76c6dde2651b, especially, since it worked before.

`21.1.6` sends the text without line breaks:
```
[DEBUG][2026-02-25 23:27:59] .../vim/lsp/rpc.lua:391	"rpc.receive"	{
  id = 39,
  jsonrpc = "2.0",
  result = {
    contents = {
      kind = "markdown",
      value = "### function `foo`  \n\n---\n→ `void`  \nthis is a comment with linebreaks  \n\n---\n```cpp\nvoid foo()\n```"
    },
    range = {
      ["end"] = {
        character = 8,
        line = 3
      },
      start = {
        character = 5,
        line = 3
      }
    }
  }
}
```

The others with linebreaks:
```
[DEBUG][2026-02-25 23:22:46] .../vim/lsp/rpc.lua:391	"rpc.receive"	{
  id = 7,
  jsonrpc = "2.0",
  result = {
    contents = {
      kind = "markdown",
      value = "### function `foo`\n\n---\n→ `void`\n\nthis is a comment\nwith\nlinebreaks\n\n---\n```cpp\nvoid foo()\n```"
    },
    range = {
      ["end"] = {
        character = 8,
        line = 3
      },
      start = {
        character = 5,
        line = 3
      }
    }
  }
}
```

My `config.yaml`:
```
Hover:
  ShowAKA: Yes
Diagnostics:
  UnusedIncludes: Strict
InlayHints:
  Enabled: Yes
  BlockEnd: No
  Designators: No
  ParameterNames: No
  DeducedTypes: Yes
  DefaultArguments: Yes
  TypeNameLimit: 0
```

**Comment by tcottin** [comment] 2026-02-26 06:53
I think the issue is that your client requests markdown content but does not render the content as markdown.
Can you share a screenshot how the rendering looks for clangd 21 and clangd 22?

There were several changes in the parsing of documentation comments for clangd 22.
The most relevant for this issue is probably llvm/llvm-project#140498.

When a client requests markdown and the server is configured with [Documentation CommentFormat; Plaintext (default)](https://clangd.llvm.org/config#commentformat), markdown syntax is escaped.
But apparently new lines are not "escaped", which actually means new lines need to be removed.

I think currently the old line break behaviour is only triggered when the client requests plaintext hover content instead of markdown.

**Comment by mphe** [comment] 2026-02-26 08:27
Neovim supports Markdown rendering partially. Bold, italic, links, etc. is highlighted correctly, but it won't reflow the text apparently. A quick Google search also revealed nothing relevant to that topic.

I made some screenshots for clangd 21 and 22 with `CommentFormat` set to `Plaintext`, `Markdown` and `Doxygen`.
I guess clangd 21 didn't have that feature, yet, as it looks the same in all modes.
Clangd 22 always retains line breaks in any mode. Was the old behavior scrapped during https://github.com/llvm/llvm-project/pull/140498?

Clangd 21 `Plaintext`/`Markdown`/`Doxygen`
<img width="788" height="200" alt="Image" src="https://github.com/user-attachments/assets/ec115b46-dbc7-4772-9a38-567b96c67b38" />


Clangd 22 `Plaintext`
<img width="360" height="248" alt="Image" src="https://github.com/user-attachments/assets/ba4f84f9-0e58-4fe2-b15c-e97101562fff" />


Clangd 22 `Markdown`
<img width="360" height="248" alt="Image" src="https://github.com/user-attachments/assets/fc8c990a-1be5-498d-b24b-c03a636dec1e" />


Clangd 22 `Doxygen`
<img width="352" height="256" alt="Image" src="https://github.com/user-attachments/assets/f577f176-d90c-43ce-afd5-aabc97ff5d6e" />

**Comment by tcottin** [comment] 2026-02-26 09:20
Yes this is what I expected.
Its requesting markdown, but does not really render markdown.

The old behaviour regarding the line breaks will only be active if the **client** requests plaintext and not markdown.
With the default server setting Plaintext and a markdown request from the client, markdown syntax like the `*` etc are escaped as you see in your screenshot.
But it is actually expected that the renderer still renders markdown, e.g. ignores the single newlines as it is done in my VSCode example.

Since this seems not the case at least for the nvim client, we need to also remove the line breaks when the server is configured to provide Plaintext and the client requests markdown.
The server has to do the "rendering" regarding the new lines then.

**Comment by tcottin** [comment] 2026-02-26 09:30
To use the other server settings `Markdown` or `Doxygen` with such clients, it probably makes sense to introduce another `Documentation` configuration setting to retain line breaks or not.

**Comment by tcottin** [comment] 2026-03-07 15:16
@mphe I created a PR to adress the newline handling.
Can you take a look and try on your side?
