### ISSUE TITLE
clangd find references only with opened files when home directory is symbol linked

### ISSUE THREAD

**Issue by MiniSoda** [clangd/clangd#981] opened 2022-01-10 10:18 UTC
I can observe clangd is indexing the whole project in the first run,
after clangd is idle I tried to find the references of `ClangdLSPServer::bool run();`  in the header file,
clangd find the references only with opened files:

before I open with ClangdLSPServer.cpp:

```
 I[16:28:46.546] <-- textDocument/references(40)
V[16:28:46.581] ASTWorker running References on version 1 of /home/ext/jiazhe/llvm-project/clang-tools-extra/clangd/ClangdLSPServer.h
I[16:28:46.636] --> reply:textDocument/references(40) 89 ms
V[16:28:46.636] >>> {"id":40,"jsonrpc":"2.0","result":[{"range":{"end":{"character":10,"line":81},"start":{"character":7,"line":81}},"uri":"file:///mnt/home/ext/jiazhe/llvm-project/clang-tools-extra/clangd/ClangdLSPServer.h"}]}
```

after I opened ClangdLSPServer.cpp
```
I[18:01:38.256] <<< {"id":43,"jsonrpc":"2.0","method":"textDocument/references","params":{"context":{"includeDeclaration":true},"position":{"character":8,"line":81},"textDocument":{"uri":"file:///home/ext/jiazhe/llvm-project/clang-tools-extra/clangd/ClangdLSPServer.h"}}}
I[18:01:38.256] <-- textDocument/references(43)
V[18:01:38.256] ASTWorker running References on version 1 of /home/ext/jiazhe/llvm-project/clang-tools-extra/clangd/ClangdLSPServer.h
I[18:01:38.258] --> reply:textDocument/references(43) 1 ms
V[18:01:38.258] >>> {"id":43,"jsonrpc":"2.0","result":[{"range":{"end":{"character":10,"line":81},"start":{"character":7,"line":81}},"uri":"file:///mnt/home/ext/jiazhe/llvm-project/clang-tools-extra/clangd/ClangdLSPServer.h"},{"range":{"end":{"character":25,"line":1524},"start":{"character":22,"line":1524}},"uri":"file:///mnt/home/ext/jiazhe/llvm-project/clang-tools-extra/clangd/ClangdLSPServer.cpp"},{"range":{"end":{"character":25,"line":1524},"start":{"character":22,"line":1524}},"uri":"file:///mnt/home/ext/jiazhe/llvm-project/clang-tools-extra/clangd/ClangdLSPServer.cpp"}]}
```

clangd version: clangd version 14.0.0 (https://github.com/llvm/llvm-project.git e9262edf0d11a907763098d8e101219ccd9c43e9)
I think the issue is that we have a symbol linked home directory:
`/home/ext --> /mnt/home/ext`

```
jiazhe@beibuild01:~/llvm-project$ readlink -f clang-tools-extra/clangd/ClangdLSPServer.cpp 
/mnt/home/ext/jiazhe/llvm-project/clang-tools-extra/clangd/ClangdLSPServer.cpp

jiazhe@beibuild01:~/llvm-project$ pwd
/home/ext/jiazhe/llvm-project
```

I guess the canonical path is somehow doesn't match the indexed storage?
The absolute path of the source is `/home/ext/jiazhe/llvm-project/clang-tools-extra/clangd/ClangdLSPServer.h`
It is the path in compile_commands.json as well.
But canonicalized path is `/mnt/home/ext/jiazhe/llvm-project/clang-tools-extra/clangd/ClangdLSPServer.h`
Is this the cause?

Do we have a fix or can you guys give me a pointer where to look at so I can give it a try to fix it?

**Comment by HighCommander4** [comment] 2022-01-25 06:17
Likely a duplicate of #503, there is a patch idea there that you might be able to try locally

**Comment by zoumi** [comment] 2022-03-29 02:10
clangd find references only with opened files on Windows:

![Snipaste_2022-03-29_10-06-27](https://user-images.githubusercontent.com/5162901/160518374-df57a928-0612-4dd1-b097-7c19779b48dc.jpg)

![Snipaste_2022-03-29_10-07-25](https://user-images.githubusercontent.com/5162901/160518504-9b86b1b9-799f-4494-b2d6-b970cf41c707.jpg)

**Closed** 2024-05-07 13:23 UTC
