### ISSUE TITLE
Clangd freezes my laptop when i uncomment a certain line of code.

### ISSUE THREAD

**Issue by FughyTC** [clangd/clangd#1840] opened 2023-11-28 14:55 UTC
So i was trying to learn opengl and cmake and at a certain point my system started freezing, so nothing i pressed on the keyboard worked, the mouse stopped responding, the image on the screen just freezes on both archlinux and windows. After around 10 more freezes(i had to reboot the system each time) i think i found the line of code that is causing it. Here i tried to reproduce the freeze on a smaller scale and i have succesfully frozen my laptop again: 

[renderer.hpp.txt](https://github.com/clangd/clangd/files/13489438/renderer.hpp.txt)
[main.cpp.txt](https://github.com/clangd/clangd/files/13489439/main.cpp.txt)
[renderer.cpp.txt](https://github.com/clangd/clangd/files/13489440/renderer.cpp.txt)

In renderer.cpp on 23 line if i uncomment "//sData.Data = new Vertex[MaxVertexCount];" everything freezes.

**Logs**
No logs, i just can't check them(maybe they are saved somewhere but i am not aware where).

**System information**

Output of `clangd --version`:
clangd version 17.0.1
Features: windows
Platform: x86_64-pc-windows-msvc

Editor/LSP plugin:
vscodium clangd
lapce clangd

Operating system:
archlinux
windows

**Comment by HighCommander4** [comment] 2023-11-28 22:05
I believe this is a duplicate of #967

**Comment by fishBone000** [comment] 2024-05-04 15:27
Hmmm if it's a duplicate you should close this issue

**Comment by HighCommander4** [comment] 2024-05-04 17:53
Duplicate of #967

**Closed by HighCommander4** 2024-05-04 17:53 UTC
