### ISSUE TITLE
Clangd crash when using `std::ranges::subrange`

### ISSUE THREAD

**Issue by bstaletic** [clangd/clangd#457] opened 2020-07-13 05:45 UTC
Please describe the problem.
For hints on what information is helpful, see: https://clangd.llvm.org/troubleshooting.html

If you can, provide a minimal chunk of code that shows the problem (either inline, or attach it if larger).

Clangd is often crashing when working with `<ranges>` from libstdc++. 
There's only one file, with no associated `compile_commands.json` and YCM supplies the following as the compiler flags:

    ["clang-tool","-std=c++20","-I","/home/bstaletic/work/NanoRange/include","/home/bstaletic/work/NanoRange/foo.cpp"]

I did test also without `-I` and `/home/bstaletic/work/NanoRange/include`, but that didn't change anything. I've also turned off background indexing and clangd-tidy

Here are two possible files that reliably produce the same stack trace.

```c++
#include <ranges>

int main() {
    std::ranges::subrange s({
}
```

Alternatively:

```c++
#include <ranges>

int main() {
    int c[3];
    std::ranges::subrange s(c);
}
```

Note that clang 10, the compiler, doesn't like compiling libstdc++ ranges and produces errors that just don't happen when compiling with gcc.

**Logs**
Please attach the clangd stderr log if you can. (Usually available from the editor)
If possible, run with `--log=verbose` - note that the logs will include the contents of open files!
If this is a crash, try to put `llvm-symbolizer` on your PATH per the troubleshooting instructions.

The log is from the first snippet. 
https://gist.github.com/bstaletic/9bbed8dbbeb9d390e526d8ff591b8d3a

**System information**
Output of `clangd --version`: clangd version 10.0.0
Editor/LSP plugin: vim/YCM/ycmd
Operating system: Arch Linux x86_64

**Comment by HighCommander4** [comment] 2020-07-16 06:13
> Note that clang 10, the compiler, doesn't like compiling libstdc++ ranges and produces errors that just don't happen when compiling with gcc.

This suggests that, even with this crash fixed, you may experience issues using clangd to edit code that uses libstdc++ ranges.

You may want to file a clang bug about these errors.

**Comment by HighCommander4** [comment] 2020-07-16 06:33
> The log is from the first snippet.
> https://gist.github.com/bstaletic/9bbed8dbbeb9d390e526d8ff591b8d3a

Reproducing the issue locally to see a few more frames of the stack trace, it comes from `ASTWorker::updatePreamble()`.

@kadircet Is there a standalone clangd or clang command that triggers similar / equivalent code that would repro this crash (for easier reduction to a minimal example)?

**Comment by kadircet** [comment] 2020-07-16 07:26
looks like a PCH related issue, so you could try generating a pch with
`-emit-pch` and then use it via `-include-pch` over standalone clang

**Comment by bstaletic** [comment] 2020-07-16 12:12
> You may want to file a clang bug about these errors.

Done. https://bugs.llvm.org/show_bug.cgi?id=46746

**Comment by HighCommander4** [comment] 2020-07-19 00:44
> looks like a PCH related issue, so you could try generating a pch with `-emit-pch` and then use it via `-include-pch` over standalone clang

Thanks! I was able to reduce this to a minimal repro:

```c++
template <typename T, typename U>
concept not_same_as = !__is_same(T, U);

template <int Kind>
struct subrange {
  template <not_same_as<int> R>
  subrange(R) requires (Kind == 0);

  template <not_same_as<int> R>
  subrange(R) requires (Kind != 0);
};

template <typename R>
subrange(R) -> subrange<42>;

int main() {
    int c[3];
    subrange s(c);
}
```

**Comment by HighCommander4** [comment] 2020-07-19 00:48
(Added "upstream" label since the issue reproduces with `-emit-pch` and `-include-pch`.)

**Comment by hokein** [comment] 2020-07-21 15:25
> (Added "upstream" label since the issue reproduces with -emit-pch and -include-pch.)

Thanks, I reported it in https://bugs.llvm.org/show_bug.cgi?id=46790.

**Comment by hokein** [comment] 2020-07-30 13:06
The crash is fixed in https://github.com/llvm/llvm-project/commit/73c12bd8ff1a9cd8375a357ea06f171e127ec1b8. And will be cherry-picked in 11 release.

**Closed by hokein** 2020-07-30 13:06 UTC
Labels: upstream
