### ISSUE TITLE
Include flags not carried over to header files through command inference

### ISSUE THREAD

**Issue by nathanieltooley** [clangd/clangd#1868] opened 2023-12-14 21:47 UTC
> Please describe the problem

I was working on a small project using CMake and conan and my header files were unable to locate my system headers and other included headers.

_Inside "time.h"_
![example](https://github.com/clangd/clangd/assets/27033801/db0c1679-6a4a-4754-8ae1-5bdfac15300e)

However, my cpp files were able to find them and my program compiled and executed fine.

_Inside "main.cpp"_
![example2](https://github.com/clangd/clangd/assets/27033801/5bf478f3-8c38-406a-8058-84a3ff693660)

Looking at the logs, I had noticed that while clangd had inferred the correct source file for the headers, clangd still ran without any of the -I or -isystem flags.

**Extension output for textures.cpp**
~~~
I[15:33:52.243] ASTWorker building file g:\importants\programming\c - c++\game-engine\src\utils\textures.cpp version 1 with command 
[G:/importants/programming/c - c++/game-engine/build]
"C:\\MingW\\bin\\c++.exe" --driver-mode=g++ -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL "-IG:/importants/programming/c - c++/game-engine/include" "-IG:/importants/programming/c - c++/game-engine/ext/include" -isystem C:/Users/rocke/.conan2/p/b/spdlo511412c27c6d3/p/include -isystem C:/Users/rocke/.conan2/p/b/fmt0cab72a6447fa/p/include -isystem F:/sdk/SDL2-2.28.5/x86_64-w64-mingw32/include/SDL2 -isystem F:/sdk/SDL2_ttf-2.20.2/x86_64-w64-mingw32/include/SDL2 -isystem F:/sdk/SDL2_image-2.7.1/x86_64-w64-mingw32/include/SDL2 -isystem F:/sdk/SDL2_mixer-2.6.3/x86_64-w64-mingw32/include/SDL2 -g -std=gnu++17 -Wall -Wextra -pedantic -g -Og -o "CMakeFiles\\Johnson.dir\\src\\utils\\textures.cpp.obj" -c "-resource-dir=G:\\Programs\\clangd\\lib\\clang\\17" -- "g:\\importants\\programming\\c - c++\\game-engine\\src\\utils\\textures.cpp"
~~~

**Extension output for textures.h**
~~~
I[15:34:40.750] ASTWorker building file g:\importants\programming\c - c++\game-engine\include\engine\textures.h version 1 with command inferred from G:/importants/programming/c - c++/game-engine/src/utils/textures.cpp
[G:/importants/programming/c - c++/game-engine/build]
"C:\\MingW\\bin\\c++.exe" --driver-mode=g++ -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -g -Wall -Wextra -pedantic -g -Og -c -x c++-header -std=gnu++17 "-resource-dir=G:\\Programs\\clangd\\lib\\clang\\17" -- "g:\\importants\\programming\\c - c++\\game-engine\\include\\engine\\textures.h"
~~~

Right now I am working around this by manually adding the include directories through compile flags like this:
~~~yaml
If:
  PathMatch: .*\.h
CompileFlags:
  Add: [
    "-IF:\\sdk\\SDL2-2.28.5\\x86_64-w64-mingw32\\include\\SDL2\\",
    "-IG:\\importants\\programming\\c - c++\\game-engine\\include\\",
    "-IF:\\sdk\\SDL2_ttf-2.20.2\\x86_64-w64-mingw32\\include\\SDL2\\",
    "-IF:\\sdk\\SDL2_mixer-2.6.3\\x86_64-w64-mingw32\\include\\SDL2\\",
    "-IF:\\sdk\\SDL2_image-2.7.1\\x86_64-w64-mingw32\\include\\SDL2\\"
  ]
~~~

I'm not sure if this is intended behavior or if I am misunderstanding what "with command inferred from ..." means but I figured there was some better way of doing this.

**System information**

**Output of `clangd --version`:**
clangd version 17.0.3 (https://github.com/llvm/llvm-project 888437e1b60011b8a375dd30928ec925b448da57)
Features: windows+grpc
Platform: x86_64-pc-windows-msvc

**Editor/LSP plugin:**
clangd VSCode extension

**Operating system:**
Windows 10

**Comment by HighCommander4** [comment] 2023-12-15 02:50
Assuming the command is originally coming from `compile_commands.json`, could you show a sample entry from that file pleaes?

**Comment by HighCommander4** [comment] 2023-12-15 02:51
(If the command is written using `@file.rsp` with the flags contained in a file `file.rsp`, this is a known regression in clangd 17 tracked in https://github.com/llvm/llvm-project/issues/69690.)

**Comment by nathanieltooley** [comment] 2023-12-15 03:08
Here's the entry for textures.cpp:

~~~json
{
  "directory": "G:/importants/programming/c - c++/game-engine/build",
  "command": "C:\\MingW\\bin\\c++.exe -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL @CMakeFiles/Johnson.dir/includes_CXX.rsp -g -std=gnu++17 -Wall -Wextra -pedantic -g -Og -o CMakeFiles\\Johnson.dir\\src\\utils\\textures.cpp.obj -c \"G:\\importants\\programming\\c - c++\\game-engine\\src\\utils\\textures.cpp\"",
  "file": "G:/importants/programming/c - c++/game-engine/src/utils/textures.cpp",
  "output": "CMakeFiles/Johnson.dir/src/utils/textures.cpp.obj"
},
~~~

Looking at it now, I do notice that it does not contain the include flags, though I am not sure how they get added for the cpp files and not for the header files.

**Comment by HighCommander4** [comment] 2023-12-15 03:26
Right, so the command contains `@CMakeFiles/Johnson.dir/includes_CXX.rsp`, which is a reference to a file `CMakeFiles/Johnson.dir/includes_CXX.rsp` which contains the actual flags.

So, that makes this issue a duplicate of https://github.com/llvm/llvm-project/issues/69690, which is a regression in clangd 17.

Current workarounds are to use clangd 16, or to get CMake to put the flags directly into the command instead of using a response file.

**Comment by HighCommander4** [comment] 2023-12-15 03:26
Duplicate of https://github.com/llvm/llvm-project/issues/69690

**Closed by HighCommander4** 2023-12-15 03:26 UTC
