### ISSUE TITLE
--query-driver + extension-less headers

### ISSUE THREAD

**Issue by cpsauer** [clangd/clangd#1173] opened 2022-05-31 01:02 UTC
Hey wonderful clangd folks,

Quick bug report at the intersection of --query-driver and extension-less headers that came up while trying to scope a user issue for the Bazel compile command extractor (https://github.com/hedronvision/bazel-compile-commands-extractor/issues/51)

From looking at their logs `System include extraction: invalid file type for ` it looks like an empty file extension is being marked as an invalid language (see code [here](https://github.com/llvm/llvm-project/blob/175833ed6f62b697ce6248930da54e4ddb7f4c00/clang-tools-extra/clangd/QueryDriverDatabase.cpp), searching for that string), based on the switch [here](https://github.com/llvm/llvm-project/blob/b9f3b7f89a4cb4cf541b7116d9389c73690f78fa/clang/lib/Driver/Types.cpp#L293). 

(If you look more closely at https://github.com/hedronvision/bazel-compile-commands-extractor/issues/51#issuecomment-1140468836, you might notice that they're also supplying the language which *should* have avoided this case based on my understanding of the code. Not sure what's going on there.)

Things otherwise work pretty well with extension-less headers in my experience!

Fixes might include: Treating extension-less files as C++ headers as a fallback (unless some other language has that unfortunate convention). And perhaps getting the language from the editor, because it probably has detected one before deciding to invoke clangd.

Thanks so much for your time and consideration!
Chris

**Comment by HighCommander4** [comment] 2022-06-13 05:31
I played around with this a bit, and discovered that clangd does the following which may explain some of the weirdness your user is seeing:

 * When opening a file which does not have its own entry in the CDB (let's call this "file A"), it first runs `InterpolatingCompilationDatabase`'s filesystem-based heuristic to choose a file in the CDB whose compile commands to use. Let's call the chosen file "file B".
   * In transferring the compile command from file B to file A, if file A's extension does not determine the file type (as with `<iostream>`) but file B's extension does, `InterpolatingCompilationDatabase` inserts a `-x` flag into the command.
 * The system include extractor (`QueryDriverDatabase`) then runs on the transferred command.
 * Then, clangd checks if file A is transitively included by a file which has been previously opened during this session. If it finds such a file (let's call it "file C"), it considers that file C (which we know includes file A) is a better choice of compile command for file A than file B (which was chosen by the filesystem-based heuristic), so it (roughly) repeats the above steps, transferring file C's command to file A instead.
   * (The reason for limiting this to files previously opened during this session is that information about inclusion relationships is not currently stored in the index, it's only computed and cached when opening a file. We'd like to impove this in #123.)

A couple of implications of this:

 * The `System include extraction: invalid file type for ` error should be rare -- it should only occur if the file being opened and the proxy file whose command is being used **both** have unknown file types based on their extension (e.g. both extensionless).
 * It's possible for the system include extractor to fail for file B but succeed for file C (e.g. if file B is extensionless and file C isn't). In such a case, the "invalid file type" error will appear in the logs from the time the extractor ran on file B, but the flags ultimately used will include the extracted includes.
   * (Note for interpreting logs: the results of the system include extractor are cached, under a (driver, filetype) key. It's therefore possible to see logs from the failed attempt for file B but _not_ see logs for the successful attempt for file C which uses a cached result.)
 * Since the behaviour depends on which files have been previously opened in the current session, it can potentially change from one session to the next.
   * Fortunately, for a standard library header like `<iostream>`, it's very likely to be opened by performing go-to-definition on either an #include or a standard library symbol in a project source file (rather than e.g. directly via File --> Open), so the inclusion heuristic should kick in fairly consistently.

**Comment by HighCommander4** [comment] 2022-06-13 05:36
(I do think the layering here is a bit unfortunate. I think it would be better if the inclusion heuristic were applied at the `InterpolatingCompilationDatabase` level (perhaps it can expose some sort of extension point for clients to plug in their own heuristics), rather than having the system include extractor potentially run twice and the results of the first run discarded.)

**Comment by HighCommander4** [comment] 2022-06-13 05:50
> Fixes might include: Treating extension-less files as C++ headers as a fallback (unless some other language has that unfortunate convention).

This sounds reasonable to me in principle, but I'll let others weigh in on the specifics.

Presumably we don't want to modify `clang::driver::types::lookupForExtension()` itself (I assume it has its current behaviour for a reason and other consumers may rely on it).

I tried implementing this locally by providing a fallback in `QueryDriverDatabase`, and found it wasn't sufficient -- while the system include extractor now succeeds, clang still refuses the parse the extensionless file without a `-x` flag to guide it. I had to take the different approach of changing `InterpolatingCompilationDatabase` to add a `-x` flag as a fallback, which then worked.

> And perhaps getting the language from the editor, because it probably has detected one before deciding to invoke clangd.

This could potentially work as well, though it would need to be fleshed out a bit more, e.g. how is the file type communicated over LSP, and how does a file type provided in this way interact with other sources of information such as a `-x` flag in the compiler command.

**Comment by cpsauer** [comment] 2022-06-13 07:29
Hey Nathan! Thanks so much for looking into this--and more generally for looking after the Bazel users we set up with clangd. I really appreciate it.

So [based on the logs they posted](https://github.com/hedronvision/bazel-compile-commands-extractor/issues/51), is the issue, we think, that .h headers are also language ambiguous? If so, that might explain why this case came up: I'm imaging they opened a header and then CMD+clicked into <iostream> without opening the cpp file.

(Well aware of #123, unfortunately! most of the code and runtime in our plugin is working around it, adding entries for all the headers. What I didn't realize is that the include graph of *all* opened files is stored. I knew only is that things worked if you CMD+clicked from the source.)

Cheers,
Chris

**Comment by HighCommander4** [comment] 2022-06-13 08:36
> So [based on the logs they posted](https://github.com/hedronvision/bazel-compile-commands-extractor/issues/51), is the issue, we think, that .h headers are also language ambiguous? If so, that might explain why this case came up: I'm imaging they opened a header and then CMD+clicked into `<iostream>` without opening the cpp file.

A few possibilities here:

  1. The .h header in question does not have its own entry in the CDB. In this case, it's not going to be relevant for the inclusion heuristic, and in the absence of an open file which does have its own entry, clangd will just go with the source file chosen by the filesystem-based heuristic,
  2. The .h header has an entry in the CDB, and its compile command includes `-x c++-header`. In this case, the C++ filetype should be correctly propagated to `<iostream>`.
  3. The .h header has an entry in the CDB, but its compile command does not include `-x c++-header`. This seems unlikely, as local testing shows me that in this case the .h header itself is processed as C and e.g. `<iostream>` isn't even resolved as an include.

**Comment by cpsauer** [comment] 2022-08-23 01:25
I got reminded of this, looking through logs and seeing them mostly composed of this `System include extraction: invalid file type for ` warning, spawned during indexing.

It's definitely a very common occurrence for this use case. To trace this case through your possibilities:

The extensionless header has an entry in the CDB, to work around #123. Its command is one used to compile it, i.e, containing a source file that includes it. There's shouldn't be a -x needed to disambiguate, since the source file in the command should disambiguate (see https://reviews.llvm.org/D116167). As a simplified example:
```json
"file": "<wherever>/cxx-stl/llvm-libc++/include/iostream",
    "arguments": [
        "clang",
        "main.cpp",
    ]
```

I also see some erroneous entries for .ipp files, denoting a template header implementation. For example `System include extraction: invalid file type for ipp` for "external/boost/libs/atomic/src/lock_pool_init1.ipp".

I'd like to ask/propose:
- Could I ask someone more familiar with the codebase than I check to make sure the source-file-based inference is being properly used here, parallel to https://reviews.llvm.org/D116167?
- Thoughts on designating ipp as a C++ header, as well as <no_extension> in [the switch](https://github.com/llvm/llvm-project/blob/b9f3b7f89a4cb4cf541b7116d9389c73690f78fa/clang/lib/Driver/Types.cpp#L293)? 

cc'ing @sam-mccall, beacause we're discussing https://reviews.llvm.org/D116167. Hopefully that's okay, Sam.

**Comment by HighCommander4** [comment] 2022-08-23 06:12
>    * Could I ask someone more familiar with the codebase than I check to make sure the source-file-based inference is being properly used here, parallel to https://reviews.llvm.org/D116167?

I tried the scenario you described locally:

 * `--query-driver` is used
 * The CDB contains an entry for an extensionless header, whose command refers to a `.cpp` file but has no `-x` flag
 * User opens the extensionless header

What I found was that the D116167 mechanism does **not** kick in. The reason is that this mechanism is implemented as part of `CommandMangler`, and the way things are currently layered, `QueryDriverDatabase` runs before `CommandMangler`.

So `QueryDriverDatabase` does not recognize the file type, prints the `System include extraction: invalid file type for ` message, and... returns an [empty compile command](https://searchfox.org/llvm/rev/494b6c46d6aadcf1f659634f719768e9ff6fef17/clang-tools-extra/clangd/QueryDriverDatabase.cpp#344-345) :(

[As an aside, returning an empty compile command seems like an unnecessarily destructive way for `QueryDriverDatabase` to fail. It could at least just return the incoming compile command unmodified, right?]

The compile command being empty causes `CommandMangler` to [also bail](https://searchfox.org/llvm/rev/494b6c46d6aadcf1f659634f719768e9ff6fef17/clang-tools-extra/clangd/CompileCommands.cpp#204-205), and we end up with the fallback command.

(Language-wise, the fallback command uses `-xobjective-c++-header` so it recognizes C++ constructs, but `QueryDriverDatabase` didn't get a chance to provide the compiler's built-in includes, so the overall result is potentially quite wrong.)

This is not the first time I've run into problems caused by the fact that `QueryDriverDatabase` runs before `CommandMangler` (https://github.com/clangd/clangd/issues/1089#issuecomment-1087226248 is another case). I think we should switch the order of these.

>    * Thoughts on designating ipp as a C++ header, as well as <no_extension> in [the switch](https://github.com/llvm/llvm-project/blob/b9f3b7f89a4cb4cf541b7116d9389c73690f78fa/clang/lib/Driver/Types.cpp#L293)?

Just some general observations:

 * This is code common to all clang-based tooling, not just clangd, so modifications require some care.
   * In particular for the case of extensionless headers, I can't imagine this hasn't come up before, so I assume there's a good reason why that switch doesn't consider them as C++ (but I don't know what that reason is).
 * I recently came across and poked a [patch](https://reviews.llvm.org/D67025) to add `.inl` to that switch and that doesn't seem to be uncontroversial either. (I have no thoughts on `.ipp` specifically.)

**Comment by cpsauer** [comment] 2022-08-24 02:00
Thanks for tracing things down, @HighCommander4! I don't know as much as you guys, but switching the order sounds like the basis for a good fix to me.

[And yeah, I know about the common code. Thanks for linking me to the strong resistance. Maybe ipp might have some arguments around being clearly C++ specific and fairly common, but perhaps better if <empty> and ipp just make it into a clangd-specific wrapper around that function, if that's what ends up happening.]

Cheers! Thank you!
Chris

**Comment by cpsauer** [comment] 2022-08-25 06:48
There's another bug, I think maybe, [here](https://github.com/llvm/llvm-project/blob/175833ed6f62b697ce6248930da54e4ddb7f4c00/clang-tools-extra/clangd/QueryDriverDatabase.cpp#L335), where it doesn't detect the language from the `--language` form of the flag, or from `-ObjC` or `-ObjC++`--unless things have been normalized somewhere else?

**Comment by HighCommander4** [comment] 2022-09-01 07:43
> [As an aside, returning an empty compile command seems like an unnecessarily destructive way for `QueryDriverDatabase` to fail. It could at least just return the incoming compile command unmodified, right?]

(Fixed this in https://reviews.llvm.org/D132833.)

I will try to write a patch that fixes the main issue here (and #1089 as well) by changing the order of `QueryDriverDatabase` and `CommandMangler`.

> There's another bug, I think maybe, [here](https://github.com/llvm/llvm-project/blob/175833ed6f62b697ce6248930da54e4ddb7f4c00/clang-tools-extra/clangd/QueryDriverDatabase.cpp#L335), where it doesn't detect the language from the `--language` form of the flag, or from `-ObjC` or `-ObjC++`--unless things have been normalized somewhere else?

Could I ask you to file a separate issue for this one, to make sure we don't lose track of it? Thanks!

**Comment by cpsauer** [comment] 2022-09-02 00:01
👍🏻 refiled over at #1274

**Comment by cpsauer** [comment] 2022-09-02 00:01
Again, thank you so much!

**Comment by HighCommander4** [comment] 2022-09-12 08:26
> I will try to write a patch that fixes the main issue here (and #1089 as well) by changing the order of `QueryDriverDatabase` and `CommandMangler`.

I'm close to a patch here, just need to iron out a few wrinkles.

 * It turns out we can't run `QueryDriverDatabase` after the entirety of `CommandMangler`, because the last step of `CommandMangler` [messes up](https://searchfox.org/llvm/rev/69d9bb2aade39c76de9d6da9e2383377852e4d73/clang-tools-extra/clangd/CompileCommands.cpp#160-165) relative driver paths, e.g. turning `gcc` into `/path/to/clang/bin/gcc`. Rather it needs to run **in the middle of** `CommandMangler`, after [these parts](https://searchfox.org/llvm/rev/69d9bb2aade39c76de9d6da9e2383377852e4d73/clang-tools-extra/clangd/CompileCommands.cpp#287-296,298-299) but before [this part](https://searchfox.org/llvm/rev/69d9bb2aade39c76de9d6da9e2383377852e4d73/clang-tools-extra/clangd/CompileCommands.cpp#330-337).
 * `QueryDriverDatabase` needs access to the entire `tooling::CompileCommand` because it uses the directory [here](https://searchfox.org/llvm/rev/69d9bb2aade39c76de9d6da9e2383377852e4d73/clang-tools-extra/clangd/QueryDriverDatabase.cpp#354), but `CommandMangler` currently only has access to the arguments list.

This is all solvable, it just requires tweaking some of the abstractions a bit.

**Comment by cpsauer** [comment] 2022-09-12 08:36
Thanks so much for diving into it, Nathan. I really appreciate you!

**Comment by HighCommander4** [comment] 2022-09-13 08:22
Proposed patches:
https://reviews.llvm.org/D133756
https://reviews.llvm.org/D133757

They also fix #1089 and #1263

**Comment by cpsauer** [comment] 2022-10-14 22:23
How're these going, Nathan?
Really appreciate your having dug in and fixing the underlying cause of a bunch of issues here.

**Comment by HighCommander4** [comment] 2022-10-14 22:26
Sorry, I've been out of commission for a bit due to travel... I'm back now though and getting the review comments on those patches addressed is very near the top of my list :)

**Closed** 2022-11-07 23:03 UTC

**Comment by HighCommander4** [comment] 2022-11-07 23:07
@cpsauer Patches just merged!

Once you or your users get a chance to test this, I would be curious to know if it in fact resolved this issue (and #1263).

**Comment by cpsauer** [comment] 2022-11-07 23:25
Wahoo! Thanks so much, @HighCommander4.

Will do. Best way is to wait for the next weekly prerelease and then have folks test, right?

**Comment by HighCommander4** [comment] 2022-11-07 23:39
> Best way is to wait for the next weekly prerelease and then have folks test, right?

On Linux you can get nightly packages from https://apt.llvm.org/, but otherwise yeah.

**Comment by cpsauer** [comment] 2022-11-17 06:52
These error message, too, have gone away with the latest snapshot! Thank you, again :)

[I'll test the other one shortly.]

**Comment by cpsauer** [comment] 2022-12-03 04:29
@HighCommander4, just checking in on release cycles:
Your fix will go out out in clangd 16, but not in the 15.0.x patches, right?
(That's what I was got from the code as best I could determine, but I wanted to confirm. The impetus is wanting to unwind the workarounds we had for these issues, since they're complicating inbound PRs.)

**Comment by HighCommander4** [comment] 2022-12-03 05:13
> Your fix will go out out in clangd 16, but not in the 15.0.x patches, right?

Yep. Unfortunately, I don't think any further 15.x releases are planned at this point.

**Comment by cpsauer** [comment] 2022-12-03 07:09
👍🏻 Again, huge thanks, Nathan.
