### ISSUE TITLE
Error extraneous_closing_brace in includes

### ISSUE THREAD

**Issue by Barricade** [clangd/clangd#200] opened 2019-11-17 19:21 UTC
I have the following project structure:

`tws/tws.cpp`:
```
#include <tws/lang/begin.h>
typedef int aaaaa; // There are no errors without any code here
#include <tws/lang/end.h>
```
`tws/lang/begin.h`:
```
#ifdef __cplusplus
extern "C" {
#endif
```
`tws/lang/eng.h`:
```
#ifdef __cplusplus
}
#endif
```
`compile_commands.json`:
```
[
	{
		"directory": "/Users/barricadenick/Dropbox/Workspace/TW/to_del",
		"command": "/usr/local/opt/llvm/bin/clang++ '-c' '-I/Users/barricadenick/Dropbox/Workspace/TW/to_del/src' '-xc++' '/Users/barricadenick/Dropbox/Workspace/TW/to_del/src/tws/tws.cpp' '-o/Users/barricadenick/Dropbox/Workspace/TW/to_del/tmp/build/tws-0.1.0-macos/tws.o'",
		"file": "/Users/barricadenick/Dropbox/Workspace/TW/to_del/src/tws/tws.cpp"
	}
]
```

And I get the following errors:
```
src/tws/tws.cpp|2 col 1 error| Expected '}' /Users/barricadenick/Dropbox/Workspace/TW/to_del/src/tws/lang/begin.h:2:12: note: to match this '{' [expected]
src/tws/tws.cpp|3 col 10 error| In included file: extraneous closing brace ('}') /Users/barricadenick/Dropbox/Workspace/TW/to_del/src/tws/lang/end.h:2:1: note: error occurred here [extraneous_closing_brace]
```

It seems that `begin.h` and `end.h` are analyzed independently. How could I prevent such errors showing in `tws.cpp`? (Mac OS X, llvm 9.0.0_1)

**Comment by kadircet** [comment] 2019-11-18 11:23
I suspect this is caused by our "preamble parsing".

Clangd parses each file in two parts:
- the preamble part
  - which is basically any preprocessor directives and comments at the beginning of the file up until the first "decl-like" thing (the line `typedef int aaaaa;` in your example).
- the main file part
  - anything after the preamble.

Therefore whenever building the preamble clangd sees broken code, and then when merging the rest with the preamble sees broken code again(preamble and main file contents are not just appended textually).

**Comment by sam-mccall** [comment] 2019-11-22 00:53
Yeah, the preamble processing is a hack but works on most real-world C++ code.
It'd be nice to fix this without requiring the code to change, but having half-formed constructs in the preamble doesn't seem like it's going to end well. I suspect clangd doesn't see your code as being covered in the extern block.

I think the usual idiom for extern/namespaces was to make these macros like

macros.h:
```
#if __cplusplus
#define EXTERN_C_BEGIN extern "C" {
#define EXTERN_C_END }
#else
#define EXTERN_C_BEGIN
#define EXTERN_C_END
#endif
```

tws.cpp:
```
#include "macros.h"
#include "other_stuff.h"
EXTERN_C_BEGIN
// code here
EXTERN_C_END
```

**Comment by kadircet** [comment] 2021-12-20 14:17
Closing as this is #45 in the non idiomatic case.

**Closed by kadircet** 2021-12-20 14:17 UTC

**Comment by HighCommander4** [comment] 2021-12-20 20:30
To me this doesn't seem like a strict duplicate of #45, in that errors show up even when viewing `tws.cpp`, which taken as a whole is a self-contained file.

That said, I do agree it's an edge case.
