### ISSUE TITLE
clangd doesn't find all references for define

### ISSUE THREAD

**Issue by StMartin81** [clangd/clangd#1002] opened 2022-01-27 18:01 UTC
Search for references of **SM_EVENT_BATTERY_SM_GET_SOC**. clangd will only show the references in main.c and sm_events_local.h but there should be another reference in app_config.h found.

[test-clangd.zip](https://github.com/clangd/clangd/files/7952783/test-clangd.zip)

Output of `clangd --version`:
clangd version 13.0.0
Features: linux
Platform: x86_64-pc-linux-gnu

Editor/LSP plugin:
Visual Studio Code + clangd

Operating system:
Archlinux

**Comment by sam-mccall** [comment] 2022-01-27 18:39
It would definitely be nice to capture this as a reference.

A few related things here:

- in a very formal sense, the mention inside a macro body in app_config.h isn't a reference, it's just text. If you `#undef SM_EVENT_BATTERY_SM_GET_SOC` before expanding `APP_CONFIG_BATTERY_SM_GET_SOC`, the identifier could end up referring to a variable or something
- our implementation uses clang's `PPCalllbacks::MacroExpands`, which follows the precise formal rules. We'd need to add heuristics.
- the reference is actually formally visible because the outer macro is used somewhere. But we can't use this easily in indexing because it violates our assumption that every includer indexes a header in the same way.

**Comment by HighCommander4** [comment] 2022-01-28 07:55
Dupe of #346

**Closed by HighCommander4** 2022-01-28 07:55 UTC
