### ISSUE TITLE
Nested autocompletion: the cursor does not get inside an inner pair of parentheses automaticaly

### ISSUE THREAD

**Issue by kasos5000** [clangd/clangd#1190] opened 2022-06-15 18:01 UTC
I use VSCode + clangd and a problem appeared recently. When I'm using completion e.g. a template instance and then, without escaping the snippet mode, I'm using completion for a function to get the parameter, the cursor just skips the parentheses of the completed expression, and the placeholder inside the pair of parentheses does not get selected, like at the following picture:
![completion2](https://user-images.githubusercontent.com/79150779/173893245-5f57c201-7d65-4263-8991-89d6809ab539.PNG)
With angle inner brackets all works OK, with only circle brackets used in a nested expression- too (like in a nested function call).

**Comment by HighCommander4** [comment] 2022-06-15 18:11
To help understand the issue better, could you provide a complete code example please (and then indicate where you are invoking code completion)?

**Comment by kasos5000** [comment] 2022-06-16 18:24
In more details:
![Detailed_completion](https://user-images.githubusercontent.com/79150779/174137321-b50b6258-f1a1-4365-b70e-cbdb165459e9.png)
After the second completion typing should be replacing the "expression" between the parentheses, but it's occurring after the closing one.
Overall, that's the complete example. As a template instance there could be anything instead of ArgWrapper. Like std::vector, for example.

**Comment by HighCommander4** [comment] 2022-06-22 02:38
Thanks, I understand what the issue is now.

The issue seems to be specific to the `decltype(expression)` completion proposal; in a similar situation where e.g. the template is expecting a non-type parameter, and I complete the name of a constexpr function, the cursor is inside the function call as expected.

Looking at the LSP messages, the relevant difference seems to be that for `decltype(expression)`, the `insertText` in the response to the `textDocument/completion` mesage is `decltype(${0:expression})`, whereas in a working case like a call to a function `foo`, it's `bar(${1:int})`.

According to the [spec](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#insertTextFormat), the `$0` placeholder is somewhat special:

> `$0` defines the final tab stop, it defaults to the end of the snippet.

Not sure why clangd is using `$0` in this case rather than `$1`.

**Comment by HighCommander4** [comment] 2022-06-22 02:56
> Not sure why clangd is using `$0` in this case rather than `$1`.

I guess this is a result of the logic [here](https://searchfox.org/llvm/rev/716e27bc9ad4699bbc82318834e938bcc9682cf8/clang-tools-extra/clangd/CodeCompletionStrings.cpp#103-113):

```c++
  if (CompletingPattern) {
    // In patterns, it's best to place the cursor at the last placeholder, to
    // handle cases like
    //    namespace ${1:name} {
    //      ${0:decls}
    //    }
    CursorSnippetArg =
        llvm::count_if(CCS, [](const CodeCompletionString::Chunk &C) {
          return C.Kind == CodeCompletionString::CK_Placeholder;
        });
  }
```

This logic was introduced in https://reviews.llvm.org/D62389.

**Comment by HighCommander4** [comment] 2022-06-22 03:09
Ok, so the meaning of `$0` is:

 * if `$0` is not present in the snippet, then after tabbing through `$1`, `$2`, etc., one more tab will take you to the end of the completion string
 * if `$0` is present in the snippet, then after tabbing through `$1`, `$2`, etc., one more tab will take you to the `$0`

So, when completing a function call, the string does not contain `$0`, and so after tabbing through the arguments, the next tab will take you to the end of the function call expression (after the ')`).

When completing a "pattern", clangd uses `$0` for the last placeholder, so tabbing will end there. This appears to have been done with patterns that insert declarations in mind (like the namespace pattern mentioned in the comment). Not sure if it makes sense for the `decltype(expression)` pattern, where you're fairly likely to want to write something after the `)`.

---

With all that said, I don't understand how this usage of `$0` results in the incorrect cursor placement that's at issue here. That seems like a client-side bug in vscode, worth filing separately regardless of whether we change the snippet string for the `decltype(expresion)` completion in clangd.

**Comment by HighCommander4** [comment] 2022-06-22 03:22
> With all that said, I don't understand how this usage of `$0` results in the incorrect cursor placement that's at issue here. That seems like a client-side bug in vscode, worth filing separately

In fact, this appears to be a **regression** in vscode (which is consistent with your report that this problem appeared recently).

**Comment by HighCommander4** [comment] 2022-06-22 03:30
> In fact, this appears to be a **regression** in vscode

The regression appeared between vscode 1.66 and 1.67.

So, if you don't use any new vscode features in 1.67 or later, a temporary workaround until the issue is fixed in vscode could be to downgrade to 1.66.

**Comment by HighCommander4** [comment] 2022-06-22 07:37
> In fact, this appears to be a **regression** in vscode

Filed as https://github.com/microsoft/vscode/issues/152837

**Comment by HighCommander4** [comment] 2022-06-24 07:58
> > In fact, this appears to be a **regression** in vscode
> 
> Filed as [microsoft/vscode#152837](https://github.com/microsoft/vscode/issues/152837)

Based on the discussion in that issue, it seems that clangd is misusing the snippet syntax.

There is a distinction between:

 * **tab stops**, e.g. `$1`
 * **placeholders**, e.g. `${1:something}`

Basically, placeholders are tab stops with additional behaviour (the text `something` is displayed and selected, and the placeholder can appear in multiple places in the snippet which will be modified simultaneously when the user types).

Importantly, `$0` (the special tab stop that is at the end of the snippet by default) **cannot be a placeholder**.

So, clangd is invoking unsupported behaviour by using `decltype(${0:expression})`.

**Comment by kasos5000** [comment] 2022-06-25 22:19
> The issue seems to be specific to the `decltype(expression)` completion proposal

In fact, the same problem appears with `sizeof()` and `sizeof...()`.

**Comment by HighCommander4** [comment] 2022-06-25 22:34
> > The issue seems to be specific to the `decltype(expression)` completion proposal
> 
> In fact, the same problem appears also with `sizeof()` and `sizeof...()`.

Yes, to be more precise, it happens for completion proposals which are "patterns" (as opposed to e.g. functions / other symbols).

**Comment by HighCommander4** [comment] 2022-06-27 02:43
I can't think of another fix besides reverting the change made in https://reviews.llvm.org/D62389 to try to use `$0` as a placeholder.

Sent out https://reviews.llvm.org/D128621 to do that.

**Comment by sam-mccall** [comment] 2022-07-12 14:17
Sorry to be late to the bug

We can't change the behavior of already-released clangd.
If the VSCode regression is serious, we could monkeypatch it on the client (in `vscode-clangd`).
This would be tech debt: we need to fix it on the server too, and eventually remove the client hack.

I don't have a feeling for how serious this is. Given it affects RK_Pattern but not RK_Declaration, and only VSCode (despite being debatably out-of-spec), maybe not terrible?
So I guess I lean towards a server-side fix like this but curious if others agree.

---

The options I've seen:
A. `while (${1:cond}) {${0:stmt}}` - current behavior (broken in head vscode)
B. `while (${1:cond}) {${2:stmt}}` - D128621
C. `while (${1:cond}) {${2:stmt}$0}` - @kadircet's suggestion
D. `while (${1:cond}) {$0}` - @ilya-biryukov's suggestion.

(any others?)

My evaluations:
- I like A on a technical level, *and* I like arguing (in this case, with vscode folks). However I think we'll lose.
- B is the simple fix, but feels bad for braced blocks - as you "escape" placeholders, dropping you on the outside of the braces (but on the same line) is silly.
- C & D more closely approximate the old behavior, but maybe with artifacts (presumably C eats an extra `<enter>`, D means no placeholder text. My feeling is this behavior is what you want for braced blocks but not for e.g. `sizeof()`.

I think I like D best on some combination of (similar behavior, similar implementation, reasonable behavior). In practice I don't think losing the placeholder name for "statements", "declarations" or the arg of patterns like `decltype()` matters much.

If I were to be picky I'd later want to somehow instead end up with `decltype($1)`, i.e. final tabstop outside, without changing the behavior for braced blocks. But this is outside the realm of dealing with the regression.

**Comment by HighCommander4** [comment] 2022-07-18 07:55
> I think I like D best on some combination of (similar behavior, similar implementation, reasonable behavior). In practice I don't think losing the placeholder name for "statements", "declarations" or the arg of patterns like `decltype()` matters much.

+1, updated the [patch](https://reviews.llvm.org/D128621) to take approach D

**Closed** 2022-07-24 07:01 UTC
Labels: bug
