### ISSUE TITLE
clangd respects -Werror in compile_commands.json

### ISSUE THREAD

**Issue by apache-hb** [clangd/clangd#2157] opened 2024-09-23 20:55 UTC
clangd now respects -Werror or /WX when present in compile_commands.json

as seen in these 2 logs, in defer.hpp at lines 3, 6, and 8. 18.3 produces warnings, whereas 20 produces errors.
[18-clangd.log](https://github.com/user-attachments/files/17104148/18-clangd.log)
[20-clangd.log](https://github.com/user-attachments/files/17104149/20-clangd.log)

**Comment by HighCommander4** [comment] 2024-10-16 04:23
This appears to be fixed in more recent trunk.

**Comment by HighCommander4** [comment] 2024-10-16 04:50
A regression test for exactly this issue was added in https://github.com/llvm/llvm-project/commit/9e65dcac660723a06039c7e9b30f305b9b8ca652, though it doesn't mention what changes regressed and subsequently fixed the issue.

**Comment by HighCommander4** [comment] 2024-10-16 05:51
It looks like the regressing change was https://github.com/llvm/llvm-project/pull/70976, and the fix was its revert in https://github.com/llvm/llvm-project/commit/2ad435f9f6fb792d9b010ddf56ca3ea26fbf5f15.

Closing this issue as there's nothing further to do here (the regression on trunk has been fixed, and the added regression test will make sure it does not regress again).

**Closed by HighCommander4** 2024-10-16 05:51 UTC
