### ISSUE TITLE
clang-tidy check matching translationUnitDecl does not work in clangd

### ISSUE THREAD

**Issue by vbar** [clangd/clangd#947] opened 2021-12-09 09:11 UTC
I have a custom clang-tidy check, which can be simplified to

```C++
void TopMatchCheck::registerMatchers(MatchFinder *Finder) {
  Finder->addMatcher(translationUnitDecl().bind("x"), this);
}

void TopMatchCheck::check(const MatchFinder::MatchResult &Result) {
  const auto *MatchedDecl = Result.Nodes.getNodeAs<TranslationUnitDecl>("x");
  diag(MatchedDecl->getLocation(), "matched translation unit");
}
```
(the rest or TopMatchCheck being generated by `python add_new_check.py misc top-match`). This works in `clang-tidy`:

    clang-tidy file.c --
    2 warnings generated.
    warning: matched translation unit [misc-top-match]
    /tmp/c/file.c:1:25: warning: parameter 'b' is unused [misc-unused-parameters]
    int function(int a, int b)
                            ^

but clangd built from the same sources shows only the misc-unused-parameters warning (log of opening the same file in Monaco editor attached).
[clangd.log](https://github.com/clangd/clangd/files/7683715/clangd.log)

**Comment by HighCommander4** [comment] 2021-12-10 07:10
I haven't confirmed this, but I have a suspicion this may be intentional, because clangd only runs clang-tidy checks on the declarations in the main file (not in the preamble) for performance reasons. That may preclude matching the TUDecl whose children include the preamble decls.

**Comment by HighCommander4** [comment] 2021-12-10 07:34
Actually it looks like this was fixed in clangd 13 and later: https://reviews.llvm.org/D104071. Now the TUDecl should be visited, though the child decls in the preamble are still skipped.

**Comment by sam-mccall** [comment] 2021-12-10 12:08
That's right, originally we hid the TUDecl and now we expose it but with a pruned tree. This should allow such clang-tidy checks to work. (If the check is not using RecursiveASTVisitor but rather use TUDecl::decls() directly, it may create a performance cliff).

I'm confused about the lack of version information in the log, it looks like an old log (no version information) but says "clang/14.0.0" in the resource dir. Can you clarify what commit you're building from?

**Comment by vbar** [comment] 2021-12-10 13:20
About the version information, I cut it off, and I don't remember exactly when I cloned that repo, but anyway the problem persists on LLVM sources cloned today, where the only difference is the added misc-top-match - see the attached log.
[clangd2.log](https://github.com/clangd/clangd/files/7692976/clangd2.log)

Maybe the translationUnitDecl matching had been removed again?

**Comment by HighCommander4** [comment] 2021-12-13 08:25
When I run your matcher in a debug build of clangd, I get an assertion failure:

```
clangd: clang-tools-extra/clang-tidy/ClangTidyDiagnosticConsumer.cpp:191: clang::DiagnosticBuilder clang::tidy::ClangTidyContext::diag(llvm::StringRef, clang::SourceLocation, llvm::StringRef, DiagnosticIDs::Level): Assertion `Loc.isValid()' failed.
 #0 0x00007fa5d7d1457a llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) llvm/lib/Support/Unix/Signals.inc:565:11
 #1 0x00007fa5d7d1472b PrintStackTraceSignalHandler(void*) llvm/lib/Support/Unix/Signals.inc:632:1
 #2 0x00007fa5d7d12df3 llvm::sys::RunSignalHandlers() llvm/lib/Support/Signals.cpp:97:5
 #3 0x00007fa5d7d14e55 SignalHandler(int) llvm/lib/Support/Unix/Signals.inc:407:1
 #4 0x00007fa5ddcc9730 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x12730)
 #5 0x00007fa5d71057bb raise /build/glibc-vjB4T1/glibc-2.28/signal/../sysdeps/unix/sysv/linux/raise.c:51:1
 #6 0x00007fa5d70f0535 abort /build/glibc-vjB4T1/glibc-2.28/stdlib/abort.c:81:7
 #7 0x00007fa5d70f040f _nl_load_domain /build/glibc-vjB4T1/glibc-2.28/intl/loadmsgcat.c:1177:9
 #8 0x00007fa5d70fe102 (/lib/x86_64-linux-gnu/libc.so.6+0x30102)
 #9 0x00007fa5dc6b5624 clang::tidy::ClangTidyContext::diag(llvm::StringRef, clang::SourceLocation, llvm::StringRef, clang::DiagnosticIDs::Level) clang-tools-extra/clang-tidy/ClangTidyDiagnosticConsumer.cpp:0:3
#10 0x00007fa5dc6b056d clang::tidy::ClangTidyCheck::diag(clang::SourceLocation, llvm::StringRef, clang::DiagnosticIDs::Level) clang-tools-extra/clang-tidy/ClangTidyCheck.cpp:27:19
#11 0x00007fa5d528297d clang::tidy::misc::TopMatchCheck::check(clang::ast_matchers::MatchFinder::MatchResult const&) clang-tools-extra/clang-tidy/misc/TopMatchCheck.cpp:25:3
#12 0x00007fa5dc6b067e clang::tidy::ClangTidyCheck::run(clang::ast_matchers::MatchFinder::MatchResult const&) clang-tools-extra/clang-tidy/ClangTidyCheck.cpp:46:1
#13 0x00007fa5d2f7a71d clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor::MatchVisitor::visitMatch(clang::ast_matchers::BoundNodes const&) clang/lib/ASTMatchers/ASTMatchFinder.cpp:1060:7
#14 0x00007fa5d309df1a clang::ast_matchers::internal::BoundNodesTreeBuilder::visitMatches(clang::ast_matchers::internal::BoundNodesTreeBuilder::Visitor*) clang/lib/ASTMatchers/ASTMatchersInternal.cpp:105:5
#15 0x00007fa5d2f7a3d3 clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor::matchWithFilter(clang::DynTypedNode const&) clang/lib/ASTMatchers/ASTMatchFinder.cpp:868:7
#16 0x00007fa5d2f7a0c2 clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor::matchDispatch(clang::Decl const*) clang/lib/ASTMatchers/ASTMatchFinder.cpp:887:5
#17 0x00007fa5d2f79ecd void clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor::match<clang::Decl>(clang::Decl const&) clang/lib/ASTMatchers/ASTMatchFinder.cpp:719:3
#18 0x00007fa5d2f7bc7d clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor::TraverseDecl(clang::Decl*) clang/lib/ASTMatchers/ASTMatchFinder.cpp:1247:3
#19 0x00007fa5d2ef3b92 clang::RecursiveASTVisitor<clang::ast_matchers::internal::(anonymous namespace)::MatchASTVisitor>::TraverseAST(clang::ASTContext&) clang/include/clang/AST/RecursiveASTVisitor.h:200:5
#20 0x00007fa5d2ef3a39 clang::ast_matchers::MatchFinder::matchAST(clang::ASTContext&) clang/lib/ASTMatchers/ASTMatchFinder.cpp:1476:11
#21 0x00007fa5dd1c8b07 clang::clangd::ParsedAST::build(llvm::StringRef, clang::clangd::ParseInputs const&, std::unique_ptr<clang::CompilerInvocation, std::default_delete<clang::CompilerInvocation> >, llvm::ArrayRef<clang::clangd::Diag>, std::shared_ptr<clang::clangd::PreambleData const>) clang-tools-extra/clangd/ParsedAST.cpp:495:3
#22 0x00007fa5dd360ee6 clang::clangd::(anonymous namespace)::ASTWorker::generateDiagnostics(std::unique_ptr<clang::CompilerInvocation, std::default_delete<clang::CompilerInvocation> >, clang::clangd::ParseInputs, std::vector<clang::clangd::Diag, std::allocator<clang::clangd::Diag> >) clang-tools-extra/clangd/TUScheduler.cpp:1092:40
#23 0x00007fa5dd360ba0 clang::clangd::(anonymous namespace)::ASTWorker::updatePreamble(std::unique_ptr<clang::CompilerInvocation, std::default_delete<clang::CompilerInvocation> >, clang::clangd::ParseInputs, std::shared_ptr<clang::clangd::PreambleData const>, std::vector<clang::clangd::Diag, std::allocator<clang::clangd::Diag> >, clang::clangd::WantDiagnostics)::$_2::operator()() clang-tools-extra/clangd/TUScheduler.cpp:1026:5
#24 0x00007fa5dd362a2d void llvm::detail::UniqueFunctionBase<void>::CallImpl<clang::clangd::(anonymous namespace)::ASTWorker::updatePreamble(std::unique_ptr<clang::CompilerInvocation, std::default_delete<clang::CompilerInvocation> >, clang::clangd::ParseInputs, std::shared_ptr<clang::clangd::PreambleData const>, std::vector<clang::clangd::Diag, std::allocator<clang::clangd::Diag> >, clang::clangd::WantDiagnostics)::$_2>(void*) llvm/include/llvm/ADT/FunctionExtras.h:222:5
#25 0x00007fa5dce60d5f llvm::unique_function<void ()>::operator()() llvm/include/llvm/ADT/FunctionExtras.h:384:5
#26 0x00007fa5dd369c45 void llvm::function_ref<void ()>::callback_fn<llvm::unique_function<void ()> >(long) llvm/include/llvm/ADT/STLExtras.h:177:5
#27 0x00007fa5dd369c29 llvm::function_ref<void ()>::operator()() const llvm/include/llvm/ADT/STLExtras.h:200:5
#28 0x00007fa5dd35c714 clang::clangd::(anonymous namespace)::ASTWorker::runTask(llvm::StringRef, llvm::function_ref<void ()>) clang-tools-extra/clangd/TUScheduler.cpp:1207:1
#29 0x00007fa5dd35bdfa clang::clangd::(anonymous namespace)::ASTWorker::run() clang-tools-extra/clangd/TUScheduler.cpp:1340:5
```

My guess is the diagnostic not showing up has to do with that.

**Comment by HighCommander4** [comment] 2021-12-13 09:22
A debug build of clang-tidy produces the same assertion failure, so this part is not specific to clangd.

Basically, it appears that `TranslationUnitDecl` does not get a valid location. Not sure if this is intentional or a bug in clang's AST modelling.

The difference is, in a release build, clang-tidy ploughs on and prints the diagnostic message anyways (without a location), whereas clangd drops it because it doesn't know where in the editor it should be displayed.

**Comment by HighCommander4** [comment] 2021-12-13 09:36
If I change the checker to pass a valid location to `diag()`, it does show up in clangd as well.

==> I'm inclined to say there's no bug here. (Other than a potential upstream bug about `TranslationUnitDecl` not having a valid location.) The assertion suggests that passing an invalid location to `diag()` is not valid, and the fact that clang-tidy happens to emit the message anyways should not be relied upon by your checker.

**Comment by vbar** [comment] 2021-12-13 09:42
Hmm, so how do I pass a valid location to `diag()`, when all I have is a `TranslationUnitDecl` which does not have a valid location?

**Comment by kadircet** [comment] 2021-12-13 11:56
it's usually important for diagnostics to be attached to a relevant location. You should try and find a certain AST node under the translation unit decl which is relevant for your diagnostic to be attached to and use its location.

if you're emitting a diagnostic which is not related to any location at all for whatever reason, you can make use of a fixed location in the main file (e.g. begining/end). the experience will be somewhat sub-optimal for the user though, as editors usually have limited ways to display diagnostics outside of the visible section of the code.

closing the issue as it is not related to clangd/clang. feel free to reach out to relevant clang-tidy/clang communication channels (which we're part of again) regarding your questions around developing a clang-tidy check. this is not the right medium for such a discussion.

**Closed by kadircet** 2021-12-13 11:56 UTC
