### ISSUE TITLE
clangd crashed while parsing a invalid C++20 header

### ISSUE THREAD

**Issue by qwqllh** [clangd/clangd#1107] opened 2022-04-13 17:31 UTC
I find clangd crashed when I was refactoring my code. I guess that the crash may be caused by the `export namespace`.
clangd crashed while parsing such a simple header file:

```cpp
#pragma once

#include <cmath>
#include <cstddef>
#include <type_traits>

export namespace test {

template <typename T>
concept ArithmeticType = std::is_arithmetic_v<T>;

template <ArithmeticType T>
constexpr T Abs(T value) noexcept {
    return (value >= 0 ? value : -value);
}

}

```

compile_flags.txt:

```
-xc++
-std=c++20
```

I am using visual studio code with clangd plugin. My operating system is macOS Monterey 12.3.1.

clangd version:

```
Homebrew clangd version 13.0.1
Features: mac+xpc
Platform: x86_64-apple-darwin21.4.0
```

Logs:

```
I[01:25:38.712] Homebrew clangd version 13.0.1
I[01:25:38.713] Features: mac+xpc
I[01:25:38.713] PID: 77064
I[01:25:38.713] Working directory: /Users/lilonghao/Desktop/clangd_bug
I[01:25:38.713] argv[0]: /usr/local/opt/llvm/bin/clangd
I[01:25:38.713] argv[1]: -j=1
I[01:25:38.713] argv[2]: -log=verbose
V[01:25:38.713] User config file is /Users/lilonghao/Library/Preferences/clangd/config.yaml
I[01:25:38.713] Starting LSP over stdin/stdout
V[01:25:38.713] <<< {"id":0,"jsonrpc":"2.0","method":"initialize","params":{"capabilities":{"general":{"markdown":{"parser":"marked","version":"1.1.0"},"regularExpressions":{"engine":"ECMAScript","version":"ES2020"},"staleRequestSupport":{"cancel":true,"retryOnContentModified":["textDocument/semanticTokens/full","textDocument/semanticTokens/range","textDocument/semanticTokens/full/delta"]}},"textDocument":{"callHierarchy":{"dynamicRegistration":true},"codeAction":{"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}},"dataSupport":true,"disabledSupport":true,"dynamicRegistration":true,"honorsChangeAnnotations":false,"isPreferredSupport":true,"resolveSupport":{"properties":["edit"]}},"codeLens":{"dynamicRegistration":true},"colorProvider":{"dynamicRegistration":true},"completion":{"completionItem":{"commitCharactersSupport":true,"deprecatedSupport":true,"documentationFormat":["markdown","plaintext"],"insertReplaceSupport":true,"insertTextModeSupport":{"valueSet":[1,2]},"labelDetailsSupport":true,"preselectSupport":true,"resolveSupport":{"properties":["documentation","detail","additionalTextEdits"]},"snippetSupport":true,"tagSupport":{"valueSet":[1]}},"completionItemKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]},"contextSupport":true,"dynamicRegistration":true,"editsNearCursor":true},"declaration":{"dynamicRegistration":true,"linkSupport":true},"definition":{"dynamicRegistration":true,"linkSupport":true},"documentHighlight":{"dynamicRegistration":true},"documentLink":{"dynamicRegistration":true,"tooltipSupport":true},"documentSymbol":{"dynamicRegistration":true,"hierarchicalDocumentSymbolSupport":true,"labelSupport":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]},"tagSupport":{"valueSet":[1]}},"foldingRange":{"dynamicRegistration":true,"lineFoldingOnly":true,"rangeLimit":5000},"formatting":{"dynamicRegistration":true},"hover":{"contentFormat":["markdown","plaintext"],"dynamicRegistration":true},"implementation":{"dynamicRegistration":true,"linkSupport":true},"linkedEditingRange":{"dynamicRegistration":true},"onTypeFormatting":{"dynamicRegistration":true},"publishDiagnostics":{"codeDescriptionSupport":true,"dataSupport":true,"relatedInformation":true,"tagSupport":{"valueSet":[1,2]},"versionSupport":false},"rangeFormatting":{"dynamicRegistration":true},"references":{"dynamicRegistration":true},"rename":{"dynamicRegistration":true,"honorsChangeAnnotations":true,"prepareSupport":true,"prepareSupportDefaultBehavior":1},"selectionRange":{"dynamicRegistration":true},"semanticTokens":{"dynamicRegistration":true,"formats":["relative"],"multilineTokenSupport":false,"overlappingTokenSupport":false,"requests":{"full":{"delta":true},"range":true},"tokenModifiers":["declaration","definition","readonly","static","deprecated","abstract","async","modification","documentation","defaultLibrary"],"tokenTypes":["namespace","type","class","enum","interface","struct","typeParameter","parameter","variable","property","enumMember","event","function","method","macro","keyword","modifier","comment","string","number","regexp","operator"]},"signatureHelp":{"contextSupport":true,"dynamicRegistration":true,"signatureInformation":{"activeParameterSupport":true,"documentationFormat":["markdown","plaintext"],"parameterInformation":{"labelOffsetSupport":true}}},"synchronization":{"didSave":true,"dynamicRegistration":true,"willSave":true,"willSaveWaitUntil":true},"typeDefinition":{"dynamicRegistration":true,"linkSupport":true}},"window":{"showDocument":{"support":true},"showMessage":{"messageActionItem":{"additionalPropertiesSupport":true}},"workDoneProgress":true},"workspace":{"applyEdit":true,"codeLens":{"refreshSupport":true},"configuration":true,"didChangeConfiguration":{"dynamicRegistration":true},"didChangeWatchedFiles":{"dynamicRegistration":true},"executeCommand":{"dynamicRegistration":true},"fileOperations":{"didCreate":true,"didDelete":true,"didRename":true,"dynamicRegistration":true,"willCreate":true,"willDelete":true,"willRename":true},"semanticTokens":{"refreshSupport":true},"symbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]},"tagSupport":{"valueSet":[1]}},"workspaceEdit":{"changeAnnotationSupport":{"groupsOnLabel":true},"documentChanges":true,"failureHandling":"textOnlyTransactional","normalizesLineEndings":true,"resourceOperations":["create","rename","delete"]},"workspaceFolders":true}},"clientInfo":{"name":"Visual Studio Code","version":"1.66.2"},"initializationOptions":{"clangdFileStatus":true,"fallbackFlags":[]},"locale":"zh-cn","processId":77053,"rootPath":"/Users/lilonghao/Desktop/clangd_bug","rootUri":"file:///Users/lilonghao/Desktop/clangd_bug","trace":"off","workspaceFolders":[{"name":"clangd_bug","uri":"file:///Users/lilonghao/Desktop/clangd_bug"}]}}

I[01:25:38.714] <-- initialize(0)
V[01:25:38.714] Invoking /usr/bin/xcrun to find clang installation
V[01:25:38.722] Invoking /usr/bin/xcrun to find clang installation
I[01:25:38.751] --> reply:initialize(0) 37 ms
V[01:25:38.751] >>> {"id":0,"jsonrpc":"2.0","result":{"capabilities":{"astProvider":true,"callHierarchyProvider":true,"codeActionProvider":{"codeActionKinds":["quickfix","refactor","info"]},"compilationDatabase":{"automaticReload":true},"completionProvider":{"allCommitCharacters":[" ","\t","(",")","[","]","{","}","<",">",":",";",",","+","-","/","*","%","^","&","#","?",".","=","\"","'","|"],"resolveProvider":false,"triggerCharacters":[".","<",">",":","\"","/"]},"declarationProvider":true,"definitionProvider":true,"documentFormattingProvider":true,"documentHighlightProvider":true,"documentLinkProvider":{"resolveProvider":false},"documentOnTypeFormattingProvider":{"firstTriggerCharacter":"\n","moreTriggerCharacter":[]},"documentRangeFormattingProvider":true,"documentSymbolProvider":true,"executeCommandProvider":{"commands":["clangd.applyFix","clangd.applyTweak"]},"hoverProvider":true,"implementationProvider":true,"memoryUsageProvider":true,"referencesProvider":true,"renameProvider":{"prepareProvider":true},"selectionRangeProvider":true,"semanticTokensProvider":{"full":{"delta":true},"legend":{"tokenModifiers":["declaration","deprecated","deduced","readonly","static","abstract","dependentName","defaultLibrary","functionScope","classScope","fileScope","globalScope"],"tokenTypes":["variable","variable","parameter","function","method","function","property","variable","class","interface","enum","enumMember","type","type","unknown","namespace","typeParameter","concept","type","macro","comment"]},"range":false},"signatureHelpProvider":{"triggerCharacters":["(",","]},"textDocumentSync":{"change":2,"openClose":true,"save":true},"typeHierarchyProvider":true,"workspaceSymbolProvider":true},"serverInfo":{"name":"clangd","version":"Homebrew clangd version 13.0.1 mac+xpc x86_64-apple-darwin21.4.0"}}}

V[01:25:38.874] <<< {"jsonrpc":"2.0","method":"initialized","params":{}}

I[01:25:38.874] <-- initialized
V[01:25:38.874] <<< {"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"languageId":"cpp","text":"#pragma once\n\n#include <cmath>\n#include <cstddef>\n#include <type_traits>\n\nexport namespace test {\n\ntemplate <typename T>\nconcept ArithmeticType = std::is_arithmetic_v<T>;\n\ntemplate <ArithmeticType T>\nconstexpr T Abs(T value) noexcept {\n    return (value >= 0 ? value : -value);\n}\n\n}\n","uri":"file:///Users/lilonghao/Desktop/clangd_bug/carsh.h","version":1}}}

I[01:25:38.874] <-- textDocument/didOpen
I[01:25:38.875] Loaded compilation database from /Users/lilonghao/Desktop/clangd_bug/compile_flags.txt
V[01:25:38.875] Broadcasting compilation database from /Users/lilonghao/Desktop/clangd_bug
I[01:25:38.875] ASTWorker building file /Users/lilonghao/Desktop/clangd_bug/carsh.h version 1 with command 
[/Users/lilonghao/Desktop/clangd_bug]
/usr/local/Cellar/llvm/13.0.1_1/bin/clang-tool -xc++ -std=c++20 -resource-dir=/usr/local/Cellar/llvm/13.0.1_1/lib/clang/13.0.1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -- /Users/lilonghao/Desktop/clangd_bug/carsh.h
V[01:25:38.877] Driver produced command: cc1 -cc1 -triple x86_64-apple-macosx12.0.0 -Wundef-prefix=TARGET_OS_ -Werror=undef-prefix -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -fsyntax-only -disable-free -disable-llvm-verifier -discard-value-names -main-file-name carsh.h -mrelocation-model pic -pic-level 2 -mframe-pointer=all -fno-rounding-math -munwind-tables -target-sdk-version=12.3 -fcompatibility-qualified-id-block-type-checking -fvisibility-inlines-hidden-static-local-var -target-cpu penryn -tune-cpu generic -debugger-tuning=lldb -target-linker-version 711 -fcoverage-compilation-dir=/Users/lilonghao/Desktop/clangd_bug -resource-dir /usr/local/Cellar/llvm/13.0.1_1/lib/clang/13.0.1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -stdlib=libc++ -internal-isystem /usr/local/Cellar/llvm/13.0.1_1/bin/../include/c++/v1 -internal-isystem /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/local/include -internal-isystem /usr/local/Cellar/llvm/13.0.1_1/lib/clang/13.0.1/include -internal-externc-isystem /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include -std=c++20 -fdeprecated-macro -fdebug-compilation-dir=/Users/lilonghao/Desktop/clangd_bug -ferror-limit 19 -stack-protector 1 -fblocks -fencode-extended-block-signature -fregister-global-dtors-with-atexit -fgnuc-version=4.2.1 -fno-implicit-modules -fcxx-exceptions -fexceptions -fmax-type-align=16 -D__GCC_HAVE_DWARF2_CFI_ASM=1 -x c++ /Users/lilonghao/Desktop/clangd_bug/carsh.h
I[01:25:38.877] --> textDocument/clangd.fileStatus
V[01:25:38.877] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"parsing includes, running Update (1)","uri":"file:///Users/lilonghao/Desktop/clangd_bug/carsh.h"}}

V[01:25:38.877] Building first preamble for /Users/lilonghao/Desktop/clangd_bug/carsh.h version 1
V[01:25:38.927] <<< {"id":1,"jsonrpc":"2.0","method":"textDocument/documentSymbol","params":{"textDocument":{"uri":"file:///Users/lilonghao/Desktop/clangd_bug/carsh.h"}}}

I[01:25:38.928] <-- textDocument/documentSymbol(1)
V[01:25:39.035] indexed preamble AST for /Users/lilonghao/Desktop/clangd_bug/carsh.h version 1:
  symbol slab: 4692 symbols, 1219736 bytes
  ref slab: 0 symbols, 0 refs, 128 bytes
  relations slab: 159 relations, 4376 bytes
V[01:25:39.040] <<< {"id":2,"jsonrpc":"2.0","method":"textDocument/documentLink","params":{"textDocument":{"uri":"file:///Users/lilonghao/Desktop/clangd_bug/carsh.h"}}}

I[01:25:39.040] <-- textDocument/documentLink(2)
V[01:25:39.055] <<< {"jsonrpc":"2.0","method":"$/cancelRequest","params":{"id":1}}

I[01:25:39.055] <-- $/cancelRequest
V[01:25:39.055] <<< {"id":3,"jsonrpc":"2.0","method":"textDocument/documentSymbol","params":{"textDocument":{"uri":"file:///Users/lilonghao/Desktop/clangd_bug/carsh.h"}}}

I[01:25:39.055] <-- textDocument/documentSymbol(3)
V[01:25:39.102] Build dynamic index for header symbols with estimated memory usage of 2976360 bytes
V[01:25:39.104] Built preamble of size 1508304 for file /Users/lilonghao/Desktop/clangd_bug/carsh.h version 1
I[01:25:39.104] --> workspace/semanticTokens/refresh(0)
V[01:25:39.104] >>> {"id":0,"jsonrpc":"2.0","method":"workspace/semanticTokens/refresh","params":null}

I[01:25:39.104] --> textDocument/clangd.fileStatus
V[01:25:39.104] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"parsing includes, running Build AST for (1)","uri":"file:///Users/lilonghao/Desktop/clangd_bug/carsh.h"}}

V[01:25:39.117] <<< {"id":0,"jsonrpc":"2.0","result":null}

I[01:25:39.118] <-- reply(0)
[Error - 1:25:39 AM] Connection to server got closed. Server will not be restarted.
[Error - 1:25:39 AM] Request textDocument/documentSymbol failed.
[object Object]
[Error - 1:25:39 AM] Request textDocument/documentLink failed.
[object Object]
[Error - 1:25:39 AM] Request textDocument/documentSymbol failed.
[object Object]
[Error - 1:25:39 AM] Request textDocument/semanticTokens/full failed.
[object Object]
```

**Comment by HighCommander4** [comment] 2022-04-17 06:16
Is this code valid?

When I try to compile it I get `error: export declaration can only be used within a module interface unit after the module declaration`.

**Comment by qwqllh** [comment] 2022-04-17 06:18
The code is not valid, but I was expecting that clangd could report errors but not crash directly.

**Comment by HighCommander4** [comment] 2022-04-17 06:19
> The code is not valid, but I was expecting that clangd could report errors but not crash directly.

Thanks, just wanted to make sure I was reproducing it correctly. I agree that clangd should not crash even on invalid code.

**Comment by HighCommander4** [comment] 2022-04-17 06:21
I can reproduce the crash with clangd-13, but it seems to be fixed in clangd-14.

==> Upgrading to clangd-14 should resolve the issue. You can get it rom https://github.com/clangd/clangd/releases in case your distribution does not package this version yet.

**Closed by HighCommander4** 2022-04-17 06:21 UTC
