### ISSUE TITLE
textDocument/implementation for functions?

### ISSUE THREAD

**Issue by q3cpma** [clangd/clangd#854] opened 2021-09-05 10:45 UTC
Sorry if this question has already been asked, but I can't manage to find a definitive and up-to-date answer: does clangd implements `textDocument/implementation` for simple functions and not just overrided class methods? Basically, does the last comment in https://github.com/clangd/clangd/issues/789 still stands?
If it is the case, putting something in your FAQ might be useful; or a big table detailing capabilities in detail.

**Logs**
I can give one if wanted.

**System information**

Output of `clangd --version`: clangd version 12.0.1
Editor/LSP plugin: Emacs-28 with eglot
Operating system: Gentoo

**Comment by q3cpma** [comment] 2021-09-05 10:50
Oh, and if the answer is still no: is it on the roadmap or should I consider using a different server for such an essential functionality?

**Comment by sam-mccall** [comment] 2021-09-05 12:30
What do you want the function to do in this case? Just the same as go-to-definition?

(Your username makes me a little nostalgic!)

**Comment by q3cpma** [comment] 2021-09-05 14:35
On Sun, Sep 05, 2021 at 05:30:59AM -0700, Sam McCall wrote:
> What do you want the function to do in this case? Just the same as go-to-definition?
>
Well, indeed, but trying xref-find-definitions gets me the declaration too:

```
[client-request] (id:5) Sun Sep  5 16:30:52 2021:
(:jsonrpc "2.0" :id 5 :method "textDocument/definition" :params
		  		  (:textDocument
					   (:uri "file:///home/user/Programming/clangd%20test/main.c")
					   		    :position
									   (:line 4 :character 2)))
[stderr] I[16:30:52.046] <-- textDocument/definition(5)
[stderr] I[16:30:52.046] --> reply:textDocument/definition(5) 0 ms
[server-reply] (id:5) Sun Sep  5 16:30:52 2021:
(:id 5 :jsonrpc "2.0" :result
	  [(:range
	     (:end
			(:character 9 :line 2)
						:start
							(:character 5 :line 2))
							   :uri "file:///home/user/Programming/clangd%20test/test.h")])
[stderr]
[stderr]
[stderr] nil
[stderr] nil
[stderr] Process EGLOT (clangd test/c-mode) stderr finished
...
```

> (Your username makes me a little nostalgic!)
>
Never too late to enjoy the best computer adrenaline source!

**Comment by HighCommander4** [comment] 2023-10-14 02:24
Just came across this old issue, and based on the last comment, it sounds like the real issue is that `textDocument/definition` is not working to find the definition of a function from its declaration.

This usually indicates an issue with the project configuration, e.g. the file containing the definition not being indexed.

So, @q3cpma, a couple of questions:
 1. Are you still experiencing this issue with `textDocument/definition`? If so, I'd like to invite you to file a separate issue about that and provide additional details (e.g. [clangd logs](https://clangd.llvm.org/troubleshooting#gathering-logs)) to help figure out the issue with your project configuration.
 2. Assuming the `textDocument/definition` issue is sorted out, is it still your opinion that `textDocument/implementation` should also have the same behaviour for plain (non-virtual) functions?

**Comment by q3cpma** [comment] 2023-10-14 08:56
On Sat Oct 14, 2023 at 4:25 AM CEST, Nathan Ridge wrote:
> Just came across this old issue, and based on the last comment, it sounds like the real issue is that `textDocument/definition` is not working to find the definition of a function from its declaration.
>
> This usually indicates an issue with the project configuration, e.g. the file containing the definition not being indexed.
>
> So, @q3cpma, a couple of questions:
>  1. Are you still experiencing this issue with `textDocument/definition`? If so, I'd like to invite you to file a separate issue about that and provide additional details (e.g. [clangd logs](https://clangd.llvm.org/troubleshooting#gathering-logs)) to help figure out the issue with your project configuration.
>  2. Assuming the `textDocument/definition` issue is sorted out, is it still your opinion that `textDocument/implementation` should also have the same behaviour for plain (non-virtual) functions?

No, I think the issue is purely mine, since it works at work where we use CMake (thus have a compilation database). It must not work with raw compile_flags.txt, for some reason.

**Comment by HighCommander4** [comment] 2023-10-14 23:34
> No, I think the issue is purely mine, since it works at work where we use CMake (thus have a compilation database). It must not work with raw compile_flags.txt, for some reason.

Ok, that explains it: clangd does not index the project with `compile_flags.txt`, since it does not have a list of source files to index.

This is mentioned at https://clangd.llvm.org/installation#compile_flagstxt:

> background-indexing will not work, as clangd can’t be sure which of the files are project sources

Note that there are other ways than CMake to generate a `compile_commands.json` file, discussed at https://clangd.llvm.org/installation#compile_commandsjson.

**Comment by HighCommander4** [comment] 2023-10-14 23:35
Anyways, I'm going to close this because textDocument/implementation is behaving as intended.

**Closed** 2023-10-14 23:35 UTC
