### ISSUE TITLE
Autocomplete & info popup for structs, like "MyStruct myVariable = {0, 0, 90};"

### ISSUE THREAD

**Issue by ItsCubeTime** [clangd/clangd#726] opened 2021-03-25 15:26 UTC
When using a function, clangd fills in the available parameters for you to make it easier to tell what the parameters are. Like so:
 https://u.teknik.io/jDttu.mp4 
 
![image](https://user-images.githubusercontent.com/20190653/112498024-6e43c000-8d86-11eb-8a0f-1ef2568f5ac2.png)

And gives you  some info of the parameters also when you are typing:
![image](https://user-images.githubusercontent.com/20190653/112497939-59672c80-8d86-11eb-9f4f-560528661344.png)

 Currently, this is not the case for structs or classes:
https://u.teknik.io/wDfuF.mp4

Would be nice if it gave similar feedback as what functions do.

(screenshots and videos taken from within VS Code with Clangd v0.1.11 from the marketplace)

**Comment by HighCommander4** [comment] 2021-03-25 18:03
Looks like a dupe of #306.

**Comment by ItsCubeTime** [comment] 2021-03-25 18:37
> Looks like a dupe of #306.

Yep, looks like kinda the same suggestion. His video example link is dead tho

**Comment by HighCommander4** [comment] 2021-03-26 04:16
> Yep, looks like kinda the same suggestion. His video example link is dead tho

I copied the link over to #306. Will close this as a dupe.

**Closed by HighCommander4** 2021-03-26 04:16 UTC
Labels: enhancement
