### ISSUE TITLE
Clangd imports C++ header in C file

### ISSUE THREAD

**Issue by dryBoneMarrow** [clangd/clangd#2228] opened 2024-11-22 16:06 UTC
Clangd can auto import the header when autocompleting a file. Sometimes it suggests a C++ header inside a C file (with .c suffix).
![image](https://github.com/user-attachments/assets/e7cebcdd-b637-4516-a158-b259e8e142ae)
*cstdio is proposed instead of stdlib.h*
**System information**

Output of `clangd --version`: 
```
clangd version 18.1.8
Features: linux
Platform: x86_64-pc-linux-gnu
```

Editor/LSP plugin: Helix

Operating system: Arch linux

**Comment by HighCommander4** [comment] 2024-11-22 21:58
Duplicate of #376

**Closed by HighCommander4** 2024-11-22 21:58 UTC
