### ISSUE TITLE
Sources defining "extern" variables have their own header includes marked "not used directly"

### ISSUE THREAD

**Issue by slymas** [clangd/clangd#1554] opened 2023-03-24 10:32 UTC
Basic example:

```
// e.h
extern int i;
```

```
// e.cpp
#include "e.h" // clangd says: Included header e.h is not used directly (fix available)
int i = 1;
```

However, removing that include obviously leave `i` undefined, so it's indeed used and needed there.

**System information**

Output of `clangd --version`:
clangd version 15.0.0 (git://code.qt.io/clang/llvm-project.git 218224bce00c69b6f8a396e681c51256fc6f1b99)
Features: linux
Platform: x86_64-unknown-linux-gnu

Editor/LSP plugin:
Qt Creator 9.0.2

Operating system:
Ubuntu 22.04.2 LTS

**Comment by hokein** [comment] 2023-03-28 08:06
Thanks for the report, I was going to say that this is fixed in the new include-cleaner-lib-based implementation (which will be in next clangd 17 release), but I confirm that it still exits in the new implementation (running `clang-include-cleaner` on the above example can reproduce the issue).

The issue is caused by the fact that we're missing to handle the `VarDecl` in the `WalkAST.cpp`, similar to `FunctionDecl`, the fix is to add a `VisitVarDecl` implementation.

**Closed** 2023-03-29 20:21 UTC
Labels: include-cleaner
