### ISSUE TITLE
Extreme memory usage when opening big header files

### ISSUE THREAD

**Issue by Curve** [clangd/clangd#719] opened 2021-03-09 10:55 UTC
Clangd uses up all of the available memory if you open big header files until eventually the system freezes
Example header file: [miniaudio.h](https://github.com/mackron/miniaudio/blob/master/miniaudio.h)

**Logs**
clangd output:
```
I[11:50:29.051] ASTWorker building file /.../lib/miniaudio/miniaudio.h version 1 with command inferred from /.../InstanceGuard.cpp
[/.../build]
/usr/bin/c++ --driver-mode=g++ -g -c -x c++-header -std=c++11 /.../lib/miniaudio/miniaudio.h -fsyntax-only -resource-dir=/.../clangd/lib/clang/13.0.0
I[11:50:29.052] --> textDocument/clangd.fileStatus
I[11:50:29.095] --> workspace/semanticTokens/refresh(2)
I[11:50:29.095] <-- reply(2)
I[11:50:29.127] <-- textDocument/codeAction(14)
I[11:50:29.127] <-- $/cancelRequest
I[11:50:29.131] <-- textDocument/semanticTokens/full/delta(15)
I[11:50:29.132] --> reply:textDocument/semanticTokens/full/delta(15) 0 ms
I[11:50:29.132] --> textDocument/clangd.fileStatus
I[11:50:29.846] <-- textDocument/codeAction(16)
I[11:50:29.846] <-- $/cancelRequest
```
There is no error output from the extension or clangd

**System information**
Output of `clangd --version`:
```
> clangd --version
clangd version 13.0.0 (https://github.com/llvm/llvm-project 3a11a41795bec548e91621caaa4cc00fc31b2212)
```
Editor/LSP plugin: [vscode-clangd](https://marketplace.visualstudio.com/items?itemName=llvm-vs-code-extensions.vscode-clangd)
Operating system: Arch Linux (Kernel: 5.11.0-126-tkg-pds)

Related issues:
#251 
#115 
#694

**Comment by kadircet** [comment] 2021-03-09 12:56
thanks for the reproducer! it looks like this is caused by clang-format's language guesser for ObjC on extensionless or `.h` files :(

i'll try to see if we can figure out why it is choking on big files (or even better just bypass that all together).

**Comment by Curve** [comment] 2021-05-17 22:42
Is there any progress on this?
This bug makes clangd kind of unusable

**Comment by mackron** [comment] 2021-10-09 00:29
I'm the developer of miniaudio and I've also just hit this issue. In my case the development environment is CodeLite + clangd on Windows. If it helps diagnose the issue at all, I'd be more than happy to answer any questions about miniaudio and how it's structured.

Apart from development of miniaudio being basically impossible via any IDE using clangd, my concern with this particular issue is that the library is designed to be added directly to a project's source tree rather than being included separately, so I wonder if this could have flow on effects that would cause issues for those who want to add miniaudio.h to their projects in their chosen IDE.

> it looks like this is caused by clang-format's language guesser for ObjC on extensionless or .h files

miniaudio.h does indeed have some ObjC code contained within it for some iOS support, in case that's relevant.

**Comment by HighCommander4** [comment] 2022-08-14 19:10
> this is coming from clang-format, filed https://bugs.llvm.org/show_bug.cgi?id=49519 for tracking.

Updated upstream issue link: https://github.com/llvm/llvm-project/issues/48863

**Comment by kadircet** [comment] 2023-01-24 16:57
closing this one as there's not much we can do on the clangd side and this has been reported in https://github.com/llvm/llvm-project/issues/60151 and https://github.com/llvm/llvm-project/issues/48863 already

**Closed by kadircet** 2023-01-24 16:57 UTC
Labels: performance

**Comment by HighCommander4** [comment] 2023-11-01 22:28
> closing this one as there's not much we can do on the clangd side and this has been reported in [llvm/llvm-project#60151](https://github.com/llvm/llvm-project/issues/60151) and [llvm/llvm-project#48863](https://github.com/llvm/llvm-project/issues/48863) already

Maybe we can work around this in clangd?

We already decide to **parse** the file in a certain language mode, based on the compile command and such.

Can we tell libClangFormat to use the same language mode, instead of having it try to guess?

**Comment by kadircet** [comment] 2023-11-02 08:33
> We already decide to parse the file in a certain language mode, based on the compile command and such.

Surely we can do that inside ParsedAST, but that isn't the only place we call `format::getStyle`. We also invoke it on interactions like code completion and formatting, and these don't necessarily have compile flags associated with the file, so we would need to do some plumbing (and also certain changes to the design of those features).

More importantly, clangd has its own heuristics around figuring out file language when parsing (e.g. falling back to `-xobjective-c++-header`). Any discrepancies in the outputs here will now create a different behavior compared to clang-format CLI, which will create more frustration when clangd formats files one way and a projects submission tests formats them another way.

So I am not sure that's the right trade-off here, but maybe I am missing a different solution you had in mind?

**Comment by HighCommander4** [comment] 2023-11-03 05:11
> > We already decide to parse the file in a certain language mode, based on the compile command and such.
> 
> Surely we can do that inside ParsedAST, but that isn't the only place we call `format::getStyle`. We also invoke it on interactions like code completion and formatting, and these don't necessarily have compile flags associated with the file, so we would need to do some plumbing (and also certain changes to the design of those features).

Even aside from the hang that's at issue here, it seems inefficient for a potentially non-trivial "guess language" operation to be called multiple times from code implementing different features over the course of interacting with a file. Maybe some refactoring to be more deliberate about the "guess language" operation and cache its result more aggressively would be beneficial anyways?

> More importantly, clangd has its own heuristics around figuring out file language when parsing (e.g. falling back to `-xobjective-c++-header`). Any discrepancies in the outputs here will now create a different behavior compared to clang-format CLI, which will create more frustration when clangd formats files one way and a projects submission tests formats them another way.

Good point, this seems like a thornier problem.

Just thinking out loud here, but maybe we could have a blocklist of header names for which "guess language" is known to misbehave, and for which a hardcoded language is used instead?

**Comment by HighCommander4** [comment] 2024-03-11 08:17
For folks following this issue, this should hopefully be fixed now in https://github.com/llvm/llvm-project/pull/84133.

**Comment by aliceisjustplaying** [comment] 2024-08-11 16:10
@HighCommander4 Using [Cursor](https://www.cursor.com/) the AI-enabled VSCode fork, the [VSCode clangd extension](https://marketplace.visualstudio.com/items?itemName=llvm-vs-code-extensions.vscode-clangd) and either 18.1.8 or 19.0.0-devel (whatever is in macports), simply opening `miniaudio.h` (and nothing else!) makes clangd use up infinite memory on my M1 Pro MBP (at one point it was at 160 GB).

**Comment by HighCommander4** [comment] 2024-08-11 20:26
> and either 18.1.8 or 19.0.0-devel (whatever is in macports)

18.1.8 does not contain the fix and is expected to be affected.

Regarding 19.0.0-devel, I'm not sure what commit the macports build is based on, or how to check. Perhaps it doesn't contain the fix yet; the 19 release should once it's out.

**Comment by aliceisjustplaying** [comment] 2024-08-11 23:30
Oh, my bad. i checked the timestamps of 18.1.8 and assumed that since that version is months after the merge of the PR, it'd have it.

re: devel turns out that version is from March 8th which definitely predates this patch.

I'll check out one of the weekly snapshots.

**Comment by HighCommander4** [comment] 2024-08-12 17:14
> i checked the timestamps of 18.1.8 and assumed that since that version is months after the merge of the PR, it'd have it.

In fairness, I think this bug would have qualified as sufficiently severe that it would be eligible for a backport to 18.x; apologies for not having thought of that at the time.

**Comment by aliceisjustplaying** [comment] 2024-08-12 17:16
No worries, for now I downloaded the latest weekly snapshot and that seems to work well.
