### ISSUE TITLE
Make *.ipp or *.tcc files eligible for header<->implementation file switching

### ISSUE THREAD

**Issue by MartyMcFlyInTheSky** [clangd/clangd#1898] opened 2024-01-05 17:03 UTC
Not sure if this classifies as a bug but it's certainly an issue.

Usual practice that I saw in multiple codebases (libstdc++ included) is to have a header file and a template implementation file. The later is usually denoted by the *.tcc or *.ipp file extension and included directly _after_ the declarations in the original header. The problem arises when I try to switch between header and implementation using Alt + O shortkey: It just doesn't work. clangd doesn't seem to recognise the implementation file. I understand that a template implementation file certainly "looks" like a header, but using assuming that *.ipp or *.tcc files classify as implementation files, the switching could be feasible, no?

**Comment by HighCommander4** [comment] 2024-01-06 08:34
Duplicate of #1797. Please feel free to weigh in on the discussion there.

**Closed by HighCommander4** 2024-01-06 08:34 UTC
