### ISSUE TITLE
Code completion is not working properly in the template class

### ISSUE THREAD

**Issue by lh123** [clangd/clangd#432] opened 2020-06-16 08:04 UTC
**System information**
Editor/LSP plugin: VSCode
Operating system: Win10

```c++
#include <memory>

template <typename T>
struct Test {
  struct Inner {
    void test();
  };

  void test(){
    base-> // Code completion does not list the "test" function of the Inner class.
  }

  std::unique_ptr<Inner> base;
};

```

**Comment by 1m188** [comment] 2020-08-07 10:18
yes ,and i also got a similar problem which also in vscode in win10 with the code like this:
```cpp
template <typename T>
class C
{
    private:
        struct N
        {
            T dat;
            int x;
        };
        N n;
        ...

    public:
        C()
        {
            n.  // no completion about struct N
        }
};
```
and i don't know it caused by the clangd-vscode's problem or the clangd's problem, may be it's also can be the vscode's problem?(i saw the c/c++ plugin developed by Microsoft also can not complete in that place)

**Comment by kadircet** [comment] 2020-08-07 15:48
@1m188 the issue you are facing should be fixed at head (which was a windows only problem).

**Comment by HighCommander4** [comment] 2024-12-30 03:12
This will be fixed by https://github.com/llvm/llvm-project/pull/121315.

**Comment by HighCommander4** [comment] 2024-12-30 03:12
Duplicate of #810

**Closed by HighCommander4** 2024-12-30 03:12 UTC
