### ISSUE TITLE
macOS 10.15 Catalina: error in finding header

### ISSUE THREAD

**Issue by Ye-Chenhao** [clangd/clangd#178] opened 2019-10-09 02:06 UTC
OS: macOS 10.15 Catalina
clangd: version 9.0.0 (tags/RELEASE_900/final); installed by `brew install llvm`; used in VS Code with vscode-clangd.
Problem: After updating to macOS 10.15 Catalina, clangd keeps reporting errors in finding headers.

<img width="616" alt="Screen Shot 2019-10-08 at 9 01 22 PM" src="https://user-images.githubusercontent.com/35568315/66446097-ca8a1700-ea0e-11e9-962e-3f1354ff9402.png">

After searching, I found a discussion on [StackOverflow](https://stackoverflow.com/questions/58278260/cant-compile-a-c-program-on-a-mac-after-upgrading-to-catalina-10-15/58278392#58278392): It seems Apple stops supporting putting headers under `/usr/include`, which results in the issue.

I wonder whether there any way to keep using clangd in macOS 10.15.

**Comment by badfilms** [comment] 2019-10-10 02:36
I am also struggling with this issue. `clangd` is relying on `/usr/include`, and the absence of it due to Apple deprecating the directory for all future releases, starting with Catalina, means that there is no package to install said headers going forward.

It would be great to be able to tell `clangd` to look for headers in `../include`, for example,  rather than `/usr/include`.

**Comment by badfilms** [comment] 2019-10-10 04:15
With `/usr/include`, no configuration was required to use `clangd` on simple projects, but in the absence of the directory, `compile_commands.json` seems to now be a firm requirement.

For simple projects, you can get away with a `compile_commands.json` configuration similar to the following located in the same directory as your target file.

    [
      {
        "directory": "./",
        "command": "/Library/Developer/CommandLineTools/usr/bin/c++  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk",
        "file": "/path/to/file.cc"
      }
    ]

However, to make life easier, you can generate a `compile_commands.json` via [CMake][1] or a similar build tool. 

Using the provided example in the linked tutorial, we can create a basic `CMakeLists.txt` file with the following:

    cmake_minimum_required (VERSION 2.6)
    project (Tutorial)
    add_executable(Tutorial tutorial.cxx)

then generate a `compile_commands.json` file via 

    cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1

Obviously, this solution is incredibly verbose to simply use `clangd` for simple projects, so I hope that the 0-configuration approach can return in the absence of `/usr/include`, but at the moment I don't have that solution.

  [1]: https://cmake.org/cmake-tutorial/

**Comment by arthurkiller** [comment] 2019-11-19 07:11
+1 same

**Comment by arthurkiller** [comment] 2019-11-19 07:13
I run `clangd` with options like this. 

> --query-driver=/usr/local/opt/llvm/lib,/usr/local/opt/llvm/include,/usr/local/include,/usr/local/lib,/usr/local/Cellar/llvm/9.0.0/lib,/usr/local/Cellar/llvm/9.0.0/include --all-scopes-completion --background-index -j=4

But did not work.

**Comment by sam-mccall** [comment] 2019-11-28 13:19
-query-driver should be pointed at clang (`which clang`)

We should find a way to make this "just work".
Does the following work? (We should be able to automate it):
 - export SDKROOT="$(xcrun --sdk macosx --show-sdk-path)"
 - run your editor (which spawns clangd) from that terminal

**Comment by arthurkiller** [comment] 2019-11-28 13:31
did not work at all

which clang

> let g:ale_cpp_clangd_options = '--query-driver=/usr/local/opt/llvm/include --all-scopes-completion --background-index -j=4'

> [Error] [clangd] undeclared_var_use: Use of undeclared identifier 'std'

llvm installed with brew

Have an awesome day

Arthur Lee
Email : arthur-lee@qq.com

**Comment by arthurkiller** [comment] 2019-11-28 13:33
@sam-mccall 

did not work for me

```
arthur@ArthursMacBookPro:~/g/s/i/b/d/r/p/writer:cts-expand$ which clang
/usr/local/opt/llvm/bin/clang
arthur@ArthursMacBookPro:~/g/s/i/b/d/r/p/writer:cts-expand$ which clangd
/usr/local/opt/llvm/bin/clangd
```

> let g:ale_cpp_clangd_options = '--query-driver=/usr/local/opt/llvm/include --all-scopes-completion --background-index -j=4'
> [Error] [clangd] undeclared_var_use: Use of undeclared identifier 'std'

llvm installed with brew at OSX 10.15

**Comment by kadircet** [comment] 2019-11-28 13:54
query-driver is not directly related to what you are trying to achieve:
- first of all as @sam-mccall pointed-out it should be set to path of `clang`, something like `--query-driver='/usr/local/opt/llvm/bin/*'` in your case.
- even if you did that, it won't be triggered unless you have a `compile_commands.json` mentioning `/usr/local/opt/llvm/bin/clang` as the compiler.

could you try testing with a compile_commands.json, as mentioned above, if your build system supports it?

**Comment by arthurkiller** [comment] 2019-11-28 14:47
> query-driver is not directly related to what you are trying to achieve:
> 
> * first of all as @sam-mccall pointed-out it should be set to path of `clang`, something like `--query-driver='/usr/local/opt/llvm/bin/*'` in your case.
> * even if you did that, it won't be triggered unless you have a `compile_commands.json` mentioning `/usr/local/opt/llvm/bin/clang` as the compiler.
> 
> could you try testing with a compile_commands.json, as mentioned above, if your build system supports it?

I DO have a `compile_commands.json` under my repo generate by `bear`

```
arthur@ArthursMacBookPro:~/g/s/i/b/d/river:cts-expand$ head -n 30 compile_commands.json
[

    {
        "arguments": [
            "g++",
            "-c",
            "-O3",
            "-std=c++11",
            "-g",
            "-pipe",
            "-fPIC",
            "-W",
            "-Wall",
            "-DVERSION=\"1.2.4.1\"",
            "-I/Users/arthur/golang/src/icode.baidu.com/baidu/dba/river/include",
            "-L/Users/arthur/golang/src/icode.baidu.com/baidu/dba/river/lib",
            "-L/usr/local/opt/llvm/lib",
            "-I/usr/local/opt/llvm/include",
            "-I.",
            "-I./include",
            "-I./include/mysql",
            "-I./include/sqlparser",
            "-I./plugins/reader/rdb_handler",
            "-I./deps/hiredis",
            "-I./deps/lua/src/",
            "-I./plugins/reader/",
            "-o",
            "lock_set.o",
            "lock_set.cpp"
        ],
```

is that enouth for clangd?

**Comment by sam-mccall** [comment] 2019-11-28 19:38
I've been digging into this.
It seems the issue is that apple clang has logic/paths compiled in, so the
driver can find the stdlib in its nonstandard location and pass the right
isysroot to cc1.
Thus you can build fine without passing -isysroot, and your
compile_commands.json won't specify it explicitly.

However this isn't in open source clang/clangd in the usual build config,
so the corresponding detection doesn't happen.
I gather the simplest thing to do is to invoke xcrun to get the SDK path,
then setenv SDKROOT accordingly (that variable should affect the driver as
if compiled in). Only problem is on my first attempt it didn't work, so I'm
going to stare at the code some more and then borrow a mac again.

Workaround for now would be to add -isysroot=/Library/Developer/
CommandLineTools/SDKs/MacOSX.sdk/usr/include or so to your compile
commands, or symlink /use/include to that dir if you're feeling
adventurous...

**Comment by arthurkiller** [comment] 2019-11-29 04:38
@sam-mccall thx for your reply, I will keep an eye on this issue.

**Comment by kadircet** [comment] 2019-11-29 09:18
> is that enouth for clangd?

instead of `g++` it should mention the full path of `clang`, which I believe is `/usr/local/opt/llvm/bin/clang` in your case.

btw, it will only help if you can compile c++ files using `/usr/local/opt/llvm/bin/clang` (without explicitly mentioning `isysroot` or any other include path altering commands)

**Comment by sam-mccall** [comment] 2019-11-29 16:01
So a few things I've learned about Mac clang:
 - the SDKROOT->sysroot seems like a bit of a red herring, because (at least on my machine), `xcrun --show-sdk-path` is something like `/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk`, while the standard library is in `/Library/Developer/CommandLineTools/usr/include/c++/v1`. So setting SDKROOT results in an -isysroot path that doesn't work, the standard library is elsewhere.
 - the way that apple clang finds the standard library in practice is relative to `argv[0]`. Apparently it used to do it relative to `-resource-dir` (and still will in some scenarios!). From a tool perspective, relative to `argv[0]` is worse than absolute or based on sysroot (as is used on other platforms) but better than resource-dir at least (which we *must* override to provide the builtin headers corresponding to the clangd version). And much of this happens in cc1 rather than the driver, which is totally bogus.
 - `which clang` won't give you the correct argv0, it'll provide `/usr/bin/clang` instead. That's not a symlink, it's a real binary that appoars to invoke `xcrun`. However `xcrun --find clang` will print the correct argv0 that (I think) will be interpreted correctly by the driver/cc1.

All of which is to say that I think the closest path to a fix is to replace `clang` with `$(xcrun -f clang)` both in the fallback commands and when no path to clang is specified in compile_commands.json.
On other platforms we should probably attempt to replace with `llvm::sys::findProgramByName()` so we're not completely out of sync.

**Comment by sam-mccall** [comment] 2019-11-29 16:03
(And maybe we should ALSO be setting SDKROOT, so that the Mac system SDKs are available. But we could also require users to do that)

**Comment by sam-mccall** [comment] 2019-11-29 18:39
https://reviews.llvm.org/D70863 is an attempt at a fix here, but untested yet (only verified it doesn't break linux)

**Closed** 2019-12-02 15:18 UTC

**Comment by zstreeter** [comment] 2021-02-21 00:51
I'm having similar issues here.  I'v created a compile_commands.json file but numerous things are not recognized by clangd.  For example, it complains about #include <complex> as 'complex' file not found. 

My SDKROOT is the default "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk" and I see that in /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include there is a complex.h and my environment does recognize this file, so I can use the C99 macros etc.  So my issues seem to be in line with this discussion.

Is there any suggestions nowadays to remedy this?  I will try to tack on more paths to the SDKROOT environment variable (I think this is legal) to hopefully fix it.

Thank you!

**Comment by sam-mccall** [comment] 2021-02-23 19:59
@zstreeter which clangd version are you using? That sounds like it should work.

**Comment by zstreeter** [comment] 2021-02-23 20:04
@sam-mccall I used @kadircet comment above and added the same c++ compiler that's in my compile_commands.json as my query driver with the full path and everything worked!

Hopefully my comment helps other Mac users.  Appreciate the thread!
