### ISSUE TITLE
ClangD shows `clang-tidy` messages from inside of a macro provided by a system header at the macro use site

### ISSUE THREAD

**Issue by chandlerc** [clangd/clangd#1448] opened 2022-12-31 02:02 UTC
When using the `clang-tidy` check `modernize-use-trailing-return-type` and GoogleTest, I get errors that I would expect to be suppressed due to originating in macros from system headers:

```
// The next line (with `TEST` underscored) triggers the clang-tidy check.
TEST(SomeTest, SomeMethod) {
  // ...
}
```

The fact that the macro expands to a non-trailing-return-type declaration shouldn't be reported here as it is in a macro expansion originating in a system header.

The most confusing thing is that running `clang-tidy` directly *doesn't* show this error. So it is something specific about `clangd` that leads to this.

**Logs**

[clangd-log-snippet.txt](https://github.com/clangd/clangd/files/10326712/clangd-log-snippet.txt)

**System information**

Output of `clangd --version`:
```
Homebrew clangd version 15.0.6
Features: linux
Platform: x86_64-unknown-linux-gnu
```

Editor/LSP plugin:
VSCode + ClangD

Operating system:
Mac, but with SSH-plugin of VSCode to a Linux server where ClangD is running.

**Comment by HighCommander4** [comment] 2022-12-31 02:23
Could you run the "expand macro" code action on the affected invocation, share the expansion, and (assuming you get the diagnostic in the expansion too) indicate which line of the expansion it occurs on?

I ask because when I expand this macro in a simple test file, the only function declarations/definitions in the expansion have `void` return type, and `modernize-use-trailing-return-type` does not warn on those (i.e. I haven't been able to reproduce the diagnostic you're seeing yet).

**Comment by chandlerc** [comment] 2023-01-01 02:45
For example:

```
TEST(IndirectValueTest, ConstAccess) {
  const IndirectValue<int> v = 42;
  EXPECT_EQ(*v, 42);
  EXPECT_EQ(v.GetPointer(), &*v);
}
```

In the code here:
https://github.com/carbon-language/carbon-lang/blob/trunk/common/indirect_value_test.cpp#L14,L18

Exhibits this on line 14.

And when I expand the macro:
```
static_assert(sizeof("IndirectValueTest") > 1,
              "test_suite_name must not be empty");
static_assert(sizeof("ConstAccess") > 1, "test_name must not be empty");
class IndirectValueTest_ConstAccess_Test : public ::testing ::Test {
 public:
  IndirectValueTest_ConstAccess_Test() = default;
  ~IndirectValueTest_ConstAccess_Test() override = default;
  IndirectValueTest_ConstAccess_Test(
      const IndirectValueTest_ConstAccess_Test&) = delete;
  IndirectValueTest_ConstAccess_Test& operator=(
      const IndirectValueTest_ConstAccess_Test&) = delete;
  IndirectValueTest_ConstAccess_Test(
      IndirectValueTest_ConstAccess_Test&&) noexcept = delete;
  IndirectValueTest_ConstAccess_Test& operator=(
      IndirectValueTest_ConstAccess_Test&&) noexcept = delete;

 private:
  void TestBody() override;
  static ::testing ::TestInfo* const test_info_ __attribute__((unused));
};
::testing ::TestInfo* const IndirectValueTest_ConstAccess_Test ::test_info_ =
    ::testing ::internal ::MakeAndRegisterTestInfo(
        "IndirectValueTest", "ConstAccess", nullptr, nullptr,
        ::testing ::internal ::CodeLocation(
            "/usr/local/google/home/chandlerc/src/carbon/carbon-lang/common/"
            "indirect_value_test.cpp",
            14),
        (::testing ::internal ::GetTestTypeId()),
        ::testing ::internal ::SuiteApiResolver<::testing ::Test>::
            GetSetUpCaseOrSuite("/usr/local/google/home/chandlerc/src/carbon/"
                                "carbon-lang/common/indirect_value_test.cpp",
                                14),
        ::testing ::internal ::SuiteApiResolver<::testing ::Test>::
            GetTearDownCaseOrSuite(
                "/usr/local/google/home/chandlerc/src/carbon/carbon-lang/"
                "common/indirect_value_test.cpp",
                14),
        new ::testing ::internal ::TestFactoryImpl<
            IndirectValueTest_ConstAccess_Test>);
void IndirectValueTest_ConstAccess_Test ::TestBody() {
  const IndirectValue<int> v = 42;
  EXPECT_EQ(*v, 42);
  EXPECT_EQ(v.GetPointer(), &*v);
}
```

The clang-tidy check fires on these two methods:
```
  IndirectValueTest_ConstAccess_Test& operator=(
      const IndirectValueTest_ConstAccess_Test&) = delete;
```
```
  IndirectValueTest_ConstAccess_Test& operator=(
      IndirectValueTest_ConstAccess_Test&&) noexcept = delete;
```

Weirdly, there are other enabled clang-tidy checks that fire on this code, but only the one shows up in vscode on the original `TEST` macro.

**Comment by HighCommander4** [comment] 2023-01-02 09:28
Ok, it seems the reason I couldn't reproduce the error is that I was using an older version of `gtest` where the return type of the generated class's assignment operator was `void`.

Upgrading to trunk `gtest`, I do see the same diagnostic as you.

However, I see the same error with a command-line `clang-tidy` invocation as well!

Looking at the [relevant part](https://github.com/google/googletest/blame/71140c3ca7a87bb1b5b9c9f1500fea8858cce344/googletest/include/gtest/internal/gtest-internal.h#L1543-L1550) of the gtest source, they have `/* NOLINT */` comments after the assignment operator declarations, but they're not effective because the declaration is spread out over multiple lines, and the `/* NOLINT */` comment is on the last line but the diagnostic is on the first line.

Moving the `/* NOLINT */` comment to the first line of the declaration in the gtest source successfully suppresses the diagnostic for me with both `clang-tidy` and `clangd`.

As for why you don't get the diagnostic with a command-line `clang-tidy` invocation, I don't have an explanation for that. (But note, I haven't set up the carbon codebase locally, just a minimal workspace that includes the gtest headers.)

**Comment by HighCommander4** [comment] 2023-01-02 09:50
> Looking at the [relevant part](https://github.com/google/googletest/blame/71140c3ca7a87bb1b5b9c9f1500fea8858cce344/googletest/include/gtest/internal/gtest-internal.h#L1543-L1550) of the gtest source, they have `/* NOLINT */` comments after the assignment operator declarations, but they're not effective because the declaration is spread out over multiple lines, and the `/* NOLINT */` comment is on the last line but the diagnostic is on the first line.
> 
> Moving the `/* NOLINT */` comment to the first line of the declaration in the gtest source successfully suppresses the diagnostic for me with both `clang-tidy` and `clangd`.

Filed https://github.com/google/googletest/issues/4110 for this.

**Comment by HighCommander4** [comment] 2023-01-02 09:54
> Filed [google/googletest#4110](https://github.com/google/googletest/issues/4110) for this.

I wrote a [patch](https://github.com/google/googletest/pull/4111) to fix it, too, but that seems to require a Google CLA, which in turn requires a Google account. Sigh.

**Comment by HighCommander4** [comment] 2023-01-09 22:34
> Filed [google/googletest#4110](https://github.com/google/googletest/issues/4110) for this.

In any case, this was closed as wontfix with the comment "This is not a style we're willing to adopt, nor do we believe we it should require NOLINT annotation." :shrug:

@chandlerc I don't think there's anything further to do here, unless you'd like to delve further into why clang-tidy **didn't** produce the diagnostic for you (since it does for me), which would require some additional details (e.g. your clang-tidy version, relevant config files, etc.)

**Comment by chandlerc** [comment] 2023-01-10 10:29
I'm sympathetic to the desire to not have to mark things in this way.

I think the thing to do would be to disable this clang-tidy check from within macros, or at least within macros defined within a system header. Should I move that to a separate issue?

**Comment by sam-mccall** [comment] 2023-01-10 12:05
Disabling within macros: there's no way to make everyone happy here, diverging from clang-tidy's position here seems like a bad idea.

Disabling within system macros: Yes, I think we should do this. clang-tidy has a flag for this that defaults to off, but it's implemented in the diagnostic consumer which we don't use in clangd.

I think this bug is fine, the title reflects the issue well in the end.

**Comment by sam-mccall** [comment] 2023-01-11 14:47
reviews.llvm.org/D141495

**Closed** 2023-01-11 15:11 UTC

**Comment by chandlerc** [comment] 2023-01-11 18:49
From that review, it may also explain why my clang-tidy runs weren't showing these -- I suspect it is successfully mapping the headers to system headers, and may not be for the reduced test you used @HighCommander4 -- anyways, super delighted to see a nice solution that aligns well across the tools here! Thanks so much!
