### ISSUE TITLE
Clangd can`t index any file [windows + clang-cl]

### ISSUE THREAD

**Issue by ndiogen** [clangd/clangd#632] opened 2020-12-26 13:47 UTC
Hi! I am trying to get clangd work with clang-cl frontend. But I am getting error - unable to handle compilation, expected exactly one compiler job. Seems that some flag prevents clangd to index several compile targets for one instance in compile_commands.json.
I`ve tried neovim and vscode, and getting same result.. Seems that problem in compile_commands.json, that can`t be processed by clangd directly. 
compile_commands.json has been generated by cmake 3.19.2. Using Ninja build system - 1.10.0.
What can I do to workaround or solve this problem?

PS. Thank you very much for support and your amazing job!

**Logs**

`{
  "directory": "D:/Projects/ML/mindlullaby/build",
  "command": "D:\\LLVM\\bin\\clang-cl.exe  /nologo -TP -D_SILENCE_CXX17_ITERATOR_BASE_CLASS_DEPRECATION_WARNING -I..\\emergent_vm\\inc -I..\\thirdparty\\win_clang-Debug\\llvm\\include /DWIN32 /D_WINDOWS /W3 /GR /EHsc /MDd /Zi /Ob0 /Od /RTC1 -std:c++17  /FdTARGET_COMPILE_PDB -c -- D:\\Projects\\ML\\mindlullaby\\emergent_vm\\src\\evml.cpp",
  "file": "D:/Projects/ML/mindlullaby/emergent_vm/src/evml.cpp"
},`

[lsp.log](https://github.com/clangd/clangd/files/5743140/lsp.log)

**System information**
Output of `clangd --version`: clangd version 12.0.0 (https://github.com/llvm/llvm-project 655360096f27f25a0e2f71729c1c879f1fd8d8a2)
Editor/LSP plugin: Neovim and VSCode
Operating system: Windows 10

EDIT:
After some investigation, it seems that -- (double dash) is wrongly parsed by clangd. Clangd adds several parameters after -- (like -fsyntax-only and -resource-dir ) in the very end of command line (after -- ). So clang-cl driver produces three build commands, that can`t be processed by clangd futher.

**Comment by kadircet** [comment] 2021-01-05 16:59
Your diagnosis is correct clangd and most of the other clang-based tools use a similar infrastructure for modifying the command line flags. Unfortunately none of these account for "--", I wonder how we've managed to get away with this so far, but also I haven't seen cmake putting "--" in the flags before.

The fix is trivial though it requires some yak-shaving, so it would be great to know if there's anything custom with your compile commands generation without diving into it deeply. Can you share the exact steps you took for generating it?

**Comment by ndiogen** [comment] 2021-01-11 22:08
I am using ninja and clang-cl. So its enough to create some minimal cmake file, and generate project with such command:
`cmake -GNinja -DCMAKE_CXX_COMPILER=clang-cl -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..`

cmake version 3.19.2

**Comment by ringoz** [comment] 2021-03-23 17:01
nothing custom here, also having this issue on Windows.
can't update to cmake v3.19.x, have to use cmake 3.18.5

**Comment by kadircet** [comment] 2021-03-23 17:05
There's https://reviews.llvm.org/D98824 pending to fix some parts of this issue. I also have a follow-up ready but waiting for this base to be landed first.

**Closed** 2021-06-17 07:25 UTC

**Comment by ringoz** [comment] 2021-07-08 13:27
tried clangd version 13.0.0 (https://github.com/llvm/llvm-project.git 026bb84bcd42b875d77b769eb5ee4c19fc2a9719),
the issue is not fixed.

**Comment by kadircet** [comment] 2021-07-09 16:48
please provide logs @ringoz
