### ISSUE TITLE
Const generic parameters do not get the readonly token modifier

### ISSUE THREAD

**Issue by hakonrk** [clangd/clangd#1222] opened 2022-07-21 22:28 UTC
I am trying to get VSCode to highlight all const objects different from non-const objects. I have successfully set this up in all cases except one: Generic function parameters, i.e. template parameters or parameters defined with auto. Example:

```c++
template <typename T> auto foo(const T template_type, const auto auto_type, const int explicit_type)
{
    return template_type + auto_type + explicit_type;
}
```

With code like this, every occurrence of `template_type` and `auto_type` is missing the `readonly` semantic modifier, while it is present in every occurrence of `explicit_type`. Verified using VSCode's `editor.action.inspectTMScopes` command. I don't know if this is a bug in clangd itself or the VSCode extension.

**Logs**
[clangd.log](https://github.com/clangd/vscode-clangd/files/9163120/clangd.log)

**System information**
Clangd version: 14.0.4 (mingw-w64-x86_64-clang-tools-extra 14.0.4-3)
clangd extension version: 0.1.21
Operating system: Windows 11 (10.0.22000.795)

**Comment by HighCommander4** [comment] 2022-07-21 22:33
Thanks for filing.

> I don't know if this is a bug in clangd itself or the VSCode extension.

The relevant logic is in clangd, so I transferred the issue.

**Comment by tom-anders** [comment] 2022-10-07 09:29
Seems like this is caused by the `T->isDependentType()` condition [here](https://searchfox.org/llvm/source/clang-tools-extra/clangd/SemanticHighlighting.cpp#167). Removing it fixes this issue with all other tests still passing.

According to `git blame`, @sam-mccall can maybe shed some light on this...? I assume that the reasoning is that `T` could be instantiated in such a way that the read-only modifier would not be appropriate, but I can't think of a good example.

**Comment by HighCommander4** [comment] 2022-10-12 08:09
@tom-anders agreed, the dependent type check seems unnecessary; `T` might instantiate to something const or something mutable, but `T const` will always be const.

**Comment by sam-mccall** [comment] 2022-10-12 11:35
Removing this check LGTM

The only reasons I can think of are:
 - didn't want to think about this case yet (but we do now)
 - calling code that might crash on dependent types (I just checked, we don't)
 - don't want to offer it inconsistently (but I agree it's better to provide this when we can)

**Comment by sam-mccall** [comment] 2022-10-12 11:38
(obviously there are going to be a bunch of cases in dependent code where a human could determine a type is const but these simple checks won't, e.g. `auto &x = *vec.cbegin()`. I don't think we should spend any effort chasing those).

**Comment by tom-anders** [comment] 2022-10-12 11:53
> (obviously there are going to be a bunch of cases in dependent code where a human could determine a type is const but these simple checks won't, e.g. `auto &x = *vec.cbegin()`. I don't think we should spend any effort chasing those).

I just checked, this example actually works already :)

**Comment by sam-mccall** [comment] 2022-10-12 12:03
Wow, in a dependent context? I thought `u` would be a completely unknown `DependentyTy` here for sure...

```
#include <vector>
template<typename T> void foo() {
  std::vector<T> bar;
  auto &u = *bar.cbegin();
}
```

**Comment by HighCommander4** [comment] 2022-10-13 18:22
Thanks for the fix!

**Closed by HighCommander4** 2022-10-13 18:22 UTC
Labels: bug
