### ISSUE TITLE
Base highlighting and code navigation on all parsed files

### ISSUE THREAD

**Issue by intractabilis** [clangd/clangd#402] opened 2020-05-26 04:15 UTC
I am working in VS Code with clangd 10.0.1, VS Code extension version 0.1.5.

Let's say I have `main.cpp` with (for `Eigen` library see http://eigen.tuxfamily.org/index.php?title=Main_Page)

```
#include <Eigen/Dense>
using namespace Eigen;
auto a = Array<double, Dynamic, Dynamic>{10, 10};
```

I would assume `clangd` now should know all about `Array`, including all its ancestors, because the code above perfectly compiles. However, if I navigate to `Array` definition:
```
template<typename _Scalar, int _Rows, int _Cols, int _Options, int _MaxRows, int _MaxCols>
class Array
  : public PlainObjectBase<Array<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols> >
```

`clangd` complains `No template named 'PlainObjectBase'`, which doesn't make sense for me. You just compiled `main.cpp`, there is certainly information about `PlainObjectBase` there.

**Comment by kadircet** [comment] 2020-05-26 04:44
it is because `eigen3/Eigen/src/Core/Array.h` is not self contained. i.e it doesn't contain any includes for `PlainObjectBase`.

we are able to compile that in main.cpp because `Eigen/Dense` includes all those headers in correct order.

closing as this is a duplicate of https://github.com/clangd/clangd/issues/45

**Closed by kadircet** 2020-05-26 04:44 UTC
Labels: enhancement
