### ISSUE TITLE
Clangd crash when trying to index the project.

### ISSUE THREAD

**Issue by AA1999** [clangd/clangd#1514] opened 2023-02-22 13:32 UTC
Please describe the problem.

Clangd keeps crashing when trying to index the project. I've tried removing the `.cache` folder and reloading the project. Result is still the same.

**Logs**

Please attach the clangd stderr log if you can. (Usually available from the editor)
If possible, run with `--log=verbose` - note that the logs will include the contents of open files!
If this is a crash, try to put `llvm-symbolizer` on your PATH per the troubleshooting instructions.
[clangd.log](https://github.com/clangd/clangd/files/10804320/clangd.log)

**System information**

Output of `clangd --version`: 
```zsh
clangd version 17.0.0 (https://github.com/llvm/llvm-project.git 2a06757a200cc8dd4c3aeca98509d50d75bb4a27)
Features: linux+debug
Platform: x86_64-unknown-linux-gnu
```

Editor/LSP plugin: Clangd for vscode

Operating system: Arch-linux 64-bit

**Comment by HighCommander4** [comment] 2023-02-23 06:47
From the stack trace, the crash is inside the implementation of the `bugprone-unchecked-optional-access` clang-tidy check, so as a workaround, so as a workaround, you can disable the check by adding the following to a `.clangd` config file in your project root:

```yaml
Diagnostics:
  ClangTidy:
    Remove: bugprone-unchecked-optional-access
```

**Comment by i-ky** [comment] 2023-02-23 09:36
Would be nice to try reproducing the crash with clang-tidy alone and to file this issue [upstream](https://github.com/llvm/llvm-project), ideally with a minimal code example.

**Comment by AA1999** [comment] 2023-02-23 21:24
how would I trigger a `bugprone-unchedked-optional-access`?

**Comment by HighCommander4** [comment] 2023-02-24 01:24
> how would I trigger a `bugprone-unchedked-optional-access`?

Create a `.clang-tidy` file containing

```yaml
Checks: bugprone-unchedked-optional-access
```

and then run `clang-tidy <file>` where `<file>` is the file that was being indexed during the crash (may need to run the indexer with `-j1` to determine this, see https://clangd.llvm.org/troubleshooting#crashes-in-background-indexing).

**Comment by AA1999** [comment] 2023-02-25 22:35
Here's the file structure in that folder (that I made the test env):

```
╭─[arshia-pc] as arshia in ~/test-env                                                                                                                  02:04:34
╰──➤ ls -a                                                   
.  ..  .clang-tidy  test.cpp
```

When running `clang-ridy` test.cpp:

```cpp

╭─[arshia-pc] as arshia in ~/test-env                                                                                                                  02:05:15
╰──➤ clang-tidy test.cpp              
Error while trying to load a compilation database:
Could not auto-detect compilation database for file "test.cpp"
No compilation database found in /home/arshia/test-env or any parent directory
fixed-compilation-database: Error while opening fixed database: No such file or directory
json-compilation-database: Error while opening JSON database: No such file or directory
Running without flags.
```

**Comment by HighCommander4** [comment] 2023-02-26 05:57
clang-tidy needs a `compile_commands.json` file, the same as clangd

**Comment by HighCommander4** [comment] 2024-01-15 02:45
We've disabled the `bugprone-unchedked-optional-access` check in clangd in https://github.com/clangd/clangd/issues/1700 (will be released in clangd 18). I'm going to close this as a duplicate.

For developments on the underlying instability in the checker, please follow https://github.com/llvm/llvm-project/issues/55530.

**Comment by HighCommander4** [comment] 2024-01-15 02:46
Duplicate of #1700

**Closed by HighCommander4** 2024-01-15 02:46 UTC
