### ISSUE TITLE
clangd crashed while using cuda20

### ISSUE THREAD

**Issue by moui0** [clangd/clangd#2259] opened 2024-12-18 09:39 UTC
clangd crashed while using `cuda20`, but worked fine with `cuda17`

Minimal reproducible code:
```cmake
# CMakeLists.txt
cmake_minimum_required(VERSION 3.25.2)

project(Demo LANGUAGES CXX CUDA)

find_package(CUDAToolkit REQUIRED)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CUDA_STANDARD 20)
set(CMAKE_CUDA_STANDARD_REQUIRED ON)

set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

# prevent nvcc --options-file
set(CMAKE_CUDA_USE_RESPONSE_FILE_FOR_INCLUDES OFF)
set(CMAKE_CUDA_USE_RESPONSE_FILE_FOR_LIBRARIES OFF)
set(CMAKE_CUDA_USE_RESPONSE_FILE_FOR_OBJECTS OFF)

add_executable(demo src/main.cu)
target_include_directories(demo PUBLIC include)
```

```cpp
// include/demo.h
#ifndef __DEMO_H__
#define __DEMO_H__

class Demo {
public:
  Demo(int val) { ptr = new int(val); }
  ~Demo() { delete ptr; }

protected:
  int *ptr = nullptr;
};

#endif // __DEMO_H__
```

```cpp
// src/main.cu
#include "demo.h"

int main() {
    Demo demo(100);
    return 0;
}
```

**Logs**

https://hackmd.io/r6FKexQoQVORz9XYnHFkOA

**System information**

Output of `clangd --version`:
```
clangd version 18.1.3 (https://github.com/llvm/llvm-project c13b7485b87909fcf739f62cfa382b55407433c0)
Features: linux+grpc
Platform: x86_64-unknown-linux-gnu
```

Editor/LSP plugin:
- vscode 1.96.0
- vscode-clangd 0.1.33
- nvcc 12.2/12.6

Operating system:
- Ubuntu 20.04/22.04

**Comment by HighCommander4** [comment] 2024-12-20 05:34
This looks like the same crash as the one in https://github.com/clangd/clangd/issues/1452.

**Comment by HighCommander4** [comment] 2024-12-20 05:35
Duplicate of #1452

**Closed by HighCommander4** 2024-12-20 05:35 UTC
