### ISSUE TITLE
Implement textDocument/foldingRange

### ISSUE THREAD

**Issue by HighCommander4** [clangd/clangd#310] opened 2020-03-17 18:52 UTC
LSP has support for code folding via the [`textDocument/foldingRange`](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_foldingRange) request.

It would be nice if clangd had support for it.

**Comment by sam-mccall** [comment] 2020-03-24 01:44
Not very familiar with this corner of LSP: it looks like we can fold comments and #include blocks which is fine, though not that interesting.

Is it intended to be able to fold scopes too, and just leave kind blank in that case?

**Comment by HighCommander4** [comment] 2020-03-24 01:49
> Is it intended to be able to fold scopes too, 

I believe so. The main use case I had in mind is folding class and function bodies, though we could consider other scopes (e.g. local within a function) too.

> and just leave kind blank in that case?

I think the kind enum is intended to be (potentially) extended with language-specific kinds.

**Comment by sam-mccall** [comment] 2020-03-24 02:11
> I think the kind enum is intended to be (potentially) extended with language-specific kinds.

Makes sense, I'm just used to seeing these enums being conceivably exhaustive for *some* language.

Seems like there's a few sensible sources of regions:
 - an AST traversal that reports the open/close markers of certain nodes (CompoundStmt, TagDecl, NamespaceDecl, ObjCContainerDecl, ....). I guess only when they're on different lines, and don't span the same lines as the parent...
 - `private:` etc regions - this would be part of the AST traversal, but it's a weird/different case as AccessSpecDecl doesn't have a range or contain the affected decls.
 - A pass looking for multiline comments/comment blocks, I guess once TokenBuffer retains commentsemitting runs of consecutive lines
 - a pass over the #includes recorded in ParsedAST, looking for consecutive lines  
 - a preprocessing pass matching #if with #endif etc. (These won't properly nest with others - not clear that matters?)

**Comment by kadircet** [comment] 2020-03-24 07:00
> Makes sense, I'm just used to seeing these enums being conceivably exhaustive for some language.

`kind` field in `FoldingRange` is both optional and of type `string` so I believe the `FoldingRangeKind` enum is only there for standardization of some region names and servers can send whatever they want. The comments mention that `kind` can be used to collapse/expand all regions of same type.

> private: etc regions - this would be part of the AST traversal, but it's a weird/different case as AccessSpecDecl doesn't have a range or contain the affected decls.

i think that would be really useful, even though handling is kind of weird as you mentioned :/

**Comment by sam-mccall** [comment] 2020-05-15 23:29
> a preprocessing pass matching #if with #endif etc. 

 you could also tell the client which regions are enabled vs disabled...

**Comment by kirillbobyrev** [comment] 2020-07-15 22:12
Now that the folding ranges feature skeleton is landed, we can proceed to the full implementation.

Here's a snippet of what the folds should like like in the code, feel free to add/comment, hopefully I didn't forget something improtant.

https://reviews.llvm.org/D83914

**Comment by Trass3r** [comment] 2020-07-17 13:14
So it was just in time for 11?

**Comment by kirillbobyrev** [comment] 2020-07-17 17:46
@Trass3r It is in 11 release but I used a very basic implementation (one could say a "placeholder" one) that provides ranges but they're not as nice as we want them to be, so it's off by default. Run with `--folding-ranges` (https://github.com/llvm/llvm-project/blob/release/11.x/clang-tools-extra/clangd/tool/ClangdMain.cpp#L299) to enable feature preview, but it will hopefully converge to the behavior from RFC snippet above within the next release cycle.

**Comment by njames93** [comment] 2021-01-30 20:48
The current Impl definitely has some holes in there, Gonna try and narrow it down, code and server version are from the trunk branch after the 12 release cut 
```
V[20:40:28.032] ASTWorker running FoldingRanges on version 1 of /home/nathan/src/llvm-project/clang-tools-extra/clangd/tool/ClangdMain.cpp
clangd: /home/nathan/src/llvm-project/clang/lib/Tooling/Syntax/BuildTree.cpp:455: ArrayRef<syntax::Token> clang::syntax::TreeBuilder::getRange(clang::SourceRange) const: Assertion `Range.isValid()' failed.
V[20:40:28.045] <<< {"jsonrpc":"2.0","method":"$/cancelRequest","params":{"id":9}}

I[20:40:28.045] <-- $/cancelRequest
 #0 0x0000000000c50633 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/home/nathan/.local/bin/clangd+0xc50633)
 #1 0x0000000000c4e47c llvm::sys::RunSignalHandlers() (/home/nathan/.local/bin/clangd+0xc4e47c)
 #2 0x0000000000c50a3f SignalHandler(int) (/home/nathan/.local/bin/clangd+0xc50a3f)
 #3 0x00007f6082e933c0 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x153c0)
 #4 0x00007f608292818b raise /build/glibc-ZN95T4/glibc-2.31/signal/../sysdeps/unix/sysv/linux/raise.c:51:1
 #5 0x00007f6082907859 abort /build/glibc-ZN95T4/glibc-2.31/stdlib/abort.c:81:7
 #6 0x00007f6082907729 get_sysdep_segment_value /build/glibc-ZN95T4/glibc-2.31/intl/loadmsgcat.c:509:8
 #7 0x00007f6082907729 _nl_load_domain /build/glibc-ZN95T4/glibc-2.31/intl/loadmsgcat.c:970:34
 #8 0x00007f6082918f36 (/lib/x86_64-linux-gnu/libc.so.6+0x36f36)
 #9 0x0000000001bdff3a (anonymous namespace)::BuildTreeVisitor::buildIdExpression(clang::NestedNameSpecifierLoc, clang::SourceLocation, clang::SourceRange, llvm::PointerUnion<clang::Stmt*, clang::Decl*>) (/home/nathan/.local/bin/clangd+0x1bdff3a)
#10 0x0000000001bd5681 (anonymous namespace)::BuildTreeVisitor::WalkUpFromMemberExpr(clang::MemberExpr*) (/home/nathan/.local/bin/clangd+0x1bd5681)
#11 0x0000000001bc4923 clang::RecursiveASTVisitor<(anonymous namespace)::BuildTreeVisitor>::TraverseStmt(clang::Stmt*, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt*, 1u, bool, llvm::PointerLikeTypeTraits<clang::Stmt*>, llvm::PointerIntPairInfo<clang::Stmt*, 1u, llvm::PointerLikeTypeTraits<clang::Stmt*> > > >*) (/home/nathan/.local/bin/clangd+0x1bc4923)
#12 0x0000000001bd14e8 clang::RecursiveASTVisitor<(anonymous namespace)::BuildTreeVisitor>::TraverseCXXMemberCallExpr(clang::CXXMemberCallExpr*, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt*, 1u, bool, llvm::PointerLikeTypeTraits<clang::Stmt*>, llvm::PointerIntPairInfo<clang::Stmt*, 1u, llvm::PointerLikeTypeTraits<clang::Stmt*> > > >*) (/home/nathan/.local/bin/clangd+0x1bd14e8)
#13 0x0000000001bc572d clang::RecursiveASTVisitor<(anonymous namespace)::BuildTreeVisitor>::TraverseStmt(clang::Stmt*, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt*, 1u, bool, llvm::PointerLikeTypeTraits<clang::Stmt*>, llvm::PointerIntPairInfo<clang::Stmt*, 1u, llvm::PointerLikeTypeTraits<clang::Stmt*> > > >*) (/home/nathan/.local/bin/clangd+0x1bc572d)
#14 0x0000000001bd8e98 clang::RecursiveASTVisitor<(anonymous namespace)::BuildTreeVisitor>::TraverseUnaryOperator(clang::UnaryOperator*, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt*, 1u, bool, llvm::PointerLikeTypeTraits<clang::Stmt*>, llvm::PointerIntPairInfo<clang::Stmt*, 1u, llvm::PointerLikeTypeTraits<clang::Stmt*> > > >*) (/home/nathan/.local/bin/clangd+0x1bd8e98)
#15 0x0000000001bc5d11 clang::RecursiveASTVisitor<(anonymous namespace)::BuildTreeVisitor>::TraverseStmt(clang::Stmt*, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt*, 1u, bool, llvm::PointerLikeTypeTraits<clang::Stmt*>, llvm::PointerIntPairInfo<clang::Stmt*, 1u, llvm::PointerLikeTypeTraits<clang::Stmt*> > > >*) (/home/nathan/.local/bin/clangd+0x1bc5d11)
#16 0x0000000001bc7938 clang::RecursiveASTVisitor<(anonymous namespace)::BuildTreeVisitor>::TraverseIfStmt(clang::IfStmt*, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt*, 1u, bool, llvm::PointerLikeTypeTraits<clang::Stmt*>, llvm::PointerIntPairInfo<clang::Stmt*, 1u, llvm::PointerLikeTypeTraits<clang::Stmt*> > > >*) (/home/nathan/.local/bin/clangd+0x1bc7938)
#17 0x0000000001bc5ca5 clang::RecursiveASTVisitor<(anonymous namespace)::BuildTreeVisitor>::TraverseStmt(clang::Stmt*, llvm::SmallVectorImpl<llvm::PointerIntPair<clang::Stmt*, 1u, bool, llvm::PointerLikeTypeTraits<clang::Stmt*>, llvm::PointerIntPairInfo<clang::Stmt*, 1u, llvm::PointerLikeTypeTraits<clang::Stmt*> > > >*) (/home/nathan/.local/bin/clangd+0x1bc5ca5)
#18 0x0000000001bc4731 (anonymous namespace)::BuildTreeVisitor::TraverseStmt(clang::Stmt*) (/home/nathan/.local/bin/clangd+0x1bc4731)
#19 0x0000000001bc6ea8 clang::RecursiveASTVisitor<(anonymous namespace)::BuildTreeVisitor>::TraverseCompoundStmt(clang::CompoundStmt*[Info  - 20:40:28] Connection to server got closed. Server will restart.
```

**Comment by kirillbobyrev** [comment] 2021-01-30 21:34
Yeah, sorry, I. should document it better. The current version is not very useful feature-wise. The decision is to use Syntax Trees for it (originally it wasn't but I changed it) and make this the first place in Clangd where we use Syntax Trees - sort of playground for it. We believe Syntax Trees is an important strategic feature we want to rely on in the future in more places but experiments with Folding Ranges showed that it is very much unreliable right now. It crashes and crashes a lot, that's why folding ranges are behind the flag right now.

The plan is to invest into making Syntax Trees build successfully from a valid Clang AST this quarter and then invest into making Syntax Trees not crash when given a broken AST. Hopefully, the timeline will allow us to push it into the next major release (13.0, right?).

**Comment by DavidGoldman** [comment] 2021-06-21 14:46
Any updates here? Looks like it's still disabled by default.

**Comment by Trass3r** [comment] 2021-06-21 14:49
It's still crashing every time I happen to try it. Now on clangd-12.

**Comment by kirillbobyrev** [comment] 2021-06-22 09:20
> Any updates here? Looks like it's still disabled by default.

Yes, there wasn't any work on this directly. The large enabler for this (and many other features) are Syntax Trees which we are actively experimenting with but the problem is that until they're mature enough to avoid this much crashing we can't really roll this out.

**Comment by Trass3r** [comment] 2021-06-22 09:39
How are they different from the AST?

**Comment by kirillbobyrev** [comment] 2021-06-22 12:22
When Clang AST was designed, the developers had very different needs compared to us. This led to some decisions that are hard to work around. One major problem we have is that AST throws away a lot of useful information and optimizes it away, and we spend a lot of effort to restore that information in Clangd. What we really want is some _actual syntax_ representation (that we can deduce to corresponding tokens, etc), not _abstrarct_ and optimized one.

@hokein would be the right person to ask for more details if you're curious.

**Comment by HighCommander4** [comment] 2023-01-07 08:07
It looks like clangd 16 has code folding enabled by default (since https://reviews.llvm.org/D132919) -- can we close this issue?

**Comment by kadircet** [comment] 2023-01-17 14:10
yes, thank you for the reminder!

**Closed by kadircet** 2023-01-17 14:10 UTC
Labels: enhancement, help wanted
