### ISSUE TITLE
Unexpected addition of include when completing a symbol already included

### ISSUE THREAD

**Issue by siegel** [clangd/clangd#1604] opened 2023-04-19 15:12 UTC
I've observed this symptom in my own code, and I *think* I've been able to reduce it to a small enough example to reproduce. 

Summary: when completing symbols defined in a file included by a header file, clangd generates an unnecessary include for the header containing the symbol.

Consider the following `Prefix.h`:

```c++
#ifndef PREFIX_h
#define PREFIX_h	1

#include <Foundation/Foundation.h>

const int kDeclaredInPCH = 42;

#endif
```

And the following `example.mm` that includes it:

```objective-c++
#include "Prefix.h"

@interface MyObjectClass : NSObject

- (void)doSomething: (NSString*)anArg;

@end


@implementation MyObjectClass

- (void)doSomething: (NSString*)anArg
{
	NSLog(@"%@", anArg);
}

@end


int
main (int argc, char **argv)
{
	MyObjectClass	*foo = [[MyObjectClass alloc] init];
	
	[foo doSomething: @"Hello World"];
}
```

(Files contained in the attached [Archive.zip](https://github.com/clangd/clangd/files/11274640/Archive.zip).)

This file shows no diagnostics, so evidently clangd is able to compile it.

If I start typing `NSNum` on line 25 of the source file, clangd offers completions, including `NSNumber`.

<img width="320" alt="Screenshot 2023-04-19 at 11 06 56 AM" src="https://user-images.githubusercontent.com/1295248/233120229-00d3782d-e2f9-40ea-b7be-c59d14ce112a.png">

If I choose that completion, `NSNumber` gets inserted, clangd *also* generates an edit that inserts `#include <Foundation/Foundation.h>` at the beginning of the source file (after the `#include "Prefix.h"`). This second include is unnecessary, and requires a manual edit to remove.

<img width="311" alt="Screenshot 2023-04-19 at 11 12 02 AM" src="https://user-images.githubusercontent.com/1295248/233120381-a9db6322-1933-4462-a8c4-9902b06462a3.png">

**Logs**

I don't have any relevant logging at the moment; if this impedes diagnosis please let me know and I will see what I can generate.

**System information**

Output of `clangd --version`:

```
Homebrew clangd version 16.0.1
Features: mac+xpc
Platform: arm64-apple-darwin22.4.0
```

Editor/LSP plugin: BBEdit 14.6.5

Operating system: macOS 13.3.1

**Comment by zyn0217** [comment] 2023-04-20 02:18
Please see #70 for detailed discussion.

**Comment by HighCommander4** [comment] 2023-04-20 05:57
Right, this is clangd's header insertion feature assuming the project uses the "include what you use" style, i.e. that if you use a symbol declared in `<Foundation/Foundation.h>` in a source file, then you include `<Foundation/Foundation.h>` directly in that source file.

At this time, if your project does not use the "include what you use" style, the workaround is to disable clangd's header insertion by passing `--header-insertion=never` as a command-line argument to clangd.

**Comment by siegel** [comment] 2023-04-20 14:33
> At this time, if your project does not use the "include what you use" style, the workaround is to disable clangd's header insertion by passing --header-insertion=never as a command-line argument to clangd

OK. I actually *do* find the current behavior useful in situations where the completed symbol is in my own project and one of my own headers needs to be included in order to compile the completed usage. But I will experiment with `--header-insertion=never` and see if trading one behavior for another is livable. :-)

Is it possible to configure the header insertion behavior in `.clangd`? (I didn't find anything likely in the documentation, but I might have missed something…)

**Comment by HighCommander4** [comment] 2023-04-21 04:16
> Is it possible to configure the header insertion behavior in `.clangd`?

Not currently, the mentioned #70 is open about adding an option more suitable for projects that don't use the "include what you use" style.

**Comment by HighCommander4** [comment] 2023-06-10 05:49
I think we can close this as a duplicate of #70, and have any follow-up discussion there.

**Closed by HighCommander4** 2023-06-10 05:49 UTC
