### ISSUE TITLE
openmp pragma break hover

### ISSUE THREAD

**Issue by maximeB** [clangd/clangd#596] opened 2020-11-19 09:09 UTC
When inspecting a for loop prallelized with openmp, code hover are not shown (code completion works though).

Putting the mouse over the variable th_num in the following code doesn't hover its type.  
Removing the pragma or simply comment it solves the issue
```c++
#pragma omp parallel for
for (int i = 0; i < count; ++i) {
    int th_num = omp_get_thread_num();
    printf("thread number %d", th_num);
}
```

**System information**
Output of `clangd --version`: 11.0.0
Editor/LSP plugin: vscode/clangd
Operating system: windows (remote ssh on centos 7)

**Comment by HighCommander4** [comment] 2024-04-05 19:55
I'm going to forward-dupe this to #1640. The workaround described in [this comment](https://github.com/clangd/clangd/issues/1640#issuecomment-1556637260) is applicable here too.

**Comment by HighCommander4** [comment] 2024-04-05 19:55
Duplicate of #1640

**Closed** 2024-04-05 19:55 UTC
