### ISSUE TITLE
Allow the client to specify multiple compilation databases

### ISSUE THREAD

**Issue by HighCommander4** [clangd/clangd#116] opened 2019-08-03 23:44 UTC
As previously discussed in [this mailing list thread](http://lists.llvm.org/pipermail/clangd-dev/2019-January/000232.html), there is a desire to allow clients to specify multiple compilation databases, particularly in multi-project setups where the CDBs are outside the source directories (e.g. they're in the build directories), and so clangd doesn't pick them up automatically.

I have submitted [a patch for this](https://reviews.llvm.org/D65625). I'm filing this issue mainly to have a convenient place to discuss it, including by people who don't necessarily have LLVM Phabricator accounts.

cc @ilya-biryukov, @sam-mccall

**Comment by HighCommander4** [comment] 2019-08-03 23:51
In a [review comment](https://reviews.llvm.org/D65625#1611836), Ilya asked:

> Could this be handled outside clangd? If not, what are the complications?
> 
> We currently have a capability to specify a path to a single `compile_commands.json`.
> I would expect clients using this extension (Theia?) also handle generation of `compile_commands.json`. If that's the case, could they merge multiple `compile_commands.json` files into one and ask clangd to load it using APIs we have today?

My first thought here is that clients likely delegate the generation of CDBs to other tools, e.g. build systems. They don't necessarily have an easy way to merge CDBs without implementing that functionality in the client, and it seems unfortunate for clients to have to implement that, given that clangd is able to handle multiple CDBs already -- all we're trying to do here is tell clangd explicitly where they are, for cases where clangd can't figure that out automatically.

@marcdumais-work, @marechal-p, @vince-fugnitto: could you weigh in here, with a view to Theia in particular? Is it the case that Theia delegates the generation of CDBs to build systems? Would it be inconvenient for Theia to have to merge CDBs on the client side?

**Comment by marechal-p** [comment] 2019-08-04 00:38
Well, since we could not pass multiple compilation databases to clangd, we did implement something to merge different databases. But the way I see it, language servers are supposed to factor-out common logic out of the IDE. And if you tell me that clangd already supports multiple databases, I would expect to be able to define those. It just makes more sense to me. I could understand not making clangd consume multiple databases if it meant making big changes, but apparently this is somewhat already supported, and only the configuration bit was missing...

**Comment by marcdumais-work** [comment] 2019-08-05 14:31
Hi @HighCommander4 ,

In addition to Paul's comment:

A use-case to eventually support is a project having [multiple workspace folders](https://code.visualstudio.com/docs/editor/multi-root-workspaces), sometimes called "multi-root" workspaces. See [LSP's Workspace folders request](https://microsoft.github.io/language-server-protocol/specification#workspace_workspaceFolders) for how this works at generic LSP-level. I think this would ideally imply, for clangd, having one compilation database associated to each workspace folder, and having the server handle the details (e.g. merging of compilation databases). 

I assume that clangd does not support this LSP feature ATM? If we can't agree on having clangd handle multiple compilation databases for a single workspace folder,  I think supporting multiple workspace folders could be a good way forward. 



WDYT? 

Client-side note: In Theia the current language-client we use does not yet support the configuration options to specify multiple workspace folders, but it's coming soon, after we uplift our Monaco fork and related base language client, to support a more recent version of LSP.

**Comment by ilya-biryukov** [comment] 2019-08-07 17:57
The reason we are treading carefully with this extension is because we now have more sophisticated code relying on `GlobalCompilationDatabase` than we used to when adding the `compileCommandsDir`.

In particular, we now notify background index about the compilation databases we have loaded to build the index for that project and save it on disk under the project's root directory. This forces us to special-case the `compileCommandsDir` case in rather complicated code. We need to refactor the code and provide an extension point (used by complicated code in `DirectoryBasedGlobalCDB`) that covers the directory-based traversal and lsp-extension-based-compile-dirs cases without touching the complicated bits of the code.

We discussed this and our best idea so far is to abstract away the discovery mechanism (i.e. a function to get from a filename to a directory that contains the `compile_commands.json`, or `compile_flags.txt` governing that file) from `DirectoryBasedCDB`. Waving my hands, this would mean removing the `CompileCommandsDir` parameter from `DirectoryBasedCDB` constructor and instead accepting a function or a interface that would find the project root from which we should load our CDBs, given a filename. Obviously, another constraint is that `CompileCommandsDir` and the new proposed extension should be implementable on top of that.
But given the plugin-based design of clang's CompilationDatabase interface, it might need to be more complicated than that.

We could try to squeeze in time to do this refactoring this or next quarter, but would also welcome contributions/alternative proposals on properly abstracting away these things from `DirectoryBasedCDB` while still sharing the other bits (e.g. background index notifications).

But those are technical problems, also wanted to clarify a few design choices.
1. How should this extension figure out which compilation database governs a particular file?
2. The one matching longest prefix common of the filename (this would emulate going up the directory tree)?
3. Should the matching be case-insensitive on Windows? 

Last, but not least, what are the clients that want to use this extension?

**Comment by ilya-biryukov** [comment] 2019-08-07 17:59
> But given the plugin-based design of clang's CompilationDatabase interface, it might need to be more complicated than that.
That probably means that returning just a "project root" directory won't work, but the function could probably return a list of directories to search in.

**Comment by marechal-p** [comment] 2019-08-07 20:50
> 1. How should this extension figure out which compilation database governs a particular file?

According to the following:

```
diff --git a/clang-tools-extra/clangd/GlobalCompilationDatabase.cpp b/clang-tools-extra/clangd/GlobalCompilationDatabase.cpp
--- a/clang-tools-extra/clangd/GlobalCompilationDatabase.cpp
+++ b/clang-tools-extra/clangd/GlobalCompilationDatabase.cpp
@@ -92,8 +92,10 @@
 
 DirectoryBasedGlobalCompilationDatabase::
     DirectoryBasedGlobalCompilationDatabase(
-        llvm::Optional<Path> CompileCommandsDir)
-    : CompileCommandsDir(std::move(CompileCommandsDir)) {}
+        llvm::Optional<Path> CompileCommandsDir,
+        llvm::Optional<CompilationDatabaseMap> CDBMap)
+    : CompileCommandsDir(std::move(CompileCommandsDir)),
+      CDBMap(std::move(CDBMap)) {}
 
 DirectoryBasedGlobalCompilationDatabase::
     ~DirectoryBasedGlobalCompilationDatabase() = default;
@@ -168,6 +170,13 @@
     CachedCDB *Entry = nullptr;
     if (CompileCommandsDir) {
       Entry = &getCDBInDirLocked(*CompileCommandsDir);
+    } else if (CDBMap) {
+      for (const auto &MapEntry : *CDBMap) {
+        if (StringRef(Request.FileName).startswith(MapEntry.sourceDir)) {
+          Entry = &getCDBInDirLocked(MapEntry.dbPath);
+          break;
+        }
+      }
     } else {
       // Traverse the canonical version to prevent false positives. i.e.:
       // src/build/../a.cc can detect a CDB in /src/build if not canonicalized.
```

It seems like it would find the first match where the provided source directory matches with the requested file name. The extension doesn't simply allow us to provide a list of databases, but a map `source -> database`. Is this the best way? I don't know, but it allows to control how and what it applies to.

> 2. The one matching longest prefix common of the filename (this would emulate going up the directory tree)?

If it were only a list of databases, it could be a good strategy.

> 3. Should the matching be case-insensitive on Windows?

Makes sense to me.

> Last, but not least, what are the clients that want to use this extension?

In Theia's C++ extension, we want to be able to define a compilation database per workspace root, so we have code that would use this clangd extension and send a `source -> database` map to clangd. We also implemented the CDB merging as a fallback, but we did not expect that having clangd consume multiple databases would bring the technical problems you mentioned.

It is more of a convenience thing, and to have clangd aligned with the multi-root concepts from the LSP, since IDEs will most likely support this feature as well (VS Code, Theia, Atom?, etc). Developers might want to edit different projects at the same time, in the case where it would be built in two different locations, it would make sense from a client perspective to be able to direct clangd to both places.

As background, we usually simply allow the users to configure what needs to be passed to the tools, then send it over and do as little processing as possible, as most projects are handled and built by external build systems. Keep in mind that most recent "IDEs" are closer to text editors than they are from older proper IDEs where almost everything was managed by it, bloating them with internal features. Our basic IDE extensions can take care of merging different databases in the event that clangd doesn't support this use case, but it sounds more like a work around than anything else.

But this is my opinion as a "clangd consumer", and I unfortunately cannot really help with implementation details in clangd, so I would understand any friction with the current design of things.

**Comment by HighCommander4** [comment] 2019-08-09 04:59
>     1. How should this extension figure out which compilation database governs a particular file?
> 
>     2. The one matching longest prefix common of the filename (this would emulate going up the directory tree)?

To add to what Paul said, I expect that in a typical use scenario, the source paths in the CDB map are disjoint, such that only one of them is a prefix for any given source file (and so we'd use the CDB path mapped to that source path).

If we eventually want to support scenarios where the source paths are not necessarily disjoint, then "longest prefix" sounds like a reasonable disambiguation rule.

**Comment by HighCommander4** [comment] 2019-08-09 05:05
> In particular, we now notify background index about the compilation databases we have loaded to build the index for that project and save it on disk under the project's root directory. This forces us to special-case the `compileCommandsDir` case in rather complicated code. We need to refactor the code and provide an extension point (used by complicated code in `DirectoryBasedGlobalCDB`) that covers the directory-based traversal and lsp-extension-based-compile-dirs cases without touching the complicated bits of the code.

Is the "complicated code" you refer to the logic in `DirectoryBasedGlobalCompilationDatabase::broadcastCDB()` to determine which subset of files in a CDB are "governed by" that CDB?

IIUC, the motivation for having this logic is to handle "nested CDB" scenarios, where a directory "A" and an ancestor of A both contain a CDB with an entry for a file inside A (in which case we want to prefer the CDB in A, not its ancestor).

Would it help manage the complexity here if, in a first pass, we assumed (possibly even enforced) that the source paths in the CDB map are disjoint? That way, the "nested CDB" scenario would not occur, and `broadcastCDB()` could broadcast all files in the CDB if the CDB comes from the CDB map.

**Comment by MarkZ3** [comment] 2020-08-27 01:41
I think it makes sense to support to specify multiple compilation databases in the server. Even for a single large project, some libraries come from other groups with even different build systems but that do generate their own CDBs in they build folders which vary greatly in term of location. Leaving it to the clients to do the merge seems like a lot of duplicated efforts over multiple clients.

**Comment by devcrafter** [comment] 2020-12-05 13:13
I guess from a developer perspective the simplest example, where multiple CDBs support is desired, would be a project with unit tests. So, even a simple project with unit tests has normally at least 2 targets, - some main target and unit test target. I'd like to be able to manage this simple setup out of the box

**Comment by HighCommander4** [comment] 2020-12-05 20:12
> I guess from a developer perspective the simplest example, where multiple CDBs support is desired, would be a project with unit tests. So, even a simple project with unit tests has normally at least 2 targets, - some main target and unit test target. I'd like to be able to manage this simple setup out of the box

Why does this setup require multiple CDBs? It seems like in this case, a single CDB for the project, which includes all of the project's source files including the unit test files, should work fine.

**Comment by studgeek** [comment] 2020-12-09 05:18
In terms of disambiguation, I would suggest that CDBs provided on the command line would have precedence (in order provided over CDBs) over the file system CDBs (which would follow based on longest prefix). This allows the client to control precedence if it wants.

**Comment by studgeek** [comment] 2020-12-09 05:19
Another use case that multiple command line CDBs would help with is when a project has multiple targets/toolchains (with different compile flags). In that case the user may need the ability to view the same project from each target's perspective (which could could be quite different due to C macros). File system-based compile_commands.json files will not work for that  since there is only one CDB for each source sub-tree.
If there is just a single CDB for the entire project then the client can set the CDB based on the target using the existing `--compile-commands-dir` flag (e.g. user could have a vscode `.code-workspace` per target with different `clangd.arguments`).
But if there are multiple CDBs (either at different levels or in different roots) then a way to indicate multiple CDBs on the command line is needed.

**Comment by sam-mccall** [comment] 2020-12-09 10:55
It seems to me there's a long tail of possible ways to set up projects and that we're doing a reasonable job of the simple cases (CDB next to project, or single CDB passed on command-line).

For the cases beyond this I don't think small extensions will really solve this in the long run - they'll solve things for a few more projects, but still won't be flexible enough for others.

I think the [config subsystem](https://clangd.llvm.org/config.html) is the best way to offer the flexibility we need.
The idea would be:
 - `CompileFlags: { CompilationDatabaseDirectory: "/some/path" }` would push the directory onto the list of paths searched for a CDB (currently `.`, `..`, etc)
 - existing mechanisms can be used to restrict which files this applies to (e.g. `If: { PathMatch: /src/proj/.* }` or placing the config file in `/src/proj/.clangd`)
 - for e.g. the multi-config setup @studgeek mentioned, we could have a generic way to switch on/off config fragments (e.g. with env variables: `If: { Env: CONFIG=ARM }`

This places some burden on clients/users but doesn't require them to actually merge the CDBs. 
It does mean the config needs to specify some path-based mapping to CDBs rather than just "load all the CDBs and see which one covers which file" - the latter isn't really compatible with some of our current CDB handling. (Specifically non-enumerable CDBs, and interpolation for missing files)

**Comment by studgeek** [comment] 2020-12-09 19:28
I'm not sure `If` logic in the config subsystem language can handle all ways in which a target can be defined/detected. I also think a general rule should be the invoker should have the option to explicitly control how clangd runs (vs files). So I would suggest there also should also be a command line flag for overriding the config system file location. It also feels like the config system language would need to support multiple fragments within a file so that multiple CDBs could each be assigned to different PathMatches?

I will say I think using a config system seems like a bit more work for the developer. I personally think multiple compile commands is useful enough that adding the ability for multiple `--compile-commands-dir` flags would be worth while in of itself. But that is based on just my experience and I may not fully appreciate how tricky disambiguation is.

**Comment by sam-mccall** [comment] 2021-01-22 16:09
> I also think a general rule should be the invoker should have the option to explicitly control how clangd runs (vs files)

The concept of "invoker" is pretty vague, clangd is usually implicitly invoked by the editor, using flags taken from the editor's config file. Flags have several weaknesses (hard to read/write complex configuration, can't pick up changes while running, errors tend to lead to complete failure, ...). And ultimately the UX is a config file anyway, for most editors. So we've decided to move options to a first-class clangd config file wherever possible.

> So I would suggest there also should also be a command line flag for overriding the config system file location

Yup, this is a good idea - we need some flags to control config files that are loaded. And maybe even to define config inline in a flag value, for where that's really needed.

> It also feels like the config system language would need to support multiple fragments within a file 

This is supported, fragments are delimited by `---` lines.

> I will say I think using a config system seems like a bit more work for the developer

Worth noting that all this only applies to users who won't/can't follow the convention that CDBs live above the project root (or in a 'build' subdirectory). It's a minority and there's some tradeoffs between ease-of-use vs flexibility vs internal complexity.

> the ability for multiple --compile-commands-dir flags

If you want clangd to load all these and automatically understand which files are associated with which... that's not totally unimplementable but there's a bunch of interactions to consider (hot-reload, background indexing, missing-command interpolation...). It's at least as much work to implement as the config solution, is easier to use, but solves fewer cases.

**Comment by gou4shi1** [comment] 2021-05-05 08:10
> Is the "complicated code" you refer to the logic in `DirectoryBasedGlobalCompilationDatabase::broadcastCDB()` to determine which subset of files in a CDB are "governed by" that CDB?
> 
> IIUC, the motivation for having this logic is to handle "nested CDB" scenarios, where a directory "A" and an ancestor of A both contain a CDB with an entry for a file inside A (in which case we want to prefer the CDB in A, not its ancestor).
> 
> Would it help manage the complexity here if, in a first pass, we assumed (possibly even enforced) that the source paths in the CDB map are disjoint? That way, the "nested CDB" scenario would not occur, and `broadcastCDB()` could broadcast all files in the CDB if the CDB comes from the CDB map.

I met some troubles because of this logic, my project is built with [bazel](https://bazel.build), the `directory` field in the generate CDB is `/home/username/.cache/bazel/_bazel_username/hash/execroot/project_name` while the CDB is located in project root `/home/username/project_name`, then `broadcastCDB()` thinks that CDB govern nothing...
Is it by design or a bug?

**Comment by kadircet** [comment] 2021-05-05 08:53
This is an unfortunate interaction with symlinks :( As you've mentioned clangd find the CDB in `/home/username/project_name` and assumes it as the project root correctly.

Later on during broadcast CDB reports files under `/home/username/.cache/bazel/_bazel_username/hash/execroot/project_name` which are by design not part of the project under `/home/username/project_name`. But in reality they are, since the files in CDB are just symlinks to sources under the other directory.

One workaround would be to have a clangd config for files under `/home/username/project_name` telling compilation database lies at `/home/username/project_name`, e.g:
```
If: # If block can be ignored if config file is at project root already
  PathMatch: /home/username/project_name/.* 
CompileFlags:
  CompilationDatabase: /home/username/project_name # Or just `.` if config file is at project root
```

More details about config files in https://clangd.llvm.org/config.html. Note that you'll need clangd-12 for `CompileFlags.CompilationDatabase`. This tells clangd to only (and always) broadcast contents of the compilation database in the mentioned directory, for the files affected by this configuration fragment.

**Comment by gou4shi1** [comment] 2021-05-05 09:18
Thanks for your quick reply :)
My previous workaround is to change the `directory` field of CDB from `/home/username/.cache/bazel/_bazel_username/hash/execroot/project_nam` to `/home/username/project_name/bazel-project_name`, while the latter is a symbolic link of the former, then `broadcastCDB()` thinks that CDB govern my project files.
I also noticed that `CompileFlags.CompilationDatabase` tells clangd to only and **always** broadcast, this also solved my issue.
I just think these constrains are not well documented, I have to dive into the codes.

**Comment by kadircet** [comment] 2021-12-16 15:14
It looks like the discussion here started with covering compilation databases for different projects (e.g. an application and its dependencies) and evolved into multi-configuration support. I believe the latter deserves its own issue as specification of the compilation database is not the only concern there. Whereas for the former situation has evolved a lot, and we've most of the requests in https://lists.llvm.org/pipermail/clangd-dev/2019-January/000232.html working and rest of the discussions fixable through clangd config mechanism as @sam-mccall mentioned in https://github.com/clangd/clangd/issues/116#issuecomment-741695313.

To sum it up a little bit:
- When there are multiple compilation databases governing distinct source files, clangd will query the one closest to the source or it can be configured to look for a database in a particular directory for files matching a certain pattern. Communicating this config through LSP rather than config files on disk is not implemented yet but definitely something we have in mind.
- Index will only contain information around compilation databases discovered so far, hence xrefs/definition won't include information from dependencies of an application, until a source file inside the dependency is opened by the editor. We've decided on not loading/indexing all the dependents/users of a code explicitly, as it provided much worse UX on big code bases like chromium, in which users didn't really cared much about definitions/refs inside third party code. Happy to have more discussions on this one and provide easier ways to explicitly tell clangd to discover extra compilation databases.

Since issue has been stale for a long while and we don't have any other action items in mind, i am closing it. Feel free to re-open if you've more suggestions/requests.

**Closed by kadircet** 2021-12-16 15:14 UTC
Labels: config
