### ISSUE TITLE
Clangd crashes when background index runs across a concept template argument

### ISSUE THREAD

**Issue by MrOverlord** [clangd/clangd#1930] opened 2024-02-13 15:28 UTC
The background indexer crashes with SIGSEGV when it encountered a template argument with a concept bounding it. I think I have a rough MVE below.

`test.h`:
```c++
template <typename T>
  concept c = true;
class d {};
template <template <c> typename f>
void fun()
{
  f<d>{};
}
```
`compile_commands.json`:
```json
[
  {
    "file": "test.h",
    "arguments": [
      "/usr/bin/gcc",
      "-xc++",
      "-iquote",
      ".",
      "-std=c++20",
      "-c",
      "test.cc",
      "-o",
      "test.o"
    ],
    "directory": "/home/marcin/Workspace/mve-problem"
  },
  {
    "file": "test.cc",
    "arguments": [
      "/usr/bin/gcc",
      "-xc++",
      "-iquote",
      ".",
      "-std=c++20",
      "-c",
      "test.cc",
      "-o",
      "test.o"
    ],
    "directory": "/home/marcin/Workspace/mve-problem"
  }
]
```
Contents of `test.cc` do not affect this behaviour.

**Logs**

```
[START][2024-02-13 16:14:35] LSP logging initiated
[ERROR][2024-02-13 16:14:35] .../vim/lsp/rpc.lua:734	"rpc"	"/home/marcin/.local/share/nvim/mason/bin/clangd"	"stderr"	'I[16:14:35.320] clangd version 17.0.3 (https://github.com/llvm/llvm-project 888437e1b60011b8a375dd30928ec925b448da57)
I[16:14:35.320] Features: linux+grpc
I[16:14:35.320] PID: 102349
I[16:14:35.320] Working directory: /home/marcin/Workspace/mve-problem
I[16:14:35.320] argv[0]: /home/marcin/.local/share/nvim/mason/bin/clangd
I[16:14:35.320] argv[1]: --offset-encoding=utf-16
I[16:14:35.320] argv[2]: --log=verbose
V[16:14:35.320] User config file is /home/marcin/.config/clangd/config.yaml
I[16:14:35.320] Starting LSP over stdin/stdout
V[16:14:35.320] <<< {"id":1,"jsonrpc":"2.0","method":"initialize","params":{"capabilities":{"offsetEncoding":["utf-16"],"textDocument":{"callHierarchy":{"dynamicRegistration":false},"codeAction":{"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}},"dataSupport":true,"dynamicRegistration":false,"isPreferredSupport":true,"resolveSupport":{"properties":["edit"]}},"completion":{"completionItem":{"commitCharactersSupport":true,"deprecatedSupport":true,"documentationFormat":["markdown","plaintext"],"insertReplaceSupport":true,"insertTextModeSupport":{"valueSet":[1,2]},"labelDetailsSupport":true,"preselectSupport":true,"resolveSupport":{"properties":["documentation","detail","additionalTextEdits","sortText","filterText","insertText","textEdit","insertTextFormat","insertTextMode"]},"snippetSupport":true,"tagSupport":{"valueSet":[1]}},"completionItemKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]},"completionList":{"itemDefaults":["commitCharacters","editRange","insertTextFormat","insertTextMode","data"]},"contextSupport":true,"dynamicRegistration":false,"editsNearCursor":true,"insertTextMode":1},"declaration":{"linkSupport":true},"definition":{"linkSupport":true},"documentHighlight":{"dynamicRegistration":false},"documentSymbol":{"dynamicRegistration":false,"hierarchicalDocumentSymbolSupport":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]}},"hover":{"contentFormat":["markdown","plaintext"],"dynamicRegistration":false},"implementation":{"linkSupport":true},"publishDiagnostics":{"relatedInformation":true,"tagSupport":{"valueSet":[1,2]}},"references":{"dynamicRegistration":false},"rename":{"dynamicRegistration":false,"prepareSupport":true},"semanticTokens":{"augmentsSyntaxTokens":true,"dynamicRegistration":false,"formats":["relative"],"multilineTokenSupport":false,"overlappingTokenSupport":true,"requests":{"full":{"delta":true},"range":false},"serverCancelSupport":false,"tokenModifiers":["declaration","definition","readonly","static","deprecated","abstract","async","modification","documentation","defaultLibrary"],"tokenTypes":["namespace","type","class","enum","interface","struct","typeParameter","parameter","variable","property","enumMember","event","function","method","macro","keyword","modifier","comment","string","number","regexp","operator","decorator"]},"signatureHelp":{"dynamicRegistration":false,"signatureInformation":{"activeParameterSupport":true,"documentationFormat":["markdown","plaintext"],"parameterInformation":{"labelOffsetSupport":true}}},"synchronization":{"didSave":true,"dynamicRegistration":false,"willSave":true,"willSaveWaitUntil":true},"typeDefinition":{"linkSupport":true}},"window":{"showDocument":{"support":true},"showMessage":{"messageActionItem":{"additionalPropertiesSupport":false}},"workDoneProgress":true},"workspace":{"applyEdit":true,"configuration":true,"didChangeWatchedFiles":{"dynamicRegistration":false,"relativePatternSupport":true},"semanticTokens":{"refreshSupport":true},"symbol":{"dynamicRegistration":false,"hierarchicalWorkspaceSymbolSupport":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]}},"workspaceEdit":{"resourceOperations":["rename","create","delete"]},"workspaceFolders":true}},"clientInfo":{"name":"Neovim","version":"0.9.5"},"initializationOptions":{"clangdFileStatus":true,"completeUnimported":true,"usePlaceholders":true},"processId":102345,"rootPath":"/home/marcin/Workspace/mve-problem","rootUri":"file:///home/marcin/Workspace/mve-problem","trace":"off","workspaceFolders":[{"name":"/home/marcin/Workspace/mve-problem","uri":"file:///home/marcin/Workspace/mve-problem"}]}}

I[16:14:35.320] <-- initialize(1)
I[16:14:35.322] --> reply:initialize(1) 1 ms
V[16:14:35.322] >>> {"id":1,"jsonrpc":"2.0","result":{"capabilities":{"astProvider":true,"callHierarchyProvider":true,"clangdInlayHintsProvider":true,"codeActionProvider":{"codeActionKinds":["quickfix","refactor","info"]},"compilationDatabase":{"automaticReload":true},"completionProvider":{"resolveProvider":false,"triggerCharacters":[".","<",">",":","\"","/","*"]},"declarationProvider":true,"definitionProvider":true,"documentFormattingProvider":true,"documentHighlightProvider":true,"documentLinkProvider":{"resolveProvider":false},"documentOnTypeFormattingProvider":{"firstTriggerCharacter":"\n","moreTriggerCharacter":[]},"documentRangeFormattingProvider":true,"documentSymbolProvider":true,"executeCommandProvider":{"commands":["clangd.applyFix","clangd.applyTweak"]},"foldingRangeProvider":true,"hoverProvider":true,"implementationProvider":true,"inactiveRegionsProvider":true,"inlayHintProvider":true,"memoryUsageProvider":true,"referencesProvider":true,"renameProvider":{"prepareProvider":true},"selectionRangeProvider":true,"semanticTokensProvider":{"full":{"delta":true},"legend":{"tokenModifiers":["declaration","definition","deprecated","deduced","readonly","static","abstract","virtual","dependentName","defaultLibrary","usedAsMutableReference","usedAsMutablePointer","constructorOrDestructor","userDefined","functionScope","classScope","fileScope","globalScope"],"tokenTypes":["variable","variable","parameter","function","method","function","property","variable","class","interface","enum","enumMember","type","type","unknown","namespace","typeParameter","concept","type","macro","modifier","operator","bracket","label","comment"]},"range":false},"signatureHelpProvider":{"triggerCharacters":["(",")","{","}","<",">",","]},"standardTypeHierarchyProvider":true,"textDocumentSync":{"change":2,"openClose":true,"save":true},"typeDefinitionProvider":true,"typeHierarchyProvider":true,"workspaceSymbolProvider":true},"offsetEncoding":"utf-16","serverInfo":{"name":"clangd","version":"clangd version 17.0.3 (https://github.com/llvm/llvm-project 888437e1b60011b8a375dd30928ec925b448da57) linux+grpc x86_64-unknown-linux-gnu"}}}

'
[ERROR][2024-02-13 16:14:35] .../vim/lsp/rpc.lua:734	"rpc"	"/home/marcin/.local/share/nvim/mason/bin/clangd"	"stderr"	'V[16:14:35.344] <<< {"jsonrpc":"2.0","method":"initialized","params":{}}

I[16:14:35.344] <-- initialized
V[16:14:35.344] <<< {"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"languageId":"cpp","text":"#include \"test.h\"\nint main()\n{\n  return 0;\n}\n","uri":"file:///home/marcin/Workspace/mve-problem/test.cc","version":0}}}

I[16:14:35.344] <-- textDocument/didOpen
I[16:14:35.344] Loaded compilation database from /home/marcin/Workspace/mve-problem/compile_commands.json
I[16:14:35.344] ASTWorker building file /home/marcin/Workspace/mve-problem/test.cc version 0 with command 
[/home/marcin/Workspace/mve-problem]
/usr/bin/gcc -xc++ -iquote . -std=c++20 -c -o test.o -resource-dir=/home/marcin/.local/share/nvim/mason/packages/clangd/clangd_17.0.3/lib/clang/17 -- /home/marcin/Workspace/mve-problem/test.cc
'
[ERROR][2024-02-13 16:14:35] .../vim/lsp/rpc.lua:734	"rpc"	"/home/marcin/.local/share/nvim/mason/bin/clangd"	"stderr"	'V[16:14:35.344] Broadcasting compilation database from /home/marcin/Workspace/mve-problem
I[16:14:35.344] --> window/workDoneProgress/create(0)
V[16:14:35.344] >>> {"id":0,"jsonrpc":"2.0","method":"window/workDoneProgress/create","params":{"token":"backgroundIndexProgress"}}

I[16:14:35.344] Enqueueing 2 commands for indexing
V[16:14:35.344] BackgroundIndex: building version 1 after loading index from disk
V[16:14:35.344] BackgroundIndex: serving version 1 (15904 bytes)
V[16:14:35.344] Indexing test.cc (digest:=062D67BC1DC8FB16)
V[16:14:35.344] Indexing test.h (digest:=50EF6E158AB36014)
V[16:14:35.345] Driver produced command: cc1 -cc1 -triple x86_64-unknown-linux-gnu -fsyntax-only -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name test.cc -mrelocation-model pic -pic-level 2 -pic-is-pie -mframe-pointer=all -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu x86-64 -tune-cpu generic -debugger-tuning=gdb -fcoverage-compilation-dir=/home/marcin/Workspace/mve-problem -resource-dir /home/marcin/.local/share/nvim/mason/packages/clangd/clangd_17.0.3/lib/clang/17 -iquote . -internal-isystem /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1 -internal-isystem /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/x86_64-pc-linux-gnu -internal-isystem /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/backward -internal-isystem /home/marcin/.local/share/nvim/mason/packages/clangd/clangd_17.0.3/lib/clang/17/include -internal-isystem /usr/local/include -internal-isystem /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../x86_64-pc-linux-gnu/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -std=c++20 -fdeprecated-macro -fdebug-compilation-dir=/home/marcin/Workspace/mve-problem -ferror-limit 19 -fgnuc-version=4.2.1 -fno-implicit-modules -fcxx-exceptions -fexceptions -no-round-trip-args -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -x c++ /home/marcin/Workspace/mve-problem/test.cc
I[16:14:35.345] --> textDocument/clangd.fileStatus
V[16:14:35.345] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"parsing includes, running Update","uri":"file:///home/marcin/Workspace/mve-problem/test.cc"}}

V[16:14:35.345] Building first preamble for /home/marcin/Workspace/mve-problem/test.cc version 0
'

```
**System information**

Output of `clangd --version`:
```
clangd version 17.0.3 (https://github.com/llvm/llvm-project 888437e1b60011b8a375dd30928ec925b448da57)
Features: linux+grpc
Platform: x86_64-unknown-linux-gnu
```

Editor/LSP plugin: neovim with mason/lspconfig 

Operating system: arch linux

**Comment by HighCommander4** [comment] 2024-02-13 15:41
This is fixed in clangd 18

**Comment by HighCommander4** [comment] 2024-02-13 16:05
Fixed by https://github.com/llvm/llvm-project/commit/0c7d46a7fd5b7956e285d385a6945153d6a06eb0 (making this a duplicate of https://github.com/llvm/llvm-project/issues/57410).

**Closed by HighCommander4** 2024-02-13 16:05 UTC
