### ISSUE TITLE
Detect included headers based on the main file instead of by looking at each file individually

### ISSUE THREAD

**Issue by alexlnkp** [clangd/clangd#2210] opened 2024-11-11 13:42 UTC
Here's the problem:

Main file looks like this:
```c
// main.c
#include <raylib.h> /* we include raylib so we can use Rectangle, Vector2, etc */

#include "player/player.h" /* since player/player.h is included after raylib - it can also use Rectangle, Vector2, etc */
// . . .
```
And the player/player.h looks like this:
```c
// player/player.h

#ifndef   __PLAYER_H__
#define   __PLAYER_H__

typedef struct player_t {
    Rectangle shape; /* we have Rectangle defined, but clangd doesn't seem to think this way */
    Vector2 vel; /* we have Vector2 defined, but clangd doesn't seem to think this way */
} player_t;

#endif /* __PLAYER_H__ */
```

So because of the order of inclusion of the headers in the main file - this will compile without any issues, but clangd constantly complains about `Rectangle` and `Vector2` not being defined.

My question is... What is the workaround for this? I don't want to include raylib.h in the `player/player.h`, besides, there were some cases where i couldn't just include the header within a header, like when using a single-header-library like STB:
```c
// main.c
#define STB_C_LEXER_IMPLEMENTATION
#include "stb_c_lexer.h"

#include "a.h" /* despite include guards, we get error because of redefenition */

// . . .
```
With:
```c
// a.h

#include "stb_c_lexer.h" /* forced to include this header for clangd to work with its types */
// . . .
```
And with:
```c
// othersource.c
#include "a.h" /* error because of redefenition */
// . . .
```
So that's not an ideal solution.

I'm not sure if that's a feature that exists as I couldn't find any information on how to make clangd see the includes in the order they are in the source file associated. 

Lastly, just in case, I'll add that I'm using `nob.h` for project compilation and I don't want to have to use CMake, even if that could fix this inconvenience.

**Comment by HighCommander4** [comment] 2024-11-11 20:59
Duplicate of #45 

There isn't a great / fully general workaround, but the one discussed in [this comment](https://github.com/clangd/clangd/issues/45#issuecomment-1700325968) sometimes works. In your case, that would amount to adding the following to `.clangd`:

```yaml
CompileFlags:
  Add: [-include=raylib.h]
```

**Closed by HighCommander4** 2024-11-11 20:59 UTC
Labels: enhancement

**Comment by alexlnkp** [comment] 2024-11-12 05:07
> Duplicate of #45
> 
> There isn't a great / fully general workaround, but the one discussed in [this comment](https://github.com/clangd/clangd/issues/45#issuecomment-1700325968) sometimes works. In your case, that would amount to adding the following to `.clangd`:
> 
> ```yaml
> CompileFlags:
>   Add: [-include=raylib.h]
> ```

Thanks for a response! Adding raylib include to `.clangd` worked for me!
I apologize for not noticing the existing issue, though; I should've checked the tracker more thoroughly.
