### ISSUE TITLE
"undeclared" issues when handling template classes in .h files

### ISSUE THREAD

**Issue by Qizhi697** [clangd/clangd#2168] opened 2024-09-29 06:10 UTC
clangd-vscode may encounter "undeclared" issues when handling template classes in .h files if the header files are not included.
<img width="1055" alt="image" src="https://github.com/user-attachments/assets/1e1b23fe-bb09-411c-b89f-61fca9915404">

**System information**

Output of `clangd --version`:18.1.3

Editor/LSP plugin: clangd-vscode

Operating system: ubuntu 20.04

**Comment by HighCommander4** [comment] 2024-09-29 06:15
Duplicate of https://github.com/clangd/clangd/issues/45.

**Closed by HighCommander4** 2024-09-29 06:15 UTC
