### ISSUE TITLE
System header included from header not found due to missing .clangd CompileFlag Adds

### ISSUE THREAD

**Issue by bear24rw** [clangd/clangd#1462] opened 2023-01-11 20:00 UTC
I believe this issue is similar to #1100 but with the twist that I'm using a `.clangd` file to add the paths to the system headers

If i include the system header from a .cpp file it finds it:

<img width="517" alt="image" src="https://user-images.githubusercontent.com/778194/211904309-36ca1061-3cd8-4de0-a213-0daccbb2bfdb.png">

But if another system header include it it does not find it:

<img width="1639" alt="image" src="https://user-images.githubusercontent.com/778194/211904109-add2fd61-8587-4692-92ed-cc4b1368e509.png">

In the clangd log you can see the command to process the system header (_stdint.h in this example) is missing the `-isystem` flags from my `.clangd` file:

```
I[11:54:03.095] ASTWorker building file /Users/max_thrun/.espressif/tools/xtensa-esp32s3-elf/esp-2022r1-11.2.0/xtensa-esp32s3-elf/xtensa-esp32s3-elf/include/sys/_stdint.h version 1 with command inferred from /Users/max_thrun/projects/repo/main/src/imu.cpp
[/Users/max_thrun/projects/repo/build/esp-idf/main]
/Users/max_thrun/.espressif/tools/xtensa-esp32s3-elf/esp-2022r1-11.2.0/xtensa-esp32s3-elf/bin/xtensa-esp32s3-elf-g++ --driver-mode=g++ -DJSON_NOEXCEPTION -mlongcalls -fdiagnostics-color=always -ffunction-sections -fdata-sections -Wall -Werror=all -Wno-error=unused-function -Wno-error=unused-variable -Wno-error=deprecated-declarations -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-enum-conversion -gdwarf-4 -ggdb -Og -fmacro-prefix-map=/Users/max_thrun/projects/repo=. -fmacro-prefix-map=/Users/max_thrun/projects/repo/esp-idf=/IDF -fstrict-volatile-bitfields -Wno-error=unused-but-set-variable -fno-jump-tables -fno-tree-switch-conversion -DconfigENABLE_FREERTOS_DEBUG_OCDAWARE=1 -fno-exceptions -fno-rtti -D_GNU_SOURCE "-DIDF_VER=\"v5.0\"" -DESP_PLATFORM -D_POSIX_READER_WRITER_LOCKS -fconcepts -Wfloat-conversion -Wno-error=restrict -Wno-missing-field-initializers -Wunused -c -resource-dir=/opt/homebrew/Cellar/llvm/15.0.6/lib/clang/15.0.6 -isysroot /Applications/XcodeInternal.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.5.sdk -x c++-header -std=gnu++20 -- /Users/max_thrun/.espressif/tools/xtensa-esp32s3-elf/esp-2022r1-11.2.0/xtensa-esp32s3-elf/xtensa-esp32s3-elf/include/sys/_stdint.h
```

But the command the compile `main.cpp` has the `-isystem` flags added correctly

```
I[11:57:06.908] ASTWorker building file /Users/max_thrun/projects/repo/main/src/main.cpp version 1 with command 
[/Users/max_thrun/projects/repo/build/esp-idf/main]
/Users/max_thrun/.espressif/tools/xtensa-esp32s3-elf/esp-2022r1-11.2.0/xtensa-esp32s3-elf/bin/xtensa-esp32s3-elf-g++ --driver-mode=g++ -fdiagnostics-color=always -ffunction-sections -fdata-sections -Wall -Werror=all -Wno-error=unused-function -Wno-error=unused-variable -Wno-error=deprecated-declarations -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-enum-conversion -gdwarf-4 -ggdb -Og -fmacro-prefix-map=/Users/max_thrun/projects/repo=. -fmacro-prefix-map=/Users/max_thrun/projects/repo/esp-idf=/IDF -Wno-error=unused-but-set-variable -fno-jump-tables -DconfigENABLE_FREERTOS_DEBUG_OCDAWARE=1 -std=gnu++20 -fno-exceptions -fno-rtti -D_GNU_SOURCE "-DIDF_VER=\"v5.0\"" -DESP_PLATFORM -D_POSIX_READER_WRITER_LOCKS -Wfloat-conversion -Wno-error=restrict -Wno-missing-field-initializers -Wunused -std=gnu++20 -o CMakeFiles/__idf_main.dir/src/main.cpp.obj -c -D__XTENSA__ -D_POSIX_THREADS -D_POSIX_TIMEOUTS -D_UNIX98_THREAD_MUTEX_ATTRIBUTES -fno-blocks --target=aarch64-unknown-linux-gnu -isysroot/Users/max_thrun/.espressif/tools/xtensa-esp32s3-elf/esp-2022r1-11.2.0/xtensa-esp32s3-elf -isystem/Users/max_thrun/.espressif/tools/xtensa-esp32s3-elf/esp-2022r1-11.2.0/xtensa-esp32s3-elf/xtensa-esp32s3-elf/include/c++/11.2.0 -isystem/Users/max_thrun/.espressif/tools/xtensa-esp32s3-elf/esp-2022r1-11.2.0/xtensa-esp32s3-elf/xtensa-esp32s3-elf/include/c++/11.2.0/xtensa-esp32s3-elf -isystem/Users/max_thrun/.espressif/tools/xtensa-esp32s3-elf/esp-2022r1-11.2.0/xtensa-esp32s3-elf/xtensa-esp32s3-elf/include -isystem/Users/max_thrun/.espressif/tools/xtensa-esp32s3-elf/esp-2022r1-11.2.0/xtensa-esp32s3-elf/xtensa-esp32s3-elf/sys-include -resource-dir=/opt/homebrew/Cellar/llvm/15.0.6/lib/clang/15.0.6 -isysroot /Applications/XcodeInternal.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.5.sdk -- /Users/max_thrun/projects/repo/main/src/main.cpp
```

`.clangd`: 
```
  CompileFlags:
      Add: [
          -D__XTENSA__,
          -D_POSIX_THREADS,
          -D_POSIX_TIMEOUTS,
          -D_UNIX98_THREAD_MUTEX_ATTRIBUTES,
          -fno-blocks,
          --target=aarch64-unknown-linux-gnu,
          -isysroot/Users/max_thrun/.espressif/tools/xtensa-esp32s3-elf/esp-2022r1-11.2.0/xten...,         
          -isystem/Users/max_thrun/.espressif/tools/xtensa-esp32s3-elf/esp-2022r1-11.2.0/xten...,          
          -isystem/Users/max_thrun/.espressif/tools/xtensa-esp32s3-elf/esp-2022r1-11.2.0/xten...,      
          -isystem/Users/max_thrun/.espressif/tools/xtensa-esp32s3-elf/esp-2022r1-11.2.0/xten...,          
          -isystem/Users/max_thrun/.espressif/tools/xtensa-esp32s3-elf/esp-2022r1-11.2.0/xten...,      
    ]
      Remove: [
          -mlongcalls,
          -fstrict-volatile-bitfields,
          -fno-tree-switch-conversion,
          -fconcepts,
      ]
```

**System information**

Output of `clangd --version`:

```
Homebrew clangd version 15.0.6
Features: mac+xpc
Platform: arm64-apple-darwin21.6.0
```

Editor/LSP plugin:

nvim coc-clangd

```
     2 I[11:31:31.070] Homebrew clangd version 15.0.6
     3 I[11:31:31.070] Features: mac+xpc
     4 I[11:31:31.070] PID: 38666
     5 I[11:31:31.070] Working directory: /Users/project/repo
     6 I[11:31:31.070] argv[0]: /opt/homebrew/opt/llvm/bin/clangd
     7 I[11:31:31.070] argv[1]: --background-index
     8 I[11:31:31.070] argv[2]: --clang-tidy
     9 I[11:31:31.070] argv[3]: --suggest-missing-includes
    10 I[11:31:31.070] argv[4]: --compile-commands-dir=build
    11 I[11:31:31.070] argv[5]: --log=verbose
```

Operating system:

```
ProductName:    macOS
ProductVersion: 12.5.1
```

**Comment by sam-mccall** [comment] 2023-01-11 20:34
Where is the `.clangd` file? Is it above `_stdint.h`?

**Comment by bear24rw** [comment] 2023-01-11 20:39
> Where is the `.clangd` file? Is it above `_stdint.h`?

They share a common ancestor director (my home folder)

**Comment by sam-mccall** [comment] 2023-01-11 21:23
Hmm, sounds very strange. Can you run `clangd --check=/path/to/_stdint.h --verbose` and report all the lines with "config" in them as well as the "compile command from CDB"?

**Comment by HighCommander4** [comment] 2023-01-12 01:18
> > Where is the `.clangd` file? Is it above `_stdint.h`?
> 
> They share a common ancestor director (my home folder)

Just to clarify, `.clangd` is located at `/Users/max_thrun/.clangd`? Otherwise, if it's located at e.g. `/Users/max_thrun/projects/repo/.clangd` or somesuch, it will not apply to headers in `/Users/max_thrun/.espressif/...`

**Comment by bear24rw** [comment] 2023-01-12 19:23
>Can you run `clangd --check=/path/to/_stdint.h --verbose` and report all the lines with "config" in them 
```
max_thrun@thrun ~/projects/repo/ % clangd --log=verbose --check=~/.espressif/tools/xtensa-esp32s3-elf/esp-2022r1-11.2.0/xtensa-esp32s3-elf/xtensa-esp32s3-elf/sys-include/sys/_stdint.h 2>&1 | grep -i config
V[11:17:53.766] User config file is /Users/max_thrun/Library/Preferences/clangd/config.yaml
```
My .clangd file is in `~/projects/repo/ `

If I check one of the cpp files in my project:
```
max_thrun@thrun ~/projects/repo % clangd --compile-commands-dir=build --log=verbose --check=main/src/main.cpp 2>&1 | grep "config"
V[11:20:01.458] User config file is /Users/max_thrun/Library/Preferences/clangd/config.yaml
V[11:20:01.458] config note at /Users/max_thrun/projects/repo/.clangd:1:0: Parsing config fragment
V[11:20:01.458] config note at /Users/max_thrun/projects/repo/.clangd:1:0: Parsed 1 fragments from file
```

> as well as the "compile command from CDB"?

No match for `_stdint.h`

For the cpp file in my repo:

```
max_thrun@thrun ~/projects/repo % clangd --compile-commands-dir=build --log=verbose --check=main/src/main.cpp 2>&1 | grep "CDB"
I[11:21:26.285] Compile command from CDB is: /Users/max_thrun/.espressif/tools/xtensa-esp32s3-elf/esp-2022r1-11.2.0/xtensa-esp32s3-elf/bin/xtensa-esp32s3-elf-g++ --driver-mode=g++ <more flags snipped>
```

**Comment by bear24rw** [comment] 2023-01-12 19:26
> > > Where is the `.clangd` file? Is it above `_stdint.h`?
> > 
> > They share a common ancestor director (my home folder)
> 
> Just to clarify, `.clangd` is located at `/Users/max_thrun/.clangd`? Otherwise, if it's located at e.g. `/Users/max_thrun/projects/repo/.clangd` or somesuch, it will not apply to headers in `/Users/max_thrun/.espressif/...`

It's located at `/Users/max_thrun/projects/repo/.clangd`, so maybe that explains it, although slightly surprising behavior imo. I am running `clangd` from `/Users/max_thrun/projects/repo/` so I would expect the config to apply to any file it processes.

I can solve this problem by using `--query-driver` and removing the `-isystem` from my `.clangd` config but I don't want to have to have my whole team set their `--query-driver`. I was hoping to solve the issue for this repository specifically.

**Comment by sam-mccall** [comment] 2023-01-12 19:39
.clangd files apply to files within their directory scope as documented here: https://clangd.llvm.org/config#files

If you want config to apply to all files, put it in ~/.config/clangd/config.yaml.

Configs checked into a repo can only affect how files in that repo are processed, by design.

**Closed by sam-mccall** 2023-01-12 19:39 UTC
