### ISSUE TITLE
Support renaming virtual methods

### ISSUE THREAD

**Issue by tom-anders** [clangd/clangd#1051] opened 2022-03-11 12:16 UTC
There's already a FIXME for this in Rename.cpp:218 that claims the index doesn't have the required information for this feature. However, I think this might be outdated, since clangd supports "textDocument/implementation" which actually is able to find overrides of virtual methods.

**Comment by HighCommander4** [comment] 2022-03-11 19:33
Dupe of #706

**Closed by HighCommander4** 2022-03-11 19:33 UTC
Labels: enhancement

**Comment by tom-anders** [comment] 2022-03-11 20:10
Ah I actually used the search function but must have overlooked it, sorry!
