### ISSUE TITLE
Can't clangd in cmake (already enabled export compile command) work out of the box?

### ISSUE THREAD

**Issue by K1ngst0m** [clangd/clangd#1114] opened 2022-04-19 12:09 UTC
### Discussed in https://github.com/clangd/clangd/discussions/1113

<div type='discussions-op-text'>

<sup>Originally posted by **K1ngst0m** April 19, 2022</sup>
In my emacs, I use `lsp-emacs`  + `clangd`, there are so many clangd error outputs but it can compile success, there's also happened in other projects. And when I use clion with clangd these errors are just gone and the syntax check outputs are the same as compiler compilation output. 

These are my operations when I get starting with a project: 
`cmake -B build -DCMAKE_EXPORT_COMPILE_COMMAND=YES -DCMAKE_BUILD_TYPE=Debug && ln -s build/compile_command.json .`. 

Are there any operations and configurations I missed?

|[clion] clangd configuration|[emacs] lsp error outputs with clangd backend|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/34272057/163998431-346dc7c3-ed2e-4932-ae4c-93fc30f5b6c7.png)|![image](https://user-images.githubusercontent.com/34272057/163998458-9e496efc-d13d-4421-88e7-d16155cb70ac.png)|

Here are my clangd-related configurations, the error still produces whether these configurations exist or not.
|clangd arguments|clangd/config.yaml|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/34272057/163999659-6b39dc73-3d59-44eb-9ff5-2629b026f8f1.png)|![image](https://user-images.githubusercontent.com/34272057/163999680-19f0464d-eeab-4cf3-8581-e44c0c9381fc.png)|

</div>

**Comment by HighCommander4** [comment] 2022-04-20 02:13
Dupe of #1113 (there is no need to have both a discussion and an issue)

**Closed by HighCommander4** 2022-04-20 02:13 UTC
