### ISSUE TITLE
clangd do not recognise headers located in pch

### ISSUE THREAD

**Issue by dylsonowski** [clangd/clangd#2034] opened 2024-05-10 13:05 UTC
Please describe the problem.
I try to create project with build system Premake5 and clangd as an alternative to Intellisence. I'm using gcc compiler. I was able to generate **compile_commands.json** and clangd was able to load it. The problem is that I use precompiled headers in my project and clangd highlights all components from std library as errors.

![image](https://github.com/clangd/clangd/assets/32763547/e06d92c0-db5c-47ec-bc4c-2b4f4ae81766)

I'm also attaching link to my repository to let you check my configuration https://github.com/dylsonowski/AI-Playground. Can someone tell me what I'm doing wrong?

**Logs**

[clangd-logs.json](https://github.com/clangd/clangd/files/15275379/clangd-logs.json)

**System information**

`clangd version 17.0.2
Features: windows
Platform: x86_64-pc-windows-msvc`

Operating system: Windows 10

**Comment by HighCommander4** [comment] 2024-05-11 07:39
The issue is not related to the use of PCH. Clangd basically ignores that (it has its own optimization similar to PCH called preambles which it uses by default).

Rather, the issue is that the file shown in the screenshot, `Expect.hpp` is not self-contained (it does not include any header that declares the `std` symbols is uses). Clangd does not support opening files which are not self-contained, as discussed in https://github.com/clangd/clangd/issues/45.

A workaround would be to include `palepch.hpp` from `Expect.hpp`.

**Comment by HighCommander4** [comment] 2024-05-11 07:39
Duplicate of #45

**Closed by HighCommander4** 2024-05-11 07:39 UTC
