### ISSUE TITLE
Support for folding code surround by region and endregion 

### ISSUE THREAD

**Issue by c0nstexpr** [clangd/clangd#1911] opened 2024-01-17 09:29 UTC
Using MS cpp extension, code surround by `#pragma region` and `#pragma endregion` could be folded in editor.
![image](https://github.com/clangd/vscode-clangd/assets/38137746/8f03bcce-5c1e-4861-b32c-b8aa6047ac7f)
And Clang also is able [recognize](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAKxAEZSAbAQwDtRkBSAJgCFufSAZ1QBXYskwgA5NwDMAB2JNgAWyYBqYpmB5ULdcJWZ1aLBwAMAQQuWA9LYOojJjMYSYtNr1wVLVGzBZ0LR09KQBKRmkAVilSFmlzONRpAGF%2BfkcxCXU5WjiCRIjIgGsQWVkAOgqa2rqANiipABY4hKkk0hSpOMEQc1JCjojSOFgYRBQneTwGD3JKNBUZueIQYEEWJnlBBFQCUgAzWYIPPogAIyLSC7wt4gBPaXzSJaMWAgB5FgYn4dIsGo2HNrvgtMgCHgAG6YPr/TAAD0wyBEp2ecTupwY1wIxDwKiKkWYbBQGV4jDwFz6kEiqHkkL0cIAtAB1JgMBi9UTiSS0IkxNrXboIgAc9SZ9Wa6mAyGQ6gguJELBK4XluEIJFyPno6lS01mHi1sj5urJPAKhMi7iYWDWEFKIGiA2xLTiBNoIsqAE5ZNERbIAOxcZrRepeyXxIXSXr9QaE0YTCBIUQEeSohYQJYrDx0UiYfBENb0ADuSnk6P5Ulikf%2B3Ty6mLhAQ6lF4sl0tl8sVyvCFuG4StmBtOftTVapAJItolXMkto9S4AeizVk5lkjXanW6MYGQySA9IZQq1Tqp4qjRdskFtejcf7CfgY0mWYNZAomf1qxQxOAAH1uyURwnGclBXP8tz3H8LxvIEXw/H8nSAqwwAgv8YLIpCMJwp0iLIqikhSC8mKYC6nS4vi8Y/qSvD8BSVLwLS9K6CwzJshyXLZLylbVpuyTSK2EpSsgP5dsQSoqmqBaankpC6p%2BhpyFwqrpDRvB9vuDrHmeZ5jm6dBejOtDNOYIohuYAbmM0XBcKGNZbrefS7vGT5JiAKZpgc74vl%2BXB5lJRakKW2wVk0PFRjIPhcA2TYtmKgkmCJCpiT26nFKQ1q2pQlbjpO5jeiK0RerQy5elwXrRAGAYbuFO53hph7lFU2mnk0V52XxPR1WlLpcNe9mdXuaUwsQgjMSAzRAA%3D%3D%3D) those directives.

**Comment by HighCommander4** [comment] 2024-01-17 18:17
Moved to server repository as this would be a server-side feature.

**Comment by HighCommander4** [comment] 2024-01-17 18:17
Actually, it looks like we already have https://github.com/clangd/clangd/issues/1623 on file for it

**Comment by HighCommander4** [comment] 2024-01-17 18:18
Duplicate of https://github.com/clangd/clangd/issues/1623

**Closed by HighCommander4** 2024-01-17 18:18 UTC
Labels: enhancement
