### ISSUE TITLE
Code completion does not display macros defined in the current file

### ISSUE THREAD

**Issue by lh123** [clangd/clangd#28] opened 2019-04-11 04:26 UTC
* version: r357435
* OS: Win10

**1. Code completion does not display macros defined in the current file.**
![image](https://user-images.githubusercontent.com/10697249/55930655-e9bd0d00-5c54-11e9-89e7-6d627c3bf489.png)

**2.Code completion does not display macro documents.**
test.h
```c
#ifndef __TEST_H
#define __TEST_H

// Doc1
#define DOC1_TEST 10
#define DOC2_TEST 10 // Doc2

#endif
```
test.c
![image](https://user-images.githubusercontent.com/10697249/55930807-95665d00-5c55-11e9-9a93-f7c0afc613ef.png)
![image](https://user-images.githubusercontent.com/10697249/55930922-14f42c00-5c56-11e9-9f39-420d54c2bf42.png)

**Comment by sam-mccall** [comment] 2019-04-11 12:12
Ah, this one fell through the cracks. It's important that the `#define` is part of the preamble (the initial block of preprocessor directives). Add `int x;` to the top of the file and everything works again.

The problem is we assumed that "in the preamble" was the same thing as "not in the main file", and so we don't index symbols in the main file. This assumption is true for decls, but not for macros.

**Comment by lh123** [comment] 2019-04-11 13:54
> Ah, this one fell through the cracks. It's important that the #define is part of the preamble (the initial block of preprocessor directives). Add int x; to the top of the file and everything works again.

Yes, add int x; to the top of the file and everything is back to normal. But the macro's document still doesn't show in codecomplete.
![image](https://user-images.githubusercontent.com/10697249/55962744-151b1880-5ca4-11e9-8dc9-1f5f1f4cf523.png)
![image](https://user-images.githubusercontent.com/10697249/55962773-206e4400-5ca4-11e9-9006-bc035c41cb6b.png)

**Comment by sam-mccall** [comment] 2019-04-18 14:18
This is a bit hairy:
 - we see the macros when indexing the preamble, but we don't actually want the macros in the index: that would make them complete while in other files.
 - we don't see the macros when indexing the main file, because the lexer starts after the preamble region

I see two main options:
 - when building the preamble, record the macros and store them alongside the preamble
 - when code completing, preprocess the preamble region in single-file mode to get the macros
In either case, we then need to overlay the result onto the index.
The first option is more correct - single-file mode doesn't follow includes and therefore isn't accurate. But the first option probably involves some layering violations or code duplication (if the preamble-building code needs to run SymbolCollector), and certainly involves more plumbing.

Macro doc I'm not sure about - I forget exactly how we extract doc comments, will have a look into that if it persists after the main issue is fixed.

**Comment by sam-mccall** [comment] 2019-04-18 18:44
On further reflection, clearly the preamble contains the macros, the question is whether we can get them out efficiently.

`ASTReader::ReadDefinedMacros` is responsible for decoding.
The preprocessor block appears to be very small: it's 0.8%, or roughly 300kB in a 45M LLVM preamble. 
As far as I can see, it contains macro identifiers (`PP_MACRO_FUNCTION_LIKE`, `PP_MACRO_OBJECT_LIKE`), macro definition sites (`PP_MACRO_DIRECTIVE_HISTORY`), and a little bit of stuff we don't need. So far so good.

Unfortunately it looks like the path from identifier -> definition site goes through the name lookup table that's used for all identifiers, and deserializing anything that matches! I'll need to measure if this is expensive.

**Comment by sam-mccall** [comment] 2019-04-20 17:19
Finally have an approach here that seems okayish...
https://reviews.llvm.org/D60937

**Comment by sam-mccall** [comment] 2019-05-02 22:48
Fixed in r359799.
Thanks for reporting!

**Closed by sam-mccall** 2019-05-02 22:48 UTC
Labels: bug
