### ISSUE TITLE
Show potential parameter candidates in functions using "perfect forwarding"

### ISSUE THREAD

**Issue by upsj** [clangd/clangd#517] opened 2020-09-04 14:16 UTC
Functions like std::make_shared that use universal references on variadic template arguments to forward parameters to other functions like constructors are currently (clangd 10, or did anything change since then?) only shown with their own signature 
![Screenshot from 2020-09-04 16-10-47](https://user-images.githubusercontent.com/1693511/92248651-4adc2500-eec9-11ea-861a-6fed475e9798.png)
Would it be possible in this example to replace make_shared(Args&&...) by make_shared with all parameter combinations from std::pair<int, int> constructors?
I saw this feature in CLion and believe this could greatly benefit development in template-heavy code.
If somebody can point me in the right direction, I would also be interested in implementing this myself, but I only have a limited knowledge of LLVM so far.

**Comment by HighCommander4** [comment] 2020-09-05 05:49
Dupe of #447.

**Closed by HighCommander4** 2020-09-05 05:49 UTC
Labels: enhancement
