### ISSUE TITLE
Find references does not work in templates and lambdas with auto

### ISSUE THREAD

**Issue by fedorbirjukov** [clangd/clangd#1628] opened 2023-05-09 15:20 UTC
I think that's the same problem as:
- #258: Find referenes in dependent contexts
- #399: can't find reference nested in template
- #675: find-refs missing references from dependent node

I am opening this because all of the above issues co-exist and because closing #675 did not fix the issue in main (tried the 20230507 pre-release version).

Here is a code snippet that only requires VS Code with ClangD extension, nothing else:

```
struct Circle {
    void draw() {}
};

struct Rectangle {
    void draw() {}
};

struct Lambda 
{
    template <typename T>
    auto operator()(T &c) const{
        c.draw(); // find references never finds this line while go to definition finds both draw() functions correctly
    }
};

int main() {
    auto l = [](auto &c) {
       c.draw(); // find references never finds this line while go to definition finds both draw() functions correctly
    };
    
    Circle c;
    c.draw();
    l(c);

    Rectangle r;
    l(r);
    
    auto l2 = Lambda{};
    l2(r);
    
    return 0;
}

```

**System information**

Output of `clangd --version`:
```
clangd version 16.0.0
Features: windows
Platform: x86_64-pc-windows-msvc
```

Editor/LSP plugin: VS Code 1.77.3 with ClangD extension 0.1.24

Operating system: Windows Server 2022 Datacenter

**Comment by HighCommander4** [comment] 2023-05-11 08:14
#675 solved a fairly narrow subset of this problem: cases where name lookup of a function can be performed prior to instantiation, and it's only the arguments which are dependent on a template parameter. In such cases, clangd makes find-references work without ever instantiating the template, by considering every overload of the looked-up function a potential result.

#399 is a duplicate of #675 (though it was filed earlier), I just closed it.

This is a duplicate of #258, which tracks the more general version of the problem. In cases like this, there is no way for clangd to find the reference by only analyzing the un-instantiated body of the template, it needs to analyze the instantiations (which then has larger implications on the performance of indexing).

I'm going to close this, if you have any follow-up thoughts please post them to #258.

**Closed by HighCommander4** 2023-05-11 08:14 UTC

**Comment by HighCommander4** [comment] 2023-05-11 08:18
Oh, let me add why go-to-definition works: it uses a purely textual heuristic (added in #241).

If you add a class like this:

```c++
struct CompletelyUnrelated {
  void draw();
};
```

now go-to-def will, based on the textual heuristic, offer the `draw()` method of this class too, even though the template is never instantiated with this type.
