### ISSUE TITLE
Crash (assertion in RemoveNestedImmediateInvocation) while building AST

### ISSUE THREAD

**Issue by PowellNGL** [clangd/clangd#1311] opened 2022-09-27 15:00 UTC
Clangd crashes when parsing the source file in the attached project. This is just about the smallest project I've been able to make that still exhibits the problem

**Reproduction steps**
1. Extract the project at [clangd_crash.tar.gz](https://github.com/clangd/clangd/files/9657178/clangd_crash.tar.gz) and change the hardcoded directory in build/compile_commands.json to the project's top-level directory
2. Run `clangd --check=src/bad_file.cpp` in the project folder

**Verbose log**
```
I[16:45:23.813] clangd version 15.0.1
I[16:45:23.813] Features: linux
I[16:45:23.813] PID: 5152
I[16:45:23.813] Working directory: /home/nick/clangd_crash
I[16:45:23.813] argv[0]: /opt/llvm-15.0/bin/clangd
I[16:45:23.813] argv[1]: --check=src/bad_file.cpp
I[16:45:23.813] argv[2]: --log=verbose
V[16:45:23.813] User config file is /home/nick/.config/clangd/config.yaml
I[16:45:23.813] Entering check mode (no LSP server)
I[16:45:23.813] Testing on source file /home/nick/clangd_crash/src/bad_file.cpp
I[16:45:23.813] Loading compilation database...
I[16:45:23.813] Loaded compilation database from /home/nick/clangd_crash/build/compile_commands.json
V[16:45:23.813] Broadcasting compilation database from /home/nick/clangd_crash
I[16:45:23.814] Compile command from CDB is: /opt/gcc-11.2.0/bin/g++ --driver-mode=g++ -DBOOST_ALL_NO_LIB -DSPDLOG_FMT_EXTERNAL -Iinclude -g -ggdb -gdwarf-4 -Wall -Wpedantic -Wextra -std=gnu++2a -o build/bad_file.cpp.o -c -resource-dir=/opt/llvm-15.0/lib/clang/15.0.1 -- /home/nick/clangd_crash/src/bad_file.cpp
I[16:45:23.814] Parsing command...
I[16:45:23.816] internal (cc1) args are: -cc1 -triple x86_64-unknown-linux-gnu -fsyntax-only -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name bad_file.cpp -mrelocation-model pic -pic-level 2 -pic-is-pie -mframe-pointer=all -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu x86-64 -tune-cpu generic -mllvm -treat-scalable-fixed-error-as-warning -debug-info-kind=constructor -dwarf-version=4 -debugger-tuning=gdb -fcoverage-compilation-dir=/home/nick/clangd_crash -resource-dir /opt/llvm-15.0/lib/clang/15.0.1 -D BOOST_ALL_NO_LIB -D SPDLOG_FMT_EXTERNAL -I include -internal-isystem /opt/gcc-11.2.0/bin/../lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../include/c++/11.2.0 -internal-isystem /opt/gcc-11.2.0/bin/../lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../include/c++/11.2.0/x86_64-pc-linux-gnu -internal-isystem /opt/gcc-11.2.0/bin/../lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../include/c++/11.2.0/backward -internal-isystem /opt/llvm-15.0/lib/clang/15.0.1/include -internal-isystem /usr/local/include -internal-isystem /opt/gcc-11.2.0/bin/../lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../x86_64-pc-linux-gnu/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -Wall -Wpedantic -Wextra -std=gnu++2a -fdeprecated-macro -fdebug-compilation-dir=/home/nick/clangd_crash -ferror-limit 19 -fgnuc-version=4.2.1 -fcxx-exceptions -fexceptions -no-round-trip-args -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -x c++ /home/nick/clangd_crash/src/bad_file.cpp
I[16:45:23.816] Building preamble...
I[16:45:26.014] Indexing headers...
V[16:45:26.371] indexed preamble AST for /home/nick/clangd_crash/src/bad_file.cpp version null:
  symbol slab: 25888 symbols, 7341432 bytes
  ref slab: 0 symbols, 0 refs, 128 bytes
  relations slab: 1359 relations, 34840 bytes
V[16:45:26.547] Build dynamic index for header symbols with estimated memory usage of 16991688 bytes
V[16:45:26.584] Built preamble of size 26973300 for file /home/nick/clangd_crash/src/bad_file.cpp version null in 2.77 seconds
I[16:45:26.586] Building AST...
 #0 0x000000000053e471 PrintStackTraceSignalHandler(void*) Signals.cpp:0:0
 #1 0x000000000053c464 SignalHandler(int) Signals.cpp:0:0
 #2 0x00007f6409697630 __restore_rt sigaction.c:0:0
 #3 0x00000000006cc0c5 clang::StmtVisitorBase<llvm::make_const_ptr, (anonymous namespace)::RecordExprEvaluator, bool>::Visit(clang::Stmt const*) ExprConstant.cpp:0:0
 #4 0x00000000006bffef EvaluateInPlace(clang::APValue&, (anonymous namespace)::EvalInfo&, (anonymous namespace)::LValue const&, clang::Expr const*, bool) ExprConstant.cpp:0:0
 #5 0x00000000006e0232 clang::Expr::EvaluateAsConstantExpr(clang::Expr::EvalResult&, clang::ASTContext const&, clang::Expr::ConstantExprKind) const (/opt/llvm-15.0/bin/clangd+0x6e0232)
 #6 0x00000000010d8c9a clang::Sema::PopExpressionEvaluationContext() (/opt/llvm-15.0/bin/clangd+0x10d8c9a)
 #7 0x0000000000f44838 clang::Sema::ActOnFinishFunctionBody(clang::Decl*, clang::Stmt*, bool) (/opt/llvm-15.0/bin/clangd+0xf44838)
 #8 0x0000000002111555 clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) (/opt/llvm-15.0/bin/clangd+0x2111555)
 #9 0x000000000204a98e clang::Parser::ParseFunctionDefinition(clang::ParsingDeclarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::LateParsedAttrList*) (/opt/llvm-15.0/bin/clangd+0x204a98e)
#10 0x00000000020762e2 clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::ParsedAttributes&, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/opt/llvm-15.0/bin/clangd+0x20762e2)
#11 0x00000000020465b0 clang::Parser::ParseDeclarationOrFunctionDefinition(clang::ParsedAttributes&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (.part.0) Parser.cpp:0:0
#12 0x000000000204d293 clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsingDeclSpec*) (/opt/llvm-15.0/bin/clangd+0x204d293)
#13 0x000000000208d12f clang::Parser::ParseInnerNamespace(llvm::SmallVector<clang::Parser::InnerNamespaceInfo, 4u> const&, unsigned int, clang::SourceLocation&, clang::ParsedAttributes&, clang::BalancedDelimiterTracker&) (/opt/llvm-15.0/bin/clangd+0x208d12f)
#14 0x0000000002092448 clang::Parser::ParseNamespace(clang::DeclaratorContext, clang::SourceLocation&, clang::SourceLocation) (/opt/llvm-15.0/bin/clangd+0x2092448)
#15 0x0000000002078837 clang::Parser::ParseDeclaration(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributes&, clang::ParsedAttributes&, clang::SourceLocation*) (/opt/llvm-15.0/bin/clangd+0x2078837)
#16 0x000000000204cace clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsingDeclSpec*) (/opt/llvm-15.0/bin/clangd+0x204cace)
#17 0x000000000204e2c8 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/opt/llvm-15.0/bin/clangd+0x204e2c8)
#18 0x000000000204e720 clang::Parser::ParseFirstTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/opt/llvm-15.0/bin/clangd+0x204e720)
#19 0x00000000020401d2 clang::ParseAST(clang::Sema&, bool, bool) (/opt/llvm-15.0/bin/clangd+0x20401d2)
#20 0x0000000001e44d49 clang::FrontendAction::Execute() (/opt/llvm-15.0/bin/clangd+0x1e44d49)
#21 0x00000000015dde9a clang::clangd::ParsedAST::build(llvm::StringRef, clang::clangd::ParseInputs const&, std::unique_ptr<clang::CompilerInvocation, std::default_delete<clang::CompilerInvocation>>, llvm::ArrayRef<clang::clangd::Diag>, std::shared_ptr<clang::clangd::PreambleData const>) (/opt/llvm-15.0/bin/clangd+0x15dde9a)
#22 0x0000000000445bb0 clang::clangd::check(llvm::StringRef, llvm::Optional<clang::clangd::Range>, clang::clangd::ThreadsafeFS const&, clang::clangd::ClangdLSPServer::Options const&, bool) (/opt/llvm-15.0/bin/clangd+0x445bb0)
#23 0x000000000042257e main (/opt/llvm-15.0/bin/clangd+0x42257e)
#24 0x00007f6408170555 __libc_start_main (/lib64/libc.so.6+0x22555)
#25 0x000000000042bcfe _start (/opt/llvm-15.0/bin/clangd+0x42bcfe)
```

**Output of `clangd --version`:**
 /opt/llvm-15.0/bin/clangd --version
clangd version 15.0.1
Features: linux
Platform: x86_64-unknown-linux-gnu

**Operating system:**
Oracle Linux Server 7.9

**Comment by HighCommander4** [comment] 2022-09-28 00:08
Unfortunately, I don't think the testcase packaged this way is portable. I get:

```
$ clangd-15 --check=src/bad_file.cpp
I[14:06:09.913] Debian clangd version 15.0.2-++20220926063016+451e3b68306d-1~exp1~20220926063109.67
I[14:06:09.913] Features: linux+grpc
I[14:06:09.913] PID: 57759
I[14:06:09.913] Working directory: /home/nr/temp/clangd-debugging/issue-1311/clangd_crash
I[14:06:09.913] argv[0]: clangd-15
I[14:06:09.913] argv[1]: --check=src/bad_file.cpp
I[14:06:09.913] Entering check mode (no LSP server)
I[14:06:09.913] Testing on source file /home/nr/temp/clangd-debugging/issue-1311/clangd_crash/src/bad_file.cpp
I[14:06:09.913] Loading compilation database...
I[14:06:09.913] Loaded compilation database from /home/nr/temp/clangd-debugging/issue-1311/clangd_crash/build/compile_commands.json
I[14:06:09.914] Compile command from CDB is: /opt/gcc-11.2.0/bin/g++ --driver-mode=g++ -DBOOST_ALL_NO_LIB -DSPDLOG_FMT_EXTERNAL -Iinclude -g -ggdb -gdwarf-4 -Wall -Wpedantic -Wextra -std=gnu++2a -o build/bad_file.cpp.o -c -resource-dir=/usr/lib/llvm-15/lib/clang/15.0.2 -- /home/nr/temp/clangd-debugging/issue-1311/clangd_crash/src/bad_file.cpp
I[14:06:09.914] Parsing command...
I[14:06:09.915] internal (cc1) args are: -cc1 -triple x86_64-pc-linux-gnu -fsyntax-only -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name bad_file.cpp -mrelocation-model pic -pic-level 2 -pic-is-pie -mframe-pointer=all -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu x86-64 -tune-cpu generic -mllvm -treat-scalable-fixed-error-as-warning -debug-info-kind=constructor -dwarf-version=4 -debugger-tuning=gdb -fcoverage-compilation-dir=/home/nr/temp/clangd-debugging/issue-1311/clangd_crash -resource-dir /usr/lib/llvm-15/lib/clang/15.0.2 -D BOOST_ALL_NO_LIB -D SPDLOG_FMT_EXTERNAL -I include -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/10/../../../../include/x86_64-linux-gnu/c++/10 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/backward -internal-isystem /usr/lib/llvm-15/lib/clang/15.0.2/include -internal-isystem /usr/local/include -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/10/../../../../x86_64-linux-gnu/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -Wall -Wpedantic -Wextra -std=gnu++2a -fdeprecated-macro -fdebug-compilation-dir=/home/nr/temp/clangd-debugging/issue-1311/clangd_crash -ferror-limit 19 -fgnuc-version=4.2.1 -fcxx-exceptions -fexceptions -no-round-trip-args -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -x c++ /home/nr/temp/clangd-debugging/issue-1311/clangd_crash/src/bad_file.cpp
I[14:06:09.915] Building preamble...
I[14:06:11.092] Indexing headers...
E[14:06:11.422] [pp_file_not_found] Line 2: in included file: 'boost/core/cmath.hpp' file not found
I[14:06:11.422] Building AST...
E[14:06:11.476] [undeclared_var_use] Line 19: use of undeclared identifier 'NewOrder'
E[14:06:11.476] [unknown_typename] Line 48: unknown type name 'NewOrder'
E[14:06:11.476] [undeclared_var_use] Line 50: use of undeclared identifier 'transaction'
E[14:06:11.476] [undeclared_var_use] Line 64: use of undeclared identifier 'args'
E[14:06:11.476] [static_assert_requirement_failed] Line 68: in template: static assertion failed due to requirement '__is_duration<int>::value': duration must be a specialization of std::chrono::duration
E[14:06:11.476] [ovl_no_viable_member_function_in_call] Line 68: no matching member function for call to 'log'
E[14:06:11.476] [ovl_no_viable_member_function_in_call] Line 70: no matching member function for call to 'log'
E[14:06:11.476] [undeclared_var_use] Line 71: use of undeclared identifier 'send'
E[14:06:11.476] [undeclared_var_use] Line 74: use of undeclared identifier 'args'
E[14:06:11.476] [undeclared_var_use] Line 76: use of undeclared identifier 'args'
E[14:06:11.476] [undeclared_var_use] Line 81: use of undeclared identifier 'args'
E[14:06:11.476] [undeclared_var_use] Line 82: use of undeclared identifier 'args'
E[14:06:11.476] [undeclared_var_use] Line 87: use of undeclared identifier 'args'
E[14:06:11.476] [undeclared_var_use] Line 88: use of undeclared identifier 'args'
E[14:06:11.476] [undeclared_var_use] Line 89: use of undeclared identifier 'args'
E[14:06:11.476] [undeclared_var_use] Line 90: use of undeclared identifier 'args'
E[14:06:11.476] [undeclared_var_use] Line 91: use of undeclared identifier 'args'
E[14:06:11.476] [undeclared_var_use] Line 92: use of undeclared identifier 'args'
E[14:06:11.476] [undeclared_var_use] Line 93: use of undeclared identifier 'args'
E[14:06:11.476] [fatal_too_many_errors] Line 1: too many errors emitted, stopping now
I[14:06:11.476] Indexing AST...
I[14:06:11.477] Building inlay hints
I[14:06:11.477] Testing features at each token (may be slow in large files)
I[14:06:11.481] Found definition heuristically in index for std
I[14:06:11.481] Found definition heuristically in index for std
I[14:06:11.481] Found definition heuristically in index for runtime_error
I[14:06:11.482] Found definition heuristically in index for runtime_error
I[14:06:11.482] Found definition heuristically in index for fmt
I[14:06:11.482] Found definition heuristically in index for fmt
E[14:06:11.512]     tweak: ExpandAutoType ==> FAIL: Could not deduce type for 'auto' type
I[14:06:11.523] Found definition heuristically in index for OrderId
I[14:06:11.586] All checks completed, 22 errors
```

because `include/boost/lexical_cast/detail/inf_nan.hpp` contains `#include <boost/core/cmath.hpp>` but this header is not included in the zip.

**Comment by HighCommander4** [comment] 2022-09-28 00:13
I tried to get past this by installing some boost packages, but I'm not sure which package provides `<boost/core/cmath.hpp>` (I tried `libboost-dev` and `libboost-math-dev` and neither contained it), and in any case I suspect that mixing boost headers from your zip with others installed on my system is likely to cause other issues.

**Comment by HighCommander4** [comment] 2022-09-28 00:24
Ah it's because `<boost/core/cmath.hpp>` was added in boost 1.78, but my package manager only provides packages for boost 1.76.

**Comment by PowellNGL** [comment] 2022-09-28 00:33
Ah, that's my mistake. I removed as many boost headers as I could and checked that I could still reproduce it but it must have actually been falling back to my system boost install. I can upload an updated archive tomorrow

**Comment by HighCommander4** [comment] 2022-09-28 01:48
Reproduced in clangd 15 by installing boost 1.80 locally.

Seems to be fixed on trunk. (I do still get diagnostics like `Use of undeclared identifier 'NewOrder'`, but that looks like a legitimate diagnostic (i.e. the input is an invalid source file) rather than a configuration problem involving missing files.)

**Comment by HighCommander4** [comment] 2022-09-28 01:51
It would be nice to find the commit that fixed it so we can consider it for backport to the 15.x branch.

**Comment by HighCommander4** [comment] 2022-09-28 01:53
Here's a symbolicated stack trace for the record:

```
clangd-dev: llvm/src/clang/lib/Sema/SemaExpr.cpp:17622: void RemoveNestedImmediateInvocation(clang::Sema &, Sema::ExpressionEvaluationContextRecord &, SmallVector<Sema::ImmediateInvocationCandidate, 4>::reverse_iterator): Assertion `Res.isUsable()' failed.
 #0 0x00007f5b6193ce1a llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) llvm/src/llvm/lib/Support/Unix/Signals.inc:569:11
 #1 0x00007f5b6193cfeb PrintStackTraceSignalHandler(void*) llvm/src/llvm/lib/Support/Unix/Signals.inc:636:1
 #2 0x00007f5b6193b55b llvm::sys::RunSignalHandlers() llvm/src/llvm/lib/Support/Signals.cpp:102:5
 #3 0x00007f5b6193d761 SignalHandler(int) llvm/src/llvm/lib/Support/Unix/Signals.inc:407:1
 #4 0x00007f5b681ce140 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x13140)
 #5 0x00007f5b610edce1 raise (/lib/x86_64-linux-gnu/libc.so.6+0x38ce1)
 #6 0x00007f5b610d7537 abort (/lib/x86_64-linux-gnu/libc.so.6+0x22537)
 #7 0x00007f5b610d740f (/lib/x86_64-linux-gnu/libc.so.6+0x2240f)
 #8 0x00007f5b610e6662 (/lib/x86_64-linux-gnu/libc.so.6+0x31662)
 #9 0x00007f5b64694ea4 RemoveNestedImmediateInvocation(clang::Sema&, clang::Sema::ExpressionEvaluationContextRecord&, std::reverse_iterator<llvm::PointerIntPair<clang::ConstantExpr*, 1u, unsigned int, llvm::PointerLikeTypeTraits<clang::ConstantExpr*>, llvm::PointerIntPairInfo<clang::ConstantExpr*, 1u, llvm::PointerLikeTypeTraits<clang::ConstantExpr*>>>*>) llvm/src/clang/lib/Sema/SemaExpr.cpp:17623:9
#10 0x00007f5b646801a7 HandleImmediateInvocations(clang::Sema&, clang::Sema::ExpressionEvaluationContextRecord&) llvm/src/clang/lib/Sema/SemaExpr.cpp:17650:23
#11 0x00007f5b64677bd3 clang::Sema::PopExpressionEvaluationContext() llvm/src/clang/lib/Sema/SemaExpr.cpp:17716:19
#12 0x00007f5b643396ea ExitFunctionBodyRAII::~ExitFunctionBodyRAII() llvm/src/clang/lib/Sema/SemaDecl.cpp:15039:3
#13 0x00007f5b64307e6c clang::Sema::ActOnFinishFunctionBody(clang::Decl*, clang::Stmt*, bool) llvm/src/clang/lib/Sema/SemaDecl.cpp:15462:3
#14 0x00007f5b64306067 clang::Sema::ActOnFinishFunctionBody(clang::Decl*, clang::Stmt*) llvm/src/clang/lib/Sema/SemaDecl.cpp:15028:3
#15 0x00007f5b5e9147aa clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) llvm/src/clang/lib/Parse/ParseStmt.cpp:2452:1
#16 0x00007f5b5e93e4c2 clang::Parser::ParseFunctionDefinition(clang::ParsingDeclarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::LateParsedAttrList*) llvm/src/clang/lib/Parse/Parser.cpp:1428:3
#17 0x00007f5b5e805657 clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::ParsedAttributes&, clang::SourceLocation*, clang::Parser::ForRangeInit*) llvm/src/clang/lib/Parse/ParseDecl.cpp:2117:27
#18 0x00007f5b5e93d2ae clang::Parser::ParseDeclOrFunctionDefInternal(clang::ParsedAttributes&, clang::ParsingDeclSpec&, clang::AccessSpecifier) llvm/src/clang/lib/Parse/Parser.cpp:1179:10
#19 0x00007f5b5e93c810 clang::Parser::ParseDeclarationOrFunctionDefinition(clang::ParsedAttributes&, clang::ParsingDeclSpec*, clang::AccessSpecifier) llvm/src/clang/lib/Parse/Parser.cpp:1193:12
#20 0x00007f5b5e93c09a clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsingDeclSpec*) llvm/src/clang/lib/Parse/Parser.cpp:1019:12
#21 0x00007f5b5e834516 clang::Parser::ParseInnerNamespace(llvm::SmallVector<clang::Parser::InnerNamespaceInfo, 4u> const&, unsigned int, clang::SourceLocation&, clang::ParsedAttributes&, clang::BalancedDelimiterTracker&) llvm/src/clang/lib/Parse/ParseDeclCXX.cpp:259:7
#22 0x00007f5b5e833e4c clang::Parser::ParseNamespace(clang::DeclaratorContext, clang::SourceLocation&, clang::SourceLocation) llvm/src/clang/lib/Parse/ParseDeclCXX.cpp:240:18
#23 0x00007f5b5e7ff515 clang::Parser::ParseDeclaration(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributes&, clang::ParsedAttributes&, clang::SourceLocation*) llvm/src/clang/lib/Parse/ParseDecl.cpp:1793:12
#24 0x00007f5b5e93bb3e clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsingDeclSpec*) llvm/src/clang/lib/Parse/Parser.cpp:946:14
#25 0x00007f5b5e939de5 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) llvm/src/clang/lib/Parse/Parser.cpp:737:12
#26 0x00007f5b5e939480 clang::Parser::ParseFirstTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) llvm/src/clang/lib/Parse/Parser.cpp:591:8
#27 0x00007f5b5e7de037 clang::ParseAST(clang::Sema&, bool, bool) llvm/src/clang/lib/Parse/ParseAST.cpp:161:15
#28 0x00007f5b65d2f412 clang::ASTFrontendAction::ExecuteAction() llvm/src/clang/lib/Frontend/FrontendAction.cpp:1154:1
#29 0x00007f5b65d2edd8 clang::FrontendAction::Execute() llvm/src/clang/lib/Frontend/FrontendAction.cpp:1049:7
#30 0x00007f5b670a35af clang::clangd::ParsedAST::build(llvm::StringRef, clang::clangd::ParseInputs const&, std::unique_ptr<clang::CompilerInvocation, std::default_delete<clang::CompilerInvocation>>, llvm::ArrayRef<clang::clangd::Diag>, std::shared_ptr<clang::clangd::PreambleData const>) llvm/src/clang-tools-extra/clangd/ParsedAST.cpp:623:19
#31 0x00000000007e4270 clang::clangd::(anonymous namespace)::Checker::buildAST() llvm/src/clang-tools-extra/clangd/tool/Check.cpp:182:11
#32 0x00000000007e33d7 clang::clangd::check(llvm::StringRef, llvm::Optional<clang::clangd::Range>, clang::clangd::ThreadsafeFS const&, clang::clangd::ClangdLSPServer::Options const&, bool) llvm/src/clang-tools-extra/clangd/tool/Check.cpp:301:7
#33 0x00000000007a720f main llvm/src/clang-tools-extra/clangd/tool/ClangdMain.cpp:1004:12
#34 0x00007f5b610d8d0a __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x23d0a)
#35 0x000000000043f43a _start (llvm/build/bin/clangd+0x43f43a)
Aborted
```

**Comment by HighCommander4** [comment] 2022-09-28 02:36
Actually, my stack trace looks like it may be for a different assertion/crash than yours. Maybe just a different manifestation of the same issue in an assertions-enabled build? Or maybe we're running into different issues because we're ultimately parsing different code (e.g. different boost versions).

**Comment by HighCommander4** [comment] 2022-09-28 02:38
> It would be nice to find the commit that fixed it so we can consider it for backport to the 15.x branch.

Seems like it may be https://reviews.llvm.org/D133948.

**Comment by PowellNGL** [comment] 2022-09-28 08:50
Thanks for investigating this so quickly. I'll use LLVM trunk until the fix is released

**Comment by HighCommander4** [comment] 2024-01-15 02:55
Closing as this has been fixed in clangd 16 as discussed above.

**Closed by HighCommander4** 2024-01-15 02:55 UTC
