### ISSUE TITLE
compile_commands.json with single translation unit

### ISSUE THREAD

**Issue by vkrajacic89** [clangd/clangd#599] opened 2020-11-24 13:10 UTC
Does clangd supports "Unity build" or compiling all source code as a single translation unit? I'm not experienced in using clang, so I might be missing some compiler flag.
So in short, if I manually compile this from command line with `clang Foo.c`, everything is fine. Notice how `Foo.c` includes `Bar.c`. `Bar.c` does not have forward declarations. But I can't get clangd to compile it as a single translation unit. Maybe I misunderstood docs, but I thought that no matter which file I open, clang would compile it with `Foo.c` as the main file and so it would be able to resolve dependencies in `Bar.c`. But looking at the log that doesn't seem to be the case. If I open `Bar.c` clang uses it as the main file, even though it inferred command from `Foo.c`. So it can't find symbols `Foo` and `PrintFoo`.

```
11/24/2020 1:47:11 PM:["<---(stderr)",1,"clangd",["I[13:47:11.165] <-- initialized\r","I[13:47:11.168] <-- textDocument/didOpen\r","I[13:47:11.170] Loaded compilation database from C:\\Users\\Vjekoslav\\Desktop\\Test\r","I[13:47:11.170] Enqueueing 1 commands for indexing\r","I[13:47:11.171] ASTWorker building file C:\\Users\\Vjekoslav\\Desktop\\Test\\Bar.c version 1 with command inferred from Foo.c\r","[C:/Users/Vjekoslav/Desktop/Test]\r","C:\\Program Files\\LLVM\\bin\\clang C:\\Users\\Vjekoslav\\Desktop\\Test\\Bar.c -fsyntax-only -resource-dir=C:\\Users\\Vjekoslav\\Apps\\clangd_11.0.0\\lib\\clang\\11.0.0\r","I[13:47:11.200] --> textDocument/publishDiagnostics\r",""]]
```

Project structure:
```
Test
    - Foo.c
    - Bar.c
    - compile_commands.json
```
Foo.c
```
typedef struct Foo
{
	int value;
} Foo;
void PrintFoo(Foo foo)
{
	// print foo
}
#include "Bar.c"
int main()
{
	return 0;
}
```
Bar.c
```
typedef struct Bar
{
	int value;
} Bar;

void PrintFooBar(Foo foo, Bar bar)
{
	PrintFoo(foo);
	// print bar
}
```

Hand written `compile_commands.json`
```
[
	{ "directory" : "C:/Users/Vjekoslav/Desktop/Test",
	  "command" : "clang Foo.c",
	  "file" : "Foo.c"
	}
]
```

**Logs**
[vim-lsp.log](https://github.com/clangd/clangd/files/5590003/vim-lsp.log)

**System information**
Output of `clangd --version`: clangd version 11.0.0
Editor/LSP plugin: Vim8.2 / [vim-lsp](https://github.com/prabirshrestha/vim-lsp)
Operating system: Windows 10 64-bit

**Comment by HighCommander4** [comment] 2020-11-24 18:49
Based on the discussion [here](https://github.com/clangd/clangd/issues/147#issuecomment-529223278), unity builds are not currently supported by clangd.

Our project also uses a unity build, but for the purpose of generating a `compile_commands.json` for clangd's consumption, we disable it.

**Comment by kadircet** [comment] 2020-11-25 08:28
I think the problem here is more about #45 rather than #147. Long story short, clangd can in theory work with a single entry in your compilation database iff:
- Files you are editing are self-contained, i.e. they can compile on their own. That's not the case with sources in here, Bar.c cannot compile on its own.
- Compile command transference logic can work its magic (#147). e.g. include paths are absolute. Looks like this should be the case, as both Bar.c and Foo.c seem to be in the same directory, so if one can compile with a set of flags the other should also be fine.

I am closing this one as it is a duplicate of #45

**Closed by kadircet** 2020-11-25 08:28 UTC
