### ISSUE TITLE
[Feature Request] Enhance type deduce on Hover.

### ISSUE THREAD

**Issue by lh123** [clangd/clangd#58] opened 2019-06-12 10:02 UTC
## Expected
**1. Hover on decltype**
![1](https://user-images.githubusercontent.com/10697249/59342186-d6edb400-8d3b-11e9-817d-03ffbbd32c1d.png)

**2. Hover on template type**
![2](https://user-images.githubusercontent.com/10697249/59342253-fd135400-8d3b-11e9-99f1-ba73412ea347.png)
![3](https://user-images.githubusercontent.com/10697249/59342286-10beba80-8d3c-11e9-87a9-81374b6ac426.png)

## Current
**1. Hover on decltype**
![4](https://user-images.githubusercontent.com/10697249/59342365-364bc400-8d3c-11e9-81ec-3567d486d562.png)

**2. Hover on template type**
![5](https://user-images.githubusercontent.com/10697249/59342346-2af89880-8d3c-11e9-9082-8c9ec3cad495.png)
![6](https://user-images.githubusercontent.com/10697249/59342554-9e020f00-8d3c-11e9-9b90-74123fd780a3.png)

**Comment by sam-mccall** [comment] 2019-06-12 13:20
Agree with these (though not sure the "expected" behavior is ideal, I think we just need to show both in some cases).

Current implementation is a couple of special cases:
 - hover on a `decltype` or `auto` keyword shows its expansion
 - hover on a reference to an `expr` shows its declaration (mostly as spelled, with initializer)

Showing actual vs spelled types is a tricky tradeoff. Expanding `auto` is usually good (not always possible). Expanding typedefs is iffier.

I think the plan of record is to show both the (expanded) type, and the spelled initializer.

e.g.

---
Variable **a**
Declared in function `main`

Type: `int`
Value: `0`

`TestHover<int>::Type a;`

---

@kadircet similar to adding values of constants, we may have to modify the current approach of "resolve everything to a Decl and then extract", in favor of extracting some info from the `Expr`, `TypeLoc` etc. 

e.g. in the second example here, the typeloc `TestHover<int>::Type` spells a concrete type `int`, where the decl `Type` it resolves to is dependent. So the correct `Type` information can only be extracted at the `TypeLoc` level.

There's probably two stages of heuristic needed: the first one to determine "what's the interesting thing under the cursor (declaration, expression, typeloc, stmt)", and then the second to extract information (e.g. by traversing Expr->DeclRefExpr->Decl. SelectionTree can help with the former I think.

**Comment by bstaletic** [comment] 2019-07-02 16:38
Isn't this basically a duplicate of #36?

**Comment by puremourning** [comment] 2019-07-02 18:49
> Showing actual vs spelled types is a tricky tradeoff. Expanding auto is usually good (not always possible). Expanding typedefs is iffier.

Well, I added the GetType request to ycmd specifically for this use case. Our decision was to always [show both](https://github.com/ycm-core/ycmd/blob/master/cpp/ycm/ClangCompleter/TranslationUnit.cpp#L352) the expanded (canonical) type and the referenced type, [if they differ](https://github.com/ycm-core/ycmd/blob/master/cpp/ycm/ClangCompleter/TranslationUnit.cpp#L377_. This has been used in ycmd for ~4 years without complaint. Not expanding auto to the deduced type is pretty bad, as one of the key things that "modern c++" zealots will tell you is that "your tools can tell you the type if you need to know it". 

From #36, here's the comment explaining the reasoning:

**Comment by kadircet** [comment] 2020-01-15 17:24
there have been some changes to hover, the current state is:
- prefer the type as written
- print the canonical type when the type is not spelled in the source code(auto, decltype)
- use template instantiations rather than patterns, so we display `using Type = int` not `T`.
- don't provide underlying type for decltypes and type aliases(except the one in definition line)
- provide underlying canonical type for auto

**Comment by Trass3r** [comment] 2020-07-20 14:46
Can't clang's [implementation](https://clang.llvm.org/diagnostics.html) be reused or taken as a model? It does a good job of providing the type and the underlying type as 'aka'.

**Comment by kadircet** [comment] 2020-07-20 15:22
IIRC, clang's AKA works in the opposite way(please do correct me if i am misremembering), e.g. they convert a type as written into its desugared type (`std::string -> std::basic_string<char>`). we need the opposite, whenever the type isn't explicitly spelled (e.g. it is inferred via `auto`) we get the "desugared" type and we want to go to some "sugared" type. the problem is the wanted sugared type isn't obvious(neither well-defined).

**Comment by lh123** [comment] 2020-07-20 15:32
Yes, but I still think that providing both spelled and canonical types is better than just providing spelled type.

**Comment by Trass3r** [comment] 2020-08-14 11:03
> Isn't this basically a duplicate of #36?

Very similar indeed.

**Comment by Trass3r** [comment] 2020-08-14 11:24
> IIRC, clang's AKA works in the opposite way, e.g. they convert a type as written into its desugared type (`std::string -> std::basic_string<char>`). we need the opposite, whenever the type isn't explicitly spelled (e.g. it is inferred via `auto`) we get the "desugared" type and we want to go to some "sugared" type.

Looks like you are right: https://godbolt.org/z/qfdq1K
It expands the `std::vector<int, class std::allocator<int>>::const_iterator` that clangd shows for `begin`'s return type.

**Comment by lh123** [comment] 2021-12-08 06:36
This should already fix in 
- https://reviews.llvm.org/D114665
- https://reviews.llvm.org/D114522

**Closed** 2021-12-08 06:36 UTC
