### ISSUE TITLE
Crash when initializing variable using field designator in different order. Struct contains bitfields

### ISSUE THREAD

**Issue by djobet** [clangd/clangd#1244] opened 2022-08-10 12:36 UTC
The following code snippet

```c++
#pragma once

#include <cstdint>

typedef struct __attribute__((packed))
{
    uint16_t f0;
    uint16_t f1;
    uint8_t : 3;
    uint8_t f2 : 1;
    uint8_t f3 : 4;
    uint8_t f4;
    uint8_t f5;
    uint8_t f6;
} PackedWithBitField;

// static PackedWithBitField crash0 = {.f6 = 1, .f5 = 2, .f4 = 0, .f3 = 1, .f2 = 1, .f1 = 0, .f0 = 1};
static PackedWithBitField noCrash0 = {.f0 = 1, .f1 = 2, .f2 = 0, .f3 = 1, .f4 = 1, .f5 = 0, .f6 = 1};

typedef struct
{
    uint16_t f0;
    uint16_t f1;
    uint8_t : 3;
    uint8_t f2 : 1;
    uint8_t f3 : 4;
    uint8_t f4;
    uint8_t f5;
    uint8_t f6;
} NotPackedWithBitField;

// static NotPackedWithBitField crash1   = {.f6 = 1, .f5 = 2, .f4 = 0, .f3 = 1, .f2 = 1, .f1 = 0, .f0 = 1};
static NotPackedWithBitField noCrash1 = {.f0 = 1, .f1 = 2, .f2 = 0, .f3 = 1, .f4 = 1, .f5 = 0, .f6 = 1};

typedef struct __attribute__((packed))
{
    uint8_t f0;
    uint8_t f1;
    uint8_t f2;
} PackedNoBitField;

static PackedNoBitField noCrash2 = {.f2 = 1, .f1 = 0, .f0 = 1};
static PackedNoBitField noCrash3 = {.f0 = 1, .f1 = 2, .f2 = 0};
```

Will make clangd crash as soon as you remove one of the commented lines (variables crash0 and/or crash1).
Reordering the fields in struct order prevents the crash. (noCrash0 and noCrash1)
Removing the packed attribute still makes clangd crash.
Removing the bit fields seems to prevent the crash as well.

**Logs**

[Error - 1:20:59 PM] Client Clang Language Server: connection to server is erroring. Shutting down server.
[Error - 1:20:59 PM] Connection to server got closed. Server will not be restarted.
[Error - 1:20:59 PM] Request textDocument/documentSymbol failed.
[object Object]
[Error - 1:20:59 PM] Request textDocument/codeAction failed.
[object Object]
[Error - 1:20:59 PM] Request textDocument/codeAction failed.
[object Object]
[Error - 1:20:59 PM] Request textDocument/documentLink failed.
[object Object]
[Error - 1:20:59 PM] Request textDocument/documentLink failed.
[object Object]
[Error - 1:20:59 PM] Stopping server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 1:20:59 PM] Stopping server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
 #0 0x00007f1efbce47b3 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/spare/local/djobet/conda_root/envs/default/bin/../lib/libLLVMSupport.so.12+0x20d7b3)
 #1 0x00007f1efbce35ec llvm::sys::RunSignalHandlers() (/spare/local/djobet/conda_root/envs/default/bin/../lib/libLLVMSupport.so.12+0x20c5ec)
 #2 0x00007f1efbce412a SignalHandler(int) (/spare/local/djobet/conda_root/envs/default/bin/../lib/libLLVMSupport.so.12+0x20d12a)
 #3 0x00007f1efdcc0630 __restore_rt (/lib64/libpthread.so.0+0xf630)
 #4 0x00007f1efcb4ad2c clang::Stmt::getBeginLoc() const (/spare/local/djobet/conda_root/envs/default/bin/../lib/libclangAST.so.12+0x673d2c)
 #5 0x00007f1efd2c88b3 (anonymous namespace)::InitListChecker::CheckDesignatedInitializer(clang::InitializedEntity const&, clang::InitListExpr*, clang::DesignatedInitExpr*, unsigned int, clang::QualType&, clang::DeclContext::specific_decl_iterator<clang::FieldDecl>*, llvm::APSInt*, unsigned int&, clang::InitListExpr*, unsigned int&, bool, bool) (/spare/local/djobet/conda_root/envs/default/bin/../lib/libclangSema.so.12+0x6bc8b3)
 #6 0x00007f1efd2c4bec (anonymous namespace)::InitListChecker::CheckStructUnionTypes(clang::InitializedEntity const&, clang::InitListExpr*, clang::QualType, llvm::iterator_range<clang::CXXBaseSpecifier*>, clang::DeclContext::specific_decl_iterator<clang::FieldDecl>, bool, unsigned int&, clang::InitListExpr*, unsigned int&, bool) (/spare/local/djobet/conda_root/envs/default/bin/../lib/libclangSema.so.12+0x6b8bec)
 #7 0x00007f1efd2a9f63 (anonymous namespace)::InitListChecker::CheckListElementTypes(clang::InitializedEntity const&, clang::InitListExpr*, clang::QualType&, bool, unsigned int&, clang::InitListExpr*, unsigned int&, bool) (/spare/local/djobet/conda_root/envs/default/bin/../lib/libclangSema.so.12+0x69df63)
 #8 0x00007f1efd2a8c44 (anonymous namespace)::InitListChecker::InitListChecker(clang::Sema&, clang::InitializedEntity const&, clang::InitListExpr*, clang::QualType&, bool, bool, bool) (/spare/local/djobet/conda_root/envs/default/bin/../lib/libclangSema.so.12+0x69cc44)
 #9 0x00007f1efd2b3567 clang::InitializationSequence::Perform(clang::Sema&, clang::InitializedEntity const&, clang::InitializationKind const&, llvm::MutableArrayRef<clang::Expr*>, clang::QualType*) (/spare/local/djobet/conda_root/envs/default/bin/../lib/libclangSema.so.12+0x6a7567)
#10 0x00007f1efd0311e7 clang::Sema::AddInitializerToDecl(clang::Decl*, clang::Expr*, bool) (/spare/local/djobet/conda_root/envs/default/bin/../lib/libclangSema.so.12+0x4251e7)
#11 0x00007f1efa040d37 clang::Parser::ParseDeclarationAfterDeclaratorAndAttributes(clang::Declarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::ForRangeInit*) (/spare/local/djobet/conda_root/envs/default/bin/../lib/./libclangParse.so.12+0x80d37)
#12 0x00007f1efa03ee87 clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/spare/local/djobet/conda_root/envs/default/bin/../lib/./libclangParse.so.12+0x7ee87)
#13 0x00007f1efa0f0b54 clang::Parser::ParseDeclOrFunctionDefInternal(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/spare/local/djobet/conda_root/envs/default/bin/../lib/./libclangParse.so.12+0x130b54)
#14 0x00007f1efa0f07bd clang::Parser::ParseDeclarationOrFunctionDefinition(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (/spare/local/djobet/conda_root/envs/default/bin/../lib/./libclangParse.so.12+0x1307bd)
#15 0x00007f1efa0ef50a clang::Parser::ParseExternalDeclaration(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*) (/spare/local/djobet/conda_root/envs/default/bin/../lib/./libclangParse.so.12+0x12f50a)
#16 0x00007f1efa0ed57d clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, bool) (/spare/local/djobet/conda_root/envs/default/bin/../lib/./libclangParse.so.12+0x12d57d)
#17 0x00007f1efa011d8d clang::ParseAST(clang::Sema&, bool, bool) (/spare/local/djobet/conda_root/envs/default/bin/../lib/./libclangParse.so.12+0x51d8d)

**System information**

Output of `clangd --version`:
clangd version 12.0.1

Editor/LSP plugin:
vscode 1.68.1 + clangd v0.1.21 extension

Operating system:
CentOS 7 Linux 4.14.39-el7

**Comment by HighCommander4** [comment] 2022-08-14 18:56
Confirmed, affects trunk as well.

**Comment by HighCommander4** [comment] 2024-01-14 08:59
This crash no longer occurs with clangd 17.

**Comment by HighCommander4** [comment] 2024-01-15 02:02
Fixed by https://github.com/llvm/llvm-project/commit/c9ef33e1d8a8aeb68a18f24af6d9fc9ab4ecf257

**Comment by HighCommander4** [comment] 2024-01-15 02:03
Duplicate of https://github.com/llvm/llvm-project/issues/63605

**Closed by HighCommander4** 2024-01-15 02:03 UTC
Labels: bug
