### ISSUE TITLE
bug: Clangd doesn't provide completions for concept template classes when definitions are outside of class body

### ISSUE THREAD

**Issue by tjzel** [clangd/clangd#2165] opened 2024-09-27 13:51 UTC
When you specify a template class with a concept and then define a method outside of its body clangd doesn't suggest anything. When the method is in class body, everything works well.

```c++
template <class Clazz>
concept IFoo = requires(Clazz clazz) {
  { clazz.foo() } -> std::same_as<void>;
};

template <IFoo Foo> class Clazz {
  Foo _foo;
  void foo(); // If you put the definition here, then `_foo.foo()` gets suggested.
};

template <IFoo Foo> void Clazz<Foo>::foo() { _foo.foo(); } // Clangd doesn't suggest anything after `_foo.`
```

**Logs**

Method definition in body
```console
/opt/homebrew/Cellar/llvm/18.1.8/bin/clang++ --driver-mode=g++ -Dcontroller_EXPORTS -I/Users/bigpoppe/projects/dashing-board/controller/src -Wall -Wextra -Wpedantic -O0 -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.0.sdk -fPIC -c -std=gnu++20 -xc++ -std=c++20 -resource-dir=/opt/homebrew/Cellar/llvm/18.1.8/lib/clang/18 -- /Users/bigpoppe/projects/dashing-board/controller/src/ICommunicator.hpp
I[15:44:35.577] --> textDocument/clangd.fileStatus
I[15:44:35.586] <-- textDocument/semanticTokens/full/delta(2555)
I[15:44:35.592] --> textDocument/publishDiagnostics
I[15:44:35.592] --> textDocument/inactiveRegions
I[15:44:35.593] --> reply:textDocument/semanticTokens/full/delta(2555) 6 ms
I[15:44:35.593] --> textDocument/clangd.fileStatus
I[15:44:35.726] <-- textDocument/foldingRange(2556)
I[15:44:35.726] --> reply:textDocument/foldingRange(2556) 0 ms
I[15:44:35.822] <-- textDocument/didChange
I[15:44:35.822] --> textDocument/clangd.fileStatus
I[15:44:35.825] <-- textDocument/completion(2557)
I[15:44:35.840] Code complete: sema context DotMemberAccess, query scopes [] (AnyScope=true), expected type <none>
I[15:44:35.841] Code complete: 1 results from Sema, 0 from Index, 0 matched, 0 from identifiers, 1 returned.
I[15:44:35.841] --> reply:textDocument/completion(2557) 15 ms
```

Method definition outside of body
```console
/opt/homebrew/Cellar/llvm/18.1.8/bin/clang++ --driver-mode=g++ -Dcontroller_EXPORTS -I/Users/bigpoppe/projects/dashing-board/controller/src -Wall -Wextra -Wpedantic -O0 -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.0.sdk -fPIC -c -std=gnu++20 -xc++ -std=c++20 -resource-dir=/opt/homebrew/Cellar/llvm/18.1.8/lib/clang/18 -- /Users/bigpoppe/projects/dashing-board/controller/src/ICommunicator.hpp
I[15:46:42.929] --> textDocument/clangd.fileStatus
I[15:46:42.946] --> textDocument/publishDiagnostics
I[15:46:42.946] --> textDocument/inactiveRegions
I[15:46:42.946] --> textDocument/clangd.fileStatus
I[15:46:43.071] <-- textDocument/foldingRange(2591)
I[15:46:43.071] --> reply:textDocument/foldingRange(2591) 0 ms
I[15:46:43.171] <-- textDocument/semanticTokens/full/delta(2592)
I[15:46:43.172] --> reply:textDocument/semanticTokens/full/delta(2592) 0 ms
I[15:46:43.172] --> textDocument/clangd.fileStatus
I[15:46:43.199] <-- textDocument/codeAction(2593)
I[15:46:43.199] --> reply:textDocument/codeAction(2593) 0 ms
I[15:46:43.199] --> textDocument/clangd.fileStatus
I[15:46:43.222] <-- textDocument/documentSymbol(2594)
I[15:46:43.223] <-- textDocument/documentSymbol(2595)
I[15:46:43.223] --> reply:textDocument/documentSymbol(2594) 0 ms
I[15:46:43.223] --> reply:textDocument/documentSymbol(2595) 0 ms
I[15:46:43.223] --> textDocument/clangd.fileStatus
I[15:46:43.874] <-- textDocument/documentLink(2596)
I[15:46:43.875] --> reply:textDocument/documentLink(2596) 0 ms
I[15:46:43.875] --> textDocument/clangd.fileStatus
I[15:46:44.124] <-- textDocument/inlayHint(2597)
I[15:46:44.124] --> reply:textDocument/inlayHint(2597) 0 ms
I[15:46:44.124] --> textDocument/clangd.fileStatus
I[15:46:49.882] <-- textDocument/hover(2598)
I[15:46:49.886] --> reply:textDocument/hover(2598) 3 ms
I[15:46:49.886] --> textDocument/clangd.fileStatus
I[15:46:51.400] <-- textDocument/didChange
I[15:46:51.400] --> textDocument/clangd.fileStatus
I[15:46:51.403] <-- textDocument/completion(2599)
I[15:46:51.421] Code complete: 0 results from Sema, 0 from Index, 0 matched, 0 from identifiers, 0 returned.
I[15:46:51.421] --> reply:textDocument/completion(2599) 17 ms
```

**System information**

Output of `clangd --version`:
Homebrew clangd version 18.1.8
Features: mac+xpc
Platform: arm64-apple-darwin24.1.0

Editor/LSP plugin:
VSCode/clangd 0.1.29

Operating system:
MacOS 15 Sequioa

**Comment by HighCommander4** [comment] 2024-09-28 06:57
Duplicate of https://github.com/clangd/clangd/issues/1207

**Closed by HighCommander4** 2024-09-28 06:57 UTC
