### ISSUE TITLE
clangd cannot find headers when included from header file

### ISSUE THREAD

**Issue by gianmarcoodorizzi** [clangd/clangd#1280] opened 2022-09-08 07:10 UTC
I know this might be related to: https://github.com/clangd/clangd/issues/695, but I would have expected a different result.

I have a Timeout class as follows:

```
#pragma once

#include <chrono>
#include <cstdint>
#include <mutex>

class Timeout
{
public:
	explicit Timeout(std::uint32_t ms, bool resetOnCreation = false);
	void reset();
	bool expired();

private:
	std::chrono::time_point<std::chrono::system_clock> mStart;
	std::uint32_t mDuration;
	std::mutex mMtx;
};
```

but VSC is complaining about not finding chrono.

This is the entry related to the class's source file in my compile_commands.json:

` {
  "directory": "/home/user/git/proj",
  "arguments": [
   "arm-fslc-linux-gnueabi-g++",
   "-march=armv7-a",
   "-mthumb",
   "-mfpu=neon",
   "-mfloat-abi=hard",
   "--sysroot=/opt/fslc-framebuffer/2.4.1/sysroots/armv7at2hf-neon-fslc-linux-gnueabi",
   "-DSPDLOG_COMPILED_LIB",
   "-Wall",
   "-Wextra",
   "-pedantic-errors",
   "-Wno-psabi",
   "-std=c++17",
   "-Isrc",
   "-I../common",
   "-I../common/include",
   "-O2",
   "-pipe",
   "-g",
   "-feliminate-unused-debug-types",
   "-c",
   "src/Timeout/Timeout.cpp",
   "-MMD",
   "-MP",
   "-MFbuild/src/Timeout/Timeout.d",
   "-MTbuild/src/Timeout/Timeout.o",
   "-o",
   "build/src/Timeout/Timeout.o"
  ],
  "file": "src/Timeout/Timeout.cpp"
 }`

which should be correct . When including the same header in the source file, clangd is indeed able to find it, but the same does not happen in the header file.

Skimming through clangd's log file, I see this entry:

> I[09:03:41.040] ASTWorker building file /home/user/git/proj/src/Timeout/Timeout.hpp version 1 with command inferred from src/Timeout/Timeout.cpp
[/home/user/git/proj]

From my understanding, it means that clangd is deducing the compilation flags for the class's header from the respective source file, which should be fine (I get no errors reported in the source file).

So, why is this happening? Thank you in advance!

**Comment by HighCommander4** [comment] 2022-09-08 07:15
Could you share a complete log please?

**Comment by gianmarcoodorizzi** [comment] 2022-09-08 07:20
Sure, here it is:

> I[09:17:56.709] clangd version 14.0.3 (https://github.com/llvm/llvm-project 1f9140064dfbfb0bbda8e51306ea51080b2f7aac)
I[09:17:56.710] Features: linux+grpc
I[09:17:56.710] PID: 31452
I[09:17:56.710] Working directory: /home/user/git/proj
I[09:17:56.710] argv[0]: /home/user/.vscode-server/data/User/globalStorage/llvm-vs-code-extensions.vscode-clangd/install/14.0.3/clangd_14.0.3/bin/clangd
I[09:17:56.710] argv[1]: --query-driver=/opt/fslc-framebuffer/2.4.1/sysroots/x86_64-fslcsdk-linux/usr/bin/arm-fslc-linux-gnueabi/arm-fslc-linux-gnueabi-g++
I[09:17:56.710] argv[2]: --compile-commands-dir=build
I[09:17:56.710] argv[3]: -header-insertion=never
I[09:17:56.711] Starting LSP over stdin/stdout
I[09:17:56.724] <-- initialize(0)
I[09:17:56.795] --> reply:initialize(0) 71 ms
I[09:17:57.146] <-- initialized
I[09:17:57.201] <-- textDocument/didOpen
I[09:17:57.208] Loaded compilation database from /home/user/git/proj/build/compile_commands.json
I[09:17:57.221] --> window/workDoneProgress/create(0)
I[09:17:57.221] Enqueueing 39 commands for indexing
I[09:17:57.222] System includes extractor: successfully executed /opt/fslc-framebuffer/2.4.1/sysroots/x86_64-fslcsdk-linux/usr/bin/arm-fslc-linux-gnueabi/arm-fslc-linux-gnueabi-g++
	got includes: "/opt/fslc-framebuffer/2.4.1/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/include/c++/7.2.0, /opt/fslc-framebuffer/2.4.1/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/include/c++/7.2.0/arm-fslc-linux-gnueabi, /opt/fslc-framebuffer/2.4.1/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/include/c++/7.2.0/backward, /opt/fslc-framebuffer/2.4.1/sysroots/x86_64-fslcsdk-linux/usr/lib/arm-fslc-linux-gnueabi/gcc/arm-fslc-linux-gnueabi/7.2.0/include, /opt/fslc-framebuffer/2.4.1/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/gcc/arm-fslc-linux-gnueabi/7.2.0/include, /opt/fslc-framebuffer/2.4.1/sysroots/x86_64-fslcsdk-linux/usr/lib/arm-fslc-linux-gnueabi/gcc/arm-fslc-linux-gnueabi/7.2.0/include-fixed, /opt/fslc-framebuffer/2.4.1/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/include/"
	got target: "arm-fslc-linux-gnueabi"
I[09:17:57.222] ASTWorker building file /home/user/git/proj/src/Timeout/Timeout.hpp version 1 with command inferred from src/Timeout/Timeout.cpp
[/home/user/git/proj]
/opt/fslc-framebuffer/2.4.1/sysroots/x86_64-fslcsdk-linux/usr/bin/arm-fslc-linux-gnueabi/arm-fslc-linux-gnueabi-g++ --target=arm-fslc-linux-gnueabi --driver-mode=g++ -march=armv7-a -mthumb -mfpu=neon -mfloat-abi=hard --sysroot=/opt/fslc-framebuffer/2.4.1/sysroots/armv7at2hf-neon-fslc-linux-gnueabi -DSPDLOG_COMPILED_LIB -Wall -Wextra -pedantic-errors -Wno-psabi -Isrc -I../common -I../common/include -O2 -pipe -g -feliminate-unused-debug-types -c -MMD -MP -MFbuild/src/Timeout/Timeout.d -MTbuild/src/Timeout/Timeout.o -std=c++17 -resource-dir=/home/user/.vscode-server/data/User/globalStorage/llvm-vs-code-extensions.vscode-clangd/install/14.0.3/clangd_14.0.3/lib/clang/14.0.3 -- /home/user/git/proj/src/Timeout/Timeout.hpp
I[09:17:57.256] <-- reply(0)
I[09:17:57.256] --> $/progress
I[09:17:57.256] --> $/progress
I[09:17:57.295] --> textDocument/clangd.fileStatus
I[09:17:57.315] --> workspace/semanticTokens/refresh(1)
I[09:17:57.315] --> textDocument/clangd.fileStatus
I[09:17:57.319] <-- textDocument/documentSymbol(1)
I[09:17:57.320] <-- textDocument/documentLink(2)
I[09:17:57.320] <-- clangd/inlayHints(3)
I[09:17:57.396] <-- reply(1)
I[09:17:57.429] <-- $/cancelRequest
I[09:17:57.430] <-- textDocument/documentSymbol(4)
I[09:17:57.447] --> textDocument/publishDiagnostics
I[09:17:57.447] --> reply:textDocument/documentSymbol(1) 128 ms, error: Task was cancelled.
I[09:17:57.447] --> reply:textDocument/documentLink(2) 127 ms
I[09:17:57.447] --> reply:clangd/inlayHints(3) 127 ms
I[09:17:57.448] --> reply:textDocument/documentSymbol(4) 17 ms
I[09:17:57.448] --> textDocument/clangd.fileStatus
[Error - 9:17:57 AM] Request textDocument/documentSymbol failed.
[object Object]
I[09:17:57.683] --> $/progress
I[09:17:57.683] --> $/progress
I[09:17:57.684] --> $/progress
I[09:17:57.684] --> $/progress
I[09:17:57.698] System includes extractor: successfully executed /opt/fslc-framebuffer/2.4.1/sysroots/x86_64-fslcsdk-linux/usr/bin/arm-fslc-linux-gnueabi/arm-fslc-linux-gnueabi-g++
	got includes: "/opt/fslc-framebuffer/2.4.1/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/include/c++/7.2.0, /opt/fslc-framebuffer/2.4.1/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/include/c++/7.2.0/arm-fslc-linux-gnueabi, /opt/fslc-framebuffer/2.4.1/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/include/c++/7.2.0/backward, /opt/fslc-framebuffer/2.4.1/sysroots/x86_64-fslcsdk-linux/usr/lib/arm-fslc-linux-gnueabi/gcc/arm-fslc-linux-gnueabi/7.2.0/include, /opt/fslc-framebuffer/2.4.1/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/gcc/arm-fslc-linux-gnueabi/7.2.0/include, /opt/fslc-framebuffer/2.4.1/sysroots/x86_64-fslcsdk-linux/usr/lib/arm-fslc-linux-gnueabi/gcc/arm-fslc-linux-gnueabi/7.2.0/include-fixed, /opt/fslc-framebuffer/2.4.1/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/include/"
	got target: "arm-fslc-linux-gnueabi"
I[09:17:57.698] System includes extractor: successfully executed /opt/fslc-framebuffer/2.4.1/sysroots/x86_64-fslcsdk-linux/usr/bin/arm-fslc-linux-gnueabi/arm-fslc-linux-gnueabi-g++
	got includes: "/opt/fslc-framebuffer/2.4.1/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/include/c++/7.2.0, /opt/fslc-framebuffer/2.4.1/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/include/c++/7.2.0/arm-fslc-linux-gnueabi, /opt/fslc-framebuffer/2.4.1/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/include/c++/7.2.0/backward, /opt/fslc-framebuffer/2.4.1/sysroots/x86_64-fslcsdk-linux/usr/lib/arm-fslc-linux-gnueabi/gcc/arm-fslc-linux-gnueabi/7.2.0/include, /opt/fslc-framebuffer/2.4.1/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/gcc/arm-fslc-linux-gnueabi/7.2.0/include, /opt/fslc-framebuffer/2.4.1/sysroots/x86_64-fslcsdk-linux/usr/lib/arm-fslc-linux-gnueabi/gcc/arm-fslc-linux-gnueabi/7.2.0/include-fixed, /opt/fslc-framebuffer/2.4.1/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/include/"
	got target: "arm-fslc-linux-gnueabi"
I[09:17:58.106] Indexed src/Timeout/Timeout.cpp (3 symbols, 5114 refs, 170 files)
I[09:17:58.112] --> $/progress
I[09:17:58.487] <-- textDocument/semanticTokens/full(5)
I[09:17:58.487] --> reply:textDocument/semanticTokens/full(5) 0 ms
I[09:17:58.487] --> textDocument/clangd.fileStatus
I[09:17:59.835] Indexed src/main.cpp (1 symbols, 11291 refs, 397 files)
I[09:18:00.053] --> $/progress

**Comment by HighCommander4** [comment] 2022-09-08 08:21
Ah, query-driver + clangd 14.

This is a known regression in clangd 14 (#1100), which has been fixed in clangd 15 and trunk, you can pick up the fix by upgrading.

**Closed by HighCommander4** 2022-09-08 08:21 UTC

**Comment by gianmarcoodorizzi** [comment] 2022-09-09 06:21
Replaced the clangd binary with https://github.com/clangd/clangd/releases/tag/15.0.0

> I[08:16:23.075] clangd version 15.0.0 (https://github.com/llvm/llvm-project 4ba6a9c9f65bbc8bd06e3652cb20fd4dfc846137)
I[08:16:23.075] Features: linux+grpc
I[08:16:23.075] PID: 5630
I[08:16:23.075] Working directory: /home/user/git/proj
I[08:16:23.075] argv[0]: /home/user/.vscode-server/data/User/globalStorage/llvm-vs-code-extensions.vscode-clangd/install/14.0.3/clangd_14.0.3/bin/clangd
I[08:16:23.075] argv[1]: --query-driver=/opt/fslc-framebuffer/2.4.1/sysroots/x86_64-fslcsdk-linux/usr/bin/arm-fslc-linux-gnueabi/arm-fslc-linux-gnueabi-g++
I[08:16:23.075] argv[2]: --compile-commands-dir=build
I[08:16:23.075] argv[3]: -header-insertion=never
I[08:16:23.076] Starting LSP over stdin/stdout
I[08:16:23.094] <-- initialize(0)
I[08:16:23.200] --> reply:initialize(0) 106 ms
I[08:16:23.799] <-- initialized
I[08:16:23.927] <-- textDocument/didOpen
I[08:16:23.942] Loaded compilation database from /home/user/git/proj/build/compile_commands.json
I[08:16:23.972] System includes extractor: successfully executed /opt/fslc-framebuffer/2.4.1/sysroots/x86_64-fslcsdk-linux/usr/bin/arm-fslc-linux-gnueabi/arm-fslc-linux-gnueabi-g++
	got includes: "/opt/fslc-framebuffer/2.4.1/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/include/c++/7.2.0, /opt/fslc-framebuffer/2.4.1/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/include/c++/7.2.0/arm-fslc-linux-gnueabi, /opt/fslc-framebuffer/2.4.1/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/include/c++/7.2.0/backward, /opt/fslc-framebuffer/2.4.1/sysroots/x86_64-fslcsdk-linux/usr/lib/arm-fslc-linux-gnueabi/gcc/arm-fslc-linux-gnueabi/7.2.0/include, /opt/fslc-framebuffer/2.4.1/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/gcc/arm-fslc-linux-gnueabi/7.2.0/include, /opt/fslc-framebuffer/2.4.1/sysroots/x86_64-fslcsdk-linux/usr/lib/arm-fslc-linux-gnueabi/gcc/arm-fslc-linux-gnueabi/7.2.0/include-fixed, /opt/fslc-framebuffer/2.4.1/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/include/"
	got target: "arm-fslc-linux-gnueabi"
I[08:16:23.972] --> window/workDoneProgress/create(0)
I[08:16:23.973] Enqueueing 39 commands for indexing
I[08:16:23.973] ASTWorker building file /home/user/git/proj/src/Timeout/Timeout.hpp version 1 with command inferred from src/Timeout/Timeout.cpp
[/home/user/git/proj]
/opt/fslc-framebuffer/2.4.1/sysroots/x86_64-fslcsdk-linux/usr/bin/arm-fslc-linux-gnueabi/arm-fslc-linux-gnueabi-g++ --target=arm-fslc-linux-gnueabi --driver-mode=g++ -march=armv7-a -mthumb -mfpu=neon -mfloat-abi=hard --sysroot=/opt/fslc-framebuffer/2.4.1/sysroots/armv7at2hf-neon-fslc-linux-gnueabi -DSPDLOG_COMPILED_LIB -Wall -Wextra -pedantic-errors -Wno-psabi -Isrc -I../common -I../common/include -O2 -pipe -g -feliminate-unused-debug-types -c -MMD -MP -MFbuild/src/Timeout/Timeout.d -MTbuild/src/Timeout/Timeout.o -isystem /opt/fslc-framebuffer/2.4.1/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/include/c++/7.2.0 -isystem /opt/fslc-framebuffer/2.4.1/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/include/c++/7.2.0/arm-fslc-linux-gnueabi -isystem /opt/fslc-framebuffer/2.4.1/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/include/c++/7.2.0/backward -isystem /opt/fslc-framebuffer/2.4.1/sysroots/x86_64-fslcsdk-linux/usr/lib/arm-fslc-linux-gnueabi/gcc/arm-fslc-linux-gnueabi/7.2.0/include -isystem /opt/fslc-framebuffer/2.4.1/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/gcc/arm-fslc-linux-gnueabi/7.2.0/include -isystem /opt/fslc-framebuffer/2.4.1/sysroots/x86_64-fslcsdk-linux/usr/lib/arm-fslc-linux-gnueabi/gcc/arm-fslc-linux-gnueabi/7.2.0/include-fixed -isystem /opt/fslc-framebuffer/2.4.1/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/include/ -std=c++17 -resource-dir=/home/user/.vscode-server/data/User/globalStorage/llvm-vs-code-extensions.vscode-clangd/install/14.0.3/clangd_14.0.3/lib/clang/15.0.0 -- /home/user/git/proj/src/Timeout/Timeout.hpp
I[08:16:24.030] <-- reply(0)
I[08:16:24.030] --> $/progress
I[08:16:24.030] --> $/progress
I[08:16:24.078] --> textDocument/clangd.fileStatus
I[08:16:24.084] <-- textDocument/documentSymbol(1)
I[08:16:24.129] <-- $/cancelRequest
I[08:16:24.130] <-- textDocument/documentLink(2)
I[08:16:24.130] <-- textDocument/inlayHint(3)
I[08:16:24.130] <-- textDocument/documentSymbol(4)
I[08:16:24.704] --> $/progress
I[08:16:24.704] --> $/progress
I[08:16:25.113] --> workspace/semanticTokens/refresh(1)
I[08:16:25.113] --> textDocument/clangd.fileStatus
I[08:16:25.113] --> textDocument/clangd.fileStatus
I[08:16:25.372] --> textDocument/publishDiagnostics
I[08:16:25.373] --> reply:textDocument/documentSymbol(1) 1288 ms, error: Task was cancelled.
I[08:16:25.373] --> reply:textDocument/documentLink(2) 1243 ms
I[08:16:25.373] --> reply:textDocument/inlayHint(3) 1242 ms
I[08:16:25.373] --> reply:textDocument/documentSymbol(4) 1242 ms
I[08:16:25.373] --> textDocument/clangd.fileStatus
I[08:16:25.691] <-- textDocument/semanticTokens/full(5)
I[08:16:25.691] --> reply:textDocument/semanticTokens/full(5) 0 ms
I[08:16:25.691] --> textDocument/clangd.fileStatus
I[08:16:25.987] <-- reply(1)
[Error - 8:16:26 AM] Request textDocument/documentSymbol failed.
[object Object]
I[08:16:29.814] <-- textDocument/codeAction(6)
I[08:16:29.825] --> reply:textDocument/codeAction(6) 10 ms
I[08:16:29.825] --> textDocument/clangd.fileStatus

It seems like the issue is still there?

**Comment by HighCommander4** [comment] 2022-09-09 06:32
The log did change in a relevant way: if you look at the line that says

> ASTWorker building file /home/user/git/proj/src/Timeout/Timeout.hpp version 1 with command inferred from src/Timeout/Timeout.cpp

the command on the following line includes a bunch of `-isystem` flags, for example, `-isystem /opt/fslc-framebuffer/2.4.1/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/include/c++/7.2.0`, that previously it did not.

Just to confirm, the issue is that `#include <chrono>` is still not resolved? (I would expect it to be found in that `include/c++/7.2.0` directory.)

**Comment by gianmarcoodorizzi** [comment] 2022-09-09 06:39
The header is indeed there and yes, it is not found by clangd. But Ctrl-clinking takes me to the header.
I removed .cache folder and rebuilt the compilation database.

**Comment by HighCommander4** [comment] 2022-09-09 06:48
If Ctrl+Click takes you to the header, that suggests clangd is able to resolve it.

Maybe the diagnostic you're seeing about the `#include` is a stale one (does it persist across a vscode restart?), or produced by a different plugin (not clangd)?

**Comment by gianmarcoodorizzi** [comment] 2022-09-09 06:58
You're right, the diagnostic was coming from clang-tidy (version 14). 
So it seem like the issue is resolved. 

Thank you for your time!
