### ISSUE TITLE
Wrong diagnostics information for headers

### ISSUE THREAD

**Issue by timxx** [clangd/clangd#930] opened 2021-11-17 11:13 UTC
If the header file never include the header it reference to or no forward declare for pointers, clangd will treat it as **expected_class_name**, **undeclared_var_use**, **override_keyword_only_allowed_on_virtual_member_functions** etc.
Most of the time the header compiled with c/cpp without any problems.

From TUScheduler.cpp source I see clangd just uses command line from which includes it, treat header as a c/cxx file to parse individually.  It's not the way as compiler do.

Is it possible generate diagnostics from c/cpp source file instead header?
If the cpp source opened, and specify header contains error, just show tips to user that header contains errors.
If open the header file and edit directly, fetch diagnostics from corresponding c/cpp file. If no corresponding c/cpp file found, use the old way to generate diagnostics.

I known is best practices to include headers and forward declare everything that referenced, but not all projects do. Too many noisy diagnostics in such cases.

**System information**

Output of `clangd --version`:
13.0.0

**Comment by kadircet** [comment] 2021-11-17 12:21
Hi @timxx, IIUC this is the same as https://github.com/clangd/clangd/issues/45.

Unfortunately providing semantic functionality through clangd is more complex than just diagnostics (which is already complicated enough, since it looses a lot of value when it's not correct). Hence making use of a TU including the header doesn't work in practice (the idea you described is great, but misses a couple things about general clangd design && what to do when we have multiple files including a header).

Closing as it's a duplicate of #45, please re-open if I misunderstood.

**Closed by kadircet** 2021-11-17 12:21 UTC
