### ISSUE TITLE
clangd can't find included header (msys2/mingw) 

### ISSUE THREAD

**Issue by iiifr** [clangd/clangd#308] opened 2020-03-13 06:03 UTC
I am using vim and its extension `coc.nvim` to create my IDE-like vim. To let `coc.nvim` support `clangd`, I also  install `coc-clangd`, the extension of `coc.nvim`. I am on Windows and use msys2/mingw platform to create my IDE-like vim. I have an ARM MCU project, it's a cross-platform project, and it's makefile-based. I succeeded installing `coc.nvim` and `coc-clangd` and all their requirements, and I use `compiledb` to generate `compile_commands.json` for my project. But it seems `clangd` cannot find header I include in my source code.  For example, I include the header `main.h` in `main.c` , and `coc.nvim` complained `main.h file not found [clangd:]`, also, for struct defined in header, `coc.nvim` complained `unknown type name XXX [clangd:]`. Is there anyone here could help me debug this problem? I get `clangd` from msys2 package `mingw-w64-x86_64-clang-tools-extra`.
Here is the part of `compile_commands.json` related to `main.c`
```
{
  "directory": "/c/Users/XXXX/Desktop/XXXX_project",
  "arguments": [
   "arm-none-eabi-gcc",
   "-c",
   "-mcpu=cortex-m7",
   "-mthumb",
   "-mfpu=fpv5-d16",
   "-mfloat-abi=hard",
   "-DUSE_HAL_DRIVER",
   "-DSTM32F765xx",
   "-IInc",
   "-IDrivers/STM32F7xx_HAL_Driver/Inc",
   "-IDrivers/STM32F7xx_HAL_Driver/Inc/Legacy",
   "-IMiddlewares/ST/STM32_USB_Device_Library/Core/Inc",
   "-IMiddlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc",
   "-IDrivers/CMSIS/Device/ST/STM32F7xx/Include",
   "-IDrivers/CMSIS/Include",
   "-O0",
   "-Wall",
   "-fdata-sections",
   "-ffunction-sections",
   "-g",
   "-gdwarf-2",
   "-MMD",
   "-MP",
   "-MFbuild/main.d",
   "-Wa,-a,-ad,-alms=build/main.lst",
   "Src/main.c",
   "-o",
   "build/main.o"
  ],
  "file": "Src/main.c"
 },
```

**Comment by kadircet** [comment] 2020-03-13 09:39
directory path mentioned in the compile commands looks suspicious. it doesn't seem like a real directory and clangd tries to find headers relative to that.

could you also provide clangd logs, while passing `-log=verbose` to clangd as a command line flag?

**Comment by iiifr** [comment] 2020-03-13 10:37
Using `coc.nvim` command `CocInfo`, I can get clangd log:
```
## Output channel: clangd log

I[18:09:24.032] <-- initialize(0)
I[18:09:24.034] --> reply:initialize(0) 1 ms
I[18:09:24.037] <-- initialized
I[18:09:24.037] unhandled notification initialized
I[18:09:24.043] <-- textDocument/didOpen
I[18:09:24.044] Failed to find compilation database for \c\Users\iscre\Desktop\paperproj_openmv_m7_cubemx\Src\main.c
I[18:09:24.044] --> textDocument/clangd.fileStatus
I[18:09:24.044] Updating file \c\Users\iscre\Desktop\paperproj_openmv_m7_cubemx\Src\main.c with command [\c\Users\iscre\Desktop\paperproj_openmv_m7_cubemx\Src] D:\msys64\mingw64\bin\clang \c\Users\iscre\Desktop\paperproj_openmv_m7_cubemx\Src\main.c
I[18:09:24.044] Couldn't set working directory when creating compiler invocation.
I[18:09:24.048] Couldn't set working directory when building the preamble.
I[18:09:24.086] Couldn't set working directory when building the preamble.
I[18:09:24.099] Dropped diagnostic outside main file: : too many errors emitted, stopping now
I[18:09:24.100] --> textDocument/publishDiagnostics
I[18:09:24.101] --> textDocument/clangd.fileStatus
```

The file path in log looks not right. I run vim and all its environment on msys2 shell, it seems that msys2 will automatically do some unix-style dos-style path conversion. Maybe this is the reason why path go wrong?

**Comment by kadircet** [comment] 2020-03-13 12:20
i suppose you would need to invoke `compiledb` in a non-msys2 environment. compile_commands.json should contain logical windows paths(e.g. C:\Users), instead of remapped msys2 paths(e.g /c/users)

**Comment by kadircet** [comment] 2020-03-18 10:44
this is duplicate of https://github.com/clangd/clangd/issues/291

**Closed by kadircet** 2020-03-18 10:44 UTC
Labels: wontfix

**Comment by iiifr** [comment] 2020-03-19 03:02
I had tried to change file path in compile_commands.json. The same problem still exists. Like the answer in #291 , it seems that the problem is caused by msys shell. In `msys2`, there are two different subsystem: `msys` and `mingw`, the program in first subsystem accept and generate unix-style path, the program in second subsystem accept and generate dos-style path. However, whichever subsystem you choose to enter `msys2`, the shell is always a msys shell, it could accept dos-style path (the path seperator `\` needs to be replaced by `/`), but it always output unix-style path by default.<br/>
Even changing file path in compile_commands.json, `coc.nvim` also has chance to send unix-style file path  to the mingw version clangd, because my `vim` is a `msys` subsystem program, and I run it on msys shell.<br/>
Now I am using a native Windows gvim, and the mingw subsystem of msys2 as its backend. Now clangd works.
