### ISSUE TITLE
Crash when invalid Escape sequences `\N` appear at the end of string

### ISSUE THREAD

**Issue by melodicule** [clangd/clangd#1406] opened 2022-11-30 14:39 UTC
**Code**
```c
#include <stdio.h>
#include <math.h>

int main(int argc, char **argv)
{
#ifdef MY_FLAG
    printf("%d\n\N", argc);
#else
    printf("pi=%.2lf\n",  acos(0) * 2);
#endif
    return 0;
}
```

**logs**
```plain
V[22:24:44.535] indexed preamble AST for /home/$USER/src/clangdtest/main.cpp version 3:
  symbol slab: 1824 symbols, 484728 bytes
  ref slab: 0 symbols, 0 refs, 128 bytes
  relations slab: 0 relations, 24 bytes
V[22:24:44.545] Build dynamic index for header symbols with estimated memory usage of 1986976 bytes
V[22:24:44.546] Built preamble of size 880432 for file /home/$USER/src/clangdtest/main.cpp version 3 in 0.07 seconds
I[22:24:44.546] --> workspace/semanticTokens/refresh(1)
V[22:24:44.546] >>> {"id":1,"jsonrpc":"2.0","method":"workspace/semanticTokens/refresh","params":null}

I[22:24:44.546] --> textDocument/clangd.fileStatus
V[22:24:44.546] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"parsing includes, running Build AST","uri":"file:///home/$USER/src/clangdtest/main.cpp"}}

V[22:24:44.547] <<< {"id":1,"jsonrpc":"2.0","result":null}

I[22:24:44.547] <-- reply(1)
V[22:24:44.579] <<< {"id":5,"jsonrpc":"2.0","method":"textDocument/semanticTokens/full","params":{"textDocument":{"uri":"file:///home/$USER/src/clangdtest/main.cpp"}}}

I[22:24:44.579] <-- textDocument/semanticTokens/full(5)
 #0 0x000055d37bd98b11 PrintStackTraceSignalHandler(void*) Signals.cpp:0:0
 #1 0x000055d37bd96b04 SignalHandler(int) Signals.cpp:0:0
 #2 0x00007f85296c8cb0 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0xfcb0)
 #3 0x000055d37ce2e8e1 clang::clangd::ParsedAST::build(llvm::StringRef, clang::clangd::ParseInputs const&, std::unique_ptr<clang::CompilerInvocation, std::default_delete<clang::CompilerInvocation>>, llvm::ArrayRef<clang::clangd::Diag>, std::shared_ptr<clang::clangd::PreambleData const>)::'lambda0'(clang::DiagnosticsEngine::Level, clang::Diagnostic const&)::operator()(clang::DiagnosticsEngine::Level, clang::Diagnostic const&) const ParsedAST.cpp:0:0
 #4 0x000055d37cd5e5c6 clang::clangd::StoreDiags::HandleDiagnostic(clang::DiagnosticsEngine::Level, clang::Diagnostic const&) (/home/$USER/local/bin/clangd+0x15f05c6)
 #5 0x000055d37c15e270 clang::DiagnosticIDs::ProcessDiag(clang::DiagnosticsEngine&) const (/home/$USER/local/bin/clangd+0x9f0270)
 #6 0x000055d37c1571db clang::DiagnosticsEngine::EmitCurrentDiagnostic(bool) (/home/$USER/local/bin/clangd+0x9e91db)
 #7 0x000055d37c32e44a clang::StringLiteralParser::CopyStringFragment(clang::Token const&, char const*, llvm::StringRef) (/home/$USER/local/bin/clangd+0xbc044a)
 #8 0x000055d37c3367d6 clang::StringLiteralParser::init(llvm::ArrayRef<clang::Token>) (/home/$USER/local/bin/clangd+0xbc87d6)
 #9 0x000055d37c8fd15f clang::Sema::ActOnStringLiteral(llvm::ArrayRef<clang::Token>, clang::Scope*) (/home/$USER/local/bin/clangd+0x118f15f)
#10 0x00007f84f800f6c8 
Signalled during AST worker action: Build AST
  Filename: /home/$USER/src/clangdtest/main.cpp
  Directory: /home/$USER/src/clangdtest
  Command Line: /home/$USER/local/gcc11/bin/gcc -c -O2 -g -DMY_FLAG -o main.o -resource-dir=/home/$USER/local/lib/clang/15.0.6 -- /home/$USER/src/clangdtest/main.cpp
  Version: 3
```

Output of `clangd --version`:
```plain
clangd version 15.0.6
Features: linux
Platform: x86_64-unknown-linux-gnu
```

Editor/LSP plugin:
Visual Studio Code & clangd

Operating system:
Ubuntu 12.04.2, and it also can happen in Windows 10(clangd 15.0.2)

**Comment by sam-mccall** [comment] 2022-11-30 14:50
This doesn't crash on my machine. Could you:
 - make it self-contained? it probably depends on the exact declaration of printf your standard library provides, are you able to move it into the file and remove the include of `<stdio.h>`?
 - reduce it further? is the <math.h>, acos, #ifdef stuff required in order to crash?
 - confirm it crashes with clangd --check=main.cpp

**Comment by melodicule** [comment] 2022-11-30 15:02
Simple content that can make clangd crash.
```sh
echo 'char str[] = "hello, world\n\N";' > test.cpp
clangd --check=test.cpp
```
**output**
```plain
I[22:55:57.715] clangd version 15.0.6
I[22:55:57.715] Features: linux
I[22:55:57.715] PID: 982
I[22:55:57.715] Working directory: /tmp
I[22:55:57.715] argv[0]: clangd
I[22:55:57.715] argv[1]: --check=test.cpp
I[22:55:57.715] Entering check mode (no LSP server)
I[22:55:57.715] Testing on source file /tmp/test.cpp
I[22:55:57.715] Loading compilation database...
I[22:55:57.716] Failed to find compilation database for /tmp/test.cpp
I[22:55:57.716] Generic fallback command is: /home/luotian/local/gcc11/bin/clang -resource-dir=/home/luotian/local/lib/clang/15.0.6 -- /tmp/test.cpp
I[22:55:57.716] Parsing command...
I[22:55:57.717] internal (cc1) args are: -cc1 -triple x86_64-unknown-linux-gnu -fsyntax-only -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name test.cpp -mrelocation-model pic -pic-level 2 -pic-is-pie -mframe-pointer=all -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu x86-64 -tune-cpu generic -mllvm -treat-scalable-fixed-error-as-warning -debugger-tuning=gdb -fcoverage-compilation-dir=/tmp -resource-dir /home/luotian/local/lib/clang/15.0.6 -internal-isystem /home/luotian/local/gcc11/bin/../lib/gcc/x86_64-linux-gnu/11.3.0/../../../../include/c++/11.3.0 -internal-isystem /home/luotian/local/gcc11/bin/../lib/gcc/x86_64-linux-gnu/11.3.0/../../../../include/c++/11.3.0/x86_64-linux-gnu -internal-isystem /home/luotian/local/gcc11/bin/../lib/gcc/x86_64-linux-gnu/11.3.0/../../../../include/c++/11.3.0/backward -internal-isystem /home/luotian/local/lib/clang/15.0.6/include -internal-isystem /usr/local/include -internal-isystem /home/luotian/local/gcc11/bin/../lib/gcc/x86_64-linux-gnu/11.3.0/../../../../x86_64-linux-gnu/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -fdeprecated-macro -fdebug-compilation-dir=/tmp -ferror-limit 19 -fgnuc-version=4.2.1 -fcxx-exceptions -fexceptions -no-round-trip-args -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -x c++ /tmp/test.cpp
I[22:55:57.717] Building preamble...
I[22:55:57.722] Indexing headers...
I[22:55:57.723] Building AST...
 #0 0x0000558558df1b11 PrintStackTraceSignalHandler(void*) Signals.cpp:0:0
 #1 0x0000558558defb04 SignalHandler(int) Signals.cpp:0:0
 #2 0x00007fd26effccb0 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0xfcb0)
 #3 0x000055855938f77c clang::StringLiteralParser::init(llvm::ArrayRef<clang::Token>) (/home/luotian/local/bin/clangd+0xbc877c)
 #4 0x000055855995615f clang::Sema::ActOnStringLiteral(llvm::ArrayRef<clang::Token>, clang::Scope*) (/home/luotian/local/bin/clangd+0x118f15f)
 #5 0x000055855a94e8a6 clang::Parser::ParseStringLiteralExpression(bool) (/home/luotian/local/bin/clangd+0x21878a6)
 #6 0x000055855a952782 clang::Parser::ParseCastExpression(clang::Parser::CastParseKind, bool, bool&, clang::Parser::TypeCastState, bool, bool*) (/home/luotian/local/bin/clangd+0x218b782)
 #7 0x000055855a95550a clang::Parser::ParseCastExpression(clang::Parser::CastParseKind, bool, clang::Parser::TypeCastState, bool, bool*) (/home/luotian/local/bin/clangd+0x218e50a)
 #8 0x000055855a9556d9 clang::Parser::ParseAssignmentExpression(clang::Parser::TypeCastState) (/home/luotian/local/bin/clangd+0x218e6d9)
 #9 0x000055855a91a048 clang::Parser::ParseDeclarationAfterDeclaratorAndAttributes(clang::Declarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::ForRangeInit*) (/home/luotian/local/bin/clangd+0x2153048)
#10 0x000055855a929dfc clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::ParsedAttributes&, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/home/luotian/local/bin/clangd+0x2162dfc)
#11 0x000055855a8fa370 clang::Parser::ParseDeclarationOrFunctionDefinition(clang::ParsedAttributes&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (.part.0) Parser.cpp:0:0
#12 0x000055855a901053 clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsingDeclSpec*) (/home/luotian/local/bin/clangd+0x213a053)
#13 0x000055855a902088 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/home/luotian/local/bin/clangd+0x213b088)
#14 0x000055855a9024e0 clang::Parser::ParseFirstTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/home/luotian/local/bin/clangd+0x213b4e0)
#15 0x000055855a8f3f92 clang::ParseAST(clang::Sema&, bool, bool) (/home/luotian/local/bin/clangd+0x212cf92)
#16 0x000055855a6f8e39 clang::FrontendAction::Execute() (/home/luotian/local/bin/clangd+0x1f31e39)
#17 0x0000558559e90b48 clang::clangd::ParsedAST::build(llvm::StringRef, clang::clangd::ParseInputs const&, std::unique_ptr<clang::CompilerInvocation, std::default_delete<clang::CompilerInvocation>>, llvm::ArrayRef<clang::clangd::Diag>, std::shared_ptr<clang::clangd::PreambleData const>) (/home/luotian/local/bin/clangd+0x16c9b48)
#18 0x0000558558d6f7e0 clang::clangd::check(llvm::StringRef, llvm::Optional<clang::clangd::Range>, clang::clangd::ThreadsafeFS const&, clang::clangd::ClangdLSPServer::Options const&, bool) (/home/luotian/local/bin/clangd+0x5a87e0)
#19 0x0000558558cd62b7 main (/home/luotian/local/bin/clangd+0x50f2b7)
#20 0x00007fd26d8137ed __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x217ed)
#21 0x0000558558cdf101 _start (/home/luotian/local/bin/clangd+0x518101)
段错误 (it means segmentation fault)
```

> This doesn't crash on my machine. Could you:
> 
> * make it self-contained? it probably depends on the exact declaration of printf your standard library provides, are you able to move it into the file and remove the include of `<stdio.h>`?
> * reduce it further? is the <math.h>, acos, #ifdef stuff required in order to crash?
> * confirm it crashes with clangd --check=main.cpp

**Comment by HighCommander4** [comment] 2022-12-02 08:10
I can reproduce this with clangd 15 but not with trunk, suggesting the issue has been fixed on trunk.

@melodicule could you try a weekly snapshot build from https://github.com/clangd/clangd/releases/tag/snapshot_20221127 and see if the crash occurs with that?

**Comment by sam-mccall** [comment] 2022-12-02 08:53
Thanks Nathan, I wasn't able to repro either but forgot to try the release.
It looks like this was fixed in https://reviews.llvm.org/D135161.

Closing as it looks very likely fixed (LMK if not), and the last 15.x release is cut so no chance of a cherrypick.

**Closed by sam-mccall** 2022-12-02 08:53 UTC
