### ISSUE TITLE
clangd crashes after switching to another file

### ISSUE THREAD

**Issue by j-lohuis** [clangd/clangd#2233] opened 2024-11-24 14:28 UTC
When I open a file, clangd analyses it successfully.
If I then open another file that is part of the project,
clangd takes a few seconds to analyze and then crashes.

Unfortunately, it does not seem matter which file I start with and then switch to.
Starting clangd again after it crashed on the switched-to file, leads to the same crash again.

**Logs**

[lsp.log](https://github.com/user-attachments/files/17893613/lsp.log) (Ran with --log=verbose)
This log includes the entire "session" to reproduce the error.
First, I opened a file; clangd works fine here.
Then, I switched to another file; clangd crashes.
Then, I started clangd again (using `:LspStart` command); clangd crashes.

**System information**

Output of `clangd --version`:
clangd version 19.1.0 (https://github.com/llvm/llvm-project a4bf6cd7cfb1a1421ba92bca9d017b49936c55e4)
Features: linux+grpc
Platform: x86_64-unknown-linux-gnu

Editor/LSP plugin:
NVIM v0.10.3-dev-14+gfb5a0e28db
Build type: Release
LuaJIT 2.1.1713484068
nvim-lspconfig

Operating system:
Debian GNU/Linux 12 (bookworm) (Kernel 6.1.0-27-amd64)

**Comment by HighCommander4** [comment] 2024-11-25 03:55
Duplicate of https://github.com/llvm/llvm-project/issues/109367.

**Comment by HighCommander4** [comment] 2024-11-25 03:55
(This is a regression in 19.1.0 that was fixed in 19.1.2.)

**Closed by HighCommander4** 2024-11-25 03:55 UTC
