### ISSUE TITLE
With snippetSupport, clangd adds function 

### ISSUE THREAD

**Issue by rcorre** [clangd/clangd#1531] opened 2023-03-11 19:15 UTC
With snippetSupport enabled:

```
#include <functional>
void thing(std::function<void(int)> fn) { fn(1); }
void stuff(int) {}
int main() {
  thing(&stuff|<tab>
}
```

Gives me

```
thing(&stuff(int)
```

Which isn't helpful. Even if I press `enter` to dismiss the snippet, I get `&stuff()`, which doesn't make sense for a function reference. I just wanted `&stuff`.

**Logs**

Please attach the clangd stderr log if you can. (Usually available from the editor)
If possible, run with `--log=verbose` - note that the logs will include the contents of open files!
If this is a crash, try to put `llvm-symbolizer` on your PATH per the troubleshooting instructions.

The LSP response includes `"insertText":"stuff(${1:int})"`

[helix.log](https://github.com/clangd/clangd/files/10949246/helix.log)

**System information**

Output of `clangd --version`:

clangd version 15.0.7
Features: linux
Platform: x86_64-pc-linux-gnu

Editor/LSP plugin:

Helix

Operating system:

Linux

**Comment by HighCommander4** [comment] 2023-03-12 08:07
Duplicate of #968

**Closed by HighCommander4** 2023-03-12 08:07 UTC
