### ISSUE TITLE
15.0.1 clangd is extremely slow compare to 14.0.3 clangd

### ISSUE THREAD

**Issue by hexhexd** [clangd/clangd#1316] opened 2022-09-29 16:28 UTC
I'm using clangd with LLVM repo. go to definition and find references or go to header file is extremely slow on 15.0.1 clangd compared to the 14.0.3 version. 

Editor/LSP plugin:
vim with coc-nvim plugin

Operating system:
Windows

**Comment by sam-mccall** [comment] 2022-09-29 17:29
Can you provide more details please? Clangd provides logs with timings, -log=verbose will make this more useful.

Does the slowness appear on tiny example files? All code? When specific headers are used?

A hypothesis: if you were previously using clangd 14 on the same project your index was probably up-to-date, clangd 15 will be reindexing that project as the index format changed.

**Comment by daiyousei-qz** [comment] 2022-09-30 15:50
I'm having the same experience where clangd15 spend a ton of time on documentSymbol, but I don't have time to create a simple repro lately.

**Comment by daiyousei-qz** [comment] 2022-10-09 23:09
I did a profiling comprison on the branch llvmorg-15.0.1 and llvmorg-14.0.6
![clangd1501_profile](https://user-images.githubusercontent.com/12378019/194783653-d2ed3684-8393-47b9-aa29-7f1dcef80a04.png)
![clangd1406_profile](https://user-images.githubusercontent.com/12378019/194783656-ca2032e0-39d0-4840-9c86-6c15697b3835.png)

It turns out it's the clang::clangd::IncludeStructure::ReorderHeaders::HandleComment that eats so much time. Unfortunately, I couldn't share with you the code that I reproduce the issue. But my experience is that the 1s delay is stretched into multiple seconds on everything.

Looking into the code, I noticed that the `SM.getCharacterData` call is moved out from the `isMainFile()` predicate. My guess is that now clangd will try to read a ton lot more headers (presumably from disk) every edit. @sam-mccall any comment on why the change is made?

**Comment by sam-mccall** [comment] 2022-10-10 01:40
Fantastic, thank you for digging into this!

https://github.com/llvm/llvm-project/commit/40f361ace3e9a9c24bd99300216aeabd49ad99bb is indeed the culprit. The intention was to change behavior based on IWYU "magic comments" in included headers, not just the main file. However the implementation had a bug that caused slowdown proportional to `#comments * header-length`, i e. quadratic parsing time.

As luck would have it I found and fixed this last week also after looking at profiles, however it was "only" 3-8% on those profiles and I didn't realize it could be so extreme as the examples you showed. In hindsight it seems clear this could vary a lot by codebase- I'm guessing your codebase has some very large header files.

The fix is on the main branch as [5d2d527c32da2081b814ef8b446bc3e037f74b0a](https://github.com/llvm/llvm-project/commit/5d2d527c32da2081b814ef8b446bc3e037f74b0a) but since it's such a potentially huge regression we should get it into the next 15.x release rather than wait for 16. Filed https://github.com/llvm/llvm-project/issues/58256 to get this started.

One thing still unclear to me is the "every edit" nature of the slowdown:

> But my experience is that the usual 1s delay is stretched into multiple seconds on every edit.

For headers included at the top of the file, we shouldn't be re-parsing on every edit. (Specifically those in the "preamble" of preprocessor directives before the first declaration).

Can you confirm that your codebase is #including a (transitively) large volume of headers somewhere *inside* the main file other than at the top? Or that your main file itself is huge?

**Comment by daiyousei-qz** [comment] 2022-10-10 01:54
> Can you confirm that your codebase is #including a (transitively) large volume of headers somewhere inside the main file other than at the top? Or that your main file itself is huge?
Yes, it looks like the source file included <Windows.h> after some declarations. I suppose that could be the problem.

**Comment by sam-mccall** [comment] 2022-10-10 02:11
That would explain it. With this bug fixed it'll be *less* slow but still not great, the 1s you mentioned sounds painful.

There can be reasons it's important to do this (LLVM itself does this), but if you can avoid it then clangd will be much faster. Maybe clangd should add a warning on such includes, at least if they're large...

**Comment by sam-mccall** [comment] 2022-10-23 13:50
OK, this is fixed both on trunk and in 15.0.3, closing.

**Closed by sam-mccall** 2022-10-23 13:50 UTC
