### ISSUE TITLE
Code completion does not prompt the "printf" function

### ISSUE THREAD

**Issue by lh123** [clangd/clangd#27] opened 2019-04-10 10:50 UTC
The code completion in the 'C' file does not prompt the printf function, but works fine in the 'CPP' file.

**test.c**

![image](https://user-images.githubusercontent.com/10697249/55873016-19bad080-5bc1-11e9-8d1c-0671b34dc725.png)

**test.cpp**

![image](https://user-images.githubusercontent.com/10697249/55873048-30f9be00-5bc1-11e9-81c7-fe980141847c.png)

**compile_flags.txt**

```
-target
x86_64-w64-mingw32
```

**Comment by sam-mccall** [comment] 2019-04-10 15:32
Well, that's embarassing. I can reproduce on linux (debian):

```
~/llvmbuild-opt/bin/clangd-indexer /usr/include/stdio.h -format=yaml -extra-arg-before=-xc-header | grep printf
Name:            vdprintf
Name:            _IO_vfprintf
Name:            dprintf
```

C++ works fine:
```
~/llvmbuild-opt/bin/clangd-indexer /usr/include/stdio.h -format=yaml -extra-arg-before=-xc++-header | grep printf
Name:            obstack_vprintf
Name:            vdprintf
Name:            printf
Name:            vsprintf
Name:            _IO_vfprintf
Name:            dprintf
Name:            asprintf
Name:            __asprintf
Name:            vprintf
Name:            sprintf
Name:            snprintf
Name:            vsnprintf
Name:            obstack_printf
Name:            fprintf
Name:            vfprintf
Name:            vasprintf
```

I guess we haven't been writing a lot of C recently. Will dig into it, thanks for the report!

**Comment by sam-mccall** [comment] 2019-04-10 15:49
OK, the problem is related to the name `printf` itself: `void printffff();` indexes in C++ and C mode, `void printf()` indexes in C++ mode only.

Guess: related to the lack of overloading/namespaces in C, so the compiler can simply ignore any decl whose name matches a builtin?

**Comment by kadircet** [comment] 2019-04-10 16:10
I would expect it to be similar to: https://github.com/clangd/clangd/issues/15.

Since we don't deserialize everything from preamble, we are most likely missing "printf".

If you try code-completing after writing printf(to force deserialization of decl), it should work.

**Comment by lh123** [comment] 2019-04-10 16:13
Thank you for your reply.
Yes, most built-in functions, such as scanf and printf, do not appear in the code completion list.

**Comment by sam-mccall** [comment] 2019-04-10 16:28
Fixed in r358098.

@kadircet indeed as we don't deserialize, we won't get this result from the AST (unless the full name is typed).
We should be getting this result from the dynamic index, but it wasn't being indexed. The reason is that in C, the declaration is treated as a redecl of the built-in function, which has the "implicit" bit set.

We don't index implicit symbols, but the fix is to check the implicit bit on the redecl, not the original decl (I think).

**Closed by sam-mccall** 2019-04-10 16:28 UTC
