### ISSUE TITLE
clangd 13.0 crashes with the simplest C++ code

### ISSUE THREAD

**Issue by yaoxinliu** [clangd/clangd#890] opened 2021-10-14 10:18 UTC
The following simplest code is sure to cause `clangd` to crash repeatedly in vscode LSP mode.

```
#include <range/v3/all.hpp>

int main()
{
    auto il = {1, 2, 3};
    ranges::subrange(il.begin(), il.end()); // This line is the culprit!
}
```

```
I[18:10:42.018] <-- textDocument/semanticTokens/full(3)
V[18:11:00.537] indexed preamble AST for /data/lyx/utl/main.cpp version 1:
  symbol slab: 22283 symbols, 5923440 bytes
  ref slab: 0 symbols, 0 refs, 128 bytes
  relations slab: 1217 relations, 34840 bytes
V[18:11:01.099] Build dynamic index for header symbols with estimated memory usage of 12107732 bytes
V[18:11:01.132] Built preamble of size 18693284 for file /data/lyx/utl/main.cpp version 1
I[18:11:01.139] --> workspace/semanticTokens/refresh(0)
I[18:11:01.139] --> textDocument/clangd.fileStatus
V[18:11:01.139] >>> {
  "id": 0,
  "jsonrpc": "2.0",
  "method": "workspace/semanticTokens/refresh",
  "params": null
}

V[18:11:01.139] >>> {
  "jsonrpc": "2.0",
  "method": "textDocument/clangd.fileStatus",
  "params": {
    "state": "parsing includes, running Build AST for (1)",
    "uri": "file:///data/lyx/utl/main.cpp"
  }
}

V[18:11:01.140] <<< {
  "id": 0,
  "jsonrpc": "2.0",
  "result": null
}

I[18:11:01.140] <-- reply(0)
clangd: /data/tmp/llvm-13.0/src/llvm/tools/clang/include/clang/AST/DeclTemplate.h:375: void clang::DefaultArgStorage<clang::TemplateTypeParmDecl, clang::TypeSourceInfo *>::setInherited(const clang::ASTContext &, ParmDecl *) [ParmDecl = clang::TemplateTypeParmDecl, ArgType = clang::TypeSourceInfo *]: Assertion `!isInherited() && "default argument already inherited"' failed.
 #0 0x00000000008aafca llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/usr/local/bin/clangd+0x8aafca)
 #1 0x00000000008ab1ab PrintStackTraceSignalHandler(void*) Signals.cpp:0:0
 #2 0x00000000008a914b llvm::sys::RunSignalHandlers() (/usr/local/bin/clangd+0x8a914b)
 #3 0x00000000008abb91 SignalHandler(int) Signals.cpp:0:0
 #4 0x00007efe0e4183c0 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x153c0)
 #5 0x00007efe0de7618b raise /build/glibc-eX1tMB/glibc-2.31/signal/../sysdeps/unix/sysv/linux/raise.c:51:1
 #6 0x00007efe0de55859 abort /build/glibc-eX1tMB/glibc-2.31/stdlib/abort.c:81:7
 #7 0x00007efe0de55729 get_sysdep_segment_value /build/glibc-eX1tMB/glibc-2.31/intl/loadmsgcat.c:509:8
 #8 0x00007efe0de55729 _nl_load_domain /build/glibc-eX1tMB/glibc-2.31/intl/loadmsgcat.c:970:34
 #9 0x00007efe0de66f36 (/lib/x86_64-linux-gnu/libc.so.6+0x36f36)
#10 0x000000000301857f clang::DefaultArgStorage<clang::TemplateTypeParmDecl, clang::TypeSourceInfo*>::setInherited(clang::ASTContext const&, clang::TemplateTypeParmDecl*) (/usr/local/bin/clangd+0x301857f)
#11 0x00000000030184fe clang::TemplateTypeParmDecl::setInheritedDefaultArgument(clang::ASTContext const&, clang::TemplateTypeParmDecl*) (/usr/local/bin/clangd+0x30184fe)
#12 0x00000000030183fc bool inheritDefaultTemplateArgument<clang::TemplateTypeParmDecl>(clang::ASTContext&, clang::TemplateTypeParmDecl*, clang::Decl*) ASTReaderDecl.cpp:0:0
#13 0x000000000300c5ae inheritDefaultTemplateArguments(clang::ASTContext&, clang::TemplateDecl*, clang::TemplateDecl*) ASTReaderDecl.cpp:0:0
#14 0x000000000300c12c clang::ASTDeclReader::attachPreviousDecl(clang::ASTReader&, clang::Decl*, clang::Decl*, clang::Decl*) (/usr/local/bin/clangd+0x300c12c)
#15 0x00000000030129d0 clang::ASTReader::loadPendingDeclChain(clang::Decl*, unsigned long) (/usr/local/bin/clangd+0x30129d0)
#16 0x0000000002f4cdb4 clang::ASTReader::finishPendingActions() (/usr/local/bin/clangd+0x2f4cdb4)
#17 0x0000000002f5f713 clang::ASTReader::FinishedDeserializing() (/usr/local/bin/clangd+0x2f5f713)
#18 0x0000000000a56f7f clang::ExternalASTSource::Deserializing::~Deserializing() (/usr/local/bin/clangd+0xa56f7f)
#19 0x0000000002f41b67 clang::ASTReader::FindExternalVisibleDeclsByName(clang::DeclContext const*, clang::DeclarationName) (/usr/local/bin/clangd+0x2f41b67)
#20 0x0000000000a7dce8 clang::DeclContext::lookup(clang::DeclarationName) const (/usr/local/bin/clangd+0xa7dce8)
#21 0x0000000000a7dace clang::DeclContext::lookup(clang::DeclarationName) const (/usr/local/bin/clangd+0xa7dace)
#22 0x0000000003d9d3cc clang::Sema::DeclareImplicitDeductionGuides(clang::TemplateDecl*, clang::SourceLocation) (/usr/local/bin/clangd+0x3d9d3cc)
#23 0x0000000003a985d7 DeclareImplicitMemberFunctionsWithName(clang::Sema&, clang::DeclarationName, clang::SourceLocation, clang::DeclContext const*) SemaLookup.cpp:0:0
#24 0x0000000003a9b7d3 LookupDirect(clang::Sema&, clang::LookupResult&, clang::DeclContext const*) SemaLookup.cpp:0:0
#25 0x0000000003a98cd8 clang::Sema::LookupQualifiedName(clang::LookupResult&, clang::DeclContext*, bool) (/usr/local/bin/clangd+0x3a98cd8)
#26 0x0000000003a4e3dc clang::Sema::DeduceTemplateSpecializationFromInitializer(clang::TypeSourceInfo*, clang::InitializedEntity const&, clang::InitializationKind const&, llvm::MutableArrayRef<clang::Expr*>) (/usr/local/bin/clangd+0x3a4e3dc)
#27 0x00000000038b524e clang::Sema::BuildCXXTypeConstructExpr(clang::TypeSourceInfo*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, bool) (/usr/local/bin/clangd+0x38b524e)
#28 0x00000000038b4e35 clang::Sema::ActOnCXXTypeConstructExpr(clang::OpaquePtr<clang::QualType>, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, bool) (/usr/local/bin/clangd+0x38b4e35)
#29 0x0000000002e757e4 clang::Parser::ParseCXXTypeConstructExpression(clang::DeclSpec const&) (/usr/local/bin/clangd+0x2e757e4)
#30 0x0000000002e5cc74 clang::Parser::ParseCastExpression(clang::Parser::CastParseKind, bool, bool&, clang::Parser::TypeCastState, bool, bool*) (/usr/local/bin/clangd+0x2e5cc74)
#31 0x0000000002e550a4 clang::Parser::ParseCastExpression(clang::Parser::CastParseKind, bool, clang::Parser::TypeCastState, bool, bool*) (/usr/local/bin/clangd+0x2e550a4)
#32 0x0000000002e53448 clang::Parser::ParseAssignmentExpression(clang::Parser::TypeCastState) (/usr/local/bin/clangd+0x2e53448)
#33 0x0000000002e532e2 clang::Parser::ParseExpression(clang::Parser::TypeCastState) (/usr/local/bin/clangd+0x2e532e2)
#34 0x0000000002ed8db4 clang::Parser::ParseExprStatement(clang::Parser::ParsedStmtContext) (/usr/local/bin/clangd+0x2ed8db4)
#35 0x0000000002ed77d9 clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::ParsedAttributesWithRange&) (/usr/local/bin/clangd+0x2ed77d9)
#36 0x0000000002ed70f9 clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*) (/usr/local/bin/clangd+0x2ed70f9)
#37 0x0000000002edf88c clang::Parser::ParseCompoundStatementBody(bool) (/usr/local/bin/clangd+0x2edf88c)
#38 0x0000000002ee115b clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) (/usr/local/bin/clangd+0x2ee115b)
#39 0x0000000002dec5b6 clang::Parser::ParseFunctionDefinition(clang::ParsingDeclarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::LateParsedAttrList*) (/usr/local/bin/clangd+0x2dec5b6)
#40 0x0000000002e1189d clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/usr/local/bin/clangd+0x2e1189d)
#41 0x0000000002deafb7 clang::Parser::ParseDeclOrFunctionDefInternal(clang::ParsedAttributesWithRange&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/usr/local/bin/clangd+0x2deafb7)
#42 0x0000000002dea4d0 clang::Parser::ParseDeclarationOrFunctionDefinition(clang::ParsedAttributesWithRange&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (/usr/local/bin/clangd+0x2dea4d0)
#43 0x0000000002de9adf clang::Parser::ParseExternalDeclaration(clang::ParsedAttributesWithRange&, clang::ParsingDeclSpec*) (/usr/local/bin/clangd+0x2de9adf)
#44 0x0000000002de7ab1 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, bool) (/usr/local/bin/clangd+0x2de7ab1)
#45 0x0000000002de7303 clang::Parser::ParseFirstTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&) (/usr/local/bin/clangd+0x2de7303)
#46 0x0000000002de1dce clang::ParseAST(clang::Sema&, bool, bool) (/usr/local/bin/clangd+0x2de1dce)
#47 0x0000000002c21a62 clang::ASTFrontendAction::ExecuteAction() (/usr/local/bin/clangd+0x2c21a62)
#48 0x0000000002c21198 clang::FrontendAction::Execute() (/usr/local/bin/clangd+0x2c21198)
#49 0x000000000176cdb2 clang::clangd::ParsedAST::build(llvm::StringRef, clang::clangd::ParseInputs const&, std::unique_ptr<clang::CompilerInvocation, std::default_delete<clang::CompilerInvocation> >, llvm::ArrayRef<clang::clangd::Diag>, std::shared_ptr<clang::clangd::PreambleData const>) (/usr/local/bin/clangd+0x176cdb2)
#50 0x00000000018e8181 clang::clangd::(anonymous namespace)::ASTWorker::generateDiagnostics(std::unique_ptr<clang::CompilerInvocation, std::default_delete<clang::CompilerInvocation> >, clang::clangd::ParseInputs, std::vector<clang::clangd::Diag, std::allocator<clang::clangd::Diag> >) TUScheduler.cpp:0:0
#51 0x00000000018e7aaa clang::clangd::(anonymous namespace)::ASTWorker::updatePreamble(std::unique_ptr<clang::CompilerInvocation, std::default_delete<clang::CompilerInvocation> >, clang::clangd::ParseInputs, std::shared_ptr<clang::clangd::PreambleData const>, std::vector<clang::clangd::Diag, std::allocator<clang::clangd::Diag> >, clang::clangd::WantDiagnostics)::$_2::operator()() TUScheduler.cpp:0:0
#52 0x00000000018ebeed void llvm::detail::UniqueFunctionBase<void>::CallImpl<clang::clangd::(anonymous namespace)::ASTWorker::updatePreamble(std::unique_ptr<clang::CompilerInvocation, std::default_delete<clang::CompilerInvocation> >, clang::clangd::ParseInputs, std::shared_ptr<clang::clangd::PreambleData const>, std::vector<clang::clangd::Diag, std::allocator[Error - 6:11:03 PM] Connection to server got closed. Server will not be restarted.
[Error - 6:11:03 PM] Request textDocument/documentSymbol failed.
[object Object]
[Error - 6:11:03 PM] Request textDocument/codeAction failed.
[object Object]
[Error - 6:11:03 PM] Request textDocument/semanticTokens/full failed.
[object Object]

```
Please attach the clangd stderr log if you can. (Usually available from the editor)
If possible, run with `--log=verbose` - note that the logs will include the contents of open files!
If this is a crash, try to put `llvm-symbolizer` on your PATH per the troubleshooting instructions.

**System information**

Output of `clangd --version`:
```
clangd version 13.0.0
Features: linux+debug
Platform: x86_64-unknown-linux-gnu
```

Editor/LSP plugin: `vscode 16.1`

Operating system: `Ubuntu 20.04`

**Comment by sam-mccall** [comment] 2021-11-02 20:08
Looks like a clang bug in AST [de]serialization. Minimized:

```cpp
// header.h
template<char = 'x'> struct S;

template<char> struct S {
    template<int> requires(false) S();
    template<int> requires(true) S();
};

template<typename T> S(T) -> S<>;
```

```cpp
// main.cpp
void foo() {
  S(0); // Simply ::x; is enough to crash!
}
```

**Comment by sam-mccall** [comment] 2021-11-02 20:13
And the top of the stack from a debug build:
```
clangd: ./llvm-project/clang/include/clang/AST/DeclTemplate.h:375: void clang::DefaultArgStorage<clang::NonTypeTemplateParmDecl, clang::Expr *>::setInherited(const clang::ASTContext &, ParmDecl *) [ParmDecl = clang::NonTypeTemplateParmDecl, ArgType = clang::Expr *]: Assertion `!isInherited() && "default argument already inherited"' failed.
 #0 0x0000000000c1daf3 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) ./llvm-project/llvm/lib/Support/Unix/Signals.inc:565:13
 #1 0x0000000000c1b8fc llvm::sys::RunSignalHandlers() ./llvm-project/llvm/lib/Support/Signals.cpp:98:18
 #2 0x0000000000c1de5f SignalHandler(int) ./llvm-project/llvm/lib/Support/Unix/Signals.inc:407:1
 #3 0x00007f7b807a48e0 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x138e0)
 #4 0x00007f7b8023ee71 raise ./signal/../sysdeps/unix/sysv/linux/raise.c:50:1
 #5 0x00007f7b80228536 abort ./stdlib/abort.c:81:7
 #6 0x00007f7b8022841f get_sysdep_segment_value ./intl/loadmsgcat.c:509:8
 #7 0x00007f7b8022841f _nl_load_domain ./intl/loadmsgcat.c:970:34
 #8 0x00007f7b802377f2 (/lib/x86_64-linux-gnu/libc.so.6+0x357f2)
 #9 0x00000000018856ca getParmOwningDefaultArg ./llvm-project/clang/include/clang/AST/DeclTemplate.h:330:5
#10 0x00000000018856ca clang::DefaultArgStorage<clang::NonTypeTemplateParmDecl, clang::Expr*>::setInherited(clang::ASTContext const&, clang::NonTypeTemplateParmDecl*) ./llvm-project/clang/include/clang/AST/DeclTemplate.h:376:21
#11 0x0000000002257119 setInheritedDefaultArgument ./llvm-project/clang/include/clang/AST/DeclTemplate.h:0:21
#12 0x0000000002257119 inheritDefaultTemplateArgument<clang::NonTypeTemplateParmDecl> ./llvm-project/clang/lib/Serialization/ASTReaderDecl.cpp:3728:7
#13 0x0000000002257119 inheritDefaultTemplateArguments ./llvm-project/clang/lib/Serialization/ASTReaderDecl.cpp:3746:7
#14 0x0000000002257119 clang::ASTDeclReader::attachPreviousDecl(clang::ASTReader&, clang::Decl*, clang::Decl*, clang::Decl*) ./llvm-project/clang/lib/Serialization/ASTReaderDecl.cpp:3778:5
#15 0x000000000225c20b clang::ASTReader::loadPendingDeclChain(clang::Decl*, unsigned long) ./llvm-project/clang/lib/Serialization/ASTReaderDecl.cpp:4317:8
#16 0x00000000021f43c3 size ./llvm-project/llvm/include/llvm/ADT/SmallVector.h:70:32
#17 0x00000000021f43c3 clang::ASTReader::finishPendingActions() ./llvm-project/clang/lib/Serialization/ASTReader.cpp:9195:49
#18 0x000000000220ab20 clang::ASTReader::FinishedDeserializing() ./llvm-project/clang/lib/Serialization/ASTReader.cpp:11541:3
#19 0x00000000021ebd77 ~Deserializing ./llvm-project/clang/include/clang/AST/ExternalASTSource.h:0:15
#20 0x00000000021ebd77 clang::ASTReader::FindExternalVisibleDeclsByName(clang::DeclContext const*, clang::DeclarationName) ./llvm-project/clang/lib/Serialization/ASTReader.cpp:7639:1
#21 0x0000000000d3253a clang::DeclContext::lookup(clang::DeclarationName) const ./llvm-project/clang/lib/AST/DeclBase.cpp:1683:60
#22 0x000000000183806e operator!=<clang::NamedDecl *, clang::DeclListNode *> ./llvm-project/llvm/include/llvm/ADT/PointerUnion.h:213:31
#23 0x000000000183806e operator!= ./llvm-project/clang/include/clang/AST/DeclBase.h:1267:59
#24 0x000000000183806e clang::Sema::DeclareImplicitDeductionGuides(clang::TemplateDecl*, clang::SourceLocation) ./llvm-project/clang/lib/Sema/SemaTemplate.cpp:2469:16
#25 0x0000000001472b9a getName ./llvm-project/clang/include/clang/AST/DeclarationName.h:781:44
#26 0x0000000001472b9a getLookupName ./llvm-project/clang/include/clang/Sema/Lookup.h:244:21
#27 0x0000000001472b9a LookupDirect(clang::Sema&, clang::LookupResult&, clang::DeclContext const*) ./llvm-project/clang/lib/Sema/SemaLookup.cpp:1097:48
#28 0x000000000146eaab clang::Sema::LookupQualifiedName(clang::LookupResult&, clang::DeclContext*, bool) ./llvm-project/clang/lib/Sema/SemaLookup.cpp:2178:7
#29 0x000000000155b9af suppressDiagnostics ./llvm-project/clang/include/clang/Sema/Lookup.h:584:14
#30 0x000000000155b9af clang::Sema::DeduceTemplateSpecializationFromInitializer(clang::TypeSourceInfo*, clang::InitializedEntity const&, clang::InitializationKind const&, llvm::MutableArrayRef<clang::Expr*>) ./llvm-project/clang/lib/Sema/SemaInit.cpp:10017:10
#31 0x00000000015dda7c clang::Sema::BuildCXXTypeConstructExpr(clang::TypeSourceInfo*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, bool) ./llvm-project/clang/lib/Sema/SemaExprCXX.cpp:1472:8
#32 0x00000000015dd853 clang::Sema::ActOnCXXTypeConstructExpr(clang::OpaquePtr<clang::QualType>, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, bool) ./llvm-project/clang/lib/Sema/SemaExprCXX.cpp:1427:17
```

**Comment by HighCommander4** [comment] 2021-11-14 06:58
The reduced example is invalid right? There is no way for the constructor's template argument to be deduced.

**Comment by HighCommander4** [comment] 2021-11-14 07:22
It is however easy to make the code valid but still crash:

```c++
// header.h
template<char = 'x'> struct S;

template<char> struct S {
    template<typename U> requires(false) S(U);
    template<typename U> requires(true) S(U);
};

template<typename T> S(T) -> S<>;
```

**Comment by HighCommander4** [comment] 2021-11-15 09:18
The proximate cause of the issue is that [`inheritDefaultTemplateArgument()`](https://searchfox.org/llvm/rev/355ee18c5df9364f315f2bfad1793dd54efe6c9b/clang/lib/Serialization/ASTReaderDecl.cpp#3730) is called with its `From` and `ToD` parameters pointing to the smae `NontypeTemplateParmDecl`, which seems wrong.

In the [caller](https://searchfox.org/llvm/rev/355ee18c5df9364f315f2bfad1793dd54efe6c9b/clang/lib/Serialization/ASTReaderDecl.cpp#3739) of this function, the `From` and `To` templates appear to be the implicit deduction guide templates generated by the two constructors. The template parameter lists of these deduction guide templates consist of the template parameters of the class, followed by the template parameters of the constructor. The template parameters of the class are shared by the two, this is how the two parameter objects come to be the same.

Accordingly, [this patch](https://reviews.llvm.org/D113874) fixes the crash for me, both on the reduced testcase and the original one involving range v3. However, I'm unsure whether this is the right fix, or if e.g. `inheritDefaultTemplateArguments()` is not supposed to be called with these templates in the first place.

**Comment by HighCommander4** [comment] 2022-01-31 07:37
> Accordingly, [this patch](https://reviews.llvm.org/D113874) fixes the crash for me, both on the reduced testcase and the original one involving range-v3. However, I'm unsure whether this is the right fix, or if e.g. `inheritDefaultTemplateArguments()` is not supposed to be called with these templates in the first place.

Having thought more about this, I'm now convinced that `inheritDefaultTemplateArguments()` should not be called with these implicit deduction guide templates in the first place (and therefore my fix is not the correct one).

Template arguments should only be inherited between redeclarations of the **same** entity. In this case, the implicit deduction guide templates are generated from the two constructors, which are distinct entities (since they have different constraints), which should make the guides distinct entities as well.

The reason clang thinks the two guide decls are redeclarations of the same entity is that the transformation from the constructors into the guides does not preserve the requires-clause. [Here](https://searchfox.org/llvm/rev/dd995acedadfa27bca4e64f4cec4fa77c350adbe/clang/lib/Sema/SemaTemplate.cpp#2187)'s the relevant line which builds the template parameter list (which is what stores the requires-clause) of the implicit guide template:

```c++
      TemplateParams = TemplateParameterList::Create(
          SemaRef.Context, InnerParams->getTemplateLoc(),
          InnerParams->getLAngleLoc(), AllParams, InnerParams->getRAngleLoc(),
          /*FIXME: RequiresClause*/ nullptr);
```

Note the `/*FIXME: RequiresClause*/`. Whoops.

**Comment by HighCommander4** [comment] 2022-01-31 07:48
It's worth noting that this error is introduced into the AST **before** serialization; the serialization just preserves it. I'm not sure why it doesn't cause a problem when compiling the code normally, without serialization involved. (The answer may be uninteresting, like this particular redeclaration-matching codepath only runs when deserializing decls and not when creating these kinds of implicit decls normally.)

In any case, resolving the `FIXME` by passing in an appropriate requires-clause there seems like the correct fix approach.

**Comment by HighCommander4** [comment] 2022-01-31 08:53
[Proposed fix](https://reviews.llvm.org/D113874)

**Closed** 2022-03-25 06:46 UTC
Labels: bug, upstream
