### ISSUE TITLE
clangd "--query-driver" option doesn't follow symlinks

### ISSUE THREAD

**Issue by jcarrete5** [clangd/clangd#1975] opened 2024-03-16 16:10 UTC
When I run clangd with the `--query-driver` option set to a path containing a symlink, the argument has no effect and I still have missing system headers. In the following case, `<iostream>` can't be found.

```C++
#include <iostream>

int main(int argc, char* argv[])
{
    std::cout << "hi\n";
    return 0;
}
```

I can work around this issue by using the complete path without any symlinks.

Within the logs, the `oe-workdir` path item is a symlink to another location.

**Logs**

Please attach the clangd stderr log if you can. (Usually available from the editor)
If possible, run with `--log=verbose` - note that the logs will include the contents of open files!
If this is a crash, try to put `llvm-symbolizer` on your PATH per the troubleshooting instructions.

```
[START][2024-03-16 12:09:47] LSP logging initiated
[ERROR][2024-03-16 12:09:47] .../vim/lsp/rpc.lua:734	"rpc"	"/usr/bin/clangd"	"stderr"	'I[12:09:47.584] clangd version 17.0.6\nI[12:09:47.584] Features: linux\nI[12:09:47.584] PID: 102869\nI[12:09:47.584] Working directory: /home/jasonc/projects/quadcopter/albatros/build/workspace/sources/freeflight\nI[12:09:47.584] argv[0]: /usr/bin/clangd\nI[12:09:47.584] argv[1]: --log=verbose\nI[12:09:47.584] argv[2]: --query-driver=/home/jasonc/projects/quadcopter/albatros/build/workspace/sources/freeflight/oe-workdir/recipe-sysroot-native/usr/bin/aarch64-poky-linux/aarch64-poky-linux-g++\nV[12:09:47.584] User config file is /home/jasonc/.config/clangd/config.yaml\nI[12:09:47.584] Starting LSP over stdin/stdout\nV[12:09:47.584] <<< {"id":1,"jsonrpc":"2.0","method":"initialize","params":{"capabilities":{"offsetEncoding":["utf-8","utf-16"],"textDocument":{"callHierarchy":{"dynamicRegistration":false},"codeAction":{"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}},"dataSupport":true,"dynamicRegistration":false,"isPreferredSupport":true,"resolveSupport":{"properties":["edit"]}},"completion":{"completionItem":{"commitCharactersSupport":true,"deprecatedSupport":true,"documentationFormat":["markdown","plaintext"],"insertReplaceSupport":true,"insertTextModeSupport":{"valueSet":[1,2]},"labelDetailsSupport":true,"preselectSupport":true,"resolveSupport":{"properties":["documentation","detail","additionalTextEdits","sortText","filterText","insertText","textEdit","insertTextFormat","insertTextMode"]},"snippetSupport":true,"tagSupport":{"valueSet":[1]}},"completionItemKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]},"completionList":{"itemDefaults":["commitCharacters","editRange","insertTextFormat","insertTextMode","data"]},"contextSupport":true,"dynamicRegistration":false,"editsNearCursor":true,"insertTextMode":1},"declaration":{"linkSupport":true},"definition":{"linkSupport":true},"documentHighlight":{"dynamicRegistration":false},"documentSymbol":{"dynamicRegistration":false,"hierarchicalDocumentSymbolSupport":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]}},"hover":{"contentFormat":["markdown","plaintext"],"dynamicRegistration":false},"implementation":{"linkSupport":true},"publishDiagnostics":{"relatedInformation":true,"tagSupport":{"valueSet":[1,2]}},"references":{"dynamicRegistration":false},"rename":{"dynamicRegistration":false,"prepareSupport":true},"semanticTokens":{"augmentsSyntaxTokens":true,"dynamicRegistration":false,"formats":["relative"],"multilineTokenSupport":false,"overlappingTokenSupport":true,"requests":{"full":{"delta":true},"range":false},"serverCancelSupport":false,"tokenModifiers":["declaration","definition","readonly","static","deprecated","abstract","async","modification","documentation","defaultLibrary"],"tokenTypes":["namespace","type","class","enum","interface","struct","typeParameter","parameter","variable","property","enumMember","event","function","method","macro","keyword","modifier","comment","string","number","regexp","operator","decorator"]},"signatureHelp":{"dynamicRegistration":false,"signatureInformation":{"activeParameterSupport":true,"documentationFormat":["markdown","plaintext"],"parameterInformation":{"labelOffsetSupport":true}}},"synchronization":{"didSave":true,"dynamicRegistration":false,"willSave":true,"willSaveWaitUntil":true},"typeDefinition":{"linkSupport":true}},"window":{"showDocument":{"support":true},"showMessage":{"messageActionItem":{"additionalPropertiesSupport":false}},"workDoneProgress":true},"workspace":{"applyEdit":true,"configuration":true,"didChangeWatchedFiles":{"dynamicRegistration":false,"relativePatternSupport":true},"semanticTokens":{"refreshSupport":true},"symbol":{"dynamicRegistration":false,"hierarchicalWorkspaceSymbolSupport":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]}},"workspaceEdit":{"resourceOperations":["rename","create","delete"]},"workspaceFolders":true}},"clientInfo":{"name":"Neovim","version":"0.9.5"},"initializationOptions":{},"processId":102865,"rootPath":"/home/jasonc/projects/quadcopter/albatros/build/workspace/sources/freeflight","rootUri":"file:///home/jasonc/projects/quadcopter/albatros/build/workspace/sources/freeflight","trace":"off","workspaceFolders":[{"name":"/home/jasonc/projects/quadcopter/albatros/build/workspace/sources/freeflight","uri":"file:///home/jasonc/projects/quadcopter/albatros/build/workspace/sources/freeflight"}]}}\n\nI[12:09:47.584] <-- initialize(1)\nI[12:09:47.585] --> reply:initialize(1) 0 ms\nV[12:09:47.585] >>> {"id":1,"jsonrpc":"2.0","result":{"capabilities":{"astProvider":true,"callHierarchyProvider":true,"clangdInlayHintsProvider":true,"codeActionProvider":{"codeActionKinds":["quickfix","refactor","info"]},"compilationDatabase":{"automaticReload":true},"completionProvider":{"resolveProvider":false,"triggerCharacters":[".","<",">",":","\\"","/","*"]},"declarationProvider":true,"definitionProvider":true,"documentFormattingProvider":true,"documentHighlightProvider":true,"documentLinkProvider":{"resolveProvider":false},"documentOnTypeFormattingProvider":{"firstTriggerCharacter":"\\n","moreTriggerCharacter":[]},"documentRangeFormattingProvider":true,"documentSymbolProvider":true,"executeCommandProvider":{"commands":["clangd.applyFix","clangd.applyTweak"]},"foldingRangeProvider":true,"hoverProvider":true,"implementationProvider":true,"inactiveRegionsProvider":true,"inlayHintProvider":true,"memoryUsageProvider":true,"referencesProvider":true,"renameProvider":{"prepareProvider":true},"selectionRangeProvider":true,"semanticTokensProvider":{"full":{"delta":true},"legend":{"tokenModifiers":["declaration","definition","deprecated","deduced","readonly","static","abstract","virtual","dependentName","defaultLibrary","usedAsMutableReference","usedAsMutablePointer","constructorOrDestructor","userDefined","functionScope","classScope","fileScope","globalScope"],"tokenTypes":["variable","variable","parameter","function","method","function","property","variable","class","interface","enum","enumMember","type","type","unknown","namespace","typeParameter","concept","type","macro","modifier","operator","bracket","label","comment"]},"range":false},"signatureHelpProvider":{"triggerCharacters":["(",")","{","}","<",">",","]},"standardTypeHierarchyProvider":true,"textDocumentSync":{"change":2,"openClose":true,"save":true},"typeDefinitionProvider":true,"typeHierarchyProvider":true,"workspaceSymbolProvider":true},"offsetEncoding":"utf-8","serverInfo":{"name":"clangd","version":"clangd version 17.0.6 linux x86_64-pc-linux-gnu"}}}\n\n'
[ERROR][2024-03-16 12:09:47] .../vim/lsp/rpc.lua:734	"rpc"	"/usr/bin/clangd"	"stderr"	"V[12:09:47.699] <<< {\"jsonrpc\":\"2.0\",\"method\":\"initialized\",\"params\":{}}\n\nI[12:09:47.699] <-- initialized\nV[12:09:47.699] <<< {\"jsonrpc\":\"2.0\",\"method\":\"textDocument/didOpen\",\"params\":{\"textDocument\":{\"languageId\":\"cpp\",\"text\":\"/*\\n * SPDX-License-Identifier: GPL-3.0-or-later\\n *\\n * Copyright (C) 2023 Jason Carrete\\n *\\n * This file is part of Flight Controller.\\n *\\n * Flight Controller is free software: you can redistribute it and/or modify\\n * it under the terms of the GNU General Public License as published by\\n * the Free Software Foundation, either version 3 of the License, or\\n * (at your option) any later version.\\n *\\n * This program is distributed in the hope that it will be useful,\\n * but WITHOUT ANY WARRANTY; without even the implied warranty of\\n * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\\n * GNU General Public License for more details.\\n *\\n * You should have received a copy of the GNU General Public License\\n * along with this program.  If not, see <https://www.gnu.org/licenses/>.\\n */\\n\\n#include \\\"appinfo.h\\\"\\n#include \\\"version.h\\\"\\n\\n#include <iostream>\\n\\nnamespace ffd = freeflight_daemon;\\n\\nint main(int argc, char* argv[])\\n{\\n    std::cout << ffd::get_app_name() << ' ' << freeflight::get_version() << ' '\\n              << freeflight::get_name() << '\\\\n';\\n    return 0;\\n}\\n\",\"uri\":\"file:///home/jasonc/projects/quadcopter/albatros/build/workspace/sources/freeflight/src/flightd/main.cpp\",\"version\":0}}}\n\nI[12:09:47.699] <-- textDocument/didOpen\nV[12:09:47.699] System include extraction: driver clang expanded to /usr/bin/clang\nV[12:09:47.699] System include extraction: not allowed driver /usr/bin/clang\n"
[ERROR][2024-03-16 12:09:47] .../vim/lsp/rpc.lua:734	"rpc"	"/usr/bin/clangd"	"stderr"	'V[12:09:47.700] <<< {"id":2,"jsonrpc":"2.0","method":"textDocument/semanticTokens/full","params":{"textDocument":{"uri":"file:///home/jasonc/projects/quadcopter/albatros/build/workspace/sources/freeflight/src/flightd/main.cpp"}}}\n\n'
[ERROR][2024-03-16 12:09:47] .../vim/lsp/rpc.lua:734	"rpc"	"/usr/bin/clangd"	"stderr"	"I[12:09:47.700] <-- textDocument/semanticTokens/full(2)\n"
[ERROR][2024-03-16 12:09:47] .../vim/lsp/rpc.lua:734	"rpc"	"/usr/bin/clangd"	"stderr"	"V[12:09:47.700] config note at /home/jasonc/projects/quadcopter/albatros/build/workspace/sources/freeflight/.clangd:1:0: Parsing config fragment\n"
[ERROR][2024-03-16 12:09:47] .../vim/lsp/rpc.lua:734	"rpc"	"/usr/bin/clangd"	"stderr"	"V[12:09:47.700] config note at /home/jasonc/projects/quadcopter/albatros/build/workspace/sources/freeflight/.clangd:1:0: Parsed 1 fragments from file\nV[12:09:47.700] Config fragment: compiling /home/jasonc/projects/quadcopter/albatros/build/workspace/sources/freeflight/.clangd:1 -> 0x0000724F50003730 (trusted=false)\n"
[ERROR][2024-03-16 12:09:47] .../vim/lsp/rpc.lua:734	"rpc"	"/usr/bin/clangd"	"stderr"	"I[12:09:47.701] --> textDocument/publishDiagnostics\n"
[ERROR][2024-03-16 12:09:47] .../vim/lsp/rpc.lua:734	"rpc"	"/usr/bin/clangd"	"stderr"	'V[12:09:47.701] >>> {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[],"uri":"file:///home/jasonc/projects/quadcopter/albatros/build/workspace/sources/freeflight/.clangd"}}\n\n'
[ERROR][2024-03-16 12:09:47] .../vim/lsp/rpc.lua:734	"rpc"	"/usr/bin/clangd"	"stderr"	"I[12:09:47.701] Loaded compilation database from /home/jasonc/projects/quadcopter/albatros/build/workspace/sources/freeflight/compile_commands.json\n"
[ERROR][2024-03-16 12:09:47] .../vim/lsp/rpc.lua:734	"rpc"	"/usr/bin/clangd"	"stderr"	"V[12:09:47.701] Broadcasting compilation database from /home/jasonc/projects/quadcopter/albatros/build/workspace/sources/freeflight\n"
[ERROR][2024-03-16 12:09:47] .../vim/lsp/rpc.lua:734	"rpc"	"/usr/bin/clangd"	"stderr"	"V[12:09:47.701] System include extraction: not allowed driver /home/jasonc/projects/quadcopter/albatros/build/tmp/work/cortexa57-poky-linux/freeflight/1.0+git/recipe-sysroot-native/usr/bin/aarch64-poky-linux/aarch64-poky-linux-g++\n"
[ERROR][2024-03-16 12:09:47] .../vim/lsp/rpc.lua:734	"rpc"	"/usr/bin/clangd"	"stderr"	"I[12:09:47.701] ASTWorker building file /home/jasonc/projects/quadcopter/albatros/build/workspace/sources/freeflight/src/flightd/main.cpp version 0 with command \n[/home/jasonc/projects/quadcopter/albatros/build/tmp/work/cortexa57-poky-linux/freeflight/1.0+git/freeflight-1.0+git]\n/home/jasonc/projects/quadcopter/albatros/build/tmp/work/cortexa57-poky-linux/freeflight/1.0+git/recipe-sysroot-native/usr/bin/aarch64-poky-linux/aarch64-poky-linux-g++ --target=aarch64-poky-linux --driver-mode=g++ --sysroot=/home/jasonc/projects/quadcopter/albatros/build/tmp/work/cortexa57-poky-linux/freeflight/1.0+git/recipe-sysroot -I/home/jasonc/projects/quadcopter/albatros/build/workspace/sources/freeflight/src/flightd -I/home/jasonc/projects/quadcopter/albatros/build/workspace/sources/freeflight/src/freeflight/public -mcpu=cortex-a57 -march=armv8-a+crc -mbranch-protection=standard -fstack-protector-strong -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=/home/jasonc/projects/quadcopter/albatros/build/tmp/work/cortexa57-poky-linux/freeflight/1.0+git/recipe-sysroot -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/home/jasonc/projects/quadcopter/albatros/build/workspace/sources/freeflight=/usr/src/debug/freeflight/1.0+git-r0 -fdebug-prefix-map=/home/jasonc/projects/quadcopter/albatros/build/workspace/sources/freeflight=/usr/src/debug/freeflight/1.0+git-r0 -fmacro-prefix-map=/home/jasonc/projects/quadcopter/albatros/build/tmp/work/cortexa57-poky-linux/freeflight/1.0+git/freeflight-1.0+git=/usr/src/debug/freeflight/1.0+git-r0 -fdebug-prefix-map=/home/jasonc/projects/quadcopter/albatros/build/tmp/work/cortexa57-poky-linux/freeflight/1.0+git/freeflight-1.0+git=/usr/src/debug/freeflight/1.0+git-r0 -fdebug-prefix-map=/home/jasonc/projects/quadcopter/albatros/build/tmp/work/cortexa57-poky-linux/freeflight/1.0+git/recipe-sysroot= -fmacro-prefix-map=/home/jasonc/projects/quadcopter/albatros/build/tmp/work/cortexa57-poky-linux/freeflight/1.0+git/recipe-sysroot= -fdebug-prefix-map=/home/jasonc/projects/quadcopter/albatros/build/tmp/work/cortexa57-poky-linux/freeflight/1.0+git/recipe-sysroot-native= -fvisibility-inlines-hidden -O2 -g -DNDEBUG -std=gnu++20 -o src/flightd/CMakeFiles/flightd.dir/main.cpp.o -c -resource-dir=/usr/lib/clang/17 -- /home/jasonc/projects/quadcopter/albatros/build/workspace/sources/freeflight/src/flightd/main.cpp\n"
[ERROR][2024-03-16 12:09:47] .../vim/lsp/rpc.lua:734	"rpc"	"/usr/bin/clangd"	"stderr"	"I[12:09:47.702] Loaded compilation database from /home/jasonc/projects/quadcopter/albatros/build/tmp/work/cortexa57-poky-linux/freeflight/1.0+git/freeflight-1.0+git/compile_commands.json\n"
[ERROR][2024-03-16 12:09:47] .../vim/lsp/rpc.lua:734	"rpc"	"/usr/bin/clangd"	"stderr"	"I[12:09:47.702] --> window/workDoneProgress/create(0)\n"
[ERROR][2024-03-16 12:09:47] .../vim/lsp/rpc.lua:734	"rpc"	"/usr/bin/clangd"	"stderr"	'V[12:09:47.702] >>> {"id":0,"jsonrpc":"2.0","method":"window/workDoneProgress/create","params":{"token":"backgroundIndexProgress"}}\n\n'
[ERROR][2024-03-16 12:09:47] .../vim/lsp/rpc.lua:734	"rpc"	"/usr/bin/clangd"	"stderr"	"I[12:09:47.702] Enqueueing 1 commands for indexing\n"
[ERROR][2024-03-16 12:09:47] .../vim/lsp/rpc.lua:734	"rpc"	"/usr/bin/clangd"	"stderr"	"V[12:09:47.702] Driver produced command: cc1 -cc1 -triple aarch64-poky-linux -fsyntax-only -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name main.cpp -mrelocation-model pic -pic-level 2 -pic-is-pie -mframe-pointer=non-leaf -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu cortex-a57 -target-feature +neon -target-feature +v8a -target-feature +crc -target-abi aapcs -msign-return-address=non-leaf -msign-return-address-key=a_key -mbranch-target-enforce -debug-info-kind=constructor -dwarf-version=5 -debugger-tuning=gdb -fcoverage-compilation-dir=/home/jasonc/projects/quadcopter/albatros/build/tmp/work/cortexa57-poky-linux/freeflight/1.0+git/freeflight-1.0+git -resource-dir /usr/lib/clang/17 -I /home/jasonc/projects/quadcopter/albatros/build/workspace/sources/freeflight/src/flightd -I /home/jasonc/projects/quadcopter/albatros/build/workspace/sources/freeflight/src/freeflight/public -D _FORTIFY_SOURCE=2 -D NDEBUG -isysroot /home/jasonc/projects/quadcopter/albatros/build/tmp/work/cortexa57-poky-linux/freeflight/1.0+git/recipe-sysroot -internal-isystem /usr/lib/clang/17/include -internal-isystem /home/jasonc/projects/quadcopter/albatros/build/tmp/work/cortexa57-poky-linux/freeflight/1.0+git/recipe-sysroot/usr/local/include -internal-externc-isystem /home/jasonc/projects/quadcopter/albatros/build/tmp/work/cortexa57-poky-linux/freeflight/1.0+git/recipe-sysroot/include -internal-externc-isystem /home/jasonc/projects/quadcopter/albatros/build/tmp/work/cortexa57-poky-linux/freeflight/1.0+git/recipe-sysroot/usr/include -fmacro-prefix-map=/home/jasonc/projects/quadcopter/albatros/build/workspace/sources/freeflight=/usr/src/debug/freeflight/1.0+git-r0 -fmacro-prefix-map=/home/jasonc/projects/quadcopter/albatros/build/tmp/work/cortexa57-poky-linux/freeflight/1.0+git/freeflight-1.0+git=/usr/src/debug/freeflight/1.0+git-r0 -fmacro-prefix-map=/home/jasonc/projects/quadcopter/albatros/build/tmp/work/cortexa57-poky-linux/freeflight/1.0+git/recipe-sysroot= -O2 -Wformat -Wformat-security -Werror=format-security -std=gnu++20 -fdeprecated-macro -fdebug-compilation-dir=/home/jasonc/projects/quadcopter/albatros/build/tmp/work/cortexa57-poky-linux/freeflight/1.0+git/freeflight-1.0+git -fdebug-prefix-map=/home/jasonc/projects/quadcopter/albatros/build/workspace/sources/freeflight=/usr/src/debug/freeflight/1.0+git-r0 -fdebug-prefix-map=/home/jasonc/projects/quadcopter/albatros/build/tmp/work/cortexa57-poky-linux/freeflight/1.0+git/freeflight-1.0+git=/usr/src/debug/freeflight/1.0+git-r0 -fdebug-prefix-map=/home/jasonc/projects/quadcopter/albatros/build/tmp/work/cortexa57-poky-linux/freeflight/1.0+git/recipe-sysroot= -fdebug-prefix-map=/home/jasonc/projects/quadcopter/albatros/build/tmp/work/cortexa57-poky-linux/freeflight/1.0+git/recipe-sysroot-native= -ferror-limit 19 -fvisibility-inlines-hidden -stack-protector 2 -fno-signed-char -fgnuc-version=4.2.1 -fno-implicit-modules -fcxx-exceptions -fexceptions -vectorize-loops -vectorize-slp -no-round-trip-args -target-feature -fmv -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -x c++ /home/jasonc/projects/quadcopter/albatros/build/workspace/sources/freeflight/src/flightd/main.cpp\n"
[ERROR][2024-03-16 12:09:47] .../vim/lsp/rpc.lua:734	"rpc"	"/usr/bin/clangd"	"stderr"	'V[12:09:47.702] Building first preamble for /home/jasonc/projects/quadcopter/albatros/build/workspace/sources/freeflight/src/flightd/main.cpp version 0\nV[12:09:47.702] BackgroundIndex: building version 1 after loading index from disk\nV[12:09:47.702] <<< {"id":0,"jsonrpc":"2.0","result":null}\n\nI[12:09:47.702] <-- reply(0)\nI[12:09:47.702] --> $/progress\nV[12:09:47.702] >>> {"jsonrpc":"2.0","method":"$/progress","params":{"token":"backgroundIndexProgress","value":{"kind":"begin","percentage":0,"title":"indexing"}}}\n\n'
[ERROR][2024-03-16 12:09:47] .../vim/lsp/rpc.lua:734	"rpc"	"/usr/bin/clangd"	"stderr"	'V[12:09:47.702] BackgroundIndex: serving version 1 (50980 bytes)\nI[12:09:47.702] --> $/progress\nV[12:09:47.703] >>> {"jsonrpc":"2.0","method":"$/progress","params":{"token":"backgroundIndexProgress","value":{"kind":"report","message":"0/1","percentage":0}}}\n\nI[12:09:47.703] --> $/progress\n'
[ERROR][2024-03-16 12:09:47] .../vim/lsp/rpc.lua:734	"rpc"	"/usr/bin/clangd"	"stderr"	'V[12:09:47.703] >>> {"jsonrpc":"2.0","method":"$/progress","params":{"token":"backgroundIndexProgress","value":{"kind":"report","message":"0/1","percentage":0}}}\n\nI[12:09:47.703] --> $/progress\n'
[ERROR][2024-03-16 12:09:47] .../vim/lsp/rpc.lua:734	"rpc"	"/usr/bin/clangd"	"stderr"	'V[12:09:47.703] >>> {"jsonrpc":"2.0","method":"$/progress","params":{"token":"backgroundIndexProgress","value":{"kind":"end"}}}\n\n'
[ERROR][2024-03-16 12:09:47] .../vim/lsp/rpc.lua:734	"rpc"	"/usr/bin/clangd"	"stderr"	"I[12:09:47.716] Built preamble of size 529320 for file /home/jasonc/projects/quadcopter/albatros/build/workspace/sources/freeflight/src/flightd/main.cpp version 0 in 0.01 seconds\n"
[ERROR][2024-03-16 12:09:47] .../vim/lsp/rpc.lua:734	"rpc"	"/usr/bin/clangd"	"stderr"	'I[12:09:47.717] --> workspace/semanticTokens/refresh(1)\nV[12:09:47.717] >>> {"id":1,"jsonrpc":"2.0","method":"workspace/semanticTokens/refresh","params":null}\n\n'
[ERROR][2024-03-16 12:09:47] .../vim/lsp/rpc.lua:734	"rpc"	"/usr/bin/clangd"	"stderr"	'V[12:09:47.717] <<< {"jsonrpc":"2.0","method":"$/cancelRequest","params":{"id":2}}\n\nI[12:09:47.717] <-- $/cancelRequest\nV[12:09:47.717] indexed preamble AST for /home/jasonc/projects/quadcopter/albatros/build/workspace/sources/freeflight/src/flightd/main.cpp version 0:\n  symbol slab: 5 symbols, 5376 bytes\n  ref slab: 0 symbols, 0 refs, 128 bytes\n  relations slab: 0 relations, 24 bytes\nV[12:09:47.717] <<< {"id":3,"jsonrpc":"2.0","method":"textDocument/semanticTokens/full","params":{"textDocument":{"uri":"file:///home/jasonc/projects/quadcopter/albatros/build/workspace/sources/freeflight/src/flightd/main.cpp"}}}\n\nI[12:09:47.717] <-- textDocument/semanticTokens/full(3)\n'
[ERROR][2024-03-16 12:09:47] .../vim/lsp/rpc.lua:734	"rpc"	"/usr/bin/clangd"	"stderr"	'V[12:09:47.717] <<< {"id":1,"jsonrpc":"2.0","result":null}\n\nI[12:09:47.717] <-- reply(1)\nV[12:09:47.717] Build dynamic index for header symbols with estimated memory usage of 22004 bytes\n'
[ERROR][2024-03-16 12:09:47] .../vim/lsp/rpc.lua:734	"rpc"	"/usr/bin/clangd"	"stderr"	'V[12:09:47.724] Trying to fix unresolved name "cout" in scopes: [std::]\n'
[ERROR][2024-03-16 12:09:47] .../vim/lsp/rpc.lua:734	"rpc"	"/usr/bin/clangd"	"stderr"	"V[12:09:47.724] Dex query tree: false\nV[12:09:47.724] Dex query tree: false\n"
[ERROR][2024-03-16 12:09:47] .../vim/lsp/rpc.lua:734	"rpc"	"/usr/bin/clangd"	"stderr"	"E[12:09:47.725] IncludeCleaner: Failed to get an entry for resolved path : No such file or directory\n"
[ERROR][2024-03-16 12:09:47] .../vim/lsp/rpc.lua:734	"rpc"	"/usr/bin/clangd"	"stderr"	"V[12:09:47.726] indexed file AST for /home/jasonc/projects/quadcopter/albatros/build/workspace/sources/freeflight/src/flightd/main.cpp version 0:\n  symbol slab: 2 symbols, 4680 bytes\n  ref slab: 2 symbols, 2 refs, 4272 bytes\n  relations slab: 0 relations, 24 bytes\nV[12:09:47.726] Build dynamic index for main-file symbols with estimated memory usage of 12040 bytes\n"
[ERROR][2024-03-16 12:09:47] .../vim/lsp/rpc.lua:734	"rpc"	"/usr/bin/clangd"	"stderr"	"I[12:09:47.726] --> textDocument/publishDiagnostics\n"
[ERROR][2024-03-16 12:09:47] .../vim/lsp/rpc.lua:734	"rpc"	"/usr/bin/clangd"	"stderr"	"V[12:09:47.726] >>> {\"jsonrpc\":\"2.0\",\"method\":\"textDocument/publishDiagnostics\",\"params\":{\"diagnostics\":[{\"code\":\"pp_file_not_found\",\"message\":\"'iostream' file not found\",\"range\":{\"end\":{\"character\":19,\"line\":24},\"start\":{\"character\":9,\"line\":24}},\"relatedInformation\":[],\"severity\":1,\"source\":\"clang\"},{\"code\":\"undeclared_var_use\",\"message\":\"Use of undeclared identifier 'std'\",\"range\":{\"end\":{\"character\":7,\"line\":30},\"start\":{\"character\":4,\"line\":30}},\"relatedInformation\":[],\"severity\":1,\"source\":\"clang\"},{\"code\":\"misc-unused-alias-decls\",\"codeDescription\":{\"href\":\"https://clang.llvm.org/extra/clang-tidy/checks/misc/unused-alias-decls.html\"},\"message\":\"Namespace alias decl 'ffd' is unused (fix available)\",\"range\":{\"end\":{\"character\":0,\"line\":27},\"start\":{\"character\":0,\"line\":26}},\"relatedInformation\":[],\"severity\":2,\"source\":\"clang-tidy\",\"tags\":[1]}],\"uri\":\"file:///home/jasonc/projects/quadcopter/albatros/build/workspace/sources/freeflight/src/flightd/main.cpp\",\"version\":0}}\n\nI[12:09:47.726] --> reply:textDocument/semanticTokens/full(2) 26 ms, error: Task was cancelled.\nV[12:09:47.726] >>> {\"error\":{\"code\":-32800,\"message\":\"Request cancelled\"},\"id\":2,\"jsonrpc\":\"2.0\"}\n\nV[12:09:47.726] ASTWorker running SemanticHighlights on version 0 of /home/jasonc/projects/quadcopter/albatros/build/workspace/sources/freeflight/src/flightd/main.cpp\nI[12:09:47.726] --> reply:textDocument/semanticTokens/full(3) 8 ms\nV[12:09:47.726] >>> {\"id\":3,\"jsonrpc\":\"2.0\",\"result\":{\"data\":[26,10,3,15,65537,0,6,17,15,131072,2,4,4,3,131075,0,9,4,2,16387,0,12,4,2,16387],\"resultId\":\"1\"}}\n\n"
```

**System information**

Output of `clangd --version`:
clangd version 17.0.6
Features: linux
Platform: x86_64-pc-linux-gnu

Editor/LSP plugin:
Neovim/nvim-lspconfig

Operating system:
Arch Linux
Kernel version: 6.7.9

**Comment by HighCommander4** [comment] 2024-03-16 20:16
Duplicate of #1605

**Closed by HighCommander4** 2024-03-16 20:16 UTC
