### ISSUE TITLE
no diagnostics when sort compare function not return value

### ISSUE THREAD

**Issue by lxz12523** [clangd/clangd#1201] opened 2022-07-05 12:01 UTC
**Logs**

![image](https://user-images.githubusercontent.com/42319043/177322846-22a54da1-5daa-4168-a6d6-2140d5e84834.png)
#include <vector>
#include <algorithm>
void s_test(std::vector<int> &cuboids) {
    sort(cuboids.begin(), cuboids.end(), [](const int &u123, const int &v123) {
         // v[1] = u[1];
         // return (u[2], u[0] + u[1]) < (v[2], v[0] + v[1]);
    });
}

I[19:58:19.931] clangd version 12.0.1 (https://github.com/llvm/llvm-project fed41342a82f5a3a9201819a82bf7a48313e296b)
I[19:58:19.932] PID: 33960
I[19:58:19.932] Working directory: c:\Users\LSP\Test
I[19:58:19.932] argv[0]: D:\LLVM\clangd_12.0.1\bin\clangd.exe
I[19:58:19.932] argv[1]: --clang-tidy=false
I[19:58:19.932] argv[2]: --log=verbose
I[19:58:19.932] argv[3]: --compile-commands-dir=C:\Users\LSP\Test\build\compile_commands.json
V[19:58:19.941] User config file is C:\Users\xxx\AppData\Local\clangd\config.yaml
I[19:58:19.941] Starting LSP over stdin/stdout
V[19:58:19.942] <<< {"id":0,"jsonrpc":"2.0","method":"initialize","params":{"capabilities":{"general":{"markdown":{"parser":"marked","version":"1.1.0"},"regularExpressions":{"engine":"ECMAScript","version":"ES2020"},"staleRequestSupport":{"cancel":true,"retryOnContentModified":["textDocument/semanticTokens/full","textDocument/semanticTokens/range","textDocument/semanticTokens/full/delta"]}},"textDocument":{"callHierarchy":{"dynamicRegistration":true},"codeAction":{"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}},"dataSupport":true,"disabledSupport":true,"dynamicRegistration":true,"honorsChangeAnnotations":false,"isPreferredSupport":true,"resolveSupport":{"properties":["edit"]}},"codeLens":{"dynamicRegistration":true},"colorProvider":{"dynamicRegistration":true},"completion":{"completionItem":{"commitCharactersSupport":true,"deprecatedSupport":true,"documentationFormat":["markdown","plaintext"],"insertReplaceSupport":true,"insertTextModeSupport":{"valueSet":[1,2]},"labelDetailsSupport":true,"preselectSupport":true,"resolveSupport":{"properties":["documentation","detail","additionalTextEdits"]},"snippetSupport":true,"tagSupport":{"valueSet":[1]}},"completionItemKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]},"contextSupport":true,"dynamicRegistration":true,"editsNearCursor":true},"declaration":{"dynamicRegistration":true,"linkSupport":true},"definition":{"dynamicRegistration":true,"linkSupport":true},"documentHighlight":{"dynamicRegistration":true},"documentLink":{"dynamicRegistration":true,"tooltipSupport":true},"documentSymbol":{"dynamicRegistration":true,"hierarchicalDocumentSymbolSupport":true,"labelSupport":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]},"tagSupport":{"valueSet":[1]}},"foldingRange":{"dynamicRegistration":true,"lineFoldingOnly":true,"rangeLimit":5000},"formatting":{"dynamicRegistration":true},"hover":{"contentFormat":["markdown","plaintext"],"dynamicRegistration":true},"implementation":{"dynamicRegistration":true,"linkSupport":true},"linkedEditingRange":{"dynamicRegistration":true},"onTypeFormatting":{"dynamicRegistration":true},"publishDiagnostics":{"codeDescriptionSupport":true,"dataSupport":true,"relatedInformation":true,"tagSupport":{"valueSet":[1,2]},"versionSupport":false},"rangeFormatting":{"dynamicRegistration":true},"references":{"dynamicRegistration":true},"rename":{"dynamicRegistration":true,"honorsChangeAnnotations":true,"prepareSupport":true,"prepareSupportDefaultBehavior":1},"selectionRange":{"dynamicRegistration":true},"semanticTokens":{"dynamicRegistration":true,"formats":["relative"],"multilineTokenSupport":false,"overlappingTokenSupport":false,"requests":{"full":{"delta":true},"range":true},"tokenModifiers":["declaration","definition","readonly","static","deprecated","abstract","async","modification","documentation","defaultLibrary"],"tokenTypes":["namespace","type","class","enum","interface","struct","typeParameter","parameter","variable","property","enumMember","event","function","method","macro","keyword","modifier","comment","string","number","regexp","operator"]},"signatureHelp":{"contextSupport":true,"dynamicRegistration":true,"signatureInformation":{"activeParameterSupport":true,"documentationFormat":["markdown","plaintext"],"parameterInformation":{"labelOffsetSupport":true}}},"synchronization":{"didSave":true,"dynamicRegistration":true,"willSave":true,"willSaveWaitUntil":true},"typeDefinition":{"dynamicRegistration":true,"linkSupport":true}},"window":{"showDocument":{"support":true},"showMessage":{"messageActionItem":{"additionalPropertiesSupport":true}},"workDoneProgress":true},"workspace":{"applyEdit":true,"codeLens":{"refreshSupport":true},"configuration":true,"didChangeConfiguration":{"dynamicRegistration":true},"didChangeWatchedFiles":{"dynamicRegistration":true},"executeCommand":{"dynamicRegistration":true},"fileOperations":{"didCreate":true,"didDelete":true,"didRename":true,"dynamicRegistration":true,"willCreate":true,"willDelete":true,"willRename":true},"semanticTokens":{"refreshSupport":true},"symbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]},"tagSupport":{"valueSet":[1]}},"workspaceEdit":{"changeAnnotationSupport":{"groupsOnLabel":true},"documentChanges":true,"failureHandling":"textOnlyTransactional","normalizesLineEndings":true,"resourceOperations":["create","rename","delete"]},"workspaceFolders":true}},"clientInfo":{"name":"Visual Studio Code","version":"1.68.1"},"initializationOptions":{"clangdFileStatus":true,"fallbackFlags":[]},"locale":"zh-cn","processId":21576,"rootPath":"c:\\Users\\LSP\\Test","rootUri":"file:///c%3A/Users/LSP/Test","trace":"off","workspaceFolders":[{"name":"Test","uri":"file:///c%3A/Users/LSP/Test"}]}}

I[19:58:19.942] <-- initialize(0)
I[19:58:19.946] --> reply:initialize(0) 3 ms
V[19:58:19.946] >>> {"id":0,"jsonrpc":"2.0","result":{"capabilities":{"astProvider":true,"callHierarchyProvider":true,"codeActionProvider":{"codeActionKinds":["quickfix","refactor","info"]},"compilationDatabase":{"automaticReload":true},"completionProvider":{"allCommitCharacters":[" ","\t","(",")","[","]","{","}","<",">",":",";",",","+","-","/","*","%","^","&","#","?",".","=","\"","'","|"],"resolveProvider":false,"triggerCharacters":[".","<",">",":","\"","/"]},"declarationProvider":true,"definitionProvider":true,"documentFormattingProvider":true,"documentHighlightProvider":true,"documentLinkProvider":{"resolveProvider":false},"documentOnTypeFormattingProvider":{"firstTriggerCharacter":"\n","moreTriggerCharacter":[]},"documentRangeFormattingProvider":true,"documentSymbolProvider":true,"executeCommandProvider":{"commands":["clangd.applyFix","clangd.applyTweak"]},"hoverProvider":true,"implementationProvider":true,"memoryUsageProvider":true,"referencesProvider":true,"renameProvider":{"prepareProvider":true},"selectionRangeProvider":true,"semanticTokensProvider":{"full":{"delta":true},"legend":{"tokenModifiers":[],"tokenTypes":["variable","variable","parameter","function","method","function","property","variable","class","enum","enumMember","type","dependent","dependent","namespace","typeParameter","concept","type","macro","comment"]},"range":false},"signatureHelpProvider":{"triggerCharacters":["(",","]},"textDocumentSync":{"change":2,"openClose":true,"save":true},"typeHierarchyProvider":true,"workspaceSymbolProvider":true},"serverInfo":{"name":"clangd","version":"clangd version 12.0.1 (https://github.com/llvm/llvm-project fed41342a82f5a3a9201819a82bf7a48313e296b)"}}}

V[19:58:19.994] <<< {"jsonrpc":"2.0","method":"initialized","params":{}}

I[19:58:19.994] <-- initialized
V[19:58:20.045] <<< {"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"languageId":"cpp","text":"\n#include <vector>\n//#include <array>\n#include <algorithm>\n//void arr_test() {\n//  std::vector<std::array<int, 26>> f(10);\n//}\nvoid s_test(std::vector<int> &cuboids) {\n    sort(cuboids.begin(), cuboids.end(), [](const int &u123, const int &v123) {\n         // v[1] = u[1];\n         // return (u[2], u[0] + u[1]) < (v[2], v[0] + v[1]);\n    });\n}","uri":"file:///c%3A/Users/LSP/Test/main.cpp","version":1}}}

I[19:58:20.045] <-- textDocument/didOpen
V[19:58:20.046] <<< {"id":1,"jsonrpc":"2.0","method":"textDocument/codeAction","params":{"context":{"diagnostics":[]},"range":{"end":{"character":1,"line":12},"start":{"character":1,"line":12}},"textDocument":{"uri":"file:///c%3A/Users/LSP/Test/main.cpp"}}}

I[19:58:20.046] <-- textDocument/codeAction(1)
I[19:58:20.047] Failed to find compilation database for c:\Users\LSP\Test\main.cpp
I[19:58:20.047] ASTWorker building file c:\Users\LSP\Test\main.cpp version 1 with command clangd fallback
[c:\Users\LSP\Test]
G:\Program Files\JetBrains\CLion 2021.2.3\bin\clang c:\Users\LSP\Test\main.cpp -fsyntax-only -resource-dir=D:\LLVM\clangd_12.0.1\lib\clang\12.0.1
V[19:58:20.048] <<< {"id":2,"jsonrpc":"2.0","method":"textDocument/documentLink","params":{"textDocument":{"uri":"file:///c%3A/Users/LSP/Test/main.cpp"}}}

I[19:58:20.048] <-- textDocument/documentLink(2)
V[19:58:20.078] Driver produced command: cc1 -cc1 -triple x86_64-pc-windows-msvc19.29.30136 -fsyntax-only -disable-free -disable-llvm-verifier -discard-value-names -main-file-name main.cpp -mrelocation-model pic -pic-level 2 -mframe-pointer=none -fmath-errno -fno-rounding-math -mconstructor-aliases -munwind-tables -target-cpu x86-64 -tune-cpu generic -resource-dir D:\LLVM\clangd_12.0.1\lib\clang\12.0.1 -internal-isystem D:\LLVM\clangd_12.0.1\lib\clang\12.0.1\include -internal-isystem D:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include -internal-isystem D:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\atlmfc\include -internal-isystem D:\Windows Kits\10\Include\10.0.19041.0\ucrt -internal-isystem D:\Windows Kits\10\include\10.0.19041.0\shared -internal-isystem D:\Windows Kits\10\include\10.0.19041.0\um -internal-isystem D:\Windows Kits\10\include\10.0.19041.0\winrt -fdeprecated-macro -fdebug-compilation-dir c:\Users\LSP\Test -ferror-limit 19 -fno-use-cxa-atexit -fms-extensions -fms-compatibility -fms-compatibility-version=19.29.30136 -std=c++14 -fdelayed-template-parsing -fcxx-exceptions -fexceptions -faddrsig -x c++ c:\Users\LSP\Test\main.cpp
I[19:58:20.078] --> textDocument/clangd.fileStatus
V[19:58:20.078] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"parsing includes, running Update (1)","uri":"file:///c:/Users/LSP/Test/main.cpp"}}

V[19:58:20.078] Building first preamble for c:\Users\LSP\Test\main.cpp version 1
V[19:58:20.341] <<< {"jsonrpc":"2.0","method":"$/cancelRequest","params":{"id":2}}

I[19:58:20.341] <-- $/cancelRequest
V[19:58:20.348] <<< {"id":3,"jsonrpc":"2.0","method":"textDocument/documentLink","params":{"textDocument":{"uri":"file:///c%3A/Users/LSP/Test/main.cpp"}}}

I[19:58:20.349] <-- textDocument/documentLink(3)
V[19:58:20.496] indexed preamble AST for c:\Users\LSP\Test\main.cpp version 1:
  symbol slab: 6822 symbols, 1844976 bytes
  ref slab: 0 symbols, 0 refs, 136 bytes
  relations slab: 195 relations, 5396 bytes
V[19:58:20.561] Build dynamic index for header symbols with estimated memory usage of 4969400 bytes
V[19:58:20.566] Built preamble of size 3443740 for file c:\Users\LSP\Test\main.cpp version 1
V[19:58:20.599] indexed file AST for c:\Users\LSP\Test\main.cpp version 1:
  symbol slab: 1 symbols, 4456 bytes
  ref slab: 5 symbols, 5 refs, 4376 bytes
  relations slab: 0 relations, 24 bytes
V[19:58:20.600] Build dynamic index for main-file symbols with estimated memory usage of 11784 bytes
I[19:58:20.600] --> textDocument/publishDiagnostics
V[19:58:20.600] >>> {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[],"uri":"file:///c:/Users/LSP/Test/main.cpp","version":1}}

V[19:58:20.600] ASTWorker running EnumerateTweaks on version 1 of c:\Users\LSP\Test\main.cpp
I[19:58:20.600] --> reply:textDocument/codeAction(1) 553 ms
V[19:58:20.600] >>> {"id":1,"jsonrpc":"2.0","result":[]}

I[19:58:20.600] --> reply:textDocument/documentLink(2) 551 ms, error: Task was cancelled.
V[19:58:20.600] >>> {"error":{"code":-32800,"message":"Request cancelled"},"id":2,"jsonrpc":"2.0"}

V[19:58:20.600] ASTWorker running DocumentLinks on version 1 of c:\Users\LSP\Test\main.cpp
I[19:58:20.600] --> reply:textDocument/documentLink(3) 251 ms
V[19:58:20.600] >>> {"id":3,"jsonrpc":"2.0","result":[{"range":{"end":{"character":17,"line":1},"start":{"character":9,"line":1}},"target":"file:///D:/Program%20Files%20%28x86%29/Microsoft%20Visual%20Studio/2019/BuildTools/VC/Tools/MSVC/14.29.30133/include/vector"},{"range":{"end":{"character":20,"line":3},"start":{"character":9,"line":3}},"target":"file:///D:/Program%20Files%20%28x86%29/Microsoft%20Visual%20Studio/2019/BuildTools/VC/Tools/MSVC/14.29.30133/include/algorithm"}]}

I[19:58:20.600] --> textDocument/clangd.fileStatus
V[19:58:20.600] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"idle","uri":"file:///c:/Users/LSP/Test/main.cpp"}}

[Error - 19:58:20] Request textDocument/documentLink failed.
[object Object]
V[19:58:20.701] <<< {"id":4,"jsonrpc":"2.0","method":"textDocument/semanticTokens/full","params":{"textDocument":{"uri":"file:///c%3A/Users/LSP/Test/main.cpp"}}}

I[19:58:20.701] <-- textDocument/semanticTokens/full(4)
V[19:58:20.701] ASTWorker running SemanticHighlights on version 1 of c:\Users\LSP\Test\main.cpp
I[19:58:20.701] --> reply:textDocument/semanticTokens/full(4) 0 ms
V[19:58:20.701] >>> {"id":4,"jsonrpc":"2.0","result":{"data":[7,5,6,3,0,0,7,3,14,0,0,5,6,8,0,0,13,7,2,0,1,4,4,3,0,0,5,7,2,0,0,8,5,4,0,0,9,7,2,0,0,8,3,4,0,0,21,4,2,0,0,17,4,2,0],"resultId":"1"}}

I[19:58:20.701] --> textDocument/clangd.fileStatus
V[19:58:20.701] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"idle","uri":"file:///c:/Users/LSP/Test/main.cpp"}}

V[19:58:20.818] <<< {"id":5,"jsonrpc":"2.0","method":"textDocument/codeAction","params":{"context":{"diagnostics":[]},"range":{"end":{"character":1,"line":12},"start":{"character":1,"line":12}},"textDocument":{"uri":"file:///c%3A/Users/LSP/Test/main.cpp"}}}

I[19:58:20.818] <-- textDocument/codeAction(5)
V[19:58:20.818] ASTWorker running EnumerateTweaks on version 1 of c:\Users\LSP\Test\main.cpp
I[19:58:20.818] --> reply:textDocument/codeAction(5) 0 ms
V[19:58:20.818] >>> {"id":5,"jsonrpc":"2.0","result":[]}

I[19:58:20.818] --> textDocument/clangd.fileStatus
V[19:58:20.818] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"idle","uri":"file:///c:/Users/LSP/Test/main.cpp"}}

V[19:58:20.857] <<< {"id":6,"jsonrpc":"2.0","method":"textDocument/documentLink","params":{"textDocument":{"uri":"file:///c%3A/Users/LSP/Test/main.cpp"}}}

I[19:58:20.858] <-- textDocument/documentLink(6)
V[19:58:20.858] ASTWorker running DocumentLinks on version 1 of c:\Users\LSP\Test\main.cpp
I[19:58:20.858] --> reply:textDocument/documentLink(6) 0 ms
V[19:58:20.858] >>> {"id":6,"jsonrpc":"2.0","result":[{"range":{"end":{"character":17,"line":1},"start":{"character":9,"line":1}},"target":"file:///D:/Program%20Files%20%28x86%29/Microsoft%20Visual%20Studio/2019/BuildTools/VC/Tools/MSVC/14.29.30133/include/vector"},{"range":{"end":{"character":20,"line":3},"start":{"character":9,"line":3}},"target":"file:///D:/Program%20Files%20%28x86%29/Microsoft%20Visual%20Studio/2019/BuildTools/VC/Tools/MSVC/14.29.30133/include/algorithm"}]}

I[19:58:20.858] --> textDocument/clangd.fileStatus
V[19:58:20.858] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"idle","uri":"file:///c:/Users/LSP/Test/main.cpp"}}

V[19:58:20.986] <<< {"id":7,"jsonrpc":"2.0","method":"textDocument/codeAction","params":{"context":{"diagnostics":[]},"range":{"end":{"character":1,"line":12},"start":{"character":1,"line":12}},"textDocument":{"uri":"file:///c%3A/Users/LSP/Test/main.cpp"}}}

I[19:58:20.986] <-- textDocument/codeAction(7)
V[19:58:20.986] <<< {"id":8,"jsonrpc":"2.0","method":"textDocument/documentSymbol","params":{"textDocument":{"uri":"file:///c%3A/Users/LSP/Test/main.cpp"}}}

I[19:58:20.986] <-- textDocument/documentSymbol(8)
V[19:58:20.986] ASTWorker running EnumerateTweaks on version 1 of c:\Users\LSP\Test\main.cpp
I[19:58:20.986] --> reply:textDocument/codeAction(7) 0 ms
V[19:58:20.986] >>> {"id":7,"jsonrpc":"2.0","result":[]}

V[19:58:20.986] ASTWorker running DocumentSymbols on version 1 of c:\Users\LSP\Test\main.cpp
I[19:58:20.986] --> reply:textDocument/documentSymbol(8) 0 ms
V[19:58:20.986] >>> {"id":8,"jsonrpc":"2.0","result":[{"kind":12,"name":"s_test","range":{"end":{"character":1,"line":12},"start":{"character":0,"line":7}},"selectionRange":{"end":{"character":11,"line":7},"start":{"character":5,"line":7}}}]}

I[19:58:20.986] --> textDocument/clangd.fileStatus
V[19:58:20.986] >>> {"jsonrpc":"2.0","method":"textDocument/clangd.fileStatus","params":{"state":"idle","uri":"file:///c:/Users/LSP/Test/main.cpp"}}

**when I add "int a;" in first line, it appears diagnostics as follow**
![image](https://user-images.githubusercontent.com/42319043/177321330-d0da03dc-d632-4629-902d-e9c61e74412f.png)

**System information**

Output of `clangd --version`:

clangd version 12.0.1 (https://github.com/llvm/llvm-project fed41342a82f5a3a9201819a82bf7a48313e296b)

Editor/LSP plugin:
vscode-clangd

Operating system:
window 10

**Comment by sam-mccall** [comment] 2022-07-05 19:19
I think this is also basically a dupe of #137, right?

The lambda *does* get analyzed and is valid (if you write `->bool` you get the diagnostic about not returning a value).
The problem is in the instantiation site, and we don't instantiate (or even parse) imported functions.

It's tempting to say "sort() is called from the main file, we should parse sort()" but:
 - the relevant error isn't actually in sort, e.g. on my libstdc++ it's in `__gnu_cxx::__ops::Iter_comp_iter<...>::operator()<...>`
 - we reuse the imported AST as the main file changes

**Comment by HighCommander4** [comment] 2022-07-05 21:29
> I think this is also basically a dupe of #137, right?

Looks that way to me.

>    * we reuse the imported AST as the main file changes

(I don't understand this part -- is the "imported AST" the preamble?)

**Comment by lxz12523** [comment] 2022-07-06 01:49
> The lambda _does_ get analyzed and is valid (if you write `->bool` you get the diagnostic about not returning a value).

Yes, write `->bool`, I  get the diagnostic

**Closed** 2023-01-24 05:50 UTC
