### ISSUE TITLE
CMake Generate step failed with -DCLANGD_ENABLE_REMOTE=On

### ISSUE THREAD

**Issue by i-ky** [clangd/clangd#1255] opened 2022-08-18 07:20 UTC
I use a patched `clangd`, so I have a routine to `git pull` and rebuild it first time in the morning. Yesterday it was fine, today it is failing. Here is what I do:
```bash
cd ~
git clone --depth 1 https://github.com/llvm/llvm-project.git
cd llvm-project/
mkdir build
cd build/
cmake ~/llvm-project/llvm/ -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra" -DCLANGD_ENABLE_REMOTE=On -G Ninja
```

Here is what I get:
```
...
-- Configuring done
CMake Error: install(EXPORT "ClangTargets" ...) includes target "clangdRemoteIndex" which requires target "clangdRemoteIndexProto" that is not in any export set.
CMake Error: install(EXPORT "ClangTargets" ...) includes target "clangdRemoteIndex" which requires target "clangdRemoteIndexServiceProto" that is not in any export set.
CMake Error: install(EXPORT "ClangTargets" ...) includes target "clangdRemoteMarshalling" which requires target "clangdRemoteIndexProto" that is not in any export set.
CMake Error in /home/glebs/llvm-project/clang/cmake/modules/CMakeLists.txt:
  export called with target "clangdRemoteIndex" which requires target
  "clangdRemoteIndexProto" that is not in any export set.


CMake Error in /home/i-ky/llvm-project/clang/cmake/modules/CMakeLists.txt:
  export called with target "clangdRemoteIndex" which requires target
  "clangdRemoteIndexServiceProto" that is not in any export set.


CMake Error in /home/i-ky/llvm-project/clang/cmake/modules/CMakeLists.txt:
  export called with target "clangdRemoteMarshalling" which requires target
  "clangdRemoteIndexProto" that is not in any export set.


-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

If I omit `-DCLANGD_ENABLE_REMOTE=On` from `cmake` command, then build files can be generated successfully.

```
$ git rev-parse HEAD
fae656b2dd80246c3c6f01e9c77c49560368752c
```

Operating system: Ubuntu 22.04

**Comment by i-ky** [comment] 2022-08-18 10:57
Same issue has now been [reported in LLVM repo](https://github.com/llvm/llvm-project/issues/57213).

**Comment by sam-mccall** [comment] 2022-08-18 14:36
Thanks a lot for reporting this (and for the simple repro without stage2, and for finding the dupe in llvm-project).
I think we should track this in the LLVM repo though, as it's caused by build system changes related to non-clangd stuff. So I'll close this one in favor of https://github.com/llvm/llvm-project/issues/57213

**Closed by sam-mccall** 2022-08-18 14:36 UTC
