### ISSUE TITLE
Recover better with mismatched braces

### ISSUE THREAD

**Issue by sam-mccall** [clangd/clangd#40] opened 2019-04-29 09:09 UTC
Clang recovers very poorly sometimes with mismatched braces. e.g.

```cpp
void foo() {
  ^

void bar() {
}
```

One option is to improve clang's own recovery (e.g. using indentation) though this is likely to be hard.
We could also track the region of the file that has been modified since the last compilable version, and inject braces at the end of it.

**Comment by HighCommander4** [comment] 2019-11-24 04:39
What is an example symptom of the poor recovery?

**Comment by kadircet** [comment] 2021-11-15 10:42
Seems to be a duplicate of https://github.com/clangd/clangd/issues/35.

**Closed by kadircet** 2021-11-15 10:42 UTC
