### ISSUE TITLE
[Code completion] no suggestion of private/protected variables, methods

### ISSUE THREAD

**Issue by elkuno213** [clangd/clangd#1701] opened 2023-07-12 15:21 UTC
Hello, I'm using `clangd-16` on `VSCode` (`Ubuntu 20.04`) and I'm encountering the problem that the code completion does not suggest private/protected variables, methods:

![Screenshot from 2023-07-12 17-11-38](https://github.com/clangd/clangd/assets/55743792/85be1c94-8d32-4a73-96e8-62efb20dd632)

Here is my config:

``` json
// settings.json
  "C_Cpp.intelliSenseEngine": "disabled",
  "clangd.path": "/usr/bin/clangd-16"
  "clangd.arguments": [
    "--compile-commands-dir=${workspaceFolder}/build-debug",
    "--completion-style=detailed",
    "--clang-tidy",
    "--clang-tidy-checks=-*,modernize*",
    "--header-insertion=never",
    "--pretty",
    "--log=verbose"
  ],
```

Here is the log:
[tmp.txt](https://github.com/clangd/clangd/files/12029510/tmp.txt)

What could be causing this issue, and are there any suggested solutions or workarounds you can recommend?

**Comment by sam-mccall** [comment] 2023-07-12 17:46
Is this in a context where those are accessible?
Generally code completion will not suggest private members unless you can access them.

**Comment by elkuno213** [comment] 2023-07-12 19:41
When using an instance of class, it's reasonable that code completion does not suggest private members. However, in the context of definition of a class, I think they should be obviously accessible.

**Comment by sam-mccall** [comment] 2023-07-12 20:09
That makes sense (though sometimes the parser doesn't know exactly what the context is for incomplete code, and guesses).

In the screenshot, it doesn't look like you're in such a context, though.

**Comment by elkuno213** [comment] 2023-07-12 20:28
In the screenshot, I'm trying to implement definition of some private methods (e.g. `visualize()`) and after typing `MyClass::` I cannot get any suggestion of these methods.

**Comment by HighCommander4** [comment] 2023-07-13 06:17
Duplicate of https://github.com/clangd/clangd/issues/880

**Closed by HighCommander4** 2023-07-13 06:17 UTC
