### ISSUE TITLE
clangd doesn't find reference to ctor from perfect forwarding `make_object` function

### ISSUE THREAD

**Issue by nico** [clangd/clangd#1872] opened 2023-12-20 19:39 UTC
In a project that uses clangd, paste in the following snippet to some file and save:

```cpp
namespace Foo {

template<typename T, typename... Args>
static T* make_object(Args... args) {
  return new T(forward<Args>(args)...);
}

struct C {
  C(int a);
};

C::C(int) {}

void f() {
  C* c = make_object<C>(4);
  (void)c;
}

}
```

Then right-click the `C` of `C(int a);` in VSCode and pick "show all references".

Expected: Shows the `make_object<C>(4)` call.

Actual: Shows just ctor declaration and definition.

This is with "Apple clangd version 15.0.0 (clang-1500.0.40.1) Features: mac+xpc Platform: x86_64-apple-darwin22.6.0; target=arm64-apple-darwin22.6.0", the version in the latest Xcode.

Editor/LSP plugin: vscode, clangd plugin.

Operating system: macOS.

I have a local build of clangd, clangd-indexer etc flying around. Please let me know if there are any commands I can run to help narrow it down further.

**Comment by HighCommander4** [comment] 2023-12-20 19:48
Please see https://github.com/clangd/clangd/issues/716 for discussion of this issue and potential fix approaches.

I'll close this one as a duplicate to keep the discussion in one place.

**Comment by HighCommander4** [comment] 2023-12-20 19:49
Duplicate of #716

**Closed by HighCommander4** 2023-12-20 19:48 UTC
