### ISSUE TITLE
Completions for `.` and `->` are ordered backwards, typing `foo.` shows `foo->bar` first, and vice versa

### ISSUE THREAD

**Issue by HolyBlackCat** [clangd/clangd#1809] opened 2023-10-30 11:40 UTC
```cpp
struct A
{
    int a;
};
A aa;

struct B
{
    int b;
    
    A *operator->() {return &a;}
};
B bb;

int main()
{
    // type here
}
```

Typing `bb.` suggests `a` first (which inserts `->a`) and `b` second (which inserts `.a`). This is backwards, `b` should be shown first, since it matches the access operator that I've typed.

Conversely, `bb->` suggests `b` first, `a` second, which is again backwards, `a` should be first here.

This is cleary done delibirately, since `bb.` and `bb->` show different completions, but the order backwards in both cases.

**System information**

Output of `clangd --version`:
```none
clangd version 16.0.6
Features: linux
Platform: x86_64-pc-linux-gnu
```
(My distro doesn't ship Clang 17 yet.)

Editor/LSP plugin: VSCode

Operating system: Manjaro Linux

**Comment by HighCommander4** [comment] 2023-10-31 06:10
I believe this is a vscode-specific issue, tracked in https://github.com/clangd/vscode-clangd/issues/45. See the comments in that issue for a diagnosis.

**Comment by HighCommander4** [comment] 2023-10-31 06:12
(Adding the magic word for Github's benefit: **duplicate** of https://github.com/clangd/vscode-clangd/issues/45)

**Comment by HighCommander4** [comment] 2023-10-31 06:12
(Adding the magic word for Github's benefit: duplicate of https://github.com/clangd/vscode-clangd/issues/45)

**Closed by HighCommander4** 2023-10-31 06:12 UTC
