### ISSUE TITLE
go-to-definition does not work inside GTest assertions

### ISSUE THREAD

**Issue by ilya-biryukov** [clangd/clangd#205] opened 2019-11-19 10:38 UTC
Input:
```cpp
std::vector<int> vec;
ASSERT_EQ(ve^c.s^ize(), 1);
```

Expected: go-to-definition navigates to the local variable and `vector<T>::size`, respectively
Actual: getting errors: `no definition found for 'vec'` and `no definition found for 'size'`

**Comment by kadircet** [comment] 2019-11-19 10:52
duplicate of https://github.com/clangd/clangd/issues/202

**Closed by kadircet** 2019-11-19 10:52 UTC
