### ISSUE TITLE
System includes are not found when included from header

### ISSUE THREAD

**Issue by diggit** [clangd/clangd#1100] opened 2022-04-08 08:23 UTC
This issue appeared after updating from 13.0.1 to 14.0.
I am sure, that `clangd` is able to find system includes using extracted paths from `arm-none-eabi-*` GCC, because linting of `test.cpp` files work as expected. When I switch to header file `test.hpp` system includes are reported to be missing.

`test.cpp`
```cpp
#include <cstdint>

#include "test.hpp"

void foo() {}
```

`test.hpp`
```cpp
#pragma once

#include <cstdint>

void foo();
```

**Logs**

Paths were redacted, but everything else remained:
[clangd_14_log_redacted.txt](https://github.com/clangd/clangd/files/8449958/clangd_14_log_redacted.txt)

**System information**

Output of `clangd --version`:
```
clangd version 14.0.0
Features: windows
Platform: x86_64-pc-windows-msvc
```

Editor/LSP plugin:
```
Version: 1.66.1
Commit: 8dfae7a5cd50421d10cd99cb873990460525a898
Date: 2022-04-06T14:50:12.141Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.19044
```

Operating system:
Windows 10 Enterprise 21H2

**Comment by HighCommander4** [comment] 2022-04-10 02:59
Could you share the contents of the config file `c:\Users\redacted\fw\firmware\.clangd` as well please?

**Comment by diggit** [comment] 2022-04-10 08:16
Sure, It's:
```
CompileFlags: # Tweak the parse settings
	Add: [-Wno-gnu-zero-variadic-macro-arguments] # ignore zero variadic macro args warning
```

VSC is launching clangd with this configuration:
```json
	"clangd.arguments": [
		"--query-driver=*arm-none-eabi-*",
		"--clang-tidy",
		"--pretty",
		"--background-index",
		"-log=verbose"
	],
```

**Comment by HighCommander4** [comment] 2022-04-10 20:14
Thanks.

The relevant part of the log:

```
V[10:10:07.962] System include extraction: target extracted: "arm-none-eabi"
V[10:10:07.962] System include extraction: adding  c:\users\redacted\apps\gcc-arm-none-eabi\10-2020-q4-major\bin\../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/include/c++/10.2.1

V[10:10:07.962] System include extraction: adding  c:\users\redacted\apps\gcc-arm-none-eabi\10-2020-q4-major\bin\../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/include/c++/10.2.1/arm-none-eabi

V[10:10:07.962] System include extraction: adding  c:\users\redacted\apps\gcc-arm-none-eabi\10-2020-q4-major\bin\../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/include/c++/10.2.1/backward

V[10:10:07.962] System include extraction: adding  c:\users\redacted\apps\gcc-arm-none-eabi\10-2020-q4-major\bin\../lib/gcc/arm-none-eabi/10.2.1/include

V[10:10:07.962] System include extraction: adding  c:\users\redacted\apps\gcc-arm-none-eabi\10-2020-q4-major\bin\../lib/gcc/arm-none-eabi/10.2.1/include-fixed

V[10:10:07.962] System include extraction: adding  c:\users\redacted\apps\gcc-arm-none-eabi\10-2020-q4-major\bin\../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/include

I[10:10:07.962] System includes extractor: successfully executed C:\Users\redacted\apps\gcc-arm-none-eabi\10-2020-q4-major\bin\arm-none-eabi-g++.exe
	got includes: "c:\users\redacted\apps\gcc-arm-none-eabi\10-2020-q4-major\bin\../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/include/c++/10.2.1, c:\users\redacted\apps\gcc-arm-none-eabi\10-2020-q4-major\bin\../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/include/c++/10.2.1/arm-none-eabi, c:\users\redacted\apps\gcc-arm-none-eabi\10-2020-q4-major\bin\../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/include/c++/10.2.1/backward, c:\users\redacted\apps\gcc-arm-none-eabi\10-2020-q4-major\bin\../lib/gcc/arm-none-eabi/10.2.1/include, c:\users\redacted\apps\gcc-arm-none-eabi\10-2020-q4-major\bin\../lib/gcc/arm-none-eabi/10.2.1/include-fixed, c:\users\redacted\apps\gcc-arm-none-eabi\10-2020-q4-major\bin\../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/include"
	got target: "arm-none-eabi"
I[10:10:07.963] ASTWorker building file c:\Users\redacted\fw\firmware\app\src\test.hpp version 54 with command inferred from C:\Users\redacted\fw\firmware\app\src\test.cpp
[C:/Users/redacted/fw/firmware/build]
"C:\\redacted\\apps\\gcc-arm-none-eabi\\10-2020-q4-major\\bin\\arm-none-eabi-g++.exe" --target=arm-none-eabi --driver-mode=g++ -DDEBUG -DDEVICE=STM32L552 -DGIT_VERSION_SHORT= -DPRINTF_DISABLE_SUPPORT_EXPONENTIAL -DPRINTF_DISABLE_SUPPORT_LONG_LONG -DPRINTF_DISABLE_SUPPORT_PTRDIFF_T "-DPRINTF_INCLUDE_CONFIG_FILE=\"config/printf.h\"" -DSTM32L552xx -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -DUSE_UASSERT -D__packed=__attribute__((__packed__)) -D__weak=__attribute__((weak)) -Dtimegm=mktime -IC:/Users/redacted/fw/firmware/app/inc -IC:/Users/redacted/fw/firmware/app/src -IC:/Users/redacted/fw/firmware/drivers/STM32L5xx_HAL_Driver/SYSTEM -IC:/Users/redacted/fw/firmware/drivers/STM32L5xx_HAL_Driver/Inc -IC:/Users/redacted/fw/firmware/common/src -IC:/Users/redacted/fw/firmware/common/src/etl/include -IC:/Users/redacted/fw/firmware/common/src/printf -IC:/Users/redacted/fw/firmware/build/common -IC:/Users/redacted/fw/firmware/rtos/kernel/include -IC:/Users/redacted/fw/firmware/rtos/kernel/portable/GCC/ARM_CM33_NTZ/non_secure -isystem C:/Users/redacted/fw/firmware/drivers/CMSIS/Core/Include -isystem C:/Users/redacted/fw/firmware/drivers/CMSIS/DSP/Include -isystem C:/Users/redacted/fw/firmware/drivers/device -g -ffunction-sections -fdata-sections -Og -g -Werror=init-self -Werror=implicit-fallthrough -Werror=return-local-addr -Werror=int-in-bool-context -Werror=switch -Werror=return-type -Werror=parentheses -Wfatal-errors -Wno-psabi -Wno-unused-function -Wall -Wextra -Wundef -Wnull-dereference -Wcast-align -Wvla -Wmissing-format-attribute -Wuninitialized -Winit-self -Wdouble-promotion -Wstrict-aliasing -Wno-unused-parameter -Wshadow -pedantic -funsigned-char -fdiagnostics-color=always -fno-exceptions -fno-unwind-tables -fno-asynchronous-unwind-tables --specs=nano.specs --specs=nosys.specs -Wno-volatile -Wno-unused-local-typedefs -Wno-old-style-cast -fno-use-cxa-atexit -Wint-to-pointer-cast -Weffc++ -Wno-register -fno-rtti -fno-threadsafe-statics -mthumb -mcpu=cortex-m33 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -c -std=gnu++20 -Wno-gnu-zero-variadic-macro-arguments "-resource-dir=C:\\redacted\\scoop\\apps\\llvm\\current\\lib\\clang\\14.0.0" -- "c:\\Users\\redacted\\fw\\firmware\\app\\src\\test.hpp"
```

shows that the include extraction is successfully performed when opening the header file. However, unlike in the case of the .cpp file, the compilation command does not get `-isystem` flags added to it for the extracted header files.

I've looked over the relevant code in [QueryDriverDatabase.cpp](https://searchfox.org/llvm/source/clang-tools-extra/clangd/QueryDriverDatabase.cpp), and I haven't been able to find anything by inspection that would explain this outcome. It also doesn't look like this code has been modified since 13.0.

So, at the moment I'm at a loss as to what might have caused the observed regression.

**Comment by decimad** [comment] 2022-04-17 20:10
Currently bisecting, please stop me if you found the problem already :(

**Comment by HighCommander4** [comment] 2022-04-17 20:20
> Currently bisecting, please stop me if you found the problem already :(

Bisecting is a good idea, thanks! Unfortunately I don't have access to a Windows machine to investigate the issue further at the moment.

We have weekly pre-build snapshots at https://github.com/clangd/clangd/releases, that should allow bisecting down to a one-week range without having to do any local builds.

**Comment by decimad** [comment] 2022-04-17 22:28
The problem started with commit 4258d68dc73789bc7fc491734c9c392809b1b29a . That '--'-syntax confused me at first glance...

**Comment by HighCommander4** [comment] 2022-04-17 22:51
Thanks for tracking that down!

cc @sam-mccall and @kadircet as author/reviewer of the regressing [patch](https://reviews.llvm.org/D116721)

**Comment by laoshaw** [comment] 2022-04-27 16:29
Happened on Linux too, -isystem was ignored by clangd and pp_file_not_found was shown.

**Comment by diggit** [comment] 2022-05-09 07:14
Any progress on this issue? Did patch author or reviewer commented on this regression?

**Comment by Vigilans** [comment] 2022-05-12 17:20
Just add my 2 cents for reproduction:
* OS: Arch Linux
* Editor: VSCode + clangd extension
* Clangd version: clangd-13/clangd-14
* Project:  [sail-sg/envpool](https://github.com/sail-sg/envpool) (Bazel gcc project), extracted using [hedronvision/bazel-compile-commands-extractor](https://github.com/hedronvision/bazel-compile-commands-extractor)


This extractor generates `compile_commands.json` for both translation unit, header file, and files from external dependencies. The compiler from first argument is `/usr/bin/gcc`, and the behavior in this issue reproduced: System includes are not found when included from header.

If I manually replaced all occurrences of `/usr/bin/gcc` to `/usr/bin/g++`, the system includes can be properly found, but some other strange issues occurred.

If I set `CC=clang` when using the bazel extractor, all problems with header file disappeared and the clangd normally works, though the project is still compiled using gcc.

**Comment by HighCommander4** [comment] 2022-05-20 08:31
> cc @sam-mccall and @kadircet as author/reviewer of the regressing [patch](https://reviews.llvm.org/D116721)

I looked at this a bit and I think I understand the problem:

 * `InterpolatingCompilationDatabase` runs first, and in the case of a header file, transfers the compile command from the corresponding source file
   * This involves a call to [`transferTo()`](https://searchfox.org/llvm/rev/dd644ddf85be4abde554fc1c9af8ba63308bffa1/clang/lib/Tooling/InterpolatingCompilationDatabase.cpp#216), a function whose behaviour the patch modified to return the transferred command in "canonical" form, i.e. where it ends in `-- input`.
   * The meaning of `--` is that **every** subsequent argument is treated as an input, not an option.
 * `QueryDriverDatabase` runs next, and it [simply appends](https://searchfox.org/llvm/rev/dd644ddf85be4abde554fc1c9af8ba63308bffa1/clang-tools-extra/clangd/QueryDriverDatabase.cpp#243) the `-isystem` arguments to the command, oblivious to the fact that the command might contain a `--`.
 * Finally, `CommandMangler` runs and [drops](https://searchfox.org/llvm/rev/dd644ddf85be4abde554fc1c9af8ba63308bffa1/clang-tools-extra/clangd/CompileCommands.cpp#261-268) the excess arguments after `--`, thereby dropping the `-isystem` arguments.

I guess the fix is to change `QueryDriverDatabase` to append the `-isystem` arguments more like [this](https://searchfox.org/llvm/rev/dd644ddf85be4abde554fc1c9af8ba63308bffa1/clang-tools-extra/clangd/ConfigCompile.cpp#285-287), so it works in the presence of `--`.

Although this is making me think that this patch, whose motivation seems to have been to affect the behaviour of [this call](https://searchfox.org/llvm/rev/dd644ddf85be4abde554fc1c9af8ba63308bffa1/clang-tools-extra/clangd/CompileCommands.cpp#291) to `transferCompileCommand()` inside `CommandMangler` itself, may have broken other things by also changing the behaviour of the `transferCompileCommand()` call [inside](https://searchfox.org/llvm/rev/dd644ddf85be4abde554fc1c9af8ba63308bffa1/clang/lib/Tooling/InterpolatingCompilationDatabase.cpp#521) `InterpolatingCompilationDatabase` itself...

**Comment by HighCommander4** [comment] 2022-05-24 06:03
> Although this is making me think that this patch, whose motivation seems to have been to affect the behaviour of [this call](https://searchfox.org/llvm/rev/dd644ddf85be4abde554fc1c9af8ba63308bffa1/clang-tools-extra/clangd/CompileCommands.cpp#291) to `transferCompileCommand()` inside `CommandMangler` itself, may have broken other things by also changing the behaviour of the `transferCompileCommand()` call [inside](https://searchfox.org/llvm/rev/dd644ddf85be4abde554fc1c9af8ba63308bffa1/clang/lib/Tooling/InterpolatingCompilationDatabase.cpp#521) `InterpolatingCompilationDatabase` itself...

I think this part is fine. The original compile command in the `compile_commands.json` might contain a `--`, so it's already the case that all consumers need to handle that properly.

**Comment by HighCommander4** [comment] 2022-05-24 06:14
[Proposed fix](https://reviews.llvm.org/D126274)

**Closed** 2022-05-24 17:10 UTC
Labels: regression

**Comment by HighCommander4** [comment] 2022-06-06 07:16
No, the fix is only present on the trunk branch.

**Comment by TylerSeanRau** [comment] 2022-10-22 06:12
I'm still seeing this issue, but it appears to be closed now?

**Comment by HighCommander4** [comment] 2022-10-22 06:15
> I'm still seeing this issue, but it appears to be closed now?

It's fixed in clangd 15. If you're still experiencing a problem getting clangd to find system includes, please file a new issue and attach logs.

**Comment by TylerSeanRau** [comment] 2022-10-22 06:29
@HighCommander4 roger that, I'll get a new ticket started
