### ISSUE TITLE
Mark enum variant as variant count.  Does not include this variant in switch case.

### ISSUE THREAD

**Issue by Vaxeral** [clangd/clangd#1366] opened 2022-11-09 00:39 UTC
Often times it is useful to include a count of variants at the end of a enumeration like so.
```c
typedef enum {
    SOUTH_EAST,
    NORTH_EAST,
    NORTH,
    NORTH_WEST,
    SOUTH_WEST,
    SOUTH,
    DIRECTIONS // Count of all directional variants
} Direction;
```
But when I switch on an enumeration value it says i am missing a case ie DIRECTIONS.  But the DIRECTIONS variant is clearly not supposed to be checked.  It is just a count so if i may i can loop over all the variants or other things.  Maybe adding a comment at the end of the case to not be included would be helpfull?
```c
typedef enum {
    SOUTH_EAST,
    NORTH_EAST,
    NORTH,
    NORTH_WEST,
    SOUTH_WEST,
    SOUTH,
    DIRECTIONS // enum count
} Direction;
```

**Comment by i-ky** [comment] 2022-11-09 08:25
> But when I switch on an enumeration value it says i am missing a case

This is what [`-Wswitch`](https://clang.llvm.org/docs/DiagnosticsReference.html#wswitch) (enabled by default) does. In this case (pun intended) adding a `default:` will help. If you are unlucky enough and a more strict [`-Wswitch-enum`](https://clang.llvm.org/docs/DiagnosticsReference.html#wswitch-enum) is enabled in your project, you will have to handle `DIRECTIONS` explicitly (probably in the same way as `default:`).

The problem isn't clangd-specific, compiling code with clang will produce same warnings. In GCC you need to explicitly enable `-Wswitch`, but operation logic is the same.

I am not aware of a nice way to work around the warning, so I like the idea to do something about it on the compiler side. However, instead of comments it should probably be done with attributes, kinda
```cpp
enum {
  FOO,
  BAR,
  COUNT [[not_to_be_handled_in_switch]]
};
```
to ignore enumerator in `switch`es globally and kinda
```cpp
switch (x) {
  ...
  [[ignore(COUNT)]];
};
```
to explicitly avoid explicit handling (another pun, sorry) of enumerator on `switch`-by-`switch` basis.

I think the issue should be escalated to [LLVM repo](https://github.com/llvm/llvm-project) or even C/C++ standard committees.

**Comment by kadircet** [comment] 2022-11-11 09:04
thanks for the analysis here @i-ky! as you pointed out, this is a behaviour coming from clang and diverging/customizing diagnostics inside clangd wouldn't be a great idea. so feel free to bring this up in LLVM issue tracker, closing this one up as I don't think there's any action we can take on our side.

**Closed by kadircet** 2022-11-11 09:04 UTC
Labels: enhancement
