### ISSUE TITLE
-std:c++latest is omitted

### ISSUE THREAD

**Issue by v7a** [clangd/clangd#562] opened 2020-10-15 19:29 UTC
When the following is in my compile_commands.json:
```
clang-cl.exe  /nologo -TP  /DWIN32 /D_WINDOWS /GR /EHsc /Zi /Ob0 /Od /RTC1 -MDd /W4 /WX -std:c++latest /Fosome.obj /FdTARGET_COMPILE_PDB -c some.src
```
clangd updates the file but omits the standard flag:
```
clang-cl.exe --driver-mode=cl /nologo /DWIN32 /D_WINDOWS /GR /EHsc /Zi /Ob0 /Od /RTC1 /W4 /WX /FdTARGET_COMPILE_PDB -c <some header the TU depends on> -fsyntax-only -resource-dir=<...>
```

However, if I compile with `-std:c++17`, the flag is perfectly forwarded within clangd.

I felt kinda trolled trying to figure out the problem 😋 

**System information**
Output of `clangd --version`: clangd version 10.0.0
Editor/LSP plugin: VSCode
Operating system: Windows 10 Build 19041

**Comment by HighCommander4** [comment] 2020-10-15 19:41
Dupe of #527.

**Closed by HighCommander4** 2020-10-15 19:41 UTC
