### ISSUE TITLE
configuration paths relative to `.clangd`

### ISSUE THREAD

**Issue by l1mey112** [clangd/clangd#1722] opened 2023-08-07 12:41 UTC
I use `emscripten` a lot. Setting it up with an LSP is tricky, but possible.

My makefiles are at project root, I compile at the project root, my `.clangd` file is at the project root, so why do I have to specify the full path to `CompileFlags` ?

```yaml
CompileFlags:
  Compiler: emcc
  Add: [
    -DEMSCRIPTEN,
    -DSOKOL_GLES3,
    -target,
    wasm32-unknown-emscripten,
    --sysroot=/home/l-m/git/emsdk/upstream/emscripten/cache/sysroot, # can't get around this..
    -Xclang,
    -iwithsysroot/include/compat,
    -I/home/l-m/git/path/include, # ??
    -I/home/l-m/git/path/cimgui,  # ??
    -I/home/l-m/git/path/sokol,   # ??
    -Wno-unused-parameter,
    -Wno-unused-function,
    -Wall,
    -Wextra,
    -Wshadow,
    -std=gnu11,
  ]
```

It does not pick up `-I./relative` or `-Irelative`, you must provide the full path.

I don't need to do it with the rest of my workflow, the existing compiler simply picks up relative files.

![image](https://github.com/clangd/clangd/assets/66291634/4d95fcdd-f19d-45e1-912b-378d750b8e4d)

This would be a great addition.

**Comment by HighCommander4** [comment] 2023-08-08 04:25
I believe this is a duplicate of #1038

**Closed by HighCommander4** 2023-08-08 04:25 UTC
Labels: enhancement

**Comment by tevaughan** [comment] 2023-08-10 18:49
Seeing that relative paths seem not to work, I found this ticket.
Noticing that it was marked 'completed' three days ago, I wonder if there be a way to pick up a version of clangd that respects paths relative to '.clangd'.
It is not obvious to me that the latest snapshot would include this enhancement.
Does it?

**Comment by HighCommander4** [comment] 2023-08-10 18:52
No, this has not been implemented. If you look at the last comment, you can see I closed it as a duplicate of #1038, which is still open. "completed" is just wording Github uses whenever you close an issue, which can be misleading in cases like this.

**Comment by tevaughan** [comment] 2023-08-10 19:20
Thanks! Sorry for the noise.

**Comment by Kalankaboom** [comment] 2023-08-18 08:37
As a side note,
this is the first clangd configuration I have found that works with emscripten.
Thank you so very much !
