### ISSUE TITLE
Clang-tidy segfaults on optional value access from structured binding

### ISSUE THREAD

**Issue by scarf005** [clangd/clangd#1773] opened 2023-09-30 09:03 UTC
## Summary

https://clang.llvm.org/extra/clang-tidy/checks/bugprone/unchecked-optional-access.html segfaults on optional value access from pointers.

## Minimal Reproduction

```yaml
# .clang-tidy
Checks: bugprone-unchecked-optional-access
```

```cpp
// main.cpp
#include <map>
#include <optional>

struct Data {
  std::optional<int> x;
};


auto get_datas(const std::map<int, Data>& r) {
  for (auto& [id, data] : r) {
    data.x.value_or(0);
  }
}

auto main() -> int {
  return 0;
}
```

**Logs**

[error.simpler.log](https://github.com/clangd/clangd/files/12774326/error.simpler.log)
[error.log](https://github.com/clangd/clangd/files/12774305/error.log)

**System information**

Output of `clangd --version`:
```
clangd version 16.0.2 (https://github.com/llvm/llvm-project 18ddebe1a1a9bde349441631365f0472e9693520)
Features: linux+grpc
Platform: x86_64-unknown-linux-gnu
```

Editor/LSP plugin:
```
VSCode: 1.82.0
clangd: v0.1.24
```

Operating system: 
OS: Kubuntu 23.04 x86_64 
kernel: 6.5.0

**Comment by scarf005** [comment] 2023-09-30 09:13
might be related to https://github.com/llvm/llvm-project/issues/64201

**Comment by HighCommander4** [comment] 2023-10-01 07:07
I can reproduce this with clangd 16, but it seems to be fixed in clangd 17 and trunk., so upgrading should fix it.

**Closed by HighCommander4** 2023-10-01 07:07 UTC
