### ISSUE TITLE
Auto fill function arguments for definitions

### ISSUE THREAD

**Issue by adam3141** [clangd/clangd#2202] opened 2024-11-03 01:20 UTC
Having never filed a feature request, I am not sure of the correct way to fill one of these in, but I'll give it a go

For global and class member functions, it would be nice to auto fill the function information.
For global functions, if there are no overloads, it kind of works but still not perfect.

```cpp
void testGlobalFunction(int test_argument);
class TestClass
{
public:
   void testClassFunction(int test_argument);
};
```
in the corresponding implementation file, if I type

`void test` I can choose from testGlobalFunction and it will fill in the rest
```cpp
void testGlobalFunction(int test_argument)
```

However for class member functions, this isn't quite possible. All I can hope for is to just autofill the name
`void TestClass::` and then I can choose the `testClassFunction` and I just end up with
```cpp
void TestClass::testClassFunction
```

I guess the feature request I propose is that in the source file, you can just type the name of the symbol you wish, ie.
`test` and then invoke the Intellisense engine to display a list of matching symbols. If it's a function, select the overload if there are many of them so you can end up with (for the class example)
```cpp
void TestClass::testClassFunction(int test_argument)
```

or can auto trigger by doing `TestClass::` to bring up the class symbols.

Does it make sense what I am proposing, or has this been requested previously and is difficult due to the constraints of VSCode

Cheers

**Comment by HighCommander4** [comment] 2024-11-03 01:32
Yep, this makes sense. I believe this is the same issue as https://github.com/clangd/clangd/issues/1752 (and see https://github.com/clangd/clangd/issues/880 for a related issue with the same underlying cause), so I'll close this one as a duplicate.

**Comment by HighCommander4** [comment] 2024-11-03 01:32
Duplicate of #1752

**Closed by HighCommander4** 2024-11-03 01:32 UTC
Labels: enhancement

**Comment by centuryx476** [comment] 2025-09-01 02:00
Commenting to keep this alive.
Still cannot access non-public functions in the source code...

Thank You
