### ISSUE TITLE
Crash in C++20 mode

### ISSUE THREAD

**Issue by bstaletic** [clangd/clangd#771] opened 2021-05-07 08:04 UTC
First, apologies, really not sure how to title this better. This crash only happens in C++20 mode and with very specific source.

`compile_flags.txt`:

```
-xc++
-std=c++20
```
`foo.cpp`:

```c++
#include <vector>
#include <thread>
struct TestThread {
    ~TestThread() { delete t_; }
    std::thread * t_ = new std::thread([c='x']{ std::this_thread::sleep_for(std::chrono::microseconds(50)); });
};

int main() {
        std::vector<TestThread> threads(1);
        std::this_thread::sleep_for(std::chrono::milliseconds(50));
}
```

Steps to repro:

1. Open foo.cpp
2. Open compile_flags.txt (not always necessary)
3. Go back to foo.cpp (only if step 2 was necessary)
4. Open an empty line below `sleep_for` and type `std::`

Just to be clear, it's the completion request that kills clangd.

**Logs**

NOTE: These logs are from when I repro'd without steps 2 and 3. I can also provide logs with those two steps if needed.

Clangd log:

```
I[09:44:06.523] clangd version 12.0.0
I[09:44:06.523] PID: 2944
I[09:44:06.523] Working directory: /home/bstaletic/work/pybind11/tests
I[09:44:06.523] argv[0]: /home/bstaletic/.vim/pack/bundle/start/YouCompleteMe/third_party/ycmd/third_party/clangd/output/bin/clangd
I[09:44:06.523] argv[1]: -header-insertion-decorators=0
I[09:44:06.523] argv[2]: -resource-dir=/home/bstaletic/.vim/pack/bundle/start/YouCompleteMe/third_party/ycmd/third_party/clang/lib/clang/12.0.0
I[09:44:06.523] argv[3]: -limit-results=500
I[09:44:06.523] argv[4]: -log=verbose
V[09:44:06.523] User config file is /home/bstaletic/.config/clangd/config.yaml
I[09:44:06.523] Starting LSP over stdin/stdout
V[09:44:06.523] <<< {"id":1,"jsonrpc":"2.0","method":"initialize","params":{"capabilities":{"textDocument":{"codeAction":{"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}}},"completion":{"completionItem":{"documentationFormat":["plaintext","markdown"]},"completionItemKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]}},"documentSymbol":{"hierarchicalDocumentSymbolSupport":false,"labelSupport":false,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]}},"hover":{"contentFormat":["plaintext","markdown"]},"signatureHelp":{"signatureInformation":{"documentationFormat":["plaintext","markdown"],"parameterInformation":{"labelOffsetSupport":true}}},"synchronization":{"didSave":true}},"workspace":{"applyEdit":true,"didChangeWatchedFiles":{"dynamicRegistration":true},"symbol":{"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]}},"workspaceEdit":{"documentChanges":true}}},"initializationOptions":{},"processId":2910,"rootPath":"/home/bstaletic/work/pybind11/tests","rootUri":"file:///home/bstaletic/work/pybind11/tests"}}

I[09:44:06.523] <-- initialize(1)
I[09:44:06.524] --> reply:initialize(1) 0 ms
V[09:44:06.524] >>> {"id":1,"jsonrpc":"2.0","result":{"capabilities":{"astProvider":true,"callHierarchyProvider":true,"codeActionProvider":{"codeActionKinds":["quickfix","refactor","info"]},"compilationDatabase":{"automaticReload":true},"completionProvider":{"allCommitCharacters":[" ","\t","(",")","[","]","{","}","<",">",":",";",",","+","-","/","*","%","^","&","#","?",".","=","\"","'","|"],"resolveProvider":false,"triggerCharacters":[".","<",">",":","\"","/"]},"declarationProvider":true,"definitionProvider":true,"documentFormattingProvider":true,"documentHighlightProvider":true,"documentLinkProvider":{"resolveProvider":false},"documentOnTypeFormattingProvider":{"firstTriggerCharacter":"\n","moreTriggerCharacter":[]},"documentRangeFormattingProvider":true,"documentSymbolProvider":true,"executeCommandProvider":{"commands":["clangd.applyFix","clangd.applyTweak"]},"hoverProvider":true,"implementationProvider":true,"memoryUsageProvider":true,"referencesProvider":true,"renameProvider":true,"selectionRangeProvider":true,"semanticTokensProvider":{"full":{"delta":true},"legend":{"tokenModifiers":[],"tokenTypes":["variable","variable","parameter","function","method","function","property","variable","class","enum","enumMember","type","dependent","dependent","namespace","typeParameter","concept","type","macro","comment"]},"range":false},"signatureHelpProvider":{"triggerCharacters":["(",","]},"textDocumentSync":{"change":2,"openClose":true,"save":true},"typeHierarchyProvider":true,"workspaceSymbolProvider":true},"serverInfo":{"name":"clangd","version":"clangd version 12.0.0"}}}

V[09:44:06.527] <<< {"jsonrpc":"2.0","method":"initialized","params":{}}

I[09:44:06.527] <-- initialized
V[09:44:06.527] <<< {"jsonrpc":"2.0","method":"workspace/didChangeConfiguration","params":{"settings":{}}}

I[09:44:06.527] <-- workspace/didChangeConfiguration
V[09:44:06.527] <<< {"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"languageId":"cpp","text":"#include <vector>\n#include <thread>\nstruct TestThread {\n    ~TestThread() { delete t_; }\n    std::thread * t_ = new std::thread([c='x']{ std::this_thread::sleep_for(std::chrono::microseconds(50)); });\n};\n\nint main() {\n\tstd::vector<TestThread> threads(1);\n\tstd::this_thread::sleep_for(std::chrono::milliseconds(50));\n}\n","uri":"file:///home/bstaletic/work/pybind11/tests/foo.cpp","version":1}}}

I[09:44:06.527] <-- textDocument/didOpen
I[09:44:06.527] Loaded compilation database from /home/bstaletic/work/pybind11/tests/compile_flags.txt
V[09:44:06.528] Broadcasting compilation database from /home/bstaletic/work/pybind11/tests
I[09:44:06.528] ASTWorker building file /home/bstaletic/work/pybind11/tests/foo.cpp version 1 with command 
[/home/bstaletic/work/pybind11/tests]
/home/bstaletic/.vim/pack/bundle/start/YouCompleteMe/third_party/ycmd/third_party/clangd/output/bin/clang-tool -xc++ -std=c++20 /home/bstaletic/work/pybind11/tests/foo.cpp -fsyntax-only -resource-dir=/home/bstaletic/.vim/pack/bundle/start/YouCompleteMe/third_party/ycmd/third_party/clang/lib/clang/12.0.0
V[09:44:06.529] Driver produced command: cc1 -cc1 -triple x86_64-unknown-linux-gnu -fsyntax-only -disable-free -disable-llvm-verifier -discard-value-names -main-file-name foo.cpp -mrelocation-model static -mframe-pointer=all -fmath-errno -fno-rounding-math -mconstructor-aliases -munwind-tables -target-cpu x86-64 -tune-cpu generic -fno-split-dwarf-inlining -debugger-tuning=gdb -resource-dir /home/bstaletic/.vim/pack/bundle/start/YouCompleteMe/third_party/ycmd/third_party/clang/lib/clang/12.0.0 -internal-isystem /usr/lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0 -internal-isystem /usr/lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/x86_64-pc-linux-gnu -internal-isystem /usr/lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/backward -internal-isystem /usr/local/include -internal-isystem /home/bstaletic/.vim/pack/bundle/start/YouCompleteMe/third_party/ycmd/third_party/clang/lib/clang/12.0.0/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -std=c++20 -fdeprecated-macro -fdebug-compilation-dir /home/bstaletic/work/pybind11/tests -ferror-limit 19 -fgnuc-version=4.2.1 -fno-implicit-modules -fcxx-exceptions -fexceptions -faddrsig -x c++ /home/bstaletic/work/pybind11/tests/foo.cpp
V[09:44:06.529] Building first preamble for /home/bstaletic/work/pybind11/tests/foo.cpp version 1
V[09:44:07.736] indexed preamble AST for /home/bstaletic/work/pybind11/tests/foo.cpp version 1:
  symbol slab: 12286 symbols, 3628712 bytes
  ref slab: 0 symbols, 0 refs, 128 bytes
  relations slab: 702 relations, 17432 bytes
V[09:44:07.813] Build dynamic index for header symbols with estimated memory usage of 7655344 bytes
V[09:44:07.819] Built preamble of size 7985540 for file /home/bstaletic/work/pybind11/tests/foo.cpp version 1
V[09:44:07.901] indexed file AST for /home/bstaletic/work/pybind11/tests/foo.cpp version 1:
  symbol slab: 4 symbols, 5144 bytes
  ref slab: 12 symbols, 18 refs, 4608 bytes
  relations slab: 0 relations, 24 bytes
V[09:44:07.901] Build dynamic index for main-file symbols with estimated memory usage of 13816 bytes
I[09:44:07.901] --> textDocument/publishDiagnostics
V[09:44:07.901] >>> {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[],"uri":"file:///home/bstaletic/work/pybind11/tests/foo.cpp","version":1}}

V[09:44:08.656] <<< {"jsonrpc":"2.0","method":"textDocument/didChange","params":{"contentChanges":[{"text":"#include <vector>\n#include <thread>\nstruct TestThread {\n    ~TestThread() { delete t_; }\n    std::thread * t_ = new std::thread([c='x']{ std::this_thread::sleep_for(std::chrono::microseconds(50)); });\n};\n\nint main() {\n\tstd::vector<TestThread> threads(1);\n\tstd::this_thread::sleep_for(std::chrono::milliseconds(50));\n\tstd::\n}\n"}],"textDocument":{"uri":"file:///home/bstaletic/work/pybind11/tests/foo.cpp","version":2}}}

I[09:44:08.656] <-- textDocument/didChange
V[09:44:08.658] <<< {"id":2,"jsonrpc":"2.0","method":"textDocument/completion","params":{"position":{"character":6,"line":10},"textDocument":{"uri":"file:///home/bstaletic/work/pybind11/tests/foo.cpp"}}}

I[09:44:08.658] <-- textDocument/completion(2)
I[09:44:08.738] ASTWorker building file /home/bstaletic/work/pybind11/tests/foo.cpp version 2 with command 
[/home/bstaletic/work/pybind11/tests]
/home/bstaletic/.vim/pack/bundle/start/YouCompleteMe/third_party/ycmd/third_party/clangd/output/bin/clang-tool -xc++ -std=c++20 /home/bstaletic/work/pybind11/tests/foo.cpp -fsyntax-only -resource-dir=/home/bstaletic/.vim/pack/bundle/start/YouCompleteMe/third_party/ycmd/third_party/clang/lib/clang/12.0.0
V[09:44:08.739] Driver produced command: cc1 -cc1 -triple x86_64-unknown-linux-gnu -fsyntax-only -disable-free -disable-llvm-verifier -discard-value-names -main-file-name foo.cpp -mrelocation-model static -mframe-pointer=all -fmath-errno -fno-rounding-math -mconstructor-aliases -munwind-tables -target-cpu x86-64 -tune-cpu generic -fno-split-dwarf-inlining -debugger-tuning=gdb -resource-dir /home/bstaletic/.vim/pack/bundle/start/YouCompleteMe/third_party/ycmd/third_party/clang/lib/clang/12.0.0 -internal-isystem /usr/lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0 -internal-isystem /usr/lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/x86_64-pc-linux-gnu -internal-isystem /usr/lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/backward -internal-isystem /usr/local/include -internal-isystem /home/bstaletic/.vim/pack/bundle/start/YouCompleteMe/third_party/ycmd/third_party/clang/lib/clang/12.0.0/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -std=c++20 -fdeprecated-macro -fdebug-compilation-dir /home/bstaletic/work/pybind11/tests -ferror-limit 19 -fgnuc-version=4.2.1 -fno-implicit-modules -fcxx-exceptions -fexceptions -faddrsig -x c++ /home/bstaletic/work/pybind11/tests/foo.cpp
V[09:44:08.740] Reusing preamble version 1 for version 2 of /home/bstaletic/work/pybind11/tests/foo.cpp
 #0 0x0000000000595b6d llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/home/bstaletic/.vim/pack/bundle/start/YouCompleteMe/third_party/ycmd/third_party/clangd/output/bin/clangd+0x595b6d)
 #1 0x0000000000593aa4 llvm::sys::RunSignalHandlers() (/home/bstaletic/.vim/pack/bundle/start/YouCompleteMe/third_party/ycmd/third_party/clangd/output/bin/clangd+0x593aa4)
 #2 0x0000000000593c1b SignalHandler(int) (/home/bstaletic/.vim/pack/bundle/start/YouCompleteMe/third_party/ycmd/third_party/clangd/output/bin/clangd+0x593c1b)
 #3 0x00007faa6b0b8960 __restore_rt (/usr/lib/libpthread.so.0+0x13960)
 #4 0x0000000001eb40b2 (anonymous namespace)::LookupVisibleHelper::lookupInDeclContext(clang::DeclContext*, clang::LookupResult&, bool, bool) (.part.0) (/home/bstaletic/.vim/pack/bundle/start/YouCompleteMe/third_party/ycmd/third_party/clangd/output/bin/clangd+0x1eb40b2)
 #5 0x0000000001eb2e33 (anonymous namespace)::LookupVisibleHelper::lookupInDeclContext(clang::DeclContext*, clang::LookupResult&, bool, bool) (/home/bstaletic/.vim/pack/bundle/start/YouCompleteMe/third_party/ycmd/third_party/clangd/output/bin/clangd+0x1eb2e33)
 #6 0x0000000001eb6ea7 clang::Sema::LookupVisibleDecls(clang::DeclContext*, clang::Sema::LookupNameKind, clang::VisibleDeclConsumer&, bool, bool, bool) (/home/bstaletic/.vim/pack/bundle/start/YouCompleteMe/third_party/ycmd/third_party/clangd/output/bin/clangd+0x1eb6ea7)
 #7 0x0000000001a8f199 clang::Sema::CodeCompleteQualifiedId(clang::Scope*, clang::CXXScopeSpec&, bool, bool, clang::QualType, clang::QualType) (/home/bstaletic/.vim/pack/bundle/start/YouCompleteMe/third_party/ycmd/third_party/clangd/output/bin/clangd+0x1a8f199)
 #8 0x00000000017710e0 clang::Parser::ParseOptionalCXXScopeSpecifier(clang::CXXScopeSpec&, clang::OpaquePtr<clang::QualType>, bool, bool, bool*, bool, clang::IdentifierInfo**, bool, bool) (/home/bstaletic/.vim/pack/bundle/start/YouCompleteMe/third_party/ycmd/third_party/clangd/output/bin/clangd+0x17710e0)
 #9 0x00000000016fb235 clang::Parser::TryAnnotateTypeOrScopeToken() (.localalias) (/home/bstaletic/.vim/pack/bundle/start/YouCompleteMe/third_party/ycmd/third_party/clangd/output/bin/clangd+0x16fb235)
#10 0x00000000017edb38 clang::Parser::isCXXDeclarationSpecifier(clang::Parser::TPResult, bool*) (.localalias) (/home/bstaletic/.vim/pack/bundle/start/YouCompleteMe/third_party/ycmd/third_party/clangd/output/bin/clangd+0x17edb38)
#11 0x00000000017ef317 clang::Parser::isCXXSimpleDeclaration(bool) (/home/bstaletic/.vim/pack/bundle/start/YouCompleteMe/third_party/ycmd/third_party/clangd/output/bin/clangd+0x17ef317)
#12 0x00000000017c4da7 clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::Parser::ParsedAttributesWithRange&) (/home/bstaletic/.vim/pack/bundle/start/YouCompleteMe/third_party/ycmd/third_party/clangd/output/bin/clangd+0x17c4da7)
#13 0x00000000017c4eb8 clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*) (/home/bstaletic/.vim/pack/bundle/start/YouCompleteMe/third_party/ycmd/third_party/clangd/output/bin/clangd+0x17c4eb8)
#14 0x00000000017ce251 clang::Parser::ParseCompoundStatementBody(bool) (/home/bstaletic/.vim/pack/bundle/start/YouCompleteMe/third_party/ycmd/third_party/clangd/output/bin/clangd+0x17ce251)
#15 0x00000000017d1d3a clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) (/home/bstaletic/.vim/pack/bundle/start/YouCompleteMe/third_party/ycmd/third_party/clangd/output/bin/clangd+0x17d1d3a)
#16 0x000000000170234a clang::Parser::ParseFunctionDefinition(clang::ParsingDeclarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::LateParsedAttrList*) (/home/bstaletic/.vim/pack/bundle/start/YouCompleteMe/third_party/ycmd/third_party/clangd/output/bin/clangd+0x170234a)
#17 0x000000000172fc5f clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/home/bstaletic/.vim/pack/bundle/start/YouCompleteMe/third_party/ycmd/third_party/clangd/output/bin/clangd+0x172fc5f)
#18 0x00000000016fc842 clang::Parser::ParseDeclOrFunctionDefInternal(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/home/bstaletic/.vim/pack/bundle/start/YouCompleteMe/third_party/ycmd/third_party/clangd/output/bin/clangd+0x16fc842)
#19 0x00000000016fce75 clang::Parser::ParseDeclarationOrFunctionDefinition(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (.part.0) (/home/bstaletic/.vim/pack/bundle/start/YouCompleteMe/third_party/ycmd/third_party/clangd/output/bin/clangd+0x16fce75)
#20 0x0000000001706640 clang::Parser::ParseExternalDeclaration(clang::Parser::ParsedAttributesWithRange&, clang::ParsingDeclSpec*) (.localalias) (/home/bstaletic/.vim/pack/bundle/start/YouCompleteMe/third_party/ycmd/third_party/clangd/output/bin/clangd+0x1706640)
#21 0x0000000001706985 clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, bool) (/home/bstaletic/.vim/pack/bundle/start/YouCompleteMe/third_party/ycmd/third_party/clangd/output/bin/clangd+0x1706985)
#22 0x00000000016f5e39 clang::ParseAST(clang::Sema&, bool, bool) (/home/bstaletic/.vim/pack/bundle/start/YouCompleteMe/third_party/ycmd/third_party/clangd/output/bin/clangd+0x16f5e39)
#23 0x0000000001531ae1 clang::FrontendAction::Execute() (/home/bstaletic/.vim/pack/bundle/start/YouCompleteMe/third_party/ycmd/third_party/clangd/output/bin/clangd+0x1531ae1)
#24 0x0000000000b8180b clang::clangd::(anonymous namespace)::semaCodeComplete(std::unique_ptr<clang::CodeCompleteConsumer, std::default_delete<clang::CodeCompleteConsumer> >, clang::CodeCompleteOptions const&, clang::clangd::(anonymous namespace)::SemaCompleteInput const&, clang::clangd::IncludeStructure*) (/home/bstaletic/.vim/pack/bundle/start/YouCompleteMe/third_party/ycmd/third_party/clangd/output/bin/clangd+0xb8180b)
#25 0x0000000000b8d68e clang::clangd::codeComplete(llvm::StringRef, clang::clangd::Position, clang::clangd::PreambleData const*, clang::clangd::ParseInputs const&, clang::clangd::CodeCompleteOptions, clang::clangd::SpeculativeFuzzyFind*) (/home/bstaletic/.vim/pack/bundle/start/YouCompleteMe/third_party/ycmd/third_party/clangd/output/bin/clangd+0xb8d68e)
#26 0x0000000000b6d116 clang::clangd::ClangdServer::codeComplete(llvm::StringRef, clang::clangd::Position, clang::clangd::CodeCompleteOptions const&, llvm::unique_function<void (llvm::Expected<clang::clangd::CodeCompleteResult>)>)::'lambda'(llvm::Expected<clang::clangd::InputsAndPreamble>)::operator()(llvm::Expected<clang::clangd::InputsAndPreamble>) (/home/bstaletic/.vim/pack/bundle/start/YouCompleteMe/third_party/ycmd/third_party/clangd/output/bin/clangd+0xb6d116)
#27 0x0000000000b6dad4 void llvm::detail::UniqueFunctionBase<void, llvm::Expected<clang::clangd::InputsAndPreamble> >::CallImpl<clang::clangd::ClangdServer::codeComplete(llvm::StringRef, clang::clangd::Position, clang::clangd::CodeCompleteOptions const&, llvm::unique_function<void (llvm::Expected<clang::clangd::CodeCompleteResult>)>)::'lambda'(llvm::Expected<clang::clangd::InputsAndPreamble>)>(void*, llvm::Expected<clang::clangd::InputsAndPreamble>&) (/home/bstaletic/.vim/pack/bundle/start/YouCompleteMe/third_party/ycmd/third_party/clangd/output/bin/clangd+0xb6dad4)
#28 0x0000000000d04870 clang::clangd::TUScheduler::runWithPreamble(llvm::StringRef, llvm::StringRef, clang::clangd::TUScheduler::PreambleConsistency, llvm::unique_function<void (llvm::Expected<clang::clangd::InputsAndPreamble>)>)::'lambda'()::operator()() (/home/bstaletic/.vim/pack/bundle/start/YouCompleteMe/third_party/ycmd/third_party/clangd/output/bin/clangd+0xd04870)
#29 0x0000000000ec1750 void llvm::detail::UniqueFunctionBase<void>::CallImpl<clang::clangd::AsyncTaskRunner::runAsync(llvm::Twine const&, llvm::unique_function<void ()>)::'lambda0'()>(void*) (/home/bstaletic/.vim/pack/bundle/start/YouCompleteMe/third_party/ycmd/third_party/clangd/output/bin/clangd+0xec1750)
#30 0x0000000000595d5b threadFuncAsync(void*) (/home/bstaletic/.vim/pack/bundl
```

ycmd log:

```
2021-05-07 09:44:06,507 - DEBUG - TX: Sending message: b'Content-Length: 1252\r\n\r\n{"id":1,"jsonrpc":"2.0","method":"initialize","params":{"capabilities":{"textDocument":{"codeAction":{"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}}},"completion":{"completionItem":{"documentationFormat":["plaintext","markdown"]},"completionItemKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]}},"documentSymbol":{"hierarchicalDocumentSymbolSupport":false,"labelSupport":false,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]}},"hover":{"contentFormat":["plaintext","markdown"]},"signatureHelp":{"signatureInformation":{"documentationFormat":["plaintext","markdown"],"parameterInformation":{"labelOffsetSupport":true}}},"synchronization":{"didSave":true}},"workspace":{"applyEdit":true,"didChangeWatchedFiles":{"dynamicRegistration":true},"symbol":{"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]}},"workspaceEdit":{"documentChanges":true}}},"initializationOptions":{},"processId":2910,"rootPath":"/home/bstaletic/work/pybind11/tests","rootUri":"file:///home/bstaletic/work/pybind11/tests"}}'
2021-05-07 09:44:06,524 - DEBUG - RX: Received message: b'{"id":1,"jsonrpc":"2.0","result":{"capabilities":{"astProvider":true,"callHierarchyProvider":true,"codeActionProvider":{"codeActionKinds":["quickfix","refactor","info"]},"compilationDatabase":{"automaticReload":true},"completionProvider":{"allCommitCharacters":[" ","\\t","(",")","[","]","{","}","<",">",":",";",",","+","-","/","*","%","^","&","#","?",".","=","\\"","\'","|"],"resolveProvider":false,"triggerCharacters":[".","<",">",":","\\"","/"]},"declarationProvider":true,"definitionProvider":true,"documentFormattingProvider":true,"documentHighlightProvider":true,"documentLinkProvider":{"resolveProvider":false},"documentOnTypeFormattingProvider":{"firstTriggerCharacter":"\\n","moreTriggerCharacter":[]},"documentRangeFormattingProvider":true,"documentSymbolProvider":true,"executeCommandProvider":{"commands":["clangd.applyFix","clangd.applyTweak"]},"hoverProvider":true,"implementationProvider":true,"memoryUsageProvider":true,"referencesProvider":true,"renameProvider":true,"selectionRangeProvider":true,"semanticTokensProvider":{"full":{"delta":true},"legend":{"tokenModifiers":[],"tokenTypes":["variable","variable","parameter","function","method","function","property","variable","class","enum","enumMember","type","dependent","dependent","namespace","typeParameter","concept","type","macro","comment"]},"range":false},"signatureHelpProvider":{"triggerCharacters":["(",","]},"textDocumentSync":{"change":2,"openClose":true,"save":true},"typeHierarchyProvider":true,"workspaceSymbolProvider":true},"serverInfo":{"name":"clangd","version":"clangd version 12.0.0"}}}'
2021-05-07 09:44:06,526 - DEBUG - TX: Sending notification: b'Content-Length: 52\r\n\r\n{"jsonrpc":"2.0","method":"initialized","params":{}}'
2021-05-07 09:44:06,527 - DEBUG - TX: Sending notification: b'Content-Length: 86\r\n\r\n{"jsonrpc":"2.0","method":"workspace/didChangeConfiguration","params":{"settings":{}}}'
2021-05-07 09:44:06,527 - DEBUG - TX: Sending notification: b'Content-Length: 508\r\n\r\n{"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"languageId":"cpp","text":"#include <vector>\\n#include <thread>\\nstruct TestThread {\\n    ~TestThread() { delete t_; }\\n    std::thread * t_ = new std::thread([c=\'x\']{ std::this_thread::sleep_for(std::chrono::microseconds(50)); });\\n};\\n\\nint main() {\\n\\tstd::vector<TestThread> threads(1);\\n\\tstd::this_thread::sleep_for(std::chrono::milliseconds(50));\\n}\\n","uri":"file:///home/bstaletic/work/pybind11/tests/foo.cpp","version":1}}}'
2021-05-07 09:44:07,901 - DEBUG - RX: Received message: b'{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[],"uri":"file:///home/bstaletic/work/pybind11/tests/foo.cpp","version":1}}'
2021-05-07 09:44:08,656 - DEBUG - TX: Sending notification: b'Content-Length: 521\r\n\r\n{"jsonrpc":"2.0","method":"textDocument/didChange","params":{"contentChanges":[{"text":"#include <vector>\\n#include <thread>\\nstruct TestThread {\\n    ~TestThread() { delete t_; }\\n    std::thread * t_ = new std::thread([c=\'x\']{ std::this_thread::sleep_for(std::chrono::microseconds(50)); });\\n};\\n\\nint main() {\\n\\tstd::vector<TestThread> threads(1);\\n\\tstd::this_thread::sleep_for(std::chrono::milliseconds(50));\\n\\tstd::\\n}\\n"}],"textDocument":{"uri":"file:///home/bstaletic/work/pybind11/tests/foo.cpp","version":2}}}'
2021-05-07 09:44:08,658 - DEBUG - TX: Sending message: b'Content-Length: 183\r\n\r\n{"id":2,"jsonrpc":"2.0","method":"textDocument/completion","params":{"position":{"character":6,"line":10},"textDocument":{"uri":"file:///home/bstaletic/work/pybind11/tests/foo.cpp"}}}'
```

**System information**
Output of `clangd --version`: clangd version 12.0.0
Editor/LSP plugin: YCM/ycmd
Operating system: Linux

Since ycmd ships its own, recompiled and repackaged clangd, I should state that this repro's even with the clangd from the archive on llvm-project repo.

**Comment by gislan** [comment] 2021-05-07 13:09
Thank you for a detailed bug report.

This reproduces on main, with the following assertion:
clangd: /usr/local/google/home/adamcz/llvm/other/llvm/include/llvm/ADT/DenseMap.h:1260: DenseMapIterator<KeyT, ValueT, KeyInfoT, Bucket, IsConst> &llvm::DenseMapIterator<clang::DeclarationName, clang::StoredDeclsList, llvm::DenseMapInfo<clang::DeclarationName>, llvm::det
ail::DenseMapPair<clang::DeclarationName, clang::StoredDeclsList>, false>::operator++() [KeyT = clang::DeclarationName, ValueT = clang::StoredDeclsList, KeyInfoT = llvm::DenseMapInfo<clang::DeclarationName>, Bucket = llvm::detail::DenseMapPair<clang::DeclarationName, cla
ng::StoredDeclsList>, IsConst = false]: Assertion `isHandleInSync() && "invalid iterator access!"' failed.

I'll look into this.

**Comment by kadircet** [comment] 2021-05-07 13:40
might be related: https://reviews.llvm.org/D91524

**Comment by robbert-vdh** [comment] 2021-05-30 19:02
For me the exact same issue also happens using lsp-mode, master branch clangd, and the following code (it happens both with or without a standard specified):

```cpp
#include <boost/process/environment.hpp>

void foo(const std::string&) {}

void bar() {
    // Type `std::this_` below (this should yield 0 completions)
}
```

[Verbose STDERR log](https://github.com/clangd/clangd/files/6566772/clangd-stderr.log)  
[GDB backtrace from debug build](https://github.com/clangd/clangd/files/6566770/gdb-backtrace.log)

I've been experiencing similar crashes when trying to complete from the `std` namespace (often when trying to use iostream) since at least clangd 10.

**Comment by gislan** [comment] 2021-05-31 11:55
Sorry for lack of updates, I've been away for a few days.

This is easy to reproduce (thanks another repro!) and, as far as I can tell, has nothing to do with C++20. The -std=c++20 simply enables some ifdef-ed code in standard library.

The thing happens because lookupInDeclContext() iterates over a DenseMap with decls and then calls FoundDecl on a consumer. The code completion consumer for that might, in some cases (like when extra constructors are added to standard library in C++20 mode), mutate that map, thus invalidating the iterator.

The solution is simple, but I don't have a repro case that doesn't use external libraries (like stdlib or boost). If I can't write a test like this soon, I'll send a change for review without the test case for now.

**Comment by robbert-vdh** [comment] 2021-06-05 23:52
This still relies on the standard library, but I accidentally found another simpler way to reproduce this with GCC 11 and clangd from LLVM `13.0.0-389504-4ed2b6cccdef`:

```cpp
#include <memory>
#include <optional>

struct Foo;

struct Tree {
    std::shared_ptr<Tree> left;
    std::shared_ptr<Tree> right;
};

// struct Bar {
//     std::shared_ptr<Bar> bar;
//     std::shared_ptr<Bar> baz;
// };

int main(int argc, char* argv[]) {
    // Type `std::cout` below
}
```

The issue seems to disappear when commenting out the definition for `Tree` and uncommenting `Bar`. Maybe this is helpful in finding a way to reliably reproduce this with no external libraries.

**Comment by gislan** [comment] 2021-06-06 14:24
Thanks!

The case I was working with was:
#include <list>
int main() {

std::list<int>;
std::
}

Code completion at the second std:: crashes.

Fix is in https://reviews.llvm.org/D103472

**Comment by robbert-vdh** [comment] 2021-06-06 20:45
I've built LLVM with this patch applied and can confirm that none of these test cases cause clangd to crash anymore! I'll let you know if I somehow manage to run into another weird situation where completion causes clangd to crash. You can't believe how happy I'd be if clangd doesn't crash when using iostream/some other common STL functions anymore. I just took restarting clangd every couple of minutes for granted because other than that clangd has worked amazingly well for me! :grin:

**Comment by gislan** [comment] 2021-06-07 11:38
I committed that patch. Should fix the issues reported here once released. If you want it to get it right away, you can also just build from source.

Thanks everyone!

**Comment by kadircet** [comment] 2021-07-06 08:57
fixed with llvm/llvm-project@721476e6b2119a93033903109b54f429b6e8c91b

**Closed** 2021-07-06 08:56 UTC

**Comment by wbthomason** [comment] 2021-07-16 23:40
Is this fix included in `clangd 12.0.1`? I'm still seeing crashes that seem to match this issue - if it's expected to be fixed in 12.0.1, I'll find a minimal reproducer and file another issue.

**Comment by HighCommander4** [comment] 2021-07-17 00:13
> Is this fix included in `clangd 12.0.1`?

I don't believe so. The only tag I see on the commit linked above is `main`, which suggests that by default, it will next appear in the 13.0 release.

Appearing in a 12.x release would require a backport to the 12.x branch; I'm not sure if such a backport is planned.

**Comment by wbthomason** [comment] 2021-07-17 00:15
Ah, got it - I saw that the commit tagged for 12.0.1 was later than 721476e, so I was unsure if it had been included. Thanks for the clarification! I'll look forward to 13.0.

**Comment by HighCommander4** [comment] 2021-07-17 00:23
By the way, if anyone needs this fix sooner and doesn't mind using an unofficial release, there are weekly snapshots at https://github.com/clangd/clangd/releases.
