### ISSUE TITLE
Extra characters are inserted in include snippet completion

### ISSUE THREAD

**Issue by UtkarshVerma** [clangd/clangd#1706] opened 2023-07-20 03:04 UTC
Here is the problem I'm facing:

https://github.com/clangd/clangd/assets/31820255/9a088831-78e8-4cd2-8332-7a382be19c52

An extra angle bracket is included every time I try to use an include.

**System information**

Output of `clangd --version`:
```console
$ clangd --version 
clangd version 16.0.2 (https://github.com/llvm/llvm-project 18ddebe1a1a9bde349441631365f0472e9693520) 
Features: linux+grpc 
Platform: x86_64-unknown-linux-gnu 
```

Editor/LSP plugin:
nvim, nvim-lspconfig

Operating system:
Arch Linux

**Comment by HighCommander4** [comment] 2023-07-20 03:51
Duplicate of #1041. The discussion there in turn suggests that this is a bug in the client (nvim), since clangd is sending a correct text edit that's instructing the editor to replace a text range that includes the existing `>` with the completion text.

**Closed by HighCommander4** 2023-07-20 03:51 UTC
