### ISSUE TITLE
Can you add binary builds for FreeBSD?

### ISSUE THREAD

**Issue by chatchoi** [clangd/clangd#2149] opened 2024-09-18 16:13 UTC
FreeBSD will force me to install a big `llvm` package which will cost me about 2 to 3 GB of disk space when installed only to have clangd. The lite flavor of the `llvm` package doesn't include clangd.

**Comment by HighCommander4** [comment] 2024-09-18 16:29
Duplicate of #1265.

**Closed by HighCommander4** 2024-09-18 16:29 UTC
Labels: enhancement
