### ISSUE TITLE
Clangd doesn't understand RISC-V vector intrisics (<riscv_vector.h>)

### ISSUE THREAD

**Issue by Ferdi265** [clangd/clangd#2143] opened 2024-09-13 16:28 UTC
Clangd doesn't understand the RISC-V vector intrinsics generated by `#pragma clang riscv intrinsic vector` in `<riscv_vector.h>`. The `__riscv_vsetvl_xxx` defines work, but operations such as `__riscv_vadd_vv_u64m4()` aren't detected properly and are flagged as errors.

**Testcase**

C File: (the code is bogus, but compiles, only as demonstration to show that clangd doesn't know about the intrinsic)

```c
#include <riscv_vector.h>

vuint64m4_t v_add(vuint64m4_t a, vuint64m4_t b, size_t vl) {
    return __riscv_vadd_vv_u64m4(a, b, vl);
}
```

CMake:

```cmake
cmake_minimum_required(VERSION 3.24)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
set(CMAKE_COLOR_DIAGNOSTICS ON)

set(CMAKE_C_COMPILER "clang")
add_compile_options(--target=riscv64-linux-gnu -march=rv64gcv)

project(test-project C)

set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wall -Wextra")
set(CMAKE_C_STANDARD 23)
set(CMAKE_C_STANDARD_REQUIRED ON)
set(CMAKE_C_EXTENSIONS ON)

file(GLOB test-sources CONFIGURE_DEPENDS *.c)
add_library(test ${test-sources})

```

**Logs**

[clangd.log](https://github.com/user-attachments/files/16996807/clangd.log)

**System information**

Output of `clangd --version`:

```
clangd version 18.1.8
Features: linux
Platform: x86_64-pc-linux-gnu
```

Output of `clang --version`:

```
clang version 18.1.8
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

Editor/LSP plugin: neovim with `nvim-lspconfig`

Operating system: Arch Linux

**Comment by HighCommander4** [comment] 2024-09-22 04:06
> the code is bogus, but compiles

Could you specify what command you're using to successfully compile this code?

**Comment by Ferdi265** [comment] 2024-09-22 09:35
> > the code is bogus, but compiles
> 
> Could you specify what command you're using to successfully compile this code?

`clang --target=riscv64-linux-gnu -march=rv64gcv -Wall -Wextra -c test.c -o test.o`

**Comment by HighCommander4** [comment] 2024-09-22 20:52
> > > the code is bogus, but compiles
> > 
> > 
> > Could you specify what command you're using to successfully compile this code?
> 
> `clang --target=riscv64-linux-gnu -march=rv64gcv -Wall -Wextra -c test.c -o test.o`

When I try this, I get:

```console
$ clang-18 --target=riscv64-linux-gnu -march=rv64gcv -Wall -Wextra -c test.c -o test.o
In file included from test.c:1:
In file included from /usr/lib/llvm-18/lib/clang/18/include/riscv_vector.h:14:
In file included from /usr/lib/llvm-18/lib/clang/18/include/stdint.h:52:
/usr/include/stdint.h:26:10: fatal error: 'bits/libc-header-start.h' file not found
   26 | #include <bits/libc-header-start.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

Is there some additional setup / configuration I need to get this to work?

**Comment by Ferdi265** [comment] 2024-09-22 22:14
> > > > the code is bogus, but compiles
> > > 
> > > 
> > > Could you specify what command you're using to successfully compile this code?
> > 
> > 
> > `clang --target=riscv64-linux-gnu -march=rv64gcv -Wall -Wextra -c test.c -o test.o`
> 
> When I try this, I get:
> 
> ```
> $ clang-18 --target=riscv64-linux-gnu -march=rv64gcv -Wall -Wextra -c test.c -o test.o
> In file included from test.c:1:
> In file included from /usr/lib/llvm-18/lib/clang/18/include/riscv_vector.h:14:
> In file included from /usr/lib/llvm-18/lib/clang/18/include/stdint.h:52:
> /usr/include/stdint.h:26:10: fatal error: 'bits/libc-header-start.h' file not found
>    26 | #include <bits/libc-header-start.h>
>       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
> 1 error generated.
> ```
> 
> Is there some additional setup / configuration I need to get this to work?

Huh. It works on my Laptop (Arch Linux) and on my phone (Android, Termux); I'm gonna see if I can get this to run in Docker as well.

**Comment by Ferdi265** [comment] 2024-09-22 22:22
> > > > the code is bogus, but compiles
> > > 
> > > 
> > > Could you specify what command you're using to successfully compile this code?
> > 
> > 
> > `clang --target=riscv64-linux-gnu -march=rv64gcv -Wall -Wextra -c test.c -o test.o`
> 
> When I try this, I get:
> 
> ```
> $ clang-18 --target=riscv64-linux-gnu -march=rv64gcv -Wall -Wextra -c test.c -o test.o
> In file included from test.c:1:
> In file included from /usr/lib/llvm-18/lib/clang/18/include/riscv_vector.h:14:
> In file included from /usr/lib/llvm-18/lib/clang/18/include/stdint.h:52:
> /usr/include/stdint.h:26:10: fatal error: 'bits/libc-header-start.h' file not found
>    26 | #include <bits/libc-header-start.h>
>       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
> 1 error generated.
> ```
> 
> Is there some additional setup / configuration I need to get this to work?

I get the same error in an `ubuntu:24.04` container if I install just `clang`, but if I also install `gcc-multilib`, it works.

**Comment by HighCommander4** [comment] 2024-09-22 23:06
Thanks, installing `gcc-multilib` worked for me as well.

---

This looks like a bug in clang's precompiled headers. Steps to reproduce without clangd:

```console
$ cat test.h
#include <riscv_vector.h>
$ cat test.c
vuint64m4_t v_add(vuint64m4_t a, vuint64m4_t b, size_t vl) {
    return __riscv_vadd_vv_u64m4(a, b, vl);
}
$ clang --target=riscv64-linux-gnu -march=rv64gcv -x c-header test.h -o test.h.pch
$ clang --target=riscv64-linux-gnu -march=rv64gcv -include-pch test.h.pch -c test.c
test.c:2:12: error: call to undeclared function '__riscv_vadd_vv_u64m4'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
    2 |     return __riscv_vadd_vv_u64m4(a, b, vl);
      |            ^
test.c:2:12: error: returning 'int' from a function with incompatible result type 'vuint64m4_t' (aka '__rvv_uint64m4_t')
    2 |     return __riscv_vadd_vv_u64m4(a, b, vl);
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.
```

@Ferdi265 would you mind filing this upstream at https://github.com/llvm/llvm-project/issues/ (with the above commands involving PCH as test case)?

(If you're wondering about the connection between clangd and PCH, clangd basically compiles the part of the file containing the includes at the top as a PCH, so that the rest of the file can be reparsed quickly as you edit it.)

**Comment by HighCommander4** [comment] 2024-09-22 23:11
As a (not very satisfying) workaround, moving the include of `<riscv_vector.h>` to after a non-preprocessor declaration in the file moves it out of the PCH region and makes it work:

```c
// other includes
int dummy_declaration;  // ends the preamble region
#include <riscv_vector.h>

vuint64m4_t v_add(vuint64m4_t a, vuint64m4_t b, size_t vl) {
    return __riscv_vadd_vv_u64m4(a, b, vl);  // works
}
```

**Comment by HighCommander4** [comment] 2024-09-22 23:27
(I guess the above only actually works if the other includes do not bring in `<riscv_vector.h>`; if they do, the include further down is basically a no-op.)

**Comment by Ferdi265** [comment] 2024-09-23 08:06
Thanks for narrowing this down to PCH generation! I'll file this upstream.

**Comment by Ferdi265** [comment] 2024-09-23 08:36
Upstream bug report filed: [here](https://github.com/llvm/llvm-project/issues/109634)

**Comment by Ferdi265** [comment] 2024-09-23 08:52
> (I guess the above only actually works if the other includes do not bring in `<riscv_vector.h>`; if they do, the include further down is basically a no-op.)

as an additional workaround it seems it's enough if `#pragma clang riscv intrinsic vector` is added to the source file after the first declaration. The normal declarations in the RISC-V header work fine, and this pragma is also resistant to previous inclusion of the same header.

**Comment by HighCommander4** [comment] 2024-09-24 04:10
Duplicate of https://github.com/llvm/llvm-project/issues/109634

**Comment by HighCommander4** [comment] 2024-09-24 04:10
> Upstream bug report filed: [here](https://github.com/llvm/llvm-project/issues/109634)

Thanks! I'll close this one as a dupe to keep further discussion in one place.

**Closed by HighCommander4** 2024-09-24 04:10 UTC
