### ISSUE TITLE
bits/stdc++.h is included when tab-completing std::size_t

### ISSUE THREAD

**Issue by Aster89** [clangd/clangd#666] opened 2021-01-25 22:02 UTC
When I <kbd>Tab</kbd>-complete `std::size_t`, the header `bits/stdc++.h` gets included in a C++ file (I initially asked [a question on SO](https://stackoverflow.com/questions/65830652/what-tab-completion-is-triggering-the-insertion-of-the-include-statement-for-bit/65887798#65887798)). Since this header file is not part of the C++ standard and is, therefore, non-portable, it should be avoided, shouldn't it?

**System information**
Well it's actually YCM in Vim which uses clangd.

Editor: Vim with YCM
Operating system: ArchLinux

**Comment by HighCommander4** [comment] 2021-01-25 22:13
Dupe of (or at least related to) #68?

**Comment by kadircet** [comment] 2021-01-26 06:44
Sent out https://reviews.llvm.org/D95423

**Closed** 2021-01-26 16:53 UTC
