### ISSUE TITLE
Universal build compile command not supported

### ISSUE THREAD

**Issue by abbaswasim** [clangd/clangd#952] opened 2021-12-15 16:57 UTC
Not sure if this is a bug or feature request but I have a [project](https://github.com/ARM-software/astc-encoder) that can be built as a MacOs Universal binary for arm64 and x86_64. `clangd` isn't able to parse sources in this project with commands including `-arch arm64 -arch x86_64` while `clang/clang++`  and `gcc/g++` happily accepts that. The error I get is `Unable to handle compilation, expected exactly one compiler job in...`. I further get "Invalid AST" errors but I think that's because the file in not parsed to start with.

**Logs**
Here are the logs I am getting when I have both `-arch arm64 -arch x86_64` in the compile command.
[multi-arch.txt](https://github.com/clangd/clangd/files/7721230/multi-arch.txt)
vs `-arch x86_64` in the compile command
[single_arch.txt](https://github.com/clangd/clangd/files/7721231/single_arch.txt)

I can't seem to upload the compilation database or the lit test hence they are in text form at the end of the issue. You can use these two to reproduce the issue with `clangd -lit-test < universal.test` after the file paths are adjusted in those. Change /System/Volumes/Data/development/clangd-bug-tracking/ to where you will put `compile_commands.json`, `universal.test` and `main.cpp`.

**System information**
Output of `clangd --version`:
```
Homebrew clangd version 13.0.0
Features: mac+xpc
Platform: x86_64-apple-darwin20.6.0
```
Editor/LSP plugin:
N/A. I am using `clangd` directly via command `clangd -lit-test < universal.test` line providing a lit test "universal.test" attached. I was getting the same error in emacs/lsp. I am doing this so I can isolate the issue to `clangd`

Operating system:
MacOs 11.6.1

compile_commands.json
```
[
{
  "directory": "/System/Volumes/Data/development/clangd-bug-tracking/",
  "command": "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -I/System/Volumes/Data/development/clangd-bug-tracking -I/System/Volumes/Data/development/clangd-bug-tracking -g -arch arm64 -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk -mmacosx-version-min=11.6 -pthread -Wall -Wextra -Wpedantic -Werror -Wshadow -Wdouble-promotion -Wno-unknown-warning-option -Wno-c++98-compat-pedantic -Wno-c++98-c++11-compat-pedantic -Wno-float-equal -Wno-deprecated-declarations -Wno-atomic-implicit-seq-cst -Wno-old-style-cast -Wno-cast-align -Wno-sign-conversion -Wno-implicit-int-conversion -Wno-shift-sign-overflow -Wno-format-nonliteral -mavx2 -mpopcnt -mf16c -Wno-unused-command-line-argument -std=c++14 -o main.cpp.o -c /System/Volumes/Data/development/clangd-bug-tracking/main.cpp",
  "file": "/System/Volumes/Data/development/clangd-bug-tracking/main.cpp"
}
]
```
universal.test
```
# RUN: clangd -lit-test < %s | FileCheck -strict-whitespace %s
{"jsonrpc":"2.0","id":0,"method":"initialize","params":{"processId":123,"rootPath":"/System/Volumes/Data/development/clangd-bug-tracking","rootUri":"file:///System/Volumes/Data/development/clangd-bug-tracking/","capabilities":{"workspace":{"workspaceEdit":{"documentChanges":true,"resourceOperations":["create","rename","delete"]},"applyEdit":true,"symbol":{"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]}},"executeCommand":{"dynamicRegistration":false},"didChangeWatchedFiles":{"dynamicRegistration":true},"workspaceFolders":true,"configuration":true},"textDocument":{"declaration":{"linkSupport":true},"definition":{"linkSupport":true},"implementation":{"linkSupport":true},"typeDefinition":{"linkSupport":true},"synchronization":{"willSave":true,"didSave":true,"willSaveWaitUntil":true},"documentSymbol":{"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]},"hierarchicalDocumentSymbolSupport":true},"formatting":{"dynamicRegistration":true},"codeAction":{"dynamicRegistration":true,"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}}},"completion":{"completionItem":{"snippetSupport":true,"documentationFormat":["markdown"]},"contextSupport":true},"signatureHelp":{"signatureInformation":{"parameterInformation":{"labelOffsetSupport":true}}},"documentLink":{"dynamicRegistration":true},"hover":{"contentFormat":["markdown","plaintext"]},"foldingRange":{"dynamicRegistration":true,"rangeLimit":null,"lineFoldingOnly":false}}},"trace":"off"}}
---
{"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{
  "uri":"file:///System/Volumes/Data/development/clangd-bug-tracking/main.cpp","languageId":"cpp","version":1,"text":"#include <iostream>\n\n int main(int argc, char *argv[])\n {\n (void) argc;\n (void) argv;\n\n std::cout << \"Hello world\" << std::endl;\n return 0;\n}\n"}}}
---
{"jsonrpc":"2.0","id":1,"method":"textDocument/references","params":{
  "textDocument":{"uri":"file:///System/Volumes/Data/development/clangd-bug-tracking/main.cpp"},
  "position":{"line":0,"character":4},
  "context":{"includeDeclaration": false}
}}
#      CHECK:  "id": 1
# CHECK-NEXT:  "jsonrpc": "2.0",
# CHECK-NEXT:  "result": [
# CHECK-NEXT:    {
# CHECK-NEXT:      "range": {
# CHECK-NEXT:        "end": {
# CHECK-NEXT:          "character": 16,
# CHECK-NEXT:          "line": 0
# CHECK-NEXT:        },
# CHECK-NEXT:        "start": {
# CHECK-NEXT:          "character": 15,
# CHECK-NEXT:          "line": 0
# CHECK-NEXT:        }
# CHECK-NEXT:      },
# CHECK-NEXT:      "uri": "{{.*}}/main.cpp"
# CHECK-NEXT:    }
# CHECK-NEXT:  ]
---
{"jsonrpc":"2.0","id":3,"method":"shutdown"}
---
{"jsonrpc":"2.0","method":"exit"}
```

main.cpp
```
#include <iostream>

int main(int argc, char *argv[])
{
	(void) argc;
	(void) argv;

	std::cout << "Hello world" << std::endl;
	return 0;
}
```

**Comment by sam-mccall** [comment] 2021-12-15 17:04
Sorry, this is a dupe of #827. The fix will be in clangd 14.

https://github.com/clangd/clangd/issues/827#issuecomment-893761748 has a workaround.

**Closed by sam-mccall** 2021-12-15 17:04 UTC

**Comment by abbaswasim** [comment] 2021-12-15 18:17
Thanks @sam-mccall I failed to find this when searching, should have searched in `closed` ones too. Would have saved me 30min. Glad it's reported though and thanks in advance for the fix when it lands.
