### ISSUE TITLE
Crash During specific Template Case

### ISSUE THREAD

**Issue by avlec** [clangd/clangd#2119] opened 2024-08-16 15:53 UTC
The following bit of reduced code seems to break in a specific case that I have yet to narrow down. It seems to be crashing on version 17 and 18. The problem seems to be with the constructor. The constructor can be either removed or the arguments swapped positions and the crash goes away. When it's defined as it is below it causes the crash.

```cpp
template <template <class> typename T, typename U>
struct test
{
    test(U && arg1, T<int> arg2) {}
};
```

**Logs**
```
V[08:39:00.894] BackgroundIndex: building version 2 when background indexer is idle
 #0 0x00007fb898eda3bf llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) build-llvm/tools/clang/stage2-bins/llvm/lib/Support/Unix/Signals.inc:723:13
 #1 0x00007fb898ed84f9 llvm::sys::RunSignalHandlers() build-llvm/tools/clang/stage2-bins/llvm/lib/Support/Signals.cpp:106:18
 #2 0x00007fb898edab00 SignalHandler build-llvm/tools/clang/stage2-bins/llvm/lib/Support/Unix/Signals.inc:413:1
 #3 0x00007fb897c01320 (/lib/x86_64-linux-gnu/libc.so.6+0x45320)
 #4 0x000055f8844e2698 memcpy /usr/include/x86_64-linux-gnu/bits/string_fortified.h:29:10
 #5 0x000055f8844e2698 asInt build-llvm/tools/clang/stage2-bins/llvm/include/llvm/ADT/PointerIntPair.h:41:5
 #6 0x000055f8844e2698 operator long build-llvm/tools/clang/stage2-bins/llvm/include/llvm/ADT/PointerIntPair.h:45:48
 #7 0x000055f8844e2698 getInt build-llvm/tools/clang/stage2-bins/llvm/include/llvm/ADT/PointerIntPair.h:96:57
 #8 0x000055f8844e2698 isPossible<clang::DeclContext *> build-llvm/tools/clang/stage2-bins/llvm/include/llvm/ADT/PointerUnion.h:230:18
 #9 0x000055f8844e2698 isPossible build-llvm/tools/clang/stage2-bins/llvm/include/llvm/ADT/PointerUnion.h:248:12
#10 0x000055f8844e2698 isPossible build-llvm/tools/clang/stage2-bins/llvm/include/llvm/Support/Casting.h:396:12
#11 0x000055f8844e2698 isa<clang::DeclContext *, llvm::PointerUnion<clang::DeclContext *, clang::Decl::MultipleDC *> > build-llvm/tools/clang/stage2-bins/llvm/include/llvm/Support/Casting.h:549:10
#12 0x000055f8844e2698 is<clang::DeclContext *> build-llvm/tools/clang/stage2-bins/llvm/include/llvm/ADT/PointerUnion.h:150:57
#13 0x000055f8844e2698 isInSemaDC build-llvm/tools/clang/stage2-bins/clang/include/clang/AST/DeclBase.h:273:44
#14 0x000055f8844e2698 getDeclContext build-llvm/tools/clang/stage2-bins/clang/include/clang/AST/DeclBase.h:454:9
#15 0x000055f8844e2698 getDeclContext build-llvm/tools/clang/stage2-bins/clang/include/clang/AST/DeclBase.h:459:37
#16 0x000055f8844e2698 clang::Decl::isInStdNamespace() const build-llvm/tools/clang/stage2-bins/clang/lib/AST/DeclBase.cpp:404:27
#17 0x000055f88411298f operator() build-llvm/tools/clang/stage2-bins/clang-tools-extra/clang-tidy/bugprone/ForwardingReferenceOverloadCheck.cpp:27:41
#18 0x000055f88411298f matches build-llvm/tools/clang/stage2-bins/clang-tools-extra/clang-tidy/bugprone/ForwardingReferenceOverloadCheck.cpp:42:7
#19 0x000055f8843bf9cc clang::ast_matchers::internal::DynTypedMatcher::matches(clang::DynTypedNode const&, clang::ast_matchers::internal::ASTMatchFinder*, clang::ast_matchers::internal::BoundNodesTreeBuilder*) const build-llvm/tools/clang/stage2-bins/clang/lib/ASTMatchers/ASTMatchersInternal.cpp:304:23
#20 0x000055f88404534f clang::ast_matchers::internal::matcher_hasType0Matcher<clang::ParmVarDecl, clang::ast_matchers::internal::Matcher<clang::QualType>>::matches(clang::ParmVarDecl const&, clang::ast_matchers::internal::ASTMatchFinder*, clang::ast_matchers::internal::BoundNodesTreeBuilder*) const build-llvm/tools/clang/stage2-bins/clang/include/clang/ASTMatchers/ASTMatchers.h:4000:1
#21 0x000055f8843bf9cc clang::ast_matchers::internal::DynTypedMatcher::matches(clang::DynTypedNode const&, clang::ast_matchers::internal::ASTMatchFinder*, clang::ast_matchers::internal::BoundNodesTreeBuilder*) const build-llvm/tools/clang/stage2-bins/clang/lib/ASTMatchers/ASTMatchersInternal.cpp:304:23
#22 0x000055f884114266 matches build-llvm/tools/clang/stage2-bins/clang/include/clang/ASTMatchers/ASTMatchersInternal.h:613:27
#23 0x000055f884114266 clang::ParmVarDecl* const* clang::ast_matchers::internal::matchesFirstInPointerRange<clang::ast_matchers::internal::Matcher<clang::ParmVarDecl>, clang::ParmVarDecl* const*>(clang::ast_matchers::internal::Matcher<clang::ParmVarDecl> const&, clang::ParmVarDecl* const*, clang::ParmVarDecl* const*, clang::ast_matchers::internal::ASTMatchFinder*, clang::ast_matchers::internal::BoundNodesTreeBuilder*) build-llvm/tools/clang/stage2-bins/clang/include/clang/ASTMatchers/ASTMatchersInternal.h:867:17
#24 0x000055f884114183 matches build-llvm/tools/clang/stage2-bins/clang/include/clang/ASTMatchers/ASTMatchers.h:5256:10
#25 0x000055f8843bf9cc clang::ast_matchers::internal::DynTypedMatcher::matches(clang::DynTypedNode const&, clang::ast_matchers::internal::ASTMatchFinder*, clang::ast_matchers::internal::BoundNodesTreeBuilder*) const build-llvm/tools/clang/stage2-bins/clang/lib/ASTMatchers/ASTMatchersInternal.cpp:304:23
#26 0x000055f8843c33e5 notUnaryOperator build-llvm/tools/clang/stage2-bins/clang/lib/ASTMatchers/ASTMatchersInternal.cpp:384:28
#27 0x000055f8843c33e5 dynMatches build-llvm/tools/clang/stage2-bins/clang/lib/ASTMatchers/ASTMatchersInternal.cpp:123:12
#28 0x000055f8843bfb0e clang::ast_matchers::internal::DynTypedMatcher::matchesNoKindCheck(clang::DynTypedNode const&, clang::ast_matchers::internal::ASTMatchFinder*, clang::ast_matchers::internal::BoundNodesTreeBuilder*) const build-llvm/tools/clang/stage2-bins/clang/lib/ASTMatchers/ASTMatchersInternal.cpp:332:23
#29 0x000055f8843c2a37 __find_if<const clang::ast_matchers::internal::DynTypedMatcher *, __gnu_cxx::__ops::_Iter_negate<(lambda at clang/lib/ASTMatchers/ASTMatchersInternal.cpp:394:38)> > /usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/stl_algobase.h:2097:8
#30 0x000055f8843c2a37 __find_if_not<const clang::ast_matchers::internal::DynTypedMatcher *, __gnu_cxx::__ops::_Iter_pred<(lambda at clang/lib/ASTMatchers/ASTMatchersInternal.cpp:394:38)> > /usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/stl_algo.h:112:14
#31 0x000055f8843c2a37 find_if_not<const clang::ast_matchers::internal::DynTypedMatcher *, (lambda at clang/lib/ASTMatchers/ASTMatchersInternal.cpp:394:38)> /usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/stl_algo.h:519:14
#32 0x000055f8843c2a37 all_of<const clang::ast_matchers::internal::DynTypedMatcher *, (lambda at clang/lib/ASTMatchers/ASTMatchersInternal.cpp:394:38)> /usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/stl_algo.h:459:24
#33 0x000055f8843c2a37 all_of<llvm::ArrayRef<clang::ast_matchers::internal::DynTypedMatcher> &, (lambda at clang/lib/ASTMatchers/ASTMatchersInternal.cpp:394:38)> build-llvm/tools/clang/stage2-bins/llvm/include/llvm/ADT/STLExtras.h:1732:10
#34 0x000055f8843c2a37 allOfVariadicOperator build-llvm/tools/clang/stage2-bins/clang/lib/ASTMatchers/ASTMatchersInternal.cpp:394:10
#35 0x000055f8843c2a37 dynMatches build-llvm/tools/clang/stage2-bins/clang/lib/ASTMatchers/ASTMatchersInternal.cpp:123:12
#36 0x000055f8843c2025 dynMatches build-llvm/tools/clang/stage2-bins/clang/lib/ASTMatchers/ASTMatchersInternal.cpp:0:33
#37 0x000055f8843bf9cc clang::ast_matchers::internal::DynTypedMatcher::matches(clang::DynTypedNode const&, clang::ast_matchers::internal::ASTMatchFinder*, clang::ast_matchers::internal::BoundNodesTreeBuilder*) const build-llvm/tools/clang/stage2-bins/clang/lib/ASTMatchers/ASTMatchersInternal.cpp:304:23
#38 0x000055f88438ba4e matchWithFilter build-llvm/tools/clang/stage2-bins/clang/lib/ASTMatchers/ASTMatchFinder.cpp:1064:11
#39 0x000055f88438e58b getKind build-llvm/tools/clang/stage2-bins/clang/include/clang/AST/DeclBase.h:447:51
#40 0x000055f88438e58b TraverseDecl build-llvm/tools/clang/stage2-bins/clang/include/clang/AST/RecursiveASTVisitor.h:743:14
#41 0x000055f88438e58b TraverseDecl build-llvm/tools/clang/stage2-bins/clang/lib/ASTMatchers/ASTMatchFinder.cpp:1471:48
#42 0x000055f884393b9b TraverseDeclContextHelper build-llvm/tools/clang/stage2-bins/clang/include/clang/AST/RecursiveASTVisitor.h:1480:7
#43 0x000055f884393b9b TraverseCXXRecordDecl build-llvm/tools/clang/stage2-bins/clang/include/clang/AST/RecursiveASTVisitor.h:1996:1
#44 0x000055f88438e70f TraverseDecl build-llvm/tools/clang/stage2-bins/build-llvm/tools/clang/stage2-bins/tools/clang/include/clang/AST/DeclNodes.inc:414:1
#45 0x000055f88438e70f TraverseDecl build-llvm/tools/clang/stage2-bins/clang/lib/ASTMatchers/ASTMatchFinder.cpp:1471:48
#46 0x000055f884395541 TraverseClassTemplateDecl build-llvm/tools/clang/stage2-bins/clang/include/clang/AST/RecursiveASTVisitor.h:1883:1
#47 0x000055f88438e76f TraverseDecl build-llvm/tools/clang/stage2-bins/build-llvm/tools/clang/stage2-bins/tools/clang/include/clang/AST/DeclNodes.inc:524:1
#48 0x000055f88438e76f TraverseDecl build-llvm/tools/clang/stage2-bins/clang/lib/ASTMatchers/ASTMatchFinder.cpp:1471:48
#49 0x000055f88438ee58 TraverseTranslationUnitDecl build-llvm/tools/clang/stage2-bins/clang/include/clang/AST/RecursiveASTVisitor.h:1580:1
#50 0x000055f88438e5b3 TraverseDecl build-llvm/tools/clang/stage2-bins/build-llvm/tools/clang/stage2-bins/tools/clang/include/clang/AST/DeclNodes.inc:24:1
#51 0x000055f88438e5b3 TraverseDecl build-llvm/tools/clang/stage2-bins/clang/lib/ASTMatchers/ASTMatchFinder.cpp:1471:48
#52 0x000055f884360c65 onEndOfTranslationUnit build-llvm/tools/clang/stage2-bins/clang/lib/ASTMatchers/ASTMatchFinder.cpp:446:30
#53 0x000055f884360c65 clang::ast_matchers::MatchFinder::matchAST(clang::ASTContext&) build-llvm/tools/clang/stage2-bins/clang/lib/ASTMatchers/ASTMatchFinder.cpp:1700:11
#54 0x000055f883e2bfea build build-llvm/tools/clang/stage2-bins/clang-tools-extra/clangd/ParsedAST.cpp:717:3
#55 0x000055f883ec5c12 ~__shared_count /usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/shared_ptr_base.h:1070:6
#56 0x000055f883ec5c12 ~__shared_ptr /usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/shared_ptr_base.h:1524:31
#57 0x000055f883ec5c12 generateDiagnostics build-llvm/tools/clang/stage2-bins/clang-tools-extra/clangd/TUScheduler.cpp:1210:39
#58 0x000055f883ec5692 __destroy<clang::clangd::Diag *> /usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/stl_construct.h:162:19
#59 0x000055f883ec5692 _Destroy<clang::clangd::Diag *> /usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/stl_construct.h:195:7
#60 0x000055f883ec5692 _Destroy<clang::clangd::Diag *, clang::clangd::Diag> /usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/alloc_traits.h:948:7
#61 0x000055f883ec5692 ~vector /usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/stl_vector.h:735:2
#62 0x000055f883ec5692 operator() build-llvm/tools/clang/stage2-bins/clang-tools-extra/clangd/TUScheduler.cpp:1144:5
#63 0x000055f883ec207e operator() build-llvm/tools/clang/stage2-bins/llvm/include/llvm/ADT/STLFunctionalExtras.h:0:12
#64 0x000055f883ec207e runTask build-llvm/tools/clang/stage2-bins/clang-tools-extra/clangd/TUScheduler.cpp:1324:3
#65 0x000055f883ec1b64 run build-llvm/tools/clang/stage2-bins/clang-tools-extra/clangd/TUScheduler.cpp:1459:5
#66 0x000055f883ec1b64 operator() build-llvm/tools/clang/stage2-bins/clang-tools-extra/clangd/TUScheduler.cpp:822:42
#67 0x000055f883ec1b64 CallImpl<(lambda at clang-tools-extra/clangd/TUScheduler.cpp:822:21)> build-llvm/tools/clang/stage2-bins/llvm/include/llvm/ADT/FunctionExtras.h:221:12
#68 0x000055f884020011 memcpy /usr/include/x86_64-linux-gnu/bits/string_fortified.h:29:10
#69 0x000055f884020011 operator= build-llvm/tools/clang/stage2-bins/llvm/include/llvm/ADT/PointerIntPair.h:48:5
#70 0x000055f884020011 PunnedPointer build-llvm/tools/clang/stage2-bins/llvm/include/llvm/ADT/PointerIntPair.h:37:60
#71 0x000055f884020011 PointerIntPair build-llvm/tools/clang/stage2-bins/llvm/include/llvm/ADT/PointerIntPair.h:86:13
#72 0x000055f884020011 UniqueFunctionBase build-llvm/tools/clang/stage2-bins/llvm/include/llvm/ADT/FunctionExtras.h:341:3
#73 0x000055f884020011 unique_function build-llvm/tools/clang/stage2-bins/llvm/include/llvm/ADT/FunctionExtras.h:370:3
#74 0x000055f884020011 operator() build-llvm/tools/clang/stage2-bins/clang-tools-extra/clangd/support/Threading.cpp:103:14
#75 0x000055f884020011 operator()<(lambda at clang-tools-extra/clangd/support/Threading.cpp:98:15) &> build-llvm/tools/clang/stage2-bins/llvm/include/llvm/Support/thread.h:43:11
#76 0x000055f884020011 __invoke_impl<void, (lambda at llvm/include/llvm/Support/thread.h:42:9), (lambda at clang-tools-extra/clangd/support/Threading.cpp:98:15) &> /usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/invoke.h:61:14
#77 0x000055f884020011 __invoke<(lambda at llvm/include/llvm/Support/thread.h:42:9), (lambda at clang-tools-extra/clangd/support/Threading.cpp:98:15) &> /usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/invoke.h:96:14
#78 0x000055f884020011 __apply_impl<(lambda at llvm/include/llvm/Support/thread.h:42:9), std::tuple<(lambda at clang-tools-extra/clangd/support/Threading.cpp:98:15)> &, 0UL> /usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/tuple:2302:14
#79 0x000055f884020011 apply<(lambda at llvm/include/llvm/Support/thread.h:42:9), std::tuple<(lambda at clang-tools-extra/clangd/support/Threading.cpp:98:15)> &> /usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/tuple:2313:14
#80 0x000055f884020011 GenericThreadProxy<std::tuple<(lambda at clang-tools-extra/clangd/support/Threading.cpp:98:15)> > build-llvm/tools/clang/stage2-bins/llvm/include/llvm/Support/thread.h:41:5
#81 0x000055f884020011 ThreadProxy<std::tuple<(lambda at clang-tools-extra/clangd/support/Threading.cpp:98:15)> > build-llvm/tools/clang/stage2-bins/llvm/include/llvm/Support/thread.h:55:5
#82 0x00007fb897c58a94 start_thread ./nptl/pthread_create.c:447:8
#83 0x00007fb897ce5c3c clone3 ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:80:0
Signalled during AST worker action: Build AST
  Filename: /home/ubuntu/project/src/somedir/somefile.hpp
  Directory: /home/ubuntu/project/build
  Command Line: /usr/bin/c++ --driver-mode=g++ /* REDACTED INCLUDES */ -Wall -Werror -Wfatal-errors -Wextra -Wpedantic -pedantic-errors -Wcast-align -Wcast-qual -Wformat -Wformat-security -Wformat-y2k -Wnull-dereference -Wdate-time -Wpacked -Winline -Wshadow -Wswitch-default -Winit-self -Wdangling-else -Wunused-macros -Wmissing-include-dirs -Wdouble-promotion -Wstrict-aliasing -Wundef -fno-rtti -fno-exceptions -Wno-deprecated-enum-enum-conversion -Wformat-signedness -Wformat-truncation=2 -Wformat-overflow -Walloca -Wduplicated-branches -Wduplicated-cond -Wlogical-op -Wno-maybe-uninitialized -Wno-inline -Wno-psabi -fprofile-arcs -ftest-coverage -Wsuggest-override -c -std=c++20 -stdlib=libc++ -Wno-unknown-warning-option -Wno-double-promotion -Wuninitialized -Wimplicit-int-float-conversion -resource-dir=/usr/lib/llvm-18/lib/clang/18 -- somefile.hpp
  Version: 0
```

Redacted includes boil down to include paths though the header file has been reduced to not include or define anything.

**System information**

Output of `clangd --version`:
Ubuntu-24.04
```
Ubuntu clangd version 18.1.3 (1ubuntu1)
Features: linux+grpc
Platform: x86_64-pc-linux-gnu
```
Ubuntu 22.04
```
17.0.6 (++20231209124227+6009708b4367-1~exp1~20231209124336.77)
```

Editor/LSP plugin: emacs with lsp-mode and VSCode

Operating system: Ubuntu 24.04 and Ubuntu 22.04

How I'm Invoking clangd (different in vscode):
```
I[08:46:04.250] Working directory: /home/ubuntu/project
I[08:46:04.250] argv[0]: /usr/bin/clangd
I[08:46:04.250] argv[1]: --header-insertion-decorators=0
I[08:46:04.250] argv[2]: -j=4
I[08:46:04.250] argv[3]: --enable-config
I[08:46:04.250] argv[4]: --background-index
I[08:46:04.250] argv[5]: --clang-tidy
I[08:46:04.250] argv[6]: --limit-results=0
I[08:46:04.250] argv[7]: --limit-references=0
I[08:46:04.250] argv[8]: --log=verbose
I[08:46:04.250] argv[9]: --completion-style=detailed
I[08:46:04.250] argv[10]: --header-insertion=never
V[08:46:04.250] User config file is /home/ubuntu/.config/clangd/config.yaml
I[08:46:04.250] Starting LSP over stdin/stdout
```

**Comment by zyn0217** [comment] 2024-08-21 02:30
I tested on godbolt and it doesn't appear to crash with clang frontend.
Can you describe what specific action you were doing when you encountered the crash? e.g. formatting something / performing a refactoring.

**Comment by HighCommander4** [comment] 2024-08-21 02:45
This part of the stack trace:

> #53 0x000055f884360c65 clang::ast_matchers::MatchFinder::matchAST(clang::ASTContext&) build-llvm/tools/clang/stage2-bins/clang/lib/ASTMatchers/ASTMatchFinder.cpp:1700:11
> #54 0x000055f883e2bfea build build-llvm/tools/clang/stage2-bins/clang-tools-extra/clangd/ParsedAST.cpp:717:3

tells us clangd is running a clang-tidy checker. (However, we can't tell which checker is the problematic one because clangd registers all checkers with the same `MatchFinder`.)

**Comment by avlec** [comment] 2024-08-21 04:32
I'll see if I can provide some more information soon to try to nail down the root cause. I'll try to filter through the weeds of the config file we have. Are there any options that would make seeing what checker failed any easier? Also the clangd version should be from the same clang release on the platforms. (the Ubuntu 22.04 is manually installed from the llvm apt repo)

**Comment by HighCommander4** [comment] 2024-08-28 03:10
@avlec can you share the `.clang-tidy` file you are using when this crash occurs?

**Comment by HighCommander4** [comment] 2024-08-28 03:19
Never mind, I can see from the line printed just before the stack trace that the problematic checker is `bugprone-forwarding-reference-overload`.

**Comment by HighCommander4** [comment] 2024-08-28 03:51
Reported upstream at https://github.com/llvm/llvm-project/issues/106333.

I'm going to close this issue; a workaround until the upstream bug is fixed is to disable the `bugprone-forwarding-reference-overload` check in your `.clang-tidy` file, or alternatively in your `.clangd` file using:

```yaml
Diagnostics:
  ClangTidy:
    Remove: bugprone-forwarding-reference-overload
```

**Comment by HighCommander4** [comment] 2024-08-28 03:52
Duplicate of https://github.com/llvm/llvm-project/issues/106333

**Closed by HighCommander4** 2024-08-28 03:52 UTC
